---
title: "Humility in healing"
description: "Jesus heals a blind man."
author: Colin C.
date: 2023-09-16
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 22 - 21](https://www.bible.com/bible/111/MRK.8.NIV)

> They came to Bethsaida, and some people brought a blind man and begged Jesus to touch him. He took the blind man by the hand and led him outside the village. When he had spit on the man’s eyes and put his hands on him, Jesus asked, “Do you see anything?”\
> He looked up and said, “I see people; they look like trees walking around.”\
> Once more Jesus put his hands on the man’s eyes. Then his eyes were opened, his sight was restored, and he saw everything clearly.  Jesus sent him home, saying, “Don’t even go into the village.”

### Thoughts and questions 

In the previous passage Jesus' teaching focused on the importance of being humble.  In this passage, again Jesus shows compassion on a person who is not whole -- bringing sight to a blind man.  This would be something that Jesus and his disciples could take pride in, could highlight to all the people about how great and powerful Jesus is.  But our God is humble -- and desires that again this miracle be kept quiet: _Don't even go into the village._

This humility will continue to be important as we move into the passages ahead. 

### Prayer

Jesus, you are powerful, you are compassionate. Are there ways that I need to apply your ways to my life.  Are there ways that I need to show compassion. Are there ways that I try to build myself up more than I should.  Please show your power in my life and be compassionate to me.  Please teach me to be compassionate to others. 
