---
title: "Who am I?"
description: "Jesus let's his disciples know that he is the Messiah"
author: Colin C.
date: 2023-09-18
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 27 - 30](https://www.bible.com/bible/111/MRK.8.NIV)

> Jesus and his disciples went on to the villages around Caesarea Philippi. On the way he asked them, “Who do people say I am?”\
> They replied, “Some say John the Baptist; others say Elijah; and still others, one of the prophets.”\
> “But what about you?”he asked. “Who do you say I am?”\
> Peter answered, “You are the Messiah.”\
> Jesus warned them not to tell anyone about him.

### Thoughts and questions 

It seems that the people were talking _Who is Jesus?_.  They speculated many answers.  Of course we know, we have heard the story so many times.  But this is a really important point.  Yes, here Jesus confirms that he is the Messiah.  But again, as with the previous passages Jesus wants it kept quiet.  

The Jewish people have been waiting hundreds of years for the Messiah.  This is no simple title to take on.  But Jesus needs to take it on his way.  His way seems to always be a quiet way. 

### Prayer

Lyrics from an older song simply praising Jesus using His various names/ titles.  

[Jesus Name Above All Names](https://www.worshipsong.com/music/songs/songdetails/jesus-name-above-all-names)

>  Jesus Messiah, name above all names\
>  Blessed saviour, glorious Lord\
>  Emmanuel, God is with us\
>  Blessed Redeemer living Word\
>  \
>  Jesus, loving Shepherd\
>  Vine of the branches, Son of God\
>  Prince of Peace, Wonderful Counselor\
>  Lord of the universe, Light of the world\
