---
title: "Carry your cross"
description: "Jesus calls his disciples to a path that will lead to persecution"
author: Colin C.
date: 2023-09-24
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 34 - 38](https://www.bible.com/bible/111/MRK.8.NIV)

> Then he called the crowd to him along with his disciples and said: “Whoever wants to be my disciple must deny themselves and take up their cross and follow me. For whoever wants to save their life will lose it, but whoever loses their life for me and for the gospel will save it. What good is it for someone to gain the whole world, yet forfeit their soul? Or what can anyone give in exchange for their soul? If anyone is ashamed of me and my words in this adulterous and sinful generation, the Son of Man will be ashamed of them when he comes in his Father’s glory with the holy angels.”

### Thoughts and questions 

This is a continued response to Peter when he attempted to rebuke Jesus for describing how the Messiah would have to suffer and die.  It is really important to keep these words in context wih the last passage.  What does it mean to follow Jesus? 

-   _Take up their cross and follow me_.  The way of Jesus means that we may face persecution and rejection by society.  
-   Jesus has an eternal perspective.  Dedicating your life to him and even losing your life for the sake of the good news -- letting people know how God's kingdom has come. 
-   We need to take joy in Jesus' words -- his way is the best way and we should never be ashamed of his ways.  

### Prayer

Lord your way is good. Though it sometimes seems hard.  Give me strength to follow your ways.  Give me understanding as to how I should live in this generation at this time.  May my life show your love and compassion to others. 