---
title: "The task of the Messiah"
description: "Jesus give his disciples the straight good about what to expect."
author: Colin C.
date: 2023-09-23
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 31 - 33](https://www.bible.com/bible/111/MRK.8.NIV)

> He then began to teach them that the Son of Man must suffer many things and be rejected by the elders, the chief priests and the teachers of the law, and that he must be killed and after three days rise again. He spoke plainly about this, and Peter took him aside and began to rebuke him.\
> But when Jesus turned and looked at his disciples, he rebuked Peter. “Get behind me, Satan!” he said. “You do not have in mind the concerns of God, but merely human concerns.”

### Thoughts and questions 

I love the phrase _He spoke plainly about this_.  It just gives me the sense that Jesus  was simply giving them the facts -- he didn't make it dramatic, but he also did not hid anything from them.  Of course this was not what they were expecting.  Peter, was bold enough to challenge him.  Jesus rebukes hum strongly.  What I take from that rebuke is that the path set before Jesus is focused on a great work that God is doing.  

### Prayer

Lord God, how difficult it must have been to know your own path.  To know that rejection and suffering that you would face and then to have to live it/experience it all.  Lord God you know pain, you know suffering, you know despair.  Meet me in mine.  Meet me in the times that I suffer and comfort me.  
