---
title: "They missed the sign"
description: "Do we focus what we want and miss the work that Jesus is doing?"
author: Colin C.
date: 2023-09-03
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 1 - 13](https://www.bible.com/bible/111/MRK.7.NIV)

> During those days another large crowd gathered. Since they had nothing to eat, Jesus called his disciples to him and said, “I have compassion for these people; they have already been with me three days and have nothing to eat. If I send them home hungry, they will collapse on the way, because some of them have come a long distance.”\
> His disciples answered, “But where in this remote place can anyone get enough bread to feed them?”\
> “How many loaves do you have?” Jesus asked.\
> “Seven,” they replied.\
> He told the crowd to sit down on the ground. When he had taken the seven loaves and given thanks, he broke them and gave them to his disciples to distribute to the people, and they did so. They had a few small fish as well; he gave thanks for them also and told the disciples to distribute them. The people ate and were satisfied. Afterward the disciples picked up seven basketfuls of broken pieces that were left over. About four thousand were present. After he had sent them away, he got into the boat with his disciples and went to the region of Dalmanutha.
> The Pharisees came and began to question Jesus. To test him, they asked him for a sign from heaven. He sighed deeply and said, “Why does this generation ask for a sign? Truly I tell you, no sign will be given to it.” Then he left them, got back into the boat and crossed to the other side.

### Thoughts and questions 

My reaction to the first part of this passage is weird: _Yeah, again?_ I should be amazed -- Jesus just miraculously fed thousands of people.  Perhaps more importantly was his motivation: he did it because he had compassion on them.  

The last paragraph is also important.  The Pharisees are looking for a sign. Sure they were in a different city and had not been a part of the meal.  They had not seen for themselves the various healings that Jesus had done.  How hard would it have been for them to experience and power and teachings of Jesus?  All they would need to do is follow Jesus and they would see signs and miracles.  But no, they wanted him to perform on their terms.  They wouldn't believe because Jesus did not give them a sign that they wanted.  


### Prayer

Lord Jesus forgive me.  I want my sign. I want my miracle.  Help me to follow you and to see the work that you are doing.  

Also, please do have compassion on me and my situation. 

I will follow and I will trust you.

