---
title: "Yeast and self-importance"
description: "Jesus cautions his disciples."
author: Colin C.
date: 2023-09-09
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 8: 14 - 21](https://www.bible.com/bible/111/MRK.7.NIV)

> The disciples had forgotten to bring bread, except for one loaf they had with them in the boat. “Be careful,”Jesus warned them. “Watch out for the yeast of the Pharisees and that of Herod.”\
> They discussed this with one another and said, “It is because we have no bread.”\
> Aware of their discussion, Jesus asked them: “Why are you talking about having no bread? Do you still not see or understand? Are your hearts hardened? Do you have eyes but fail to see, and ears but fail to hear? And don’t you remember? When I broke the five loaves for the five thousand, how many basketfuls of pieces did you pick up?”\
> “Twelve,” they replied.\
> “And when I broke the seven loaves for the four thousand, how many basketfuls of pieces did you pick up?”
> They answered, “Seven.”\
> He said to them, “Do you still not understand?”

### Thoughts and questions 

Really, more bread! What is Jesus getting at here?

First, it is definitely not about the lack of bread.  Jesus highlights that every time they have not had enough bread he as made a way -- the miracles of feeding the 5,000 and 4,000.  No Jesus is providing a warning.  

> "Be very careful. Keep a sharp eye out for the contaminating yeast of Pharisees and the followers of Herod." (The Message translation)

What is yeast?  It is a typical ingredient in making bread.  A small amount is placed in with the flower and it works its way through the whole loaf.  The effect is that the bread becomes puffed up -- full of air.  The Message translation highlights that it is a contaminating yeast -- a yeast that is not planned and perhaps one that does not taste good.  From what I understand the culture at Jesus' time often ate flat breads (breads without yeast) -- so yest would be considered a bad thing.  

This is an analogy.  Jesus is warning his followers to not do things that puff themselves up.  To look and demand others to think that they are important.  I would suggest that Jesus is saying to them -- keep it humble.  

### Prayer

Jesus, help me to live a humble life that points to you.  That I would not try to make myself seem important.  That I wouldn't get puffed up to make myself more important in the eyes of others.  May my life reflect your love and compassion for this world! 

