---
title: "Victories and challenges -- we battle on"
description: "PET scan results from yesterday indicate some battles won!"
author: Colin C.
date: 2024-04-07
# date-modified: 2024-04-04
categories: [regular, new-sites, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   PET Scan with results this past Friday
-   Victories at several sites
-   Stability at the initial site
-   One new site under investigation
:::

## Cancer war

Sam has summarized this the past two PET scans in the following way
(paraphrased):

> The PET scan in February was like someone dumped a load of bricks on
> me.\
> This last PET scan was like someone removed all the bricks but then
> threw a single one at me.

Sam is great spirits. As the impacts of radiation therapy are behind
him, and the effects of GVHD[^1] are lessening he is seeing his energy
return. Today he wants to go grocery shopping with me.

[^1]: Graft versus host disease

### Review

The previous PET, back on Feb 14, provided really hard news. Following
months of seeing a new immune system be established in Sam (Nov. - Feb)
that imaging showed three new disease sites -- it seemed that all of the
previous efforts were for naught and that we were losing the cancer war.
Despite all of the efforts of the BMT to establishing a new immune
system, it did not seem to be effective at beating back the cancer.

Since the discovery of the new sites Sam has received immunotherapy (via
the drug Nivomulab) as well as targeted radiation treatment to the new
disease centers. The radiation therapy was straight forward and ended a
couple weeks ago. With the immune therapy Sam was only able to have a
single dose of the Nivomulab which triggered more GVHD[^2] than he had
seen during his BMT[^3]. Although this GVHD was not physically
comfortable (e.g. hot rashes, GI[^4] effects) it was mentally comforting
-- if the immune system was attacking healthy tissue it meant that it
was most likely also attacking the cancer. Most recently, the immune
system started getting dangerously out of control by stressing Sam's
liver. In response, he was started on some steroids to put the brakes on
his immune system and bring it back in-check.

[^2]: Graft versus host disease

[^3]: Bone marrow transplant

[^4]: gastrointestinal

This sets the stage for the PET scan this past Friday (April 5).

### PET scan results

*April 5^th^ scan*

#### Radiated sites

We have clear wins! No cancer was detectable in the three sites
discovered back in Feb. The cancer in his T3 vertebrae, hip, and shin
has been wiped out by the radiation therapy.

#### Central mass

The mass in the center of Sam's chest, the one that brought us down here
to start with, is stable. There is increased metabolic activity in the
area but it remains the same size as previous -- and potentially a
little smaller. What is exciting about this is that the only thing
keeping this site in-check would have been Sam's immune system. The fact
that this site is stable suggests that the immune system is able to
battle whatever cancer is still in this area.

#### Challenges

A single new site has been located. The new site is located in Sam's
liver. For now we have to assume that this is new disease site (i.e. the
same type of cancer in a new location). However, it is possible that is
something else. The liver is a big organ, one that is hard to do surgery
on, but this new site is superficial (near the surface) just below Sam's
lower rib on the right side. Given where this site is we are hoping that
a biopsy can be completed this coming week.

## Living Life

### Friends and Family

Although not planned this way it was great to have my parents visit this
weekend. Initial scheduling of the PET scan was not until next week. I
am glad they were here to be with us -- PET scans are often stressful.
Nana Mary, Uncles Kevin and Cal were also able to come in the afternoon
that we received the PET scan results.

Yesterday, Tina and I were able to visit with Brian, Beth, David, and
Luke. A definitely highlight from that visit was seeing Sam have energy
to talk with his friend!

### Tragedy

Yesterday's visits were filled with joy. But the day was also filled
with sorrow. Our hearts break for R and M, and their whole family, as
their daughter and sister Dani passes away in the early morning.

## Victories and concerns

-   Thankful that three disease centers have been removed. Thanksful
    that the original central mass is stable. We battle on to determine
    what the latest site is and how best to attack it.

-   Thankful that Sam's energy has increased!

-   Thankful that Sam's pain levels have been stable and generally easy
    to manage.

-   The new immunotherapy drugs seems to have released Sam's immune
    system to hit harder. As the immune system was starting to get out
    of control brakes have been applied to slow the immune system back
    down. It is good to know that the chemical brakes work, at the same
    time we do not what to suppress the immune system too long as it is
    the main method of battling the cancer.

-   We mourn the loss of Dani – grieving in solidarity with her family.

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   The cancer remains and has spread to new areas in Sam's body. The
    sites are a mass in the center of his chest (the original), and
    newer sites in his back (T3 vertebrae), his hip (right ilium), and
    left shin (tibia just below the knee).

-   We long for the day when Sam is clear of this disease.