---
title: "Credentials"
description: "The religious leaders try to trap Jesus with their questions."
author: Colin C.
date: 2023-12-31
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 11: 27 - 33](https://www.bible.com/bible/111/MRK.11.NIV)

> They arrived again in Jerusalem, and while Jesus was walking in the temple courts, the chief priests, the teachers of the law and the elders came to him. “By what authority are you doing these things?” they asked. “And who gave you authority to do this?”\
> Jesus replied, “I will ask you one question. Answer me, and I will tell you by what authority I am doing these things.John’s baptism — was it from heaven, or of human origin? Tell me!”\
> They discussed it among themselves and said, “If we say, ‘From heaven,’ he will ask, ‘Then why didn’t you believe him?’ But if we say, ‘Of human origin’ …” (They feared the people, for everyone held that John really was a prophet.)\
> So they answered Jesus, “We don’t know.”\
> Jesus said, “Neither will I tell you by what authority I am doing these things.”


### Thoughts and questions 

As a quick re-cap: What are the religious leaders talking about when they say "_Who gave you authority to do this?_".  What had Jesus done?  He totally disrupted their way of temple practice!  He kicked out the merchants, and blamed the leadership for changing the temple from its intended purpose of "_being a house of prayer for all nations_" (v. 17) and changed in into a den o robbers.  

The religious leaders response was to make plans to _get rid of Jesus_ (kill him).  These questions were intended to trap Jesus to give them grounds to arrest him.  But, again, Jesus is to smart.  He is not about to tell them who he is -- not yet.  The time is not yet right.  

### Prayer

Jesus, you are the Son of God, Messiah, you are God incarnate -- God made flesh! 

Help me to know your ways, learn your ways, and reflect your ways in my life!

You have the best timing and I submit my life to your purposes. 