---
title: "No fruit"
description: "Jesus curses the fig tree and cleans up in the temple."
author: Colin C.
date: 2023-12-21
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 11: 12 - 26](https://www.bible.com/bible/111/MRK.11.NIV)

> The next day as they were leaving Bethany, Jesus was hungry. Seeing in the distance a fig tree in leaf, he went to find out if it had any fruit. When he reached it, he found nothing but leaves, because it was not the season for figs. Then he said to the tree, “May no one ever eat fruit from you again.”And his disciples heard him say it.\
> On reaching Jerusalem, Jesus entered the temple courts and began driving out those who were buying and selling there. He overturned the tables of the money changers and the benches of those selling doves, and would not allow anyone to carry merchandise through the temple courts. And as he taught them, he said, “Is it not written: ‘My house will be called a house of prayer for all nations’? But you have made it ‘a den of robbers.’”\
> The chief priests and the teachers of the law heard this and began looking for a way to kill him, for they feared him, because the whole crowd was amazed at his teaching.\
> When evening came, Jesus and his disciples went out of the city.\
> In the morning, as they went along, they saw the fig tree withered from the roots. Peter remembered and said to Jesus, “Rabbi, look! The fig tree you cursed has withered!”\
> “Have faith in God,” Jesus answered. “Truly I tell you, if anyone says to this mountain, ‘Go, throw yourself into the sea,’ and does not doubt in their heart but believes that what they say will happen, it will be done for them. Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours. And when you stand praying, if you hold anything against anyone, forgive them, so that your Father in heaven may forgive you your sins.”


### Thoughts and questions 

Mark writes two stories at the same time here.  The story of the fig tree and Jesus visiting the temple.  Obviously, the author wants these stories connected.  Why?

I did a little extra reading on this (e.g.  [here](https://www.olivetree.com/blog/jesus-curse-fig-tree/) and [here](https://www.gotquestions.org/curse-fig-tree.html)).  I agree with the discussions presented.  

The fig tree is used as a symbol. Often we read in scripture how God will work in and through us and bear fruit -- good things out of our lives.  In this story, the fig tree, although looking like it should bear fruit was not bearing any fruit.  This is a parallel to the temple where although it was Israel's center of worship and had the appearance of worship and centering on God but it did not.  

Jesus cursed the fig tree when it failed to bare fruit, in a similar way he is angered and drives out the evil from the temple, the merchants and money lenders. In the upcoming passages there are numerous times when Jesus speaks out against the religious leaders of the day.  It is also striking that the religious leaders fear Jesus (_they began to look for a way to kill him_), and they have a reason to fear him as he is about to overturn their religious practices and their way of life. 

Though the fig tree and the temple system are cursed/rebuked for not producing good fruit (figs from the tree, or at the temple _being a house of prayer_).  There is hope.  Our hope is in the way that Jesus taught.  In prayer, no matter what we ask, we called to believe trusting that we have already received it, and at the same time Jesus also calls us to a life of forgivenes.



### Prayer

Lord God, work your will in my life that it would bear fruit. That people could know your love through your work in my life.  Guard my heart from the distractions of this world. 

Here our prayers God -- bring good life and strength.  For your purposes. 