---
title: "The humble entry"
description: "The people welcome Jesus to Jerusalem -- longing for salvation."
author: Colin C.
date: 2023-12-19
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 11: 1 - 11](https://www.bible.com/bible/111/MRK.11.NIV)

> As they approached Jerusalem and came to Bethphage and Bethany at the Mount of Olives, Jesus sent two of his disciples, saying to them, “Go to the village ahead of you, and just as you enter it, you will find a colt tied there, which no one has ever ridden. Untie it and bring it here. If anyone asks you, ‘Why are you doing this?’ say, ‘The Lord needs it and will send it back here shortly.’ ”\
They went and found a colt outside in the street, tied at a doorway. As they untied it, some people standing there asked, “What are you doing, untying that colt?” They answered as Jesus had told them to, and the people let them go. When they brought the colt to Jesus and threw their cloaks over it, he sat on it. Many people spread their cloaks on the road, while others spread branches they had cut in the fields. Those who went ahead and those who followed shouted,\
“Hosanna!”\
“Blessed is he who comes in the name of the Lord!”\
“Blessed is the coming kingdom of our father David!”\
“Hosanna in the highest heaven!”\
Jesus entered Jerusalem and went into the temple courts. He looked around at everything, but since it was already late, he went out to Bethany with the Twelve.

### Thoughts and questions 

Do you remember the crowds that were following Jesus?  Bartimeaus, once blind, was likely in that crowd.  This passage is often referred to as the _Triumphal Entry_, as Jesus enters Jerusalem as a hero -- celebrated and popular with the people.  

The people are shouting! Based on some reading and trying to understand the term _Hosanna_ this is how I would interpret this passage:

“Praise God -- Save Us!”\
“Blessed is he who comes in the name of the Lord!”\
“Blessed is the coming kingdom of our father David!”\
“Bring salvation ordered out of the highest heaven!”\

The people are looking to Jesus to save them but his salvation will look different than they expect.  However, Jesus continues to do things differently: he rides in on a colt, a young horse.  This is no royal horse, or war horse.  Not a horse that leaders would ride in on as a symbol of their power.  Rather this is a humble horse, still young, and likely not yet strong. So Jesus comes in humility.  His salvation will not be an overthrow of the political oppressors but will be conquer the hearts of humanity.  


### Prayer

Lord Jesus, save me from myself.  Continue to work out your salvation in my heart and mind that I would live as you lived.  That I would love and have compassion on the people as you did.  Let you Spirit reign in my life. 