---
title: "Mark -- Introduction I"
description: "In context of prophecy"
author: Colin C.
date: 2023-05-29
categories: [Mark, overview]
draft: false
editor: 
  markdown: 
    wrap: 72
---



### Mark 1: 1-5

> ^1^The beginning of the good news about Jesus the Messiah, the Son of
> God, ^2^as it is written in Isaiah the prophet:\
> \
> *"I will send my messenger ahead of you,\
> who will prepare your way"---\
> ^3^"a voice of one calling in the wilderness,\
> 'Prepare the way for the Lord,\
> make straight paths for him.'"*\
> \
> ^4^And so John the Baptist appeared in the wilderness, preaching a
> baptism of repentance for the forgiveness of sins. ^5^The whole Judean
> countryside and all the people of Jerusalem went out to him.
> Confessing their sins, they were baptized by him in the Jordan River.


### Thoughts and questions

Mark places the gospel in the context of prophecy -- something that Isreal has been waiting for. This initial reference, from Isaiah 40:3, highlights the role of John the Baptist.  I think it is clear that people were aware of and wanting forgiveness of sins.

This passage raises a question for me.  How can John's baptism be for the forgiveness of sins, if only God can forgive sins?  How is Jesus' message and his forgiveness different? 


### Prayer

Lord, please help me be aware of my sins, to confess, repent, and change.  Jesus thank you for your forgiveness.