---
title: "Mark -- Introduction II"
description: "In context of prophecy"
author: Colin C.
date: 2023-05-30
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### Mark 1: 4-8

And so John the Baptist appeared in the wilderness, preaching a baptism of repentance for the forgiveness of sins. The whole Judean countryside and all the people of Jerusalem went out to him. Confessing their sins, they were baptized by him in the Jordan River. John wore clothing made of camel’s hair, with a leather belt around his waist, and he ate locusts and wild honey. And this was his message: _“After me comes the one more powerful than I, the straps of whose sandals I am not worthy to stoop down and untie. I baptize you with water, but he will baptize you with the Holy Spirit.”_ 

### Thoughts and questions

As noted yesterday, people came from everywhere to be baptized, confess their sins, and receive forgiveness.  The people knew their sin -- longing to receive forgiveness.  John, provides some sort of means of forgiveness, or at least repentance.  ... This remains religious/ or ritual based through the act of being baptized.  

John also points to Jesus -- that his baptism will be different.  It will be a baptism of the Holy Spirit.

-   How does Jesus' forgiveness differ from John's?  
-   What does it mean that we are baptized in the Holy Spirit?
-   If we are forgiven through the work of the Holy Spirit -- how accessible is our forgiveness?  Does our forgiveness rely of ritual? 


### Prayer

Lord thank you for your forgiveness.  May my heart long for holiness as the people that came to John longed for right relationship with you.  In our world I pray that my friends and neighbours, our society would long to be in right relationship with you. 