---
title: "Jesus on fasting"
description: "Discussion on the discipline of fasting and doing things in their right time."
author: Colin C.
date: 2023-06-17
search: false
categories: [Mark, breaking-barriers]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 2: 18 - 22](https://www.bible.com/bible/111/MRK.2.NIV)

> Now John's disciples and the Pharisees were fasting. Some people came
> and asked Jesus, "How is it that John's disciples and the disciples of
> the Pharisees are fasting, but yours are not?"\
> Jesus answered, "How can the guests of the bridegroom fast while he is
> with them? They cannot, so long as they have him with them. But the
> time will come when the bridegroom will be taken from them, and on
> that day they will fast.\
> "No one sews a patch of unshrunk cloth on an old garment. Otherwise,
> the new piece will pull away from the old, making the tear worse. And
> no one pours new wine into old wineskins. Otherwise, the wine will
> burst the skins, and both the wine and the wineskins will be ruined.
> No, they pour new wine into new wineskins."

### Thoughts and questions

Our church tradition does not put much emphasis on fasting ... or really
any of the classic spiritual disciplines. People will often provide various lists them.  Some common ones: 

1.  Study
2. 	Prayer
3. 	Fasting 
4.  Confession
5.  Service
6.  Worship 




<!-- From: https://churchleaders.com/outreach-missions/outreach-missions-articles/325192-12-spiritual-disciplines-that-will-make-your-faith-strong-brandon-hilgemann.html/8 -->
<!-- 1.  Study of the word -->
<!-- 2.  Prayer -- spend time praying. Bring all your cares to God, seek His -->
<!--     will in your life -->
<!-- 3.  Fasting -- often abstaing from food, you could also stop other -->
<!--     activities. Use the hunger as a call to prayer.\ -->
<!-- 4.  Confession -- spending additional time examining our lives, -->
<!--     recognizing our sin, and confessing it -->
<!-- 5.  Worship -- Praising God, acknologing God's power, attributes -->
<!-- 6.  Fellowship -- our lives of faith are not individual but in community -->
<!-- 7.  Rest -- intentionally taking a break -->
<!-- 8.  Celebration -- being thankful for what God has done -->
<!-- 9.  Service -->
<!-- 10. Generosity -- giving -->
<!-- 11. Chastity -- staying away from sexual immorality -->
<!-- 12. Disciple-making  -->


Here Jesus talks on fasting ... again He is breaking from social
traditions. He and his disciples don't seem to be fasting. Jesus
essentially says -- it is not the right time to fast. Why?

Because, now is the time to celebrate. It is time to party -- he uses a
wedding analogy. You party at a wedding when everyone is together. At
that time Jesus is with his disciples, God has come to his people --
time to party.

The whole wine skins and garments thing: boils down to do things that
make sense. When it is time to party, then party; if it is time to
grieve, grieve.

Jesus also indicates that there will be a time coming when his disciples
will fast. I think this is a forshadowing of when Jesus will no longer
be with his disciples. The early church, in the book of Acts, spent time
in prayer and fasting as they sought God's direction.

### Prayer

God, today I celebrate what you are doing! You are awesome! I thank you
for the healing that we have seen. I trust you for the days ahead.
