---
title: "Mark -- Introduction III"
description: "Introduction to Jesus"
author: Colin C.
date: 2023-05-31
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 9-13](https://www.bible.com/bible/111/MRK.1.NIV)

> At that time Jesus came from Nazareth in Galilee and was baptized by John in the Jordan. Just as Jesus was coming up out of the water, he saw heaven being torn open and the Spirit descending on him like a dove. And a voice came from heaven: “You are my Son, whom I love; with you I am well pleased.”\
At once the Spirit sent him out into the wilderness, and he was in the wilderness forty days, being tempted by Satan. He was with the wild animals, and angels attended him.

### Thoughts and questions

This is our introduction to Jesus.  From the previous passage we know that he will be the one who comes after John, is more powerful than him, and who will baptize the people with the Holy Spirit. 

This passage:

1. Introduces Jesus, 
2. Spirit of God descends on him, and
2. Confirms him as the Son of God! I think this is something that is easy to skip over! 

The next short paragraph seems odd to me.  He is immediately sent out to the wilderness where he is tempted (other versions say: tested).  Then he was ministered to by angels. This is odd in that it is not within our normal understanding/ or experience.  I think what I can take from this is that he was tested and went through a challenging time and following that time Angels took care of him perhaps helped him restore his strength. 


### Prayer

Jesus, thank you for coming, and providing a means of salvation.  I thank you for your Holy Spirit, giving us access to you, providing your forgiveness -- through prayer instead of ritual.  I thank you that you know what it is to suffer and face trials.  Help me in mine. I pray that I may find relief from my trials and challenges. 