---
title: "Jesus and the sinners"
description: "Jesus breaks social norms and spends time with sinners"
author: Colin C.
date: 2023-06-15
search: false
categories: [Mark, breaking-barriers]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 2: 13 - 17](https://www.bible.com/bible/111/MRK.2.NIV)

> Once again Jesus went out beside the lake. A large crowd came to him, and he began to teach them. As he walked along, he saw Levi son of Alphaeus sitting at the tax collector’s booth. “Follow me,”Jesus told him, and Levi got up and followed him.\
While Jesus was having dinner at Levi’s house, many tax collectors and sinners were eating with him and his disciples, for there were many who followed him. When the teachers of the law who were Pharisees saw him eating with the sinners and tax collectors, they asked his disciples: “Why does he eat with tax collectors and sinners?”\
On hearing this, Jesus said to them, “It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners.”


### Thoughts and questions

Jesus' call is not just for those people that have their lives together; for those people who have an understanding of the scriptures.  He calls all people.  He went to those that were furthest from God.  He went to those that were the most spiritually sick, loved them and called them!  

In our society who do you think Jesus would be drawn to go have dinner with?  I don't think he would spend all his time at church lunchs and in bible studies ( I do think he would go -- similar to how he preached in the synagogues).  Who are the 'sinners' in our society?  How would you feel if Jesus spent his time with them? 

### Prayer

Lord God give me a heart for the spiritually sick, for those that are far from you.  How do you want me to interact with them?  May I love them as you loved them.  May they know your love and receive your call.  