---
title: "Mark -- Jesus has authority I"
description: "Jesus demonstrates his authority in the spirital world."
author: Colin C.
date: 2023-06-06
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 21 - 28](https://www.bible.com/bible/111/MRK.1.NIV)

> They went to Capernaum, and when the Sabbath came, Jesus went into the
> synagogue and began to teach. The people were amazed at his teaching,
> because he taught them as one who had authority, not as the teachers
> of the law. Just then a man in their synagogue who was possessed by an
> impure spirit cried out, "What do you want with us, Jesus of Nazareth?
> Have you come to destroy us? I know who you are---the Holy One of
> God!"
>
> "Be quiet!"said Jesus sternly. "Come out of him!" The impure spirit
> shook the man violently and came out of him with a shriek.
>
> The people were all so amazed that they asked each other, "What is
> this? A new teaching---and with authority! He even gives orders to
> impure spirits and they obey him." News about him spread quickly over
> the whole region of Galilee.

### Thoughts and questions

*He taught then as one who has authority*. The passage and several of
the following highlight that Jesus has authority. I also find it
interesting that the people were amazed that he taught with authority. I
am left wondering how his teaching differed from others. In the academic
world people often present ideas as so-and-so said this and another
person said that, and I found ... This can actually add to confusion for
people and I can't help wonder if that is what the teachers of the time
did. I think Jesus taught as one who has authority meant that he
interpreted the scriptures to people -- without debate, and without any
doubt of the meaning of the scriptures. The following verses highlight/
support Jesus' authority.

Jesus has authority in the spiritual realms. This spirit, assumed demon,
an entity that, from what I understand, is older than the creation of
the world recognized Jesus but Jesus is greater than the spirits. He has
authority to command them.

### Prayer

Lord Jesus, help me understand your teaching. Your teachings were right
and true. Help me apply them to my life. Jesus, I recognize and submit
to your authority in my life. Use my life to accomplish your purposes.
