---
title: "Mark -- Jesus has authority II"
description: "Jesus demonstrates his authority over the body."
author: Colin C.
date: 2023-06-07
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 29 - 31](https://www.bible.com/bible/111/MRK.1.NIV)

> As soon as they left the synagogue, they went with James and John to the home of Simon and Andrew. Simon’s mother-in-law was in bed with a fever, and they immediately told Jesus about her. So he went to her, took her hand and helped her up. The fever left her and she began to wait on them.


### Thoughts and questions

I read this a few times.  Why go to Simon and Andrew's house.  I think the answer is actually really simple.  They had spent a day working, preaching and teaching in the synagogue.  It was time to take a break.  It is possible that S. and A.'s mother had been looking forward to hosting he boys and their teacher -- most mothers would.  But they arrive and mom is sick.  

Jesus takes her hand and heals her! Remember for a first time reader or hearer of the gospel -- they might not know anything about Jesus yet.  Jesus demonstrated his authority over the body/ the physical. 

Why did she server them right away?  I think that was her plan all along -- or if not, its what mom's do when their son(s) show up with friends!  She was loving them. 


### Prayer

Jesus, we know that you have the authority/power to heal.  You know Sam is sick with cancer.  You know where it is, how it works.  Please God, bring healing to him.  Restore to him his youth and fill him with joy.  
