---
title: "Jesus' family"
description: "Jesus redefines family"
author: Colin C.
date: 2023-07-03
date-modified: 2023-07-03
search: false
categories: [Mark, priorities]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 3:31 - 35](https://www.bible.com/bible/111/MRK.3.NIV)

>  Then Jesus’ mother and brothers arrived. Standing outside, they sent someone in to call him. A crowd was sitting around him, and they told him, “Your mother and brothers are outside looking for you.”\
> “Who are my mother and my brothers?” he asked.\
Then he looked at those seated in a circle around him and said, “Here are my mother and my brothers!\
> Whoever does God’s will is my brother and sister and mother.”

### Thoughts and questions

I think we have a great family.  Sure we don't always get along but I know that we love each other and care for one another.  

I am not sure about the details of Jesus's mother and brothers asking for him.  Did they expect special privileges because they were family?  Were they looking to listen?  Were they hoping to stop him?  In the end it doesn't matter.  The point is that Jesus sets the true priority and redefines family.  He defines family as those that do the will of God.  More important than family by blood is family unified in spirit (i.e. the Holy Spirit).

### Prayer

Jesus I am thankful for my family.  That we are unified not just by our blood but more importantly by your Spirit!  Unify us and call us to your purposes.  Help us to do your will! 