---
title: "Mark -- Jesus takes time to pray"
description: "Jesus gets away from it all and has clarity of purpose."
author: Colin C.
date: 2023-06-09
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 35 - 39](https://www.bible.com/bible/111/MRK.1.NIV)

> Very early in the morning, while it was still dark, Jesus got up, left the house and went off to a solitary place, where he prayed. Simon and his companions went to look for him, and when they found him, they exclaimed: “Everyone is looking for you!”\
> Jesus replied, “Let us go somewhere else—to the nearby villages—so I can preach there also. That is why I have come.” So he traveled throughout Galilee, preaching in their synagogues and driving out demons.

### Thoughts and questions

Despite a huge day the day before, Jesus was up early taking time to pray.  There is an amazing mystery in his need to pray -- why does Jesus, God, need to pray to God?  This is the mystery of him being fully human -- he as limited himself.  In being fully human he had to take time to be with God.  Obviously, his time in prayer gave him clarity of purpose. 

Despite what Simon and his companions wanted, that is to stay and perform more mircles.  Jesus said "Let's go", and so they did -- I have to wonder:

-	Was everyday full like the first one described?  Probably! 
-	What would it be like to have such confidence in what God had called you to do?  
- 	How could you begin to understand what God is calling you to do? Seems to me part of the answer to this is taking time to pray andbe with God. 
-	In what ways is God working in you? In what ways is God using you?

### Prayer

Jesus help me to understand how you are working in my life.  May I be inspired to do life your way.  Allow me to be encouraged by the work you are doing in me and through me. 