---
title: "Jesus doing what is right"
description: "Again, Jesus breaks social/ religious norms by'working' on the Sabbath"
author: Colin C.
date: 2023-06-21
search: false
categories: [Mark, breaking-barriers]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 3:1 - ](https://www.bible.com/bible/111/MRK.2.NIV)

> Another time Jesus went into the synagogue, and a man with a shriveled hand was there. Some of them were looking for a reason to accuse Jesus, so they watched him closely to see if he would heal him on the Sabbath. Jesus said to the man with the shriveled hand, “Stand up in front of everyone.”\
Then Jesus asked them, “Which is lawful on the Sabbath: to do good or to do evil, to save life or to kill?” But they remained silent.\
He looked around at them in anger and, deeply distressed at their stubborn hearts, said to the man, “Stretch out your hand.”He stretched it out, and his hand was completely restored. 6Then the Pharisees went out and began to plot with the Herodians how they might kill Jesus.

### Thoughts and questions

Does Jesus care about rules? 

I don't think we can know from this passage.  What he cares about is doing what is right.  Showing compassion.  Providing healing.  Doing good work. 

A couple other points: 

1.   He is so frustrated with the religious people -- who put their rules ahead of compassion and caring.  Do we, I mean our church, do that? 
2.   The religious leaders were so entrenched in their rules that they were willing to plot to have Jesus killed! 

Who is your life is best at showing the love and compassion of Christ to you and others?  What can you learn from them?

### Prayer

Jesus, give me your heart of compassion.  Help me to have courage to act as you would. If my heart is hard or stubborn -- soften it that I might do your will.  

