---
title: "Mark -- Jesus forgives and heals the paralyzed man (II)"
description: "Jesus forgives and heals a paralyzed man."
author: Colin C.
date: 2023-06-13
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 2: 1 - 5](https://www.bible.com/bible/111/MRK.2.NIV)

> A few days later, when Jesus again entered Capernaum, the people heard that he had come home. They gathered in such large numbers that there was no room left, not even outside the door, and he preached the word to them. Some men came, bringing to him a paralyzed man, carried by four of them. Since they could not get him to Jesus because of the crowd, they made an opening in the roof above Jesus by digging through it and then lowered the mat the man was lying on. When Jesus saw their faith, he said to the paralyzed man, “Son, your sins are forgiven.”

continues ... 

### [Mark 2: 6 - 12](https://www.bible.com/bible/111/MRK.2.NIV) 

> Now some teachers of the law were sitting there, thinking to themselves, “Why does this fellow talk like that? He’s blaspheming! Who can forgive sins but God alone?”\
>
> Immediately Jesus knew in his spirit that this was what they were thinking in their hearts, and he said to them, “Why are you thinking these things? Which is easier: to say to this paralyzed man, ‘Your sins are forgiven,’ or to say, ‘Get up, take your mat and walk’? But I want you to know that the Son of Man has authority on earth to forgive sins.” So he said to the man, “I tell you, get up, take your mat and go home.”

### Thoughts and questions

Jesus, so smart, knows that there will be a controversy over him forgiving sins.  This is something only God can do! Such an important passage.  Jesus highlights that he has authority to forgive.  This is not something one can see, so he backs up his declaration of forgiveness with the visible miracle of healing.  What do you think is more important: forgiveness or healing?  Which is a greater miracle?  That a Holy God provides forgiveness of wrongs or that an all-powerful God provides physical healing?


### Prayer

Jesus we need you.  We need your forgiveness, we need your healing.  We also need you to guide our lives -- that we would bring glory and good understanding of you to the world around us -- through our lives. 