---
title: "Mark -- Jesus forgives and heals the paralyzed man (I)"
subtitle: "Reaching Jesus"
description: "Friends of a paralyzed man push through barriers to get to Jesus."
author: Colin C.
date: 2023-06-12
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 2: 1 - 5](https://www.bible.com/bible/111/MRK.2.NIV)

> A few days later, when Jesus again entered Capernaum, the people heard that he had come home. They gathered in such large numbers that there was no room left, not even outside the door, and he preached the word to them. Some men came, bringing to him a paralyzed man, carried by four of them. Since they could not get him to Jesus because of the crowd, they made an opening in the roof above Jesus by digging through it and then lowered the mat the man was lying on. When Jesus saw their faith, he said to the paralyzed man, “Son, your sins are forgiven.”



### Thoughts and questions

I think we will need to sit in this story for a few days -- these verses and some following.  There is a lot going on here.  For today, let's focus on the paralyzed man and his friends.  They are desperate.  They are willing to try anything!  They seem to know that Jesus is the answer, that he can recue their friend from his injury, from his state.  They are willing to break social rules, to get past the crowd, and interrupt the teacher.  

What are we willing to do to get to Jesus?  How do we get to Jesus? 



### Prayer

Jesus, sometimes it feels really hard to reach you. In this time, when you are not with us physically, what does it mean to reach out to you -- to gain access to your presence, to seek your healing?  I know that you sent your Spririt to us.  Please pour your Spirit to us.  Surround us with your love.  May we know your forgiveness and healing. 