---
title: "Mark -- Jesus heals the lepor"
description: "Jesus has compassion on a man with leprosy."
author: Colin C.
date: 2023-06-11
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 41 - 45](https://www.bible.com/bible/111/MRK.1.NIV)

> A man with leprosy came to him and begged him on his knees, “If you are willing, you can make me clean.”
Jesus was indignant. He reached out his hand and touched the man. “I am willing,”he said. “Be clean!” Immediately the leprosy left him and he was cleansed.\
Jesus sent him away at once with a strong warning: “See that you don’t tell this to anyone. But go, show yourself to the priest and offer the sacrifices that Moses commanded for your cleansing, as a testimony to them.” Instead he went out and began to talk freely, spreading the news. As a result, Jesus could no longer enter a town openly but stayed outside in lonely places. Yet the people still came to him from everywhere.


### Thoughts and questions

-	_Jesus was indignant?_: What? Why? \
Indignant is defined as _feeling or showing anger because of something unjust or unworthy_ ([dic](https://www.merriam-webster.com/dictionary/indignant)).
	-	When I read this I think it might mean that Jesus was sort of annoyed -- Can I? Well of course I can! But perhaps something is lost in the translation.  
	-	Other bible translations give alternate interpretations:  Deeply moved (Message); moved with compassion (NKJV); Moved with pity (NRSV).  It is important to check other translations -- especially when we run into passages that are challenging.  
	-	Given that many other translators settle with a compassionate interpreations I think I will settle here as well.  ... Otherwise I will need to learn ancient greek and read the original!

-	The real points of this story:
	-	Jesus is able to heal a man with a disease that was so incredibly rejected by society and very much uncurable at the time.
	-	Also, because this man did not follow Jesus' instruction.  Jesus' ministry was impacted. 


### Prayer

Jesus I beg you to heal this cancer.  I know you can.  But not my will but yours be done.  Help me to trust you in all of this. 