---
title: "Mark -- Jesus has authority III"
description: "Jesus demonstrates authority -- again and again"
author: Colin C.
date: 2023-06-09
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 32 - 33](https://www.bible.com/bible/111/MRK.1.NIV)

> That evening after sunset the people brought to Jesus all the sick and demon-possessed. The whole town gathered at the door, and Jesus healed many who had various diseases. He also drove out many demons, but he would not let the demons speak because they knew who he was.

### Thoughts and questions

When I read this today, what struck me was _that evening_.  Mark has been describing a single day in the life and ministry of Jesus.  To recap from the previous verses Jesus: 

-	taught in the synagogue -- with authority (v. 21-22)
-	demonstrated authority over demonic powers (v. 23-26)
-	deomontrated authority over the physical -- healing Simon and Andrews mom.

Now in this passage, the work day is over, yet Jesus is still working.  Not just healing one or two people -- but _many_.  

Jesus worked hard, bringing freedom to people in body and mind. How can this not be good news!


### Prayer

God I am struck this morning by the long days that you worked, enlightening the minds of the people, healing their bodies, freeing their minds/spririts. 

Lord, work in me.  Give me the strength to do the work you have called me to. Help us to understand your word, and how to apply your good news to oue lives.  Bring healing. 