---
title: "Jesus defends himself"
description: "Jesus is accused of using demonic power"
author: Colin C.
date: 2023-07-01
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 3:20](https://www.bible.com/bible/111/MRK.3.NIV)

> Then Jesus entered a house, and again a crowd gathered, so that he and his disciples were not even able to eat. When his family heard about this, they went to take charge of him, for they said, “He is out of his mind.”\
> And the teachers of the law who came down from Jerusalem said, “He is possessed by Beelzebul! By the prince of demons he is driving out demons.”\
> So Jesus called them over to him and began to speak to them in parables: “How can Satan drive out Satan? If a kingdom is divided against itself, that kingdom cannot stand. If a house is divided against itself, that house cannot stand. And if Satan opposes himself and is divided, he cannot stand; his end has come. In fact, no one can enter a strong man’s house without first tying him up. Then he can plunder the strong man’s house. Truly I tell you, people can be forgiven all their sins and every slander they utter, but whoever blasphemes against the Holy Spirit will never be forgiven; they are guilty of an eternal sin.”

### Thoughts and questions

I wonder what it is about this day that set his family off?  Was it that the crowds were almost out of control ... such that it was not even possible for pause and eat.  Was it that there were so many demon possessed people. This is not something that we see in our culture.  I think the closest analogy is the mentally ill -- some of whom may be tormented by demons.  However, to be clear I am not saying that mentally ill people have demons.  ... My point is that a room full of mentally ill people can be chaotic. Yet Jesus is there, he receives the people.  He heals them.  

Accusations can be so hurtful. In particular, accusations from the family, the people who are supposed to support you the most.  Yet Jesus remains confident in the work that he is doing.  But not just blindly confident. Confident and clear thinking -- he has the knowledge to defend himself. He is not speaking out of blind-faith but out of a deep understanding of the truth and of his role in God's plan.  

It is a beautiful thing, that _people can be forgiven all their sins and every slander_ -- every slander wow! What is the unforgivable sin that he speaks of? Every slander can be forgiven -- so every insult directed at Christ can be forgiven (e.g. _He is possessed)_. I think it is when the teachers of the law suggest that Jesus' power comes from the devil and not from the Holy Spirit -- that is a serious matter.  




### Prayer

Lord God, call me your purposes in this life.  Give me the confidence to know that I am doing your work so that when hard times come I do not falter or fail.  Jesus teach me and empower me by your Holy Spirit to do the work that you wish me to do. May I be sensitive to your Spirit, so that I might see you at work and working in the lives of others!