---
title: "Mark -- Answering the call"
description: "Jesus' first disciples answer the call"
author: Colin C.
date: 2023-06-05
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 16 - 20](https://www.bible.com/bible/111/MRK.1.NIV)


> As Jesus walked beside the Sea of Galilee, he saw Simon and his brother Andrew casting a net into the lake, for they were fishermen. “Come, follow me,”Jesus said, “and I will send you out to fish for people.” At once they left their nets and followed him.\
> When he had gone a little farther, he saw James son of Zebedee and his brother John in a boat, preparing their nets. Without delay he called them, and they left their father Zebedee in the boat with the hired men and followed him.


### Thoughts and questions

Jesus starts to call his disciples.  ... At my work, most jobs for that matter, and generally within our society who get the jobs, the scholarships, or the opportunities?  It is those that are deemed worthy, those that excel, those that have proven themselves.  From what I have been taught is wasn't so different back at Jesus' time.  But Jesus did not look at a pile of applications and select the best.  He selected regular people.  I also believe that he knew their hearts.  He knew that they would be up for the task!

How is Jesus calling you?  What is he calling you to?  ... If you don't know -- have you asked him? 

### Prayer

Jesus, I know that you have called me.  I know that you will use me.  Help me see it.  Help me understand your vision for my life.  Guide me so that I may act to answer your call.  That, like your disciples, when you call that I would be willing to drop everything and go with you. 
