---
title: "Jesus in demand"
description: "The people pursue Jesus seeking healing"
author: Colin C.
date: 2023-06-25
search: false
categories: [Mark, healing]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 3:7 - 12](https://www.bible.com/bible/111/MRK.2.NIV)

> Jesus withdrew with his disciples to the lake, and a large crowd from Galilee followed. When they heard about all he was doing, many people came to him from Judea, Jerusalem, Idumea, and the regions across the Jordan and around Tyre and Sidon. Because of the crowd he told his disciples to have a small boat ready for him, to keep the people from crowding him. For he had healed many, so that those with diseases were pushing forward to touch him. Whenever the impure spirits saw him, they fell down before him and cried out, “You are the Son of God.” But he gave them strict orders not to tell others about him.

### Thoughts and questions

What struck me as I read this was how Jesus was in such demand.  He was working miracles and the people sought him for healing.  The number of people was so great Jesus needed an 'escape' plan.  I wonder, did he heal them all? 


### Prayer

Jesus, what would it take for people to pursue you today? \
Lord, work in my heart and mind that I would pursue you. 
