project:
  type: website

website:
  title: "Sam Chisholm"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
    pinned: true
  page-navigation: false
  page-footer: 
    center: Copyright 2023, Colin Chisholm
    
    
  
format:
  html:
    theme: spacelab
    css: 
      - styles.css
      - timeline.css
      - custom.css

    toc: true

editor: source

