project:
  type: website
  

website:
  title: "Sam Chisholm"
  description: "News updating friends and family on our journey"
  site-url: "http://samc-news.netlify.app"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
      - icon: rss
        href: index.xml
      - text: Photos
        href: https://photos.google.com/share/AF1QipMxk44zEsg4p2JvLUAIo3JuEYJ94Z4njt3Avvmh7-QXcpvHYZR6GZ2RG4gMQek7bQ?key=SElnd1ZRXzYtV1dJWUVrcGttbVlkcjBKa3RLZXBn
    pinned: true
  page-navigation: false
  page-footer: 
    center: Copyright 2023, Colin Chisholm
    background: light
    
  
format:
  html:
    theme: spacelab
    css: 
      - styles.css
      - timeline.css
      - custom.css
    toc: true

editor: source
execute: 
  freeze: true
