project:
  type: website
  

website:
  title: "Sam Chisholm"
  description: "News updating friends and family on our journey"
  site-url: "http://samc-news.netlify.app"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
      - href: contact.qmd
        text: Contact Us
      - icon: rss
        href: index.xml
    pinned: true
  page-navigation: true
  page-footer: 
    center: Copyright 2023, Colin Chisholm
    background: light
    
  
format:
  html:
    theme: spacelab
    css: 
      - styles.css
      - timeline.css
      - custom.css
    toc: true

editor: source
execute: 
  freeze: true
