project:
  type: website
  
website:
  title: "Sam Chisholm"
  description: "News updating friends and family on our journey"
  site-url: "http://samc-news.netlify.app"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
      - href: contact.qmd
        text: Contact Us
      - icon: rss
        href: index.xml
    pinned: true
  page-navigation: true
  page-footer: 
    center: Copyright 2023 Colin Chisholm
    background: dark
  twitter-card:
    image: https://samsstory.s3.ca-central-1.amazonaws.com/chisholms-bcch-logo.jpg
    title: Sam Chisholm's cancer journey
    description: Regular updates on our lives as we journey with Sam in his journey battling cancer, including concerns and victories.  
  open-graph: 
    image: https://samsstory.s3.ca-central-1.amazonaws.com/chisholms-bcch-logo.jpg
    title: Sam Chisholm's cancer journey
    description: Regular updates on our lives as we journey with Sam in his journey battling cancer, including concerns and victories.  
    site-name: Sam C. Updates
    
  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: 
      - styles.css
      - timeline.css
      - custom.css
    toc: true

editor: source
execute: 
  freeze: true
