project:
  type: website

website:
  title: "Sam Chisholm -- Updates"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
  
format:
  html:
    theme: spacelab
    css: 
      - styles.css
      - timeline.css
      - custom.css

    toc: true

editor: source

