---
title: "Updates"
author: Colin C.
# listing:
#   contents: posts
#   sort: "date desc"
#   type: default
#   categories: false
---

Updates are listed from most recent at the top to oldest at the bottom.  The [Timeline](./timeline.html) provides a quick review of the milestone in this current journey with Sam. 



## April 22, 2023 (am)

### TLDR

We are in a waiting period, and as results from Sam's biopsies trickle in, we have some knowledge of what the disease is not. Our hearts are peaceful and we have been filled with messages of love and prayer from around the world!

### Reflections on April 21, 2023

How long have we been here? As I write this, it is only the beginning of day four and I am writing about day three, so much has happened.

Yesterday, was ... a beautiful day. Sam was far more comfortable, being another day away from his biopsy surgery. It was wonderful to watch him sleep and nap on and off through the day. This time of rest also powered him up to visit with family. It was also great to see Tina catch up on some much-needed sleep.

#### Physical Health

Medically, it was generally a quiet day. No new tests, just the routine of checking vitals, checking blood chemistry, and taking medicines (e.g. pain management from the previous surgery). We are in waiting phase. The lab has not finished processing the tissue samples taken April 20th. Despite not knowing much yet the medical team continues to communicate. The best news was that we now know that the disease is: 

- *not* in the central nervous system 
- *not* in his bone marrow.

It might be a quiet weekend as lab results may not come back until mid-next week. So we wait as a family, and the medical team waits with us. One might think this is frustrating, but it is not, rather it is a peaceful and strategic waiting. Once the tests come back the doctors will be very intentional on how to manage Sam's health. So we wait, for the right understanding, and the subsequent right treatment plan.

#### Soul Health

Wow, what a good day! We have heard from so many friends, family, some of whom we have not connected with for years, but this challenging time is pulling our people together. Thank you for reaching out to us, conveying your care, telling us your stories, or simply what is happening in your world. We are supported by your words, your love, and your prayers.

People around the world are praying -- it's awesome. Friends, family, and their friends and families, bible study and prayer groups; from Prince George, across the province, across the continent, and as far away as Zambia!

We have also had some amazing face-to-face visits/care.

-   A friend anticipated our needs and showed up with a bag of groceries and goodies picked especially for Tina and her dietary neerequirements.
-   A providential visit with the Schellenbergs with whom we have shared so much life and adventure. What are the chances that they just happened to be in the area this weekend! For those who don't know them, they live in Saskatchewan.
-   Sam had a great visit with his cousin Chris, Uncle Cal, and Auntie Tricia.

To wrap up this post, please know that we feel cared for in soul and body. Although we do not know what treatment for Sam will look like, we are in a peaceful place. That might change, we may have challenges ahead, but we bolstered by your love, we are carried.

Love to you all!

Colin




## April 21, 2023 (am)

### TLDR

Yesterday: surgery for tissue samples followed by pain management. In the weeks to come, Sam will be here at BC Children Hospital as he is treated for what is assumed to be lymphoma.


### Reflections on April 20, 2023

Hi all,

Yesterday was a big day for Sam. He had the surgery to complete a series of biopsies. These included the removal of a lymph node at the base of his neck, a lumbar puncture, a bone marrow sample from the top of his hip, and establishing a PICC ([described here](http://www.cw.bc.ca/library/pdf/pamphlets/BCCH1552_PICC.pdf)) to facilitate ongoing blood work and upcoming intravenous drug delivery. All the procedures went well. Dr. Webber, completed the lymph node removal and said it went "Perfectly". This was all done before noon. The biggest challenge of the day has been pain management, but Sam has been a trooper.

The staff here continue to be amazing, always taking the time to answer any of Sam's questions, and making complex biology and bio-chemistry understandable. It is honestly amazing to hear Sam explain his disease to others -- he gets it, understands it, and given the situation is very glad to be here.

Next steps are not totally clear. We are working with the understanding/assumption that Sam has lymphoma ([one possibility described here](http://www.bcchildrens.ca/Oncology-Site/Documents/Non-Hodgkin%20Lymphoma.pdf)). The signs all point that way (e.g. X-ray and CT scan), but this will not be totally confirmed until the tissue samples are processed. Here is what we are currently expecting:

1.  Sam will start a round of drug treatment, as soon as later today, and specific treatments will be refined following the analysis of his tissue samples
2.  Sam is currently in the ICU, and we expect him to be here for the next number of days after which, he will be transferred to the oncology unit just a few floors above where he will remain a patient for three weeks or so (timing of stay will all depend on tests).
3.  Tina and I will be able to check into the Ronald McDonald House here on hospital campus on Sunday. This will give us a home base, we will also be able to continue staying in the room with Sam.

Many thanks to all of Sam's friends and teachers, and all of our friends and family. We love to hear from you. We may not get back to you right away but know your messages are encouraging to us. If you have any questions, please feel free to ask, and I will try to answer them either directly or in a following update.

Q&A

How is Tina doing?

:   She is actually great. She has been working so hard advocating for Sam's health over the last months, trying to get the bottom of why he has been sick. Now, she can relax as Sam is where he needs to be, receiving the medical care that he needs. She also loves the medical world, she is in her element here. Our biggest challenge for Tina will be to ensure she is properly fed, especially given her dietary restrictions. We will need to find a new normal here.

How can we help / Let us know if we can help.

:   Hearing from you is currently the best. As noted, we might not be able to get back to you right away, but all of your notes are encouraging. Tina and I have literally had tears-of-joy reading them.

Thanks again for your prayers and support,

Colin and Tina

***




## April 20, 2023 (am)

Hi friends,

The last 48 hours have been a whirlwind, and we are where we need to be.

Sam is now at BC Children's hospital, and Tina and I are able to stay in the room with him. Steps are being taken to manage what all indications suggest is lymphoma. Staff here have been amazing in: providing care, communicating what is happening and next steps, and conveying a sense that 'this is serious' mixed with a calming confidence.

The process: Yesterday, tests were run -- the primary one being a CT scan of his chest. Today, Sam will start the day with a surgery to complete a series of biopsies, the primary one being one of his lymph nodes at the base of his neck. By the end of the day, we should have firmer answers as to what exactly is happening and a treatment plan.

Sam's friends and classmates have been amazing. They have been in direct communication with him via Snapchat and hearing from them has been really encouraging to him, also to Tina and I -- it is amazing to see friends rally behind him.

Thank you for your support and prayers,

Colin and Tina

------------------------------------------------------------------------

