---
title: "Samuel Chisholm"
subtitle: "Much Loved ... Beloved"
date: 2024-11-25
date-modified: 2024-11-10
draft: true
draft-mode: unlink
# author: Colin C.
# listing:
#   contents: posts
#   filter-ui: false
#   fields: [image, date, title, author, categories, description]
#   sort: "date desc"
#   sort-ui: true
#   type: default
#   categories: false
#   feed: true
#   page-size: 10
tbl-colwidths: [15,60,25]
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
editor: 
  markdown: 
    wrap: 100
---

# DRAFT Order of Service

## Outline

1.  Welcome -- Invitation
2.  Much loved and Mighty Warrior
3.  Beloved
4.  Closing -- repeat Invitation
5.  Reception

## Invitation

::: callout-note
### Concepts

-   Invitation to join the family.
-   The family knows that you are grieving too.
-   The family is thankful that you are here -- to honour Sam; to extend your care; ... *more*
:::

+-----------------------+-------------------------------------------------+-----------------------+
| Activity              | Description                                     | Who                   |
+=======================+=================================================+======================:+
| Pre-service Slideshow | Option: Use memories submitted                  | Colin                 |
|                       |                                                 |                       |
|                       |                                                 | Tech team             |
+-----------------------+-------------------------------------------------+-----------------------+
| Welcome               | -   Invite (see above). Invite those online and | Pastor Rob            |
|                       |     those in the overflow room.                 |                       |
|                       | -   Review order of service -- or highlight     |                       |
|                       |     where it is printed                         |                       |
|                       | -   Simple short prayer of comfort              |                       |
+-----------------------+-------------------------------------------------+-----------------------+
|                       |                                                 |                       |
+-----------------------+-------------------------------------------------+-----------------------+

{{< pagebreak >}} \## Much loved Mighty Warrior

::: callout-note
### Much loved -- concepts

This section is focused on how Sam was loved – human love. It focuses on our time with Sam:

-   How we all loved him: Parents, Grandparents, Ex. Family, Friends, the community around us
-   How we honour him -- for his battle fought
-   What he loved ... can be a segue to Beloved
:::

+----------------------+-------------------------------------------------+----------------------+
| Activity             | Description                                     | Who                  |
+======================+=================================================+=====================:+
| Scripture ???        | Psalm 141                                       | FRIEND(s)?           |
|                      |                                                 |                      |
|                      |                                                 | Kelsey Fricker??     |
+----------------------+-------------------------------------------------+----------------------+
| Slide Show           | Show of Sam's life. Emphasis on how he was      | Colin, Tina to       |
|                      | loved.                                          | review               |
|                      |                                                 |                      |
|                      | *Ac. Set to music*                              |                      |
+----------------------+-------------------------------------------------+----------------------+
| FRIEND Memory        |                                                 | David Hillhouse      |
+----------------------+-------------------------------------------------+----------------------+
| FRIEND Memory        |                                                 | Chase Cross          |
+----------------------+-------------------------------------------------+----------------------+
| Family Memories      | Kevin shares how Sam was much loved and some    | Kevin Fricker        |
|                      | memories of our family                          |                      |
+----------------------+-------------------------------------------------+----------------------+
| Songs ???            | *Do we want songs here?*                        | Joel Cross           |
+----------------------+-------------------------------------------------+----------------------+
|                      |                                                 |                      |
+----------------------+-------------------------------------------------+----------------------+

```{=html}
<!-- -   Slide Show? (song background)
-   Songs?
-   Scripture? *read by a friend or two?*
-   Speaker(s)
    -   Uncle Kevin Fricker. Reflections on how the family loved Sam. ... *Kev what do you have in
        mind?*
    -   Pastor Nolan or Shane N. or ??? (community person)
-   Song(s) -->
```

{{< pagebreak >}} \## Beloved

::: callout-note
### Beloved -- concepts

This section is focused on how Sam is loved – enteral love. How God loves. It focuses on the hope
that Sam had.

-   Sam as the Beloved of God.
-   How we are all Beloved
-   How then should we live?
:::

+-----------------------+-------------------------------------------------+-----------------------+
| Activity              | Description                                     | Who                   |
+=======================+=================================================+======================:+
|                       |                                                 |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Slideshow             | Focus on the cancer battle. Sam as a mighty     | Colin and Tina        |
|                       | warrior. Key character traits that we saw       |                       |
|                       | develop in him.                                 |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Beloved of God        | Sam as Beloved                                  | Cal Townsend          |
|                       |                                                 |                       |
|                       | All as Beloved                                  |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Scripture             | How then should we live                         | Kaden Fricker???\     |
|                       |                                                 | Family member         |
|                       | Micah 6:8; ???                                  |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Thoughts              | How then should we live? If Sam was Beloved and | ???                   |
|                       | we are all Beloved.                             |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Songs ???             | ??? Celebration 'camp songs'                    | Joel Cross            |
+-----------------------+-------------------------------------------------+-----------------------+
|                       |                                                 |                       |
+-----------------------+-------------------------------------------------+-----------------------+

```{=html}
<!-- -   scripture
-   Speakers
    -   Uncle Cal -- reflection on Sam and how he is Beloved. How we are Beloved.
    -   Dave Horton? -- How then should we live?
-   Celebration songs (Camp Songs) -->
```

{{< pagebreak >}} \## Closing

::: callout-note
## Purpose

-   Recognize that our grief does not end here and now
-   We will continue to honour Sam's life
    -   Gifts to Legacy Fund
-   We will continue to love and support the family
-   Sam was and is loved.
-   Invite to reception
:::

+-----------------------+-------------------------------------------------+-----------------------+
| Activity              | Description                                     | Who                   |
+=======================+=================================================+======================:+
| Announcements         | -   Gifts – Sam's legacy fund explained:        | Rob                   |
|                       |     -   Purpose, description, and management    |                       |
|                       |     -   Table in foyer                          |                       |
|                       |     -   Web Form                                |                       |
|                       | -   Reception and Youth Reception               |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Charge to\            | -   Grief does not end here                     | Rob                   |
| Friends and Family    | -   Continue to support Colin and Tina          |                       |
|                       | -   Continue to support one another             |                       |
|                       | -   It still hurts and likely will for some     |                       |
|                       |     time                                        |                       |
+-----------------------+-------------------------------------------------+-----------------------+
| Benediction           | Numbers? ???                                    | Rob                   |
+-----------------------+-------------------------------------------------+-----------------------+

{{< pagebreak >}} ::: callout-warning \## Needs and Actions

-   Review and refinement of this outline
    -   Tina
    -   Kevin
    -   Cal
    -   Gradparents
    -   Rob D.
-   Westwood and Friends:
    -   Pastor Rob -- coordination of events
    -   Ushers – *COUSINS?*
    -   Reception – *Sylvia and Del R. will coordinate.*\
        *Can Nolan coordinate the youth reception*
    -   ~~Childcare?~~
    -   Sound/Tech coordination?
    -   Songs – embed into the slide shows?
-   What songs to sing? And who to lead them (Joel?)?
-   What scriptures to be read and who to read them (friends?)?
-   Printing of Program
-   Website:
    -   Update Memorial News
    -   Legacy Fund -- page to outline purpose
    -   Program
    -   Memories of Sam Form :::

::: callout-note
## Reception Ideas

Sylvia (and Del) Reinheimner – will be the point people to coordinate Reception. Nolan to coordinate
for the youth?

### Main Reception

-   Tables along the outside walls of the lobby/foyer.

-   Sam's favourite food and chocolate/candies.

    -   Oreo cookies
    -   coffee crisp
    -   sour patch kids
    -   salt and vinegar
    -   pizza

-   Use the MealTrain contact list to provide food for the reception.

### Youth Reception

-   Youth centre will be used as overflow seating.
-   Candy Buffet
-   Small gifts from the family
:::