---
title: "The Plan"
author: Colin C.
date: 2023-09-05
date-modified: 2023-10-15
draft: false
editor: 
  markdown: 
    wrap: 72
---

::: callout-important
## Main Changes

1.  BMT transplant date: ~~Nov 9~~ ***Nov 14***
2.  Updates to the countdown dates.
:::

Following round four, Sam had a PET scan to determine how his cancer was
progressing. Results indicated that we continue to move in the right
direction. The cancer was reduced in size and remained in known
locations -- that is it had not spread anywhere else. However, it was
also apparent that the rate of reduction was not enough to remove the
cancer by the end of this chemotherapy regime.

Round six of Sam's initial chemotherapy
treatment is now complete. The PET scan results support the current plan to provide a bone marrow transplant. As the BMT date approaches Sam will have a number of tests to
determine his baseline health before starting his bone-marrow-transplant
protocol.

## BMT Plan

*BMT: Bone Marrow Transplant*\

::: callout-warning
## Disclaimer

I feel I need a quick disclaimer here as I am not sure I have all of
this right. In addition, the following dates are rough estimates from
the medical team. In broad strokes I think most of the items below are
pretty much there ... dates and details are likely to change.
:::



### Overview 

This is the plan as I understand it:

1.  Sam has completed the full six rounds of his initial chemotherapy.

2.  In preparation for BMT Sam will see numerous specialists throughout
    BC Childrens and the BC Cancer Clinic. The goal will be to create a
    strong baseline of Sam's health going into BMT.

3.  Bone Marrow Transplant: Day zero is expected to be ***Nov. 14*** .\
    Following the current chemotherapy we will transition to BMT. The
    medical team refers to the actual transplant day as day 0.
    Activities prior to this day are count-down days and then the days
    following start counting up.

    -   *Days -22 to -11* (\~Oct. 23): Radiation targeting whatever
        cancerous masses remain. The goal is to set the cancer back as
        hard as they can.

    -   *Day -6 and -4*: Full body radiation to ensure Sam's own immune
        system is completely removed -- in preparation for replacing
        with the transplant/ graft immune system.

    -   *Days -3 to -1*: Chemotherapy to suppress and remove Sam's own
        immune system.

    -   *Day zero*, currently planned for Nov. 14, Sam should receive the
        transplant. This is actually quite simple -- like receiving a
        blood transfusion. The team will hang the bag of bone marrow
        products and pump it into Sam's body via his central line.

    -   *Days 0 to 30* Sam will be in an isolation room with strict
        protocols. Tina and I, along with the medical team will be
        allowed in.

    -   *Days 31 through 90*: If all goes well Sam will be allowed out
        of the hospital but is to remain close for regular check-ins.


### Treatment Objectives 

### Challenges ahead

_Below is copied from our [Oct. 20^st^ post](/posts/2309/2023-10-18_knife-edge-no-assurances.qmd)_



Radiation therapy -- phase 1: *Targeted radiation*

:   The objective here is to directly attack the cancer and destroy as
    much as possible. There are both immediate and long term challenges.
    The radiation oncologist is trying to balance attacking the cancer
    while protecting the adjacent lungs which are very sensitive to
    radiation damage. In the short term there will be fatigue and pain
    -- think of a time that you had a bad sun burn. Now take that
    sunburn and put it on the inside of your body. Sam may feel it most
    in his throat.

Radiation therapy -- phase 2: *Total body irradiation (TBI)*

:   Next, Sam will undergo three days of total body radiation (TBI).
    This radiation will not target his cancer, rather it is undertaken
    to condition his body for the upcoming bone marrow transplant. TBI
    has the objective of permanently destroying Sam's native immune
    system so that his immune system will not compete with the
    transplant.

:   There is a long list of potential side effects from the two
    radiation treatments. A few of these include: permanent scarring of
    the lungs, impacts on the thyroid, heart disease, changes to
    metabolism, secondary cancers, and others. Needless to say this can
    be scary.

:   This step, in conjunction with the following BMT Chemotherapy, mark
    a point of no return. Once these steps are initiated a transplant
    must happen for Sam to ever have an immune system again.


BMT Chemotherapy

:   The previous chemotherapy that Sam has had focused on targeting and
    removing the disease. This upcoming chemotherapy has a different
    objective. In conjunction with TBI it will be used to remove Sam's
    own immune system. Following this chemotherapy any cells that
    produce/create blood will have been killed, and Sam's bone marrow
    will be ready to receive the transplant. As with most chemotherapy
    drugs this treatment will likely make Sam feel ill.

The transplant/graft

:   On Nov. 14^th^ Sam is scheduled to receive the donated bone marrow.
    The donated cells will need to establish or engraft to start
    providing Sam his new immune system. In the 2-3 weeks following
    receiving the transplant we will wait in anticipation for signs that
    the graft is taking hold. The whole transplant process will take
    place in an isolation room -- Sam will not be allowed to leave until
    his new immune system takes hold. Tina and I will be able to gown-up
    and be with him.

:   This will be a hard number of weeks. Given the prior steps Sam will
    likely feel horrible for numerous weeks. It is highly likely that he
    will need significant intravenous supports for management of pain,
    nausea, engraftment of the new immune system, hydration, nutrition,
    and then potentially additional medication should he become ill
    without an immune system to support him. To provide all of these
    supports Sam may need upward of 15 different intravenous lines to
    all be connected at once. His current central lines should support
    most of this.

:   Once the graft takes hold it will start generating Sam's new immune
    system and start fighting for him, including battling the cancer.
    However, this is a foreign immune system and steps will need to be
    taken ensure that the graft does not attack Sam -- potential graft
    versus host disease. The graft also must remain aggressive enough to
    continually attach the cancer.

## Choosing hope

There are many reasons to be consumed by fear -- to allow the beast of
Despair to have a foothold in our lives. Sure we have our moments of
anxiety -- but we choose hope. Sam remains a champion. We have also laid
out some great ideas for his time in isolation -- I hope he will feel
well enough to take part in the activities we have planned.

We invite you to choose hope with us. It does make this journey easier
knowing that you are there with us in mind and spirit. Please continue
in your commitment to care and prayer.
