---
title: Milestones
date-modified: 2024-06-11
tbl-colwidths: [25,75]
---


Generally speaking, Sam has been through three eras in his cancer
treatment: 

1. Chemotherapy, 
2. Bone Marrow Transplant, 
3. and now Immunotherapy.
   
Radiation was given both before the BMT and also concurrent with immunotherapy. 
   
Below is a review of the major milestones.

## Chemotherapy

+--------------+-------------------------------------------------------------+
| Date         | Description                                                 |
+==============+=============================================================+
|              |                                                             |
| **2023**     |                                                             |
|              |                                                             |
+--------------+-------------------------------------------------------------+
| April 17     | An alarming x-ray in                                        |
|              | Prince George                                               |
|              | provided evidence that                                      |
|              | Sam needed urgent                                           |
|              | care at BCCH.                                               |
+--------------+-------------------------------------------------------------+
| April 18     | Air Ambulance in the                                        |
|              | early morning and                                           |
|              | admission to BCCH's                                         |
|              | PICU.                                                       |
+--------------+-------------------------------------------------------------+
| April 22     | Transfer to BCCH                                            |
|              | Oncology Ward (T8).                                         |
+--------------+-------------------------------------------------------------+
| April 28     | Diagnosis of a extremely                                    |
|              | rare form of                                                |
|              | lymphoma.                                                   |
+--------------+-------------------------------------------------------------+
| April 29     | Chemotherapy is                                             |
|              | initiated. Sam will                                         |
|              | receive an additional 6                                     |
|              | full rounds of                                              |
|              | chemotherapy taking him                                     |
|              | into October.                                               |
+--------------+-------------------------------------------------------------+
| June 2       | Following his second                                        |
|              | round of chemotherapy                                       |
|              | Sam was discharged from                                     |
|              | the hospital for the                                        |
|              | first time. This marks                                      |
|              | the beginning of our                                        |
|              | family life at RMH. The                                     |
|              | next months we would                                        |
|              | visit the oncology                                          |
|              | clinic regularly. When                                      |
|              | it was time for each                                        |
|              | round of chemotherapy we                                    |
|              | would check into the                                        |
|              | ward for about 5 days.                                      |
+--------------+-------------------------------------------------------------+
| July 14      | Plans for a bone marrow                                     |
|              | transplant were                                             |
|              | initiated. By                                               |
|              | mid-summer it became                                        |
|              | apparent that the                                           |
|              | chemotherapy would not                                      |
|              | remove all of the                                           |
|              | cancer. The remaining                                       |
|              | rounds of                                                   |
|              | chemotherapy would                                          |
|              | reduce the cancer as                                        |
|              | much as possible, and                                       |
|              | keep it from                                                |
|              | spreading to new                                            |
|              | locations, while the                                        |
|              | BMT was being organized.                                    |
|              |                                                             |
+--------------+-------------------------------------------------------------+
| Sept. 26     | Preparations for BMT,                                       |
|              | baseline testing of Sam                                     |
|              | was initiated to                                            |
|              | evaluate impacts of the                                     |
|              | BMT (i.e. eye, ear,                                         |
|              | skin, and lung capacity                                     |
|              | testing).                                                   |
+--------------+-------------------------------------------------------------+
| Oct. 15      | Sam completed his final                                     |
|              | round of                                                    |
|              | chemotherapy.                                               |
+--------------+-------------------------------------------------------------+
| Oct. 23      | Targeted radiation                                          |
|              | therapy over three days                                     |
|              | to destroy the                                              |
|              | central mass in Sam's                                       |
|              | chest is initiated. This                                    |
|              | was completed at the BC                                     |
|              | Cancer Centre over 10                                       |
|              | days.                                                       |
+--------------+-------------------------------------------------------------+
| Nov. 8       | Total body radiation is                                     |
|              | used to completely                                          |
|              | remove Sam's existing                                       |
|              | immune system – to kill                                     |
|              | the blood producing                                         |
|              | cells in his bone                                           |
|              | marrow. This was done to                                    |
|              | make way for the bone                                       |
|              | marrow                                                      |
|              | transplant.                                                 |
+--------------+-------------------------------------------------------------+




## Bone Marrow Transplant

+--------------+-------------------------------------------------------------+
| Nov. 14      | Bone marrow                                                 |
|              | transplant is                                               |
|              | received. Sam had                                           |
|              | been admitted to                                            |
|              | the oncology ward a                                         |
|              | few days prior in                                           |
|              | preparation and                                             |
|              | would remain on                                             |
|              | ward in isolation for                                       |
|              | the next                                                    |
|              | number of weeks.                                            |
|              | This was a                                                  |
|              | particularly                                                |
|              | intense time as the                                         |
|              | medical team had to                                         |
|              | provide so many                                             |
|              | supports to his                                             |
|              | body                                                        |
+--------------+-------------------------------------------------------------+
| Nov. 25      | First indications                                           |
|              | that the BMT was                                            |
|              | establishing –                                              |
|              | engraftment.                                                |
|              | Official                                                    |
|              | engraftment would                                           |
|              | be  established                                             |
|              | on Dec. 1 based on                                          |
|              |    metrics from                                             |
|              | Sam's blood.                                                |
+--------------+-------------------------------------------------------------+
| Dec. 13      | Sam is discharged                                           |
|              | from the hospital                                           |
|              | with plans to                                               |
|              | continue regular                                            |
|              | check-ins at the                                            |
|              | oncology clinic.                                            |
+--------------+-------------------------------------------------------------+
| **2024**     |                                                             |
+--------------+-------------------------------------------------------------+
| Jan. 11      | Stepping down from                                          |
|              | all of the various                                          |
|              | medications                                                 |
|              | had its challenges.                                         |
|              | Sam was admitted to                                         |
|              | the ward for eight                                          |
|              | days to determine                                           |
|              | what was causing                                            |
|              | his extreme                                                 |
|              | lethargy. It was a                                          |
|              | complicated picture                                         |     
|              | as we all had a flu                                         |
|              | in the days prior                                           |
|              | but what Sam was                                            |
|              | experiencing was                                            |
|              | more. In the end                                            |
|              | the main issue                                              |
|              | seemed to be                                                |
|              | adrenal insufficiency.                                      |
+--------------+-------------------------------------------------------------+



## Immunotherapy

+---------------+------------------------------------------------------------+
| Feb. 14       | PET scan, that we were                                     |
|               | all hoping to be                                           |
|               | Sam's last before                                          |
|               | having to go home,                                         |
|               | revealed a horror – the                                    |
|               | cancer had spread to                                       |
|               | three new locations.                                       |
|               | New battle strategies                                      |
|               | are brought into play.                                     |
|               | Plans to return home are                                   |
|               | canceled.                                                  |
+---------------+------------------------------------------------------------+
| Feb. 29       | Sam receives his first                                     |
|               | dose of Nivomulab used to                                  |
|               | intentionally                                              |
|               | de-regulate Sam's                                          |
|               | immune system and to                                       |
|               | turn off specific                                          |
|               | protein markers on the                                     |
|               | cancer cells that allow                                    |
|               | them to hide from the                                      |
|               | immune system.                                             |
+---------------+------------------------------------------------------------+
| March 11      | Targeted radiation                                         |
|               | starts against the three                                   |
|               | new                                                        |
|               | sites. The shin and hip                                    |
|               | sites would see higher                                     |
|               | doses over four days.                                      |
|               | The T3-vertebrae would                                     |
|               | see lower daily                                            |
|               | radiation doses over                                       |
|               | ten days.                                                  |
+---------------+------------------------------------------------------------+
| April 5       | PET scan demonstrated                                      |
|               | that: a\) The three new                                    |
|               | disease sites had been                                     |
|               | effectively killed                                         |
|               | using radiation, b\) the                                   |
|               | central mass was stable                                    |
|               | c\) However, a new site                                    |
|               | in Sam's liver raised                                      |
|               | new alarm bells.                                           |
+---------------+------------------------------------------------------------+
| April 11      | Biopsy of the liver                                        |
|               | revealed that this mass                                    |
|               | is not Sam's original                                      |
|               | cancer but an indistinct                                   |
|               | mass that will be                                          |
|               | monitored.                                                 |
+---------------+------------------------------------------------------------+
| *April 21*    | *Five day break -- home!                                   |
|               | Two days of travel and                                     |
|               | three days in Prince                                       |
|               | Family, school, quick                                      |
|               | visits with friends, and                                   |
|               | an initial connection                                      |
|               | with the local medical                                     |
|               | team.*                                                     |            
+---------------+------------------------------------------------------------+
| May 8         | PET Scan indicates that                                    |
|               | the central mass has                                       |
|               | grown confirming active                                    |
|               | disease.                                                   |
+---------------+------------------------------------------------------------+
| May 15        | All immune suppressants                                    |
|               | have been removed and we                                   |
|               | wait to see what Sam's                                     |
|               | new immune system can do.                                  |
+---------------+------------------------------------------------------------+
| May 22        | Contrast CT                                                |
|               | Results suggest that the                                   |
|               | cancerous mass is stable.                                  |
+---------------+------------------------------------------------------------+
| May 29        | *Ten day break home!*                                      |
|               | As liver numbers                                           |
|               | remained stable and there was no significant change in the |
|               | cancer from the previous CT it was was deemed safe to make |
|               | a trip home.                                               |
+---------------+------------------------------------------------------------+

