---
title: "The Last Supper"
description: "Jesus presents himself as the fulfilment of God's promise"
author: Colin C.
date: 2024-02-11
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 14: 12 - 26](https://www.bible.com/bible/111/MRK.14.NIV)

> On the first day of the Festival of Unleavened Bread, when it was customary to sacrifice the Passover lamb, Jesus’ disciples asked him, “Where do you want us to go and make preparations for you to eat the Passover?”
>
> So he sent two of his disciples, telling them, “Go into the city, and a man carrying a jar of water will meet you. Follow him. Say to the owner of the house he enters, ‘The Teacher asks: Where is my guest room, where I may eat the Passover with my disciples?’15He will show you a large room upstairs, furnished and ready. Make preparations for us there.”
>
> The disciples left, went into the city and found things just as Jesus had told them. So they prepared the Passover.
> 
> When evening came, Jesus arrived with the Twelve. While they were reclining at the table eating, he said, “Truly I tell you, one of you will betray me—one who is eating with me.”
>
> They were saddened, and one by one they said to him, “Surely you don’t mean me?”
>
> “It is one of the Twelve,”he replied, “one who dips bread into the bowl with me. The Son of Man will go just as it is written about him. But woe to that man who betrays the Son of Man! It would be better for him if he had not been born.”
>
> While they were eating, Jesus took bread, and when he had given thanks, he broke it and gave it to his disciples, saying, “Take it; this is my body.”
>
> Then he took a cup, and when he had given thanks, he gave it to them, and they all drank from it.
>
> “This is my blood of the covenant, which is poured out for many,” he said to them. “Truly I tell you, I will not drink again from the fruit of the vine until that day when I drink it new in the kingdom of God.”
>
> When they had sung a hymn, they went out to the Mount of Olives.

### Thoughts and questions 

This story is hugely significant.  There are a couple key things going but the most important is when Jesus shares the last super and says that his body and blood are the fulfillment of God's covenant.  I'll describe this a bit more below.  

The other key item is that Jesus knows he is going to be betrayed.  For who's sake did he talk about this?  I think he let everyone know that he would be betrayed -- so that they would all be prepared and so they would understand that this was part of Jesus' plan.  I think it is also interesting that they all asked "Surely not I" ... perhaps they all feared their own weaknesses.  

The last supper, what we celebrate as communion in church, if probably the most unifying thing between Christians since this last supper with Jesus.  We break the bread and drink wine or juice to represent His blood.  Sharing the bread and wine, remembering Jesus, and covenant has been going on for almost 2000 years!  

But what is the covenant?  Here it is important to understand the Jewish Passover going back to when God rescued his people from Egypt.  A lamb was sacrificed and the blood placed on the doorframes of the Jewish homes marking the homes as sanctuaries from the angel of death.  Saving the people from death and recusing them from the hands of their oppressors -- the Egyptians.  

By this last supper Jesus replaces the sacrificed lamb with himself.  As a fulfillment of God's promise to keep his people safe from death and rescue them from their oppressors.   Safe-from-death, being the promise of eternal life -- in the kingdom of God.  

I do wonder about the oppressors.  How did God rescue his disciples from their oppressors?  He certainly made a break from the religious oppression of the day.  How does this apply today?  Many 'churchy' answers are I am freed from sin and guilt -- this is likely true. But I can't help but think it is more nuanced than that.  As a follower imitator of Christ is there oppression that I need to be freed from?  Or perhaps, I need to work to free others from injustice and oppression.   How does placing my faith in Jesus free me and how should I act to free others? 

### Prayer

Lord God you have freed me! I hold to the promise to meet you in your kingdom.  That you will save me from death, gifting me with eternal life.  Help me to understand the freedom that you have made for me.  Help me to bring freedom to others -- that they would know the promise and hope that you provide.  