---
title: "Honor and Betrayal"
description: "Jesus is honored by one follower and betrayed by another"
author: Colin C.
date: 2024-02-10
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 14: 1 - 11](https://www.bible.com/bible/111/MRK.14.NIV)

> Now the Passover and the Festival of Unleavened Bread were only two days away, and the chief priests and the teachers of the law were scheming to arrest Jesus secretly and kill him. “But not during the festival,” they said, “or the people may riot.”
>
> While he was in Bethany, reclining at the table in the home of Simon the Leper, a woman came with an alabaster jar of very expensive perfume, made of pure nard. She broke the jar and poured the perfume on his head.
>
> Some of those present were saying indignantly to one another, “Why this waste of perfume? It could have been sold for more than a year’s wages and the money given to the poor.” And they rebuked her harshly.
>
> “Leave her alone,”said Jesus. “Why are you bothering her? She has done a beautiful thing to me. The poor you will always have with you, and you can help them any time you want. But you will not always have me. She did what she could. She poured perfume on my body beforehand to prepare for my burial. Truly I tell you, wherever the gospel is preached throughout the world, what she has done will also be told, in memory of her.”
>
> Then Judas Iscariot, one of the Twelve, went to the chief priests to betray Jesus to them. They were delighted to hear this and promised to give him money. So he watched for an opportunity to hand him over.

### Thoughts and questions 

The passage starts and ends with the desire to bring Jesus down.  The religious leaders trying to find a means of killing Jesus and Judas Iscariot providing that means.  But why?  Why try to kill Jesus?  

Taking into account the passages that we have already gone through the motivation behind the religious leaders is pretty clear.  It is obvious from when Jesus entered Jerusalem that the people loved him (chapter 11).  The stories go on to show that the people loved his teaching while his teachings often humiliated or directly attacked the religious leaders.  But why would one of his own betray him?  

We will likely never know for certain but perhaps this passages provides some clues.  Judas Iscariot might have been in it for the money and this waste was just too much.  Or perhaps he could not stand the talk of Jesus' upcoming death -- perhaps he wanted more open revolt.  It seemed that what happened that day at Simon's house pushed Judas over the edge -- he could not follow Jesus anymore.  

The middle part of the story is really interesting to me as woman with the alabaster perfume honors Jesus. This was her gift to him.  It was expensive, extravagant gift and act of service to Jesus.  Yet I know part of me, like other Jesus followers there, would have reacted and said it was a waste.  I am rebuked by this story.  I need to pause and ask what extravagant gift could I bring? How can I honor Jesus in my life here and now? 


### Prayer

Lord Jesus, did your heart break at being betrayed by a friend?  Mine would. The agonies that you would face in the time following that day at Simon's house.  

Your life, your sacrifice is a gift beyond measure to the world ... to me.  Lord what gift of love can I bring you?  