---
title: "You will fall away"
description: "Jesus knows his disciples will fail -- but he loves them and plans to go ahead of them."
author: Colin C.
date: 2024-02-15
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 14: 27 - 31](https://www.bible.com/bible/111/MRK.14.NIV)

> “You will all fall away,” Jesus told them, “for it is written:
>
> “‘I will strike the shepherd,\
> and the sheep will be scattered.’
>
> But after I have risen, I will go ahead of you into Galilee.”
>
> Peter declared, “Even if all fall away, I will not.”
>
> “Truly I tell you,” Jesus answered, “today—yes, tonight—before the rooster crows twice you yourself will disown me three times.”
>
> But Peter insisted emphatically, “Even if I have to die with you, I will never disown you.” And all the others said the same.

### Thoughts and questions 

Falling away is not betrayal.  This short passage is tragic but beautiful.  It is beautiful as Jesus knows what will happen and despite all he is about to face he is compassionate -- providing promise in the warning:

> _But after I have risen, I will go ahead of you into Galilee_ 

Despite our best intentions, like Peter and the rest, we fail.  Peter was intent that he would not fail Jesus yet we know that he did.  Despite our failings I think Jesus' promise for his disciples is just as true for us today -- _I will go ahead of you_.  Jesus did not reject his disciples he conquered death and then went on to meet them.  It is a wonderful and beautiful thing that we are loved and accepted by God.  How is he going before us?  I need to watch for him to meet him along the way.


:::::: {.callout-note}
I am likely placing too much into this text, extending this passage to mean that Jesus is going before us in our lives today.  However, I do believe from my experience and from my understandings of the scriptures that this idea is true.
:::



### Prayer

I am grateful Lord that you forgive me Lord when, despite my best intentions, I fail. 
You did it you conquered death, you became the sacrifice.  Please go before me and prepare the way for me.  I long to be in your presence.  