---
title: "Please take this cup from me"
description: "Jesus is in desperate prayer -- _does it have to be this way?_"
author: Colin C.
date: 2024-02-17
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 14: 32 - 42](https://www.bible.com/bible/111/MRK.14.NIV)

> “They went to a place called Gethsemane, and Jesus said to his disciples, “Sit here while I pray.” He took Peter, James and John along with him, and he began to be deeply distressed and troubled. “My soul is overwhelmed with sorrow to the point of death,” he said to them. “Stay here and keep watch.”
>
> Going a little farther, he fell to the ground and prayed that if possible the hour might pass from him. “Abba,  Father,” he said, “everything is possible for you. Take this cup from me. Yet not what I will, but what you will.”
>
> Then he returned to his disciples and found them sleeping. “Simon,”he said to Peter, “are you asleep? Couldn’t you keep watch for one hour? Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak.”
>
> Once more he went away and prayed the same thing. When he came back, he again found them sleeping, because their eyes were heavy. They did not know what to say to him.
>
> Returning the third time, he said to them, “Are you still sleeping and resting? Enough! The hour has come. Look, the Son of Man is delivered into the hands of sinners. Rise! Let us go! Here comes my betrayer!”


### Thoughts and questions 

What a hard passage.  Jesus wrestles with what he knows id before him.  He is desperate.  Sure we know that Jesus goes on to face his crucifixion but in this moment he is desperate.  He is pleading with God that he would not have to go through this -- his own death and by crucifixion.  To make it worse, he calls on his friends -- he does not want to do this alone.  Despite their desires to care for him they fail and he struggles alone.  Even when he goes to his friends again, they just don't know what to say -- what words could they have had that would have brought comfort to Jesus in this desperate hour.  

_Daddy, I know you love me.  Please help. Please I don't want this.  You can do anything -- please rescue me.  But I will follow your plan, I will face death for your purposes._ (my paraphrase)

It is a beautiful and wonderful thing that God loved us enough to die in our place -- giving us eternal hope and life everlasting.


::: {.callout-note icon="false"} 
## Too close to home

Honestly, I hate how this story parallels your's right now. This cancer is scary.  We don't want it.  Yet, we trust in God, knowing that He is powerful enough to rescue you from it.  I plead with God for your life.  Jesus knew his destiny -- we do not know yours.  I pray that God would rescue you and give you a long life.  

Sam, my son, I love you, and I will stand by you, I will back you up, all the way through this cancer-war. 

Like you, I trust God and the purposes He has for you.

:::

### Prayer

_Adaptation of the Lord's Prayer_

Father God in heaven -- you are Holy; you are Good. \
Let you power be known in our lives -- let your kingdom break-through.

Take care of our needs and comfort our hearts.\

Show us how to act rightly, justly, to show compassion and forgiveness.\
Help us to walk Your paths -- that we would live for Your purposes and not our own.  
