---
title: "Peter's Denials"
description: "Peter follows at a distance.  Faced with accusation he denies Jesus."
author: Colin C.
date: 2024-02-20
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 14: 66 - 72](https://www.bible.com/bible/111/MRK.14.NIV)

> While Peter was below in the courtyard, one of the servant girls of the high priest came by. When she saw Peter warming himself, she looked closely at him.
> 
> “You also were with that Nazarene, Jesus,” she said.
> 
> But he denied it. “I don’t know or understand what you’re talking about,” he said, and went out into the entryway.
> 
> When the servant girl saw him there, she said again to those standing around, “This fellow is one of them.” Again he denied it.
> 
> After a little while, those standing near said to Peter, “Surely you are one of them, for you are a Galilean.”
>
> He began to call down curses, and he swore to them, “I don’t know this man you’re talking about.”
>
> Immediately the rooster crowed the second time. Then Peter remembered the word Jesus had spoken to him: “Before the rooster crows twice you will disown me three times.” And he broke down and wept.

### Thoughts and questions 

If I place myself in Peter's situation I am desperate to know what is going to happen to Jesus.  I must follow him and learn what I can.  I suspect that Peter was able to hear the trial as an eye-witness to the events.  But definitely, he was afraid -- that the authorities would get him too.  So he lies to save his own skin.  One of my bible footnotes made note of an ironic statement in Peter's first denial: _I don't understand what you are talking about_. The irony being that Peter and the disciples rarely seemed to understand what Jesus was talking about.  

This idea makes me wonder if Peter's experience and understanding of Jesus were solidified when the rooster crowed.  Was it at that moment that he finally understood.  Did he weep because he finally understood or did he weep because of feelings of guilt related to his own denial -- perhaps both.  

As we look forward, considering what we know of this story.  How does Jesus treat Peter?  He definitely does not reject him -- rather Peter becomes the head of the early church.  It is beautiful that Jesus keeps loving us -- even when we fail him. 

### Prayer

Lord give me the strength to follow you where ever that may lead.\
I know that I am secure in your love despite my own weaknesses, my own failings.