---
title: "Arrested"
description: "Judas brings a group to arrest Jesus"
author: Colin C.
date: 2024-02-18
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 14: 43 - 52](https://www.bible.com/bible/111/MRK.14.NIV)

> Just as he was speaking, Judas, one of the Twelve, appeared. With him was a crowd armed with swords and clubs, sent from the chief priests, the teachers of the law, and the elders.
>
> Now the betrayer had arranged a signal with them: “The one I kiss is the man; arrest him and lead him away under guard.” 
> 
> Going at once to Jesus, Judas said, “Rabbi!” and kissed him. The men seized Jesus and arrested him. Then one of those standing near drew his sword and struck the servant of the high priest, cutting off his ear.
>
> “Am I leading a rebellion,” said Jesus, “that you have come out with swords and clubs to capture me? Every day I was with you, teaching in the temple courts, and you did not arrest me. But the Scriptures must be fulfilled.” Then everyone deserted him and fled.
>
> A young man, wearing nothing but a linen garment, was following Jesus. When they seized him, he fled naked, leaving his garment behind.

### Thoughts and questions 

It is understood that it was a common cultural practice to greet your friends with a kiss (likely on the cheek). Though this might be a little weird to us it is used in other cultures -- common in Europe and Latin America. Jesus already knew his betrayer -- I wonder if it hurt him again that the betrayal came using a signal of friendship?

The religious leaders never seemed to understand Jesus.  Or else they were just taking nothing for granted, as they sent an armed group -- ready for a fight.  It seems at least one of the disciples also wanted a fight -- cutting off the ear of the servant to the high priest. But we know that Jesus was not after political revolution as he allowed himself to be arrested -- while, as predicted, his followers fled abandoning him.

The last sentence in this passage is a weird one.  What's the deal with the guy that ran away naked?  One of Jesus' followers had fallen asleep in his underwear (remember it is a warm climate there)?  This sentence doesn't seem to have any weight in the story -- no purpose.  Perhaps the author thought it was funny?  Some scholars suggest that this is the author writing himself into the story as a quick way of saying I was there.

### Prayer

Lord grant me the peace and confidence to follow the path you lay out before me even when it leads me to where I do not want to go.  I know that you will accomplish your purposes -- ones may be far greater than I could imagine.  Your obedience led to the salvation of the world.  Let my trust in you, whatever path lies before me, bring people to your love and hope. Show me your way. 