---
title: "From Step-down to Stepping-out"
description: "Sam nears the completion of the step-down process.  With each day we are close to leaving the hospital."
author: Colin C.
date: 2023-12-11
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---


It has now been 27 days since Sam received his BMT.  The initial couple weeks had big challenges and Sam needed a lot of medical supports.  His IV-tower was huge with a dozen lines running at once.  In the last ten days that has all changed!  

:::center
_I finally feel like myself again!_
-- Sam
:::


Over the last ten days the team has been continuous reducing the number of medical supports.  With one exception all his medications have been converted to pills. Sam has his appetite back and has been eating really well.  The tube feed has been there as a back up for a few hours a day but I expect the we will try to stopping it's use today.  All this means Sam is IV-tower free for most of waking hours.  

We are also seeing him return to energy.  A couple weeks ago it was difficult to cross the room.  Now, we are taking laps around the ward.  One thing that we will miss is the Sam's personal cheerleader-squad as the nurses literally cheer when he goes by the nurses station!  On Saturday Sam had an afternoon pass -- we left the hospital and wheeled over to the Ronald McDonald House.  Sam loved the cool fresh air! 

For Tina and I, it feels like a massive weight is being lifted.  We knew that this time has been hard... but I don't think we fully understood the pressure we were under.  We are now beginning to be able to contemplate returning to home -- though that is still a couple months away.  

## Next steps

Sam has done incredibly well and this engraftment process, so far, has gone smoothly and quickly.  It is likely that Sam will be discharged from the hospital later this week -- well ahead of schedule (previously we were hoping to get out a few days before Christmas). 

Once out life should be simpler.  We will be at the Ronald McDonald House (RMH) and visit the clinic 2-3 times per week to check on Sam's progress and monitor for any Graft Versus Host Disease related issues.  Practically speaking this means regular blood-work.  Sometime in the weeks and months ahead Sam will receive a PET scan or two to confirm that the cancer has been defeated.

Once out the next major milestone will be _Day 100_ (past the BMT).  This will be the day we should have the green-light to go home!  


## Victories and concerns

-   Sam is returning to strength!  We expect to be out of the hospital and living back at the RMH later this week.

-   Sam's bones are generating new blood! The engraftment process is working!  We have seen Sam's numbers come up and now stabilize! 

-   What an incredible birthday present. Sam's ANC blood metric went
    from non-detectable to 0.3. A strong indicator that the transplant
    is taking hold!

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   Thankful that what Sam has experienced so far is within the normal
    for a BMT and that he has not had any complications. Although it is
    all in the 'normal', it is not all easy:

    -   Nausea is under control! We have seen the reduction of meds and will be testing removal of some anti-nausea meds.  ~~Impacts from the pre-treatment, chemotherapy and radiation,
        remain strong. These cause deep bone and muscle pain, along with
        nausea. *These are starting to resolve!*~~
    -   Pain management is under control!  Sam is on a regular dose of morphine which he will start reducing over the weeks ahead.
    -   Nutrition mainly by mouth and I expect the NG tube will be removed in the next few days.
    -   Energy levels are returning! -- it is great to see Sam
        roam the halls! 

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he is in a
    phase where he has no immune system for the next few weeks.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.