---
title: "Engraftment!"
description: "Fourteen days after the transplant engraftment became official."
author: Colin C.
date: 2023-12-01
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

Time here in the hospital feels so warped. It is hard to believe that we
have been on the ward for three weeks now, having arrived a few days
before the transplant. It is now *day 17*.

Although not without challenges, Sam has been making excellent process.
It was beautiful to see the first numbers indicating success of the BMT
come in on his birthday, and the numbers have been climbing everyday! On
day fourteen Sams's blood counts officially confirmed that engraftment
is occurring! His bones are hard at work pushing out new blood and
rebuilding a new immune system! Genetic testing to confirm that Sam's
new blood is from the donor will be done day ±30 (Dec. 14).

## Step down

Sam has now entered the *step-down* phase. It is in this period that all
of the extra supports will be reduced, removed, or converted to oral;
and we will be prepared to leave the hospital! Already:

-   Anti-nausea medications have been reduced from continuous infusion
    to lower frequency does. We are going slow with these, as Sam is
    starts to get his appetite back we do not want to wreck that with a
    wave of nausea.
-   Nutrition is now dominantly provided via NG tube, and less so by
    IV/TPN which will likely be stopped today. As Sam gets his appetite,
    and his tastebuds back, all external supplements will eventually be
    removed.
-   Pain medications have been reduced and generally Sam is not needing
    to self administer as often.
-   Immune and transplant therapy drugs are ongoing and will eventually
    be converted to oral.

As each day passes it is great to see less medications and fewer pumps
needed. Sam is also more alert and with the help of the physio team here
we expect to see him return to an energy and strength.

## Current challenges

Sam has deep bone pain. This is not a new experience for him. With every
round of chemotherapy his blood counts would drop and his bones, more
specifically the marrow, would work hard to generate and replace the
blood cells killed by the treatment. The BMT process was this again, but
more intense. This time the marrow was entirely cleared out. The
transplant cells have taken up home in the marrow and are cranking out
new blood -- but not without pain.

It is very exciting that Sam's body is now generating new blood. The
challenge is that this blood is still foreign to him. The medial team
keeps a close eye on Sam looking for signs of Graft Versus Host Disease
(GVHD) -- where the new transplanted immune system could start attacking
Sam. It is amazing, that cancer and immune therapy research has
progressed so far that the team has a whole set of tools to address
GVHD.

To date, and relatively speaking, Sam has not had much GVHD issues --
though we will be watching for any complications in the weeks and months
ahead. Sam has had painful, hot, and blotchy rashes show up -- usually
in the evening that may be attributed to GVHD. Although we throw
everything we can at these flair-ups he often has to simply suffer
through for an hour or two.

Sam continues to be courageous! He conveys gratefulness to everyone on
the team and to Tina and I as we assist him through the days.

## Victories and concerns

-   Sam's bones are generating new blood! Engraftment is ongoing and
    everyday we see his numbers come up! We will be on the watch for
    Graft Versus Host Disease (GVHD) -- which may be causing periodic
    rashes.

-   What an incredible birthday present. Sam's ANC blood metric went
    from non-detectable to 0.3. A strong indicator that the transplant
    is taking hold!

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   Thankful that what Sam has experienced so far is within the normal
    for a BMT and that he has not had any complications. Although it is
    all in the 'normal', it is not all easy:

    -   Impacts from the pre-treatment, chemotherapy and radiation,
        remain strong. These cause deep bone and muscle pain, along with
        nausea. *These are starting to resolve!*
    -   Pain management is constantly under revision. *Update: We seem
        to have the right mix. Pain and nausea are currently under
        control*
    -   Nutrition is received by \~\~TPN (IV),\~ NG tube, and minority
        by mouth.
    -   Energy levels are low *but recovering*-- it is great to see Sam
        have energy to sit up and play when he can.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he is in a
    phase where he has no immune system for the next few weeks.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.