---
title: "Persecution"
description: "Jesus predicts that persecution will come to his disciples"
author: Colin C.
date: 2024-02-02
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 13: 9 - 13](https://www.bible.com/bible/111/MRK.13.NIV)

> “You must be on your guard. You will be handed over to the local councils and flogged in the synagogues. On account of me you will stand before governors and kings as witnesses to them.10And the gospel must first be preached to all nations. Whenever you are arrested and brought to trial, do not worry beforehand about what to say. Just say whatever is given you at the time, for it is not you speaking, but the Holy Spirit.
> 
> “Brother will betray brother to death, and a father his child. Children will rebel against their parents and have them put to death. Everyone will hate you because of me, but the one who stands firm to the end will be saved.


### Thoughts and questions 

Jesus knew that what he was doing would cause revolution.  The Jews were looking for a Messiah that would bring political revolution and free them from Rome/ their oppressors.  But Jesus is inciting an ideological revolution.  One that will cut to the core of every kingdom on earth.  One that would free people in their thinking.  A revolution that would free them spiritually.  In response to this the power holders would reject and persecute the disciples of Christ -- those that would continue to preach Jesus' messages after he was gone.  

Yet persecution is a catalyst to spreading the kingdom of God.  The disciples would be called before the leaders an asked to defend themselves -- giving them opportunity to speak about the Kingdom of God!  Yes, it would be hard.  There would be torture.  There would trials.  There would be execution.  Yet there is promise and hope in these persecutions.  First, that the word of God would be heard and that the Holy Spirit would inspire people to speak. Second, that those who remain faithful will be saved -- eternal hope. 


### Prayer

God I do not want to face persecution.  I do not want to face rejection, pain, or death.  Yet you did for our sake.  You did that we could be free.  You did and thereby have given us eternal hope.  Should you call me to similar pains give me strength to be faithful to the end.  Should I, even in-part, face similar challenges let you Holy Spirit inspire me and speak through me that I would make your ways known.  That God love this world and payed the price to allow it to be free.  Rescue you people.  Rescue this hurting world.   