---
title: "Signs of the end"
description: "Jesus discusses what the end will look like."
author: Colin C.
date: 2024-02-01
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 13: 1 - 8](https://www.bible.com/bible/111/MRK.12.NIV)

> As Jesus was leaving the temple, one of his disciples said to him, “Look, Teacher! What massive stones! What magnificent buildings!”
>
> “Do you see all these great buildings?” replied Jesus. “Not one stone here will be left on another; every one will be thrown down.”
>
> As Jesus was sitting on the Mount of Olives opposite the temple, Peter, James, John and Andrew asked him privately, “Tell us, when will these things happen? And what will be the sign that they are all about to be fulfilled?”
> 
> Jesus said to them: “Watch out that no one deceives you. Many will come in my name, claiming, ‘I am he,’ and will deceive many. When you hear of wars and rumors of wars, do not be alarmed. Such things must happen, but the end is still to come. Nation will rise against nation, and kingdom against kingdom. There will be earthquakes in various places, and famines. These are the beginning of birth pains.

### Thoughts and questions 

These next few passages are challenging and there have been many interpretations about what they mean.  Is Jesus prophesying about times in a near or distant future (e.g. events that happened within the decades after his death and resurrection or events that have not happened yet)? Alternately, some have suggested he is talking more about himself.  As readers of Mark's gospel today what should we take from this?

In this passage the disciples are amazed at the beauty, engineering, and artistry of the temple.  Jesus does not disagree calling them great buildings.  However, he then cautions them that they will be all thrown down -- that despite how great they are they will not last.  After leaving the temple and sitting on the nearby Mount of Olives the disciples, like you or I would, are curious and ask when these things will happen.  It is the following dialogue that gets more cryptic.  

What should we take from this? Here are a couple suggestions:

1.  God knows what will happen.  He is in control.
2.  Place your trust in God and what He accomplishes.  In contrast, human feats, constructions, accomplishments are temporary. 
3.  There are real events that can cause panic and anxiety -- God knows and He is in control -- trust him.  



### Prayer

God I place my trust in you.  When the world seems crazy.  When the world goes to war.  When disaster strikes.  I will continue to place my trust in you.  Comfort me and give me strength.  I will need it especially when disaster and chaos strike me directly.  Especially then, I will trust in you.  It is only in you that I will have strength and hope. 