---
title: "The abomination that causes desolation"
description: "What is Jesus talking about?"
author: Colin C.
date: 2024-02-06
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 13: 14 - 23](https://www.bible.com/bible/111/MRK.13.NIV)

>  “When you see ‘the abomination that causes desolation’ standing where it does not belong — let the reader understand — then let those who are in Judea flee to the mountains. Let no one on the housetop go down or enter the house to take anything out. Let no one in the field go back to get their cloak. How dreadful it will be in those days for pregnant women and nursing mothers! Pray that this will not take place in winter, because those will be days of distress unequaled from the beginning, when God created the world, until now—and never to be equaled again.
> 
> “If the Lord had not cut short those days, no one would survive. But for the sake of the elect, whom he has chosen, he has shortened them. At that time if anyone says to you, ‘Look, here is the Messiah!’ or, ‘Look, there he is!’ do not believe it. For false messiahs and false prophets will appear and perform signs and wonders to deceive, if possible, even the elect. So be on your guard; I have told you everything ahead of time.



### Thoughts and questions 

I think I have been delayed a few days in getting into this passage because: "*What!!! What is going on? When is this happening? How and I supposed to understand this?  Is there anything that I can apply from this?*"

There have been numerous interpretations of this passage.  Generally they ask what is the abomination that causes desolation and when does this happen?  Below I will provide a very quick review of the two main grouping of interpretations.  First a couple notes:  

1.   Jesus referring to the _abomination that causes desolation_ seems to be referring to the prophet Daniel.  Daniel speaks of a coming leader who's "armed forces will rise up to desecrate the temple fortress and will abolish the daily sacrifice. Then they will set up the abomination that causes desolation." [Daniel 11:31](https://www.bible.com/bible/111/DAN.11.NIV).
2.   There is a simple comment in the first paragraph above that I think is significant "let the reader understand".  This suggest's to me that there were events or something happening at the time Mark wrote this gospel that would enable the readers to understand how to interpret this portion of the text.  

#### Interpretations 

Prophecy of the destruction of the temple in Israel 
:   That this passage is referring to the destruction of the temple in Israel.  This happened in AD 70 when the Roman army destroyed the temple and in effort to recover all the gold from the temple did overturn every stone ([wikipedia: Siege of Jerusalem (70 CE)](https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(70_CE))). This fits with how Jesus stated at the beginning of the chapter that "Not one stone here will be left on another; every one will be thrown down.".  The linked article also describes what happened to the Jews that were in the city and this seems to line up well with how Jesus stated how difficult that this time would be.  

A still future end times 
:   This was a really common interpretation in the evangelical churches that Mom and I grew up in.  That there was a coming global level end times event, including a future global anti-Christ (associated with or as the abomination).  

#### What I think

I think, given that historians believe the Mark was written near 70 AD, and given that Mark's comment suggests that his readers should be able to interpret this, that this prophecy spoke of the destruction of the temple.  ... But this really only answers the abomination part. It does not address this second coming portion in the next section.

### Prayer

Lord, reading prophetic passages are so difficult.  It is hard to know what the authors were trying to communicate.  But my hope is in you.  I know that all of history is in your hands.  I know that you love me and that you love the people of this world.  Help me place my focus on you.  That my faith would not waver in hard times and that my life would demonstrate your love to this world. 