---
title: "The Son of Man will Return"
description: "Jesus call people to watch for his return"
author: Colin C.
date: 2024-02-08
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 13: 24 - 37](https://www.bible.com/bible/111/MRK.13.NIV)

>   “But in those days, following that distress,\
> “ ‘the sun will be darkened,\
> and the moon will not give its light;\
> the stars will fall from the sky,\
> and the heavenly bodies will be shaken.’
>
> “At that time people will see the Son of Man coming in clouds with great power and glory. And he will send his angels and gather his elect from the four winds, from the ends of the earth to the ends of the heavens.
>
> “Now learn this lesson from the fig tree: As soon as its twigs get tender and its leaves come out, you know that summer is near. Even so, when you see these things happening, you know that it is near, right at the door. Truly I tell you, this generation will certainly not pass away until all these things have happened. Heaven and earth will pass away, but my words will never pass away.
>
> “But about that day or hour no one knows, not even the angels in heaven, nor the Son, but only the Father. Be on guard! Be alert! You do not know when that time will come. It’s like a man going away: He leaves his house and puts his servants in charge, each with their assigned task, and tells the one at the door to keep watch.
>
> “Therefore keep watch because you do not know when the owner of the house will come back—whether in the evening, or at midnight, or when the rooster crows, or at dawn. If he comes suddenly, do not let him find you sleeping. What I say to you, I say to everyone: ‘Watch!’ ”


### Thoughts and questions 

In the verses above we come to the end of this passage but what has been the main point of these verses and one ones proceeding?  We have a prophetic pieces of the temple being destroyed, of the abomination that causes desolation, and now the return of Christ.  Honestly, this all has been a bit of a mind-trip and it is easy to be confused about what is going on.  

I do think there are two main messages to take from this whole chapter -- which is often referred to as the _Olivet Discourse_ as it took place on the Mount of Olives and has similar readings in Matthew and Luke. 

Two main points: 

1.  Something that we are called to do.  _Watch!_/ Be on your guard -- is a theme throughout the whole chapter
    -  "Watch out that no one deceives you..." (v. 5)
    -  "be on your guard. You will be handed over to the local councils" (v. 9)
    -  Regarding false Messiahs:  "‘Look, here is the Messiah!’ or, ‘Look, there he is!’ do not believe it.... So be on your guard; I have told you everything ahead of time." (v. 21, 23)
    -  Be on guard! Be alert! You do not know when that time will come. (v. 33)
    -  _Watch_ (v. 37)

2.  God is in control! Look to Jesus -- trust Him. God knows how it will all play out, He knows the trouble we will face, and He knows how history will end.  By the end he will set all things right as Jesus will come again.  

### Prayer

Lord, help me to be alert, to watch and be ready for whatever life brings me.  By your Spirit give me strength and wisdom to endure whatever storm-of-life comes at me.  Inspire my words that I would share your love and truth as you give me opportunity to do so.  No matter how hard things get -- I will look to you.  I will be on guard.  I will watch. Help me do this. 