---
title: "Not just for the Jews"
description: "Jesus compassion extends to all people"
author: Colin C.
date: 2023-08-25
search: false
categories: [Mark, authority, for-all]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 7: 9 - 23](https://www.bible.com/bible/111/MRK.7.NIV)

> Jesus left that place and went to the vicinity of Tyre. He entered a house and did not want anyone to know it; yet he could not keep his presence secret. In fact, as soon as she heard about him, a woman whose little daughter was possessed by an impure spirit came and fell at his feet. The woman was a Greek, born in Syrian Phoenicia. She begged Jesus to drive the demon out of her daughter.\
> “First let the children eat all they want,”he told her, “for it is not right to take the children’s bread and toss it to the dogs.”\
> “Lord,” she replied, “even the dogs under the table eat the children’s crumbs.”\
> Then he told her, “For such a reply, you may go; the demon has left your daughter.”\
> She went home and found her child lying on the bed, and the demon gone.


### Thoughts and questions 

People are constantly seeking Jesus.  So far in the story Jesus has taught and brought healing to the Jews.  He is their Messiah and he is announcing the Kingdom of God.  But Christ's kingdom is not what people are expecting.  He is not there to create an earthly kingdom to restore the nation of Isreal.  His kingdom is release from spiritual oppression.  His kingdom is also not just for the Jews.  

One of the most significant items in this passage is that the mother in this passage was a greek.  Jesus has compassion on her and her daughter.  


### Prayer

Lord God thank you that your kingdom is for all people.  That you have love and compassion for all not. 

Please see our situation.  We need you.  We need your healing.  Destroy this cancer.  

Help us to see your purposes in this.  



