---
title: "Jesus heals the deaf man"
description: "A deaf man's friends bring him Jesus and beg for healing."
author: Colin C.
date: 2023-08-30
date-modified: 2023-08-30
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 7: 31 - 37](https://www.bible.com/bible/111/MRK.7.NIV)

> Then Jesus left the vicinity of Tyre and went through Sidon, down to the Sea of Galilee and into the region of the Decapolis. There some people brought to him a man who was deaf and could hardly talk, and they begged Jesus to place his hand on him.\
> After he took him aside, away from the crowd, Jesus put his fingers into the man’s ears. Then he spit and touched the man’s tongue. He looked up to heaven and with a deep sigh said to him, “Ephphatha!” (which means “Be opened!”). At this, the man’s ears were opened, his tongue was loosened and he began to speak plainly.\
> Jesus commanded them not to tell anyone. But the more he did so, the more they kept talking about it. People were overwhelmed with amazement. “He has done everything well,” they said. “He even makes the deaf hear and the mute speak.”

### Thoughts and questions 

I love three things from this passage: 

1.  How the deaf man's friends brought him to Jesus\
    We all need help.  Also, they didn't just bring him to Jess -- they pleaded/ begged Jesus to heal him.  

2.  That Jesus has the power to heal.\
    I love this and I choose to trust that Jesus still has the power to heal.  I also have a hard time with this... I want healing now.  Yet we must trust that God has a purpose in the suffering when instant healing does not come. 

3.  That the people loved Jesus.\
    This all becomes harder when the people turn on him, not everyone but many.  

Moving forward I am committed to pleading with Jesus! 


### Prayer

Lord Jesus, you are God.\
You are holy and all powerful. 

Please work in our lives.  May they bring glory to you and your kingdom. 

We long for your healing.  You know our hurts, our pain, our ailments. \
Please, we want you to heal. 

Help us to trust you in these trying times. 


