---
title: "Jesus on true laws"
description: "The religious leaders are upset that their traditions, and additional laws are not being upheld.  Jesus sets them straight."
author: Colin C.
date: 2023-08-19
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 53 - 8](https://www.bible.com/bible/111/MRK.7.NIV)

> The Pharisees and some of the teachers of the law who had come from Jerusalem gathered around Jesus and saw some of his disciples eating food with hands that were defiled, that is, unwashed. (The Pharisees and all the Jews do not eat unless they give their hands a ceremonial washing, holding to the tradition of the elders. When they come from the marketplace they do not eat unless they wash. And they observe many other traditions, such as the washing of cups, pitchers and kettles.)\
> So the Pharisees and teachers of the law asked Jesus, “Why don’t your disciples live according to the tradition of the elders instead of eating their food with defiled hands?”\
> 
> He replied, “Isaiah was right when he prophesied about you hypocrites; as it is written:\
> 
> “ *‘These people honor me with their lips,*\
> *but their hearts are far from me.*\
> *They worship me in vain;*\
> *their teachings are merely human rules.’*\
> 
> You have let go of the commands of God and are holding on to human traditions.”


### Thoughts and questions 

The Pharisee's laws actually make sense in our world.  This is a cultural norm for us as well, and people get upset if the dishes have not been washed.  The science backs it up as well -- that this is a more sanitary and clean way to live.  I think their error is that they made these rules central to their spiritual lives... and at the same time lost sight of the important laws. 

This raises and important question for us.  Have we replaced God-living and his intent for how we should love and care for one another, including strangers, with our own sets of rules and traditions? Also I think it critical that we consider what are God's priorities.  We should learn these and focus on them first. 

### Prayer

Lord help us to take to heart and to focus on the way you would have us live.  To focus on your priorities and not get bogged down with the laws of man. 



