---
title: "Soul rot"
description: "Jesus points us to what truly defiles or rots a person."
author: Colin C.
date: 2023-08-23
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 7: 9 - 23](https://www.bible.com/bible/111/MRK.7.NIV)

> And he continued, “You have a fine way of setting aside the commands of God in order to observe your own traditions! For Moses said, ‘Honor your father and mother,’ and, ‘Anyone who curses their father or mother is to be put to death.’ But you say that if anyone declares that what might have been used to help their father or mother is Corban (that is, devoted to God) — then you no longer let them do anything for their father or mother. Thus you nullify the word of God by your tradition that you have handed down. And you do many things like that.”\
> Again Jesus called the crowd to him and said, “Listen to me, everyone, and understand this.  Nothing outside a person can defile them by going into them. Rather, it is what comes out of a person that defiles them.”\
> After he had left the crowd and entered the house, his disciples asked him about this parable. “Are you so dull?” he asked. “Don’t you see that nothing that enters a person from the outside can defile them? For it doesn’t go into their heart but into their stomach, and then out of the body.” (In saying this, Jesus declared all foods clean.) \
> He went on: “What comes out of a person is what defiles them. For it is from within, out of a person’s heart, that evil thoughts come — sexual immorality, theft, murder, adultery, greed, malice, deceit, lewdness, envy, slander, arrogance and folly. All these evils come from inside and defile a person.”


### Thoughts and questions 

I love that Jesus is concerned with our inner lives.  For it is the outflow of our inner selves that our lives bear fruit -- for good or for evil.  

Are there thoughts and internal attitudes that you need to take control of that are in Jesus' list of evil thoughts? 

What good thoughts and attitudes can you cultivate in your mind.  That is what habits of can you build in your inner-self so that your life bears fruit.  

### Prayer

Lord Jesus, guide my thoughts.  Help me to see and reject evil thoughts or patterns within me.  Cultivate and nurture a right/good spirit within me.  



