---
title: "Drafts"
---

## Updates

## Timeline

### 2023-04-18

A chest X-ray, technician sent us to the ER, ER sent us to pediatrics, and the pediatrician sent us to the BC Children's hospital. Sam accompanied by Tina, traveled by air ambulance to Vancouver.

### 2023-04-19

Tina and Sam arrive at BC ChiLdren's and he was admitted to the Pediatric ICU. Teams of Drs. consulted on and off through the day. IV, CT scan, and new IV.

Location: Peds ICU (Frog pod 201)

### 2023-04-20

Surgery to: 1) remove lymph node from left side lower neck, 2) lumbar puncture for spinal fluid and chemotherapy into spine, 3) Bone marrow, and 4) establish a PICC line.

Uncle Cal and Auntie Tricia visit (7-10)

Location: Peds ICU (Frog Pod 201; change Fox 305)

## Updates

### April 20, 2023 (am)

Hi friends,

The last 48 hours have been a whirlwind, and we are where we need to be.

Sam is now at BC Children's hospital, and Tina and I are able to stay in the room with him. Steps are being taken to manage what all indications suggest is lymphoma. Staff here have been amazing in: providing care, communicating what is happening and next steps, and conveying a sense that 'this is serious' mixed with a calming confidence.

The process: Yesterday, tests were run -- the primary one being a CT scan of his chest. Today, Sam will start the day with a surgery to complete a series of biopsies, the primary one being one of his lymph nodes at the base of his neck. By the end of the day, we should have firmer answers as to what exactly is happening and a treatment plan.

Sam's friends and classmates have been amazing. They have been in direct communication with him via Snapchat and hearing from them has been really encouraging to him, also to Tina and I -- it is amazing to see friends rally behind him.

Thank you for your support and prayers,

Colin and Tina

------------------------------------------------------------------------

### April 21, 2023 (am)

TLDR (short version): Yesterday: surgery for tissue samples followed by pain management. In the weeks to come, Sam will be here at BC Children Hospital as he is treated for what is assumed to be lymphoma.

\--

Full version:

Hi all,

Yesterday was a big day for Sam. He had the surgery to complete a series of biopsies. These included the removal of a lymph node at the base of his neck, a lumbar puncture, a bone marrow sample from the top of his hip, and establishing a PICC ([described here](http://www.cw.bc.ca/library/pdf/pamphlets/BCCH1552_PICC.pdf)) to facilitate ongoing blood work and upcoming intravenous drug delivery. All the procedures went well. Dr. Webber, completed the lymph node removal and said it went "Perfectly". This was all done before noon. The biggest challenge of the day has been pain management, but Sam has been a trooper.

The staff here continue to be amazing, always taking the time to answer any of Sam's questions, and making complex biology and bio-chemistry understandable. It is honestly amazing to hear Sam explain his disease to others -- he gets it, understands it, and given the situation is very glad to be here.

Next steps are not totally clear. We are working with the understanding/assumption that Sam has lymphoma ([described here](http://www.bcchildrens.ca/Oncology-Site/Documents/Non-Hodgkin%20Lymphoma.pdf)). The signs all point that way (e.g. X-ray and CT scan), but this will not be totally confirmed until the tissue samples are processed. Here is what we are currently expecting:

1.  Sam will start a round of drug treatment, as soon as later today, and specific treatments will be refined following the analysis of his tissue samples
2.  Sam is currently in the ICU, and we expect him to be here for the next number of days after which, he will be transferred to the oncology unit just a few floors above where he will remain a patient for three weeks or so (timing of stay will all depend on tests).
3.  Tina and I will be able to check into the Ronald McDonald House here on hospital campus on Sunday. This will give us a home base, we will also be able to continue staying in the room with Sam.

Many thanks to all of Sam's friends and teachers, and all of our friends and family. We love to hear from you. We may not get back to you right away but know your messages are encouraging to us. If you have any questions, please feel free to ask, and I will try to answer them either directly or in a following update.

Q&A

How is Tina doing?

:   She is actually great. She has been working so hard advocating for Sam's health over the last months, trying to get the bottom of why he has been sick. Now, she can relax as Sam is where he needs to be, receiving the medical care that he needs. She also loves the medical world, she is in her element here. Our biggest challenge for Tina will be to ensure she is properly fed, especially given her dietary restrictions. We will need to find a new normal here.

How can we help / Let us know if we can help.

:   Hearing from you is currently the best. As noted, we might not be able to get back to you right away, but all of your notes are encouraging. Tina and I have literally had tears-of-joy reading them.

Thanks again for your prayers and support,

Colin and Tina

<!-- > I'm feeling quite good actually. -- Sam -->

<!-- -   Surgery went well -->

<!-- -   Sam was challenged with pain following the surgery, but is managing his pain well -->

<!-- -   In conversation it is amazing to hear Sam explain his illness to others. -->

<!-- -   Drs and Nurses continue are so intentional about answering questions. In particular, questions asked by Sam. They have made complex biology and bio-chemistry very understandable. -->

<!-- -   We are still waiting on the Oncology Team to hear about treatment plans -->

<!-- -   We have felt such incredible support from all of you -- thank you! -->

<!-- -   Please keep praying.\ -->

<!-- -   If you have any questions feel free to ask and I will try to answer them in our next update. - I expect our next update will be *???* -->

### April ??, 2023

-   from being overwhelmed with fear
-   over-whelmed with joy of the support and care from friends. ... don't get me wrong all of this is still hard but we are also feeling your care.
-   My work. I have a great team who understand and support us in what is happening.

## List of our people

-   Nana
-   Gramm and Papa C
-   Cal and Tricia
-   Kevin and Shannon
-   Tom and Margaret
-   Senga
-   Hillhouse
-   Claus
-   Christenson
-   Jess and John B.
-   Vern and Dawn P.
-   Joanna Cross
-   Amy Dobson
-   Mike Jull
-   Schellenberg
-   Lodge
-   Craig and Lisa Reimmer
-   Rob and Leanne Dyck
-   Hijams
-   Leah Paulson

To bring into the loop

-   Carlaw
-   Denise Rahn
-   Aaron and Ang

## Care givers

### Nurses

-   Jad
-   Lauren (April 20) what great explanations and care, Berni-doodle, quilt
-   Brita (April 20/21 nights)
-   Kristen (April 21)

### Drs

-   E Webber -- surgeon who remove lymph node. Excellent explanations to Sam's questions with regard to blood chemistry and why they are pumping Sam so full of fluids
-   Numerous residents and fellows -- all excellent in their communication.

## Quotable Sam

-   2023-04-19: You will receive treatment, Sam: That's exhilarating
-   2023-04-20: I need to thank Ms. Darah for helping me understand everything: chemistry, electricity ...
-   Talking with Nana *This place is the best place I could ever go*
