---
title: "Navigating the chemo-storm"
description: "Sam is in the middle of round 4.  The chemo-storm rages on but we are managing"
author: Colin C.
date: 2023-08-09
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Very little to update you on.  This chemo-storm still rages on, but there have been moments of relief, and it seems we will be able to weather this latest challenge.  We are making full use of all the tools available to us -- that is the prescriptions, and they are taking the edge off.  

## Concerns and victories

_repeated_

-   Tina had an amazing number of days away, attending Marielle's bridal shower. It was good break.  Sam and I did managed well on our own, but by the end of this short time away Tina was definitely missed. 

-   We are thankful to be past the drug delivery phase of round 4.  Each round bring us closer to the end of this journey.  

-   This time the side effects more intense, with nausea, pain, fatigue, and general feeling rotten.

-   Complicating Sam’s cancer journey are Tina’s on-going health issues.  Being in Vancouver may present opportunities for us to continue to look for additional solutions.  We are hoping that referrals and connections to medical providers specific to her situation come together. 

-   We hope that there will not be a need for the contingency plan, a bone marrow transplant, yet we
    need to prepare ourselves for this possibility.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.

