---
title: "Pending results and preparing for round 5"
description: "Round 4 has been rough and we anticipate round 5 starting today. Results and recommendations are expected."
author: Colin C.
date: 2023-08-25
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Round 4 is officially complete.  It has been a rough one with little relief.  The previous rounds Sam would usually have 2-4 days of feeling more normal... This past round hardly let up.  As he was starting to feel a little better he was hit with another bought of nausea and mucositis.  

Sam has a very significant clinic appointment today.  

1.   We should receive the results of the lasted PET scan and lumbar-puncture

2.   The medical team may be ready to present recommendations for treatment -- will a bone marrow transplant be necessary?

3.   Round 5 is likely to start today. This will begin with five days in hospital for chemo-drug delivery. 

All this to say, I am a little anxious this morning. 

## Looking back -- the past week

Despite Sam has not felt great we have had some great visits this week. 

-   On Monday, we had a last visit with my parents and Buddy before they made the return drive back to Prince George. 

-   Tuesday, Tina's mom arrived!

-   Wednesday, Korena and Samuel Z. were here for the afternoon.  This was Sam's strongest day and it was great to see him reconnect with a friend.  Also great to see Korena and Tina reconnect! 


## Concerns and victories

-   So thankful for all our friends and family for your visits, care, and on-going communication.   

-   I am amazed the medical tech. that is available to support the decision making here.  Results of the PT scan are expected today. 

-   This round has been a challenge with much stronger side-effects causing pain and nausea. We have adapted and learned how to manage much of it.   

-   We expect that major decisions will be discussed regarding Sam's future treatment -- specifically determining if Sam will need a bone-marrow transplant.  

-   There is always concern that the cancer remains.   We long for the day when Sam is clear of this disease.

