---
title: "Results and recommendations"
description: "Results from the latest PET scan and recommendations following yesterday's meetings"
author: Colin C.
date: 2023-08-26
categories: [regular, results, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
---

This morning I am writing from Sam's hospital room.  He is here for the planned delivery of his fifth round of chemotherapy.  Sam is sleeping well.  I slept 'ok' but my mind has been busy as I process the results and recommendations from yesterday.  

Yesterday we reviewed the results of the latest PET scan with Sam's oncologist and clinical nurse.  The good news is that the cancerous masses have been reduced further and that there is no new cancer.  The challenge is that the rate of reduction in Sam's cancer will not be enough to see it removed by the end of either this or the next round.  We must consider further treatment options.  

Following his current treatment Sam will most likely transition to a bone-marrow-transplant treatment protocol. This will involve:

1.   Radiation

2.   Further intense chemotherapy (drugs)
3.   Isolation -- though Tina and I will still be able to be with him, Sam will be sequestered in a special room during the transplant period of 4-6 weeks. 
4.   Significantly more time here at BC Childrens to accommodate all of this.

Amazingly, we already know that there a several good transplant matches for Sam! 

There will be many meetings upcoming as new plans are made, and as we transfer his care to the bone-marrow transplant team.  Although this is hard, I don't think we would have been satisfied with anything less.  This is the best option for Sam and it should provide life-long defense against this cancer. 



## Concerns and victories

-   We are thankful that the cancer is further reduced.

-   We have a long list of new concerns which I am yet to process.  Top of mind: 
    1.   Although it seems there are good matches for Sam.  That a donor would be willing to make the donation, and all the logistics of timing and delivery would come together.
    2.   Side effects both immediate and long-term would be limited.
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.

-   We are thankful for the care and support of the medical teams here. 

-   We are thankful for willing donors who are good matches for Sam.

-   There is always concern that the cancer remains.   We long for the day when Sam is clear of this disease.

