---
title: "In the storm"
description: "Sam has seen the completion of round 4's drug delivery phase.  We have made it past the mid-way point of this treatment but this cancer-storm rages around us."
author: Colin C.
date: 2023-08-07
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

It is the morning of day 111 and we have crossed mid-way of the treatment plan. Saturday was the fifth and final day of chemo-drug delivery for this round.  That afternoon we left the hospital, returning to the Ronald McDonald House. It felt good to get away from the hospital and find the quiet of our room here, but it has been hard. 

The truth of it is this journey is hard, long and hard.  Sam has been amazing, a few days ago, day 2 and 3 of this treatment, he was the brightest and most active I have seen him in months:  playing games, seeking social connections, including making a new friend.  

In general, we were all expecting this round to be easier.  From the past experience this set of drugs did not hit as hard.  However, by day 4 Sam was lethargic and had intense brain-fog.  Now that we are out of the hospital we are catching up on sleep, The fog seems to be lifting, but nausea and pain need to be managed constantly. Generally, Sam just feels gross.

Sam longs for normal days and our return to normal life -- we all do.  I fear I do not remember what normal is or how to find it. This cancer-storm is swirling around us -- it is difficult to see beyond it.  


## Concerns and victories


-   Tina had an amazing number of days away, attending Marielle's bridal shower. It was good break.  Sam I did great on our own but by the end of this short time away she was definitely missed. 

-   We are thankful to be past the drug delivery phase of round 4.  Each round bring us closer to the end of this journey.  

-   This time the side effects more intense, with nausea, pain, fatigue, and general feeling rotten.

-   Complicating Sam’s cancer journey are Tina’s on-going health issues.  Being in Vancouver may present opportunities for us to continue to look for additional solutions.  We are hoping that referrals and connections to medical providers specific to her situation come together. 

-   We hope that there will not be a need for the contingency plan, a bone marrow transplant, yet we
    need to prepare ourselves for this possibility.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.

