---
title: "Friends and the beginning of round 4"
description: "We have had some great visits and the wait is over as round 4 begins."
author: Colin C.
date: 2023-08-02
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

I think this has been the longest gap between posts.  My silence is has simply been a break and waiting.  

This morning I am writing from Sam's hospital room, as yesterday Sam began round 4 of chemotherapy, and as per the plan he will be in the hospital for five days of drug delivery. We did have a delay over the last week as we needed to wait for his body to recover from round 3.  

It had been a quiet week until this past weekend when we were encouraged by the love of friends and family.  Unplanned, we had several visits almost back to back. So good to see you all!! 

## Recent visits

We had many great talks, some special activities, games, an ice cream run, and a couple bike rides.  Sam was encouraged to see his friends and family -- though he did not get to engage with the activities as much as his energy was low. 


-   Jess and Kate B. took Tina to Bard on the Beach and the Symphony of Fire (fireworks).  Back at the RMH I visited with John Sr. and Sam with his classmate John (jr.).  

-   A surprise visit with Auntie Shannon and Uncle Kevin.  We knew Kevin was going to be here but they surprised us with a visit with Tina's sister. 

-   Brian, Beth, David, and Luke H. were here.  The boys and Sam hung out while 

-   I was able to have a quick quality visit with Mike J. 


Many thanks to all of you! Your presence, your words, your friendship have encouraged us! 



## Concerns and victories

-   I am thrilled for Tina as she will be leaving us for a few days to attend Marielle's bridal shower (engaged to Kurtis F.).  How will Tina do away from us?  How will we do with out her?  

-   Thankful for the support of friends and family. 

-   Perhaps it was the quieter week that gave us space to realize how tired we are.  Recent visits have lifted us but we are definitely feeling this marathon.

-   We are thankful to keep going with the start of round 4.  Each round bring us closer to the end of this journey.  

-   The medical team here is great.  Returning to the hospital is fairly easy.  Many of the nurses know us and welcomed us back.  Sam knows the routine and there is a comfort in the familiarity of it. 
    

-   We hope that there will not be a need for the contingency plan
    ([bone marrow
    transplant](/posts/2307/2023-07-17_contigency-plan.qmd)), yet we
    need to prepare ourselves for it, and all the additional experiences
    and time that it may bring with it.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.