---
title: "Reflections on round 4"
description: "Ths round has been tough and we have had to re-learn the lesson of being flexible."
author: Colin C.
date: 2023-08-14
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Sam has made it past the halfway mark of the fourth round of chemotherapy.  We have been told from the beginning that we would need to remain flexible and adapt as each round would be different.  There are so many changes each round, to the drug mix, to the cancer, to Sam's body that it is not possible to know what the impacts will be each time.  To date, it seemed that each round was getting easier and I had grown to expect that pattern to continue.  However, this round turned our expectations up-side-down.

It has been a storm.  Following our last clinic appointment Sam's medications were adjusted, and this new medication plan have made things easier.  By yesterday, it seems we have his nausea and pain mostly under control and options for when it is not.  So what happened? 

Our experience and discussion with the medical team point the majority of this points to a strong case of [mucositis](https://myhealth.alberta.ca/Health/aftercareinformation/pages/conditions.aspx?hwid=ack5321) a common side-effect which results in the breakdown the mucus layer protecting the inside of the digestive track.  

## The last few days 

-   For the last few days Sam and I have enjoyed boy-time together.  As Sam's energy levels are low from a mix of the side-effects and medications we have probably had too much screen-time, and too much junk food -- though I will let Sam eat anything these days in order to get calories into him. 

-   Tina has been in Edmonton area as our representative at Kurt and Marielle's wedding.  From the video-feed, and Tina's descriptions and  photos it looked like an amazing day! Sam and I were able congratulate Kurtis via FaceTime.

-   Yesterday we had a great visit with our friend Wes S.  

## Upcoming 

-   Clinic appointments and likely blood transfusions as the chemo brings Sam's blood counts down dangerously low. 

-   PET scan at the end of this week. 

-   The _Fish for a Wish_ event will be happening at Aleza Lake is happening this Saturday, August 19.  There will be games, a bouncy castle, a silent auction, fishing, and the option to camp out. This year the community has chosen to support Sam! \
If you don't know what I am talking about and you would like to attend send me a note and I will send you a Facebook invite. 


## Concerns and victories

-   We are so excited that Tina was able to travel and attend wedding of Kurtis and Marielle F.  A beautiful celebration, and great to share it with family and friends there. 

-   This round has been a challenge with much stronger side-effects causing pain and nausea. In addition, Sam has reduced energy levels and appetite.  

-   We are thankful that recent changes to Sam's daily medications have alleviated most of the pain and nausea.  I hope that Sam get's some level of appetite back.

-   There is concern that Sam will need further treatment (bone marrow transplant).  There is always concern that the cancer remains.   We long for the day when Sam is clear of this disease.

