---
title: "The Lord is My Shepard"
description: "A reflection in a time of despair."
author: Colin C.
date: 2024-06-29
search: false
categories: [Psalm]
tbl-colwidths: [50,50]
draft: true
editor: 
  markdown: 
    wrap: 140
---

It's our 28^th^ anniversary and this has been the hardest year of our
lives. Sam is doing well but still has cancer and it remains unknown
if it can be stopped.

This morning Tina asked me to meditate on [Psalm
23](https://www.bible.com/bible/2016/PSA.23.NRSV).

My reading is dark. Today I receive little comfort from this Psalm.
The only comfort is in the recognition of the pain and torment of our
current situation.

+--------------+--------------+
| Psalm23      | My response  |
+==============+==============+
| > The Lord   | *And yet I   |
| > is my      | am left in   |
| > shepherd,  | want. Am I a |
| > I shall    | sheep,       |
| > not want.  | trapped in   |
|              | the          |
|              | wilderness?* |
|              |              |
|              | *Where is my |
|              | shepherd? I  |
|              | cry* out     |
|              | *and it      |
|              | seems He     |
|              | does not     |
|              | hear.*       |
+--------------+--------------+
| > He makes   | *I long for  |
| > me lie     | green        |
| > down in    | pastures.\   |
| > green      | To be there  |
| > pastures;\ | with my      |
| >  he leads  | family.*     |
| > me beside  |              |
| > still      | *Yet there   |
| > waters;\   | is death in  |
| >  he        | him. I       |
| > restores   | cannot leave |
| > my soul.   | him.\        |
|              | I cannot     |
|              | ignore it.   |
|              | Fear of      |
|              | death rots   |
|              | at my soul.* |
+--------------+--------------+
| > He leads   | *I try to    |
| > me in      | follow the   |
| > right      | right path,\ |
| > paths\     | remembering  |
| >  for his   | what the     |
| > name's     | shepherd has |
| > sake.      | taught me.*  |
|              |              |
|              | *Is all of   |
|              | this for his |
|              | name's       |
|              | sake?*       |
+--------------+--------------+
| > Even       | *Yes, this   |
| > though I   | is a dark,   |
| > walk       | dark valley. |
| > through    | A valley of  |
| > the        | death.*      |
| > darkest    |              |
| > valley,\   | *Though I    |
| >  I fear no | fear no*     |
| > evil;\     | eternal      |
| >  for you   | *evil, I     |
| > are with   | fear.\       |
| > me;\       | Are my fears |
| > your rod   | not          |
| > and your   | justified?\  |
| > staff—\    | The disease  |
| >  they      | in real and  |
| > comfort    | the Lord     |
| > me.        | remains      |
|              | silent.*     |
|              |              |
|              | *Though Your |
|              | ways guide   |
|              | me, I        |
|              | question if  |
|              | they are any |
|              | comfort.*    |
+--------------+--------------+
| > You        | *My enemies  |
| > prepare a  | are* Death   |
| > table      | *and*        |
| > before me\ | Despair*.*   |
| >  in the    |              |
| > presence   | *They sit    |
| > of my      | here at the  |
| > enemies;\  | table with   |
| > you anoint | us.\         |
| > my head    | Yet it seems |
| > with oil;\ | we are the   |
| >  my cup    | meals set    |
| > overflows. | before them  |
|              | – my son     |
|              | for* Death   |
|              | *and us for* |
|              | Despair*.*   |
|              |              |
|              | *There is no |
|              | cup, no meal |
|              | for me –     |
|              | rather You   |
|              | are serving  |
|              | us up.*      |
|              |              |
|              | *When will   |
|              | you rescue   |
|              | us?*         |
+--------------+--------------+
| > Surely     | *This seems  |
| > goodness   | like a false |
| > and mercy  | hope;\       |
| > shall      | a lie to     |
| > follow me\ | soothe       |
| >  all the   | mental       |
| > days of my | anguish.*    |
| > life,\     |              |
| > and I      | *I cry as    |
| > shall      | did Christ:\ |
| > dwell in   | "*My God, My |
| > the house  | God, Why     |
| > of the     | have you     |
| > Lord\      | forsaken     |
| > my whole   | me?"*, and I |
| > life long. | try to       |
|              | remain       |
|              | faithful to  |
|              | say:\        |
|              | "*yet not    |
|              | what I want, |
|              | but what You |
|              | want."       |
+--------------+--------------+