---
title: "Cautiously Optimistic"
description: "Looking forward to our return... "
author: Colin C.
date: 2024-01-29
date-modified: 2024-02-09
categories: [regular, post-BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: callout-note
# Feb. 9, 2024 

Just a quick update as we continue on this journey.  

This treatment recovery phase seems long.  I shouldn't be surprised by this, all journeys seems long when you are nearing the end.  It is always that last couple hours of a long drive that seem the longest.  

In this situation, Sam has had some incredible things done to him.  The pace of activities and medical interventions has slowed drastically, and Sam's health is continuing to move in the right direction.  His strength and stamina are returning/rebuilding.  Sam still struggles with some pain but it has shifted from deep bone pains related to the chemical treatments to muscle pains as he rebuilds his core strength.  Everything is moving in the right direction and returning home is getting closer!    

:::



It has been a good week. Sam has had a distinct return of his appetite
and with it he is growing in strength. The discipline of choosing hope,
discussed in my last post, has been getting easier given that we are not
faced with so many unknowns and anxieties are being replaced with
relief.

On the medical side, Sam's medical team is happy to see him regaining
capacity. Clinic appointments are becoming less frequent (we are
transitioning from 2-3 times per week to just once), and the repeat of
the baseline medical testing has been ongoing.  Sam should get is central-line removed within the next two weeks.

Now, our thoughts are turning towards home and what it will mean to return
there. Our current expectation is to return near the end of February.
Returning will not be as simple as jumping back into life like-it-was.
Sam's immune system, though getting stronger, will still be
compromised -- the team here suggests that it will take a year
before his immune system is back to full-strength. His stamina is
building but we will need to guard his capacity. What does this mean
practically? I am not sure, but here are a couple guesses:
visits will need to be individual or in small groups and we will still
need to avoid crowds -- at least with Sam. Sam's diminished strength may
mean that visits are short and that he simply powers-out partway
through. The return to normal will be in small steps ... but we are
getting there!

It is amazing to think of returning home. Returning to friends and
family -- we have missed you! It is also amazing to start counting down
days! For long time we counted up -- not knowing when the end would be.
Now the end is in sight! Sam has made it through all of his treatments
and it feels like we are on an exit-ramp -- we can start preparing for
home!


## Victories and concerns

-   We have a big, and exciting transition, ahead of us: the return to
    home, family, and friends. A return to work and school – though these
    responsibilities will likely need plans and modifications. There are
    many practical steps and details to be sorted out. One step at a
    time!

-   We are no longer having medical discussions about upcoming
    treatments. Discussions are now about weaning medications, removing
    the central line, completing baseline tests for comparison with the
    pre-BMT testing, and preparations to return home!

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease. A PET scan will be done in late
    February to evaluate how the cancer has been impacted by all the
    treatments. The expectation is that any remaining cancer, following
    the chemo and radiation therapies, will be removed by the newly
    transplanted immune system.