---
title: "A chemical crutch"
description: "It has been a tough week fighting a flu and changing medications."
author: Colin C.
date: 2024-01-11
categories: [regular, post-BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

The days since my last post have been rough. Whatever virus we all
picked up is still lingering. Sam and I are mostly past it, and Tina is
improving. Unfortunately, this cold also caused some confusion as the
team cared for Sam -- it was more difficult to discern what was
happening with him while he was battling this illness.

## Looking back

### Sam's medical progress

The challenges

:   Following New Year's it was like someone flipped a switch in Sam ...
    in that the power was turned off. Where prior Jan. 1^st^ Sam had
    increasing stamina and activity levels, this past week-and-a-half he
    had no energy and spent most days in bed. The virus we all had
    complicated the picture. We did have a couple clinic appointments
    but making any changes were difficult as it was hard to know what
    was happening in Sam's body apart from the illness.

:   Last Wednesday there was a decision to stop one of the steroids used
    during BMT. Initially, this did not seem to affect Sam ... but at
    the time all he was doing was sleeping (\>90% of the time). By the
    end of the weekend, Sam was mostly done with the cold but he was
    still sleeping... and not very responsive. It turns out the steroid
    was a chemical crutch and we had pulled in out from under him.

:   The next clinic appointment, earlier this week, a substitute steroid
    was introduced. Sam is now more conscious and is beginning to get
    moving again.

The positive

:   Despite the confusion and challenges above Sam has made some good
    progress having successfully dropped a number of medications from
    his list.

:   Symptoms of GVHD have been minimal with minor rashes. The medical
    team remains vigilant watching out for this.

### Visits

-   It was great to see my parents this past week. They had a couple
    windows of opportunity to chat with Sam.

-   Tina and I were able to get out for a nice meal with Kevin and
    Shannon.

## Upcoming

-   We will continue with the usual clinic visits to monitor Sam's
    progress.

-   Sam will be seen Endrocrinology Team. This team specializes in
    steroids, hormones and all of the glands in our bodies that produce
    them. It is not uncommon for someone who has been on steroids and
    then stops (e.g. Sam for his BMT) to have issues producing their own
    hormones. I expect that this team will examine Sam to determine what
    hormones he may need in the short-term, consider strategies for
    getting his own system jump-started, and worst case to determine if
    there has been any damage to his glands.

-   There is talk of removing Sam's central line!

-   All of the pre-BMT baseline tests will be completed

## Victories and concerns

-   It has been a hard week watching our son sleep most day and not
    understanding why. His brief periods of wakefulness re-assured us
    that he was still in-there. This was stressful and exhausting for
    Tina and I. We now have some direction and started on some supports
    for him. The biggest underlying concern is the return of his body's
    ability to produce and regulate natural hormone levels.

-   Sam has gotten past the his cold. His new immune system beat it back
    and we did not have to go into hospital. ~~Our first challenge of
    2024 seems to have been exposure to a flu. Sam has been feeling
    rough, with higher pain levels, and lots of fatigue. We initially
    attributed this as a response to increased activity levels ... but
    then Tina and I started battling colds.~~

-   We have had an great holiday season celebrating Christmas, Tina's
    birthday, and New Years with family in the area.

-   We are no longer having medical discussions about upcoming
    treatments. Discussions are now about weaning medications, removing
    the central line, and preparations to return home!

-   New blood cells in Sam's body are all from the donor! Sam's bone
    marrow is pumping-out/generating new blood! The engraftment process
    is working! We have seen Sam's numbers come up and now stabilize!

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern if the cancer remains. We long for the day
    when Sam is clear of this disease. A PET scan will be done in
    February to evaluate how the cancer has been impacted by all the
    treatments. The expectation is that any remaining cancer, following
    the chemo and radiation therapies, will be removed by the newly
    transplanted immune system.