---
title: "Happy New Year!!"
description: "We are so incredibly thankful and joyful coming into this new year"
author: Colin C.
date: 2024-01-04
categories: [regular, post-BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

Happy New Year! We have so much to be thankful for this year! Although,
2023 was incredibly challenging it ended with joy as we celebrate
Sam's new life. Looking up and looking forward we are filled with hope
and joy for the year ahead.  

Joy has been a theme for Sam. Many mornings he wakes up and the first
thing he says is "*I'm so happy!*" On New Year's day it was "*I'm so happy. I am
immensely happy!*" In the last couple weeks he also commonly adds "*I have
an amazing life!*"

Taking a van trip our to see the family and bring in the New Year, Tina brought up Psalm 23, a passage that many also sent on to us. Sam reflected on how he feels
like God has lay down beside the green pastures.

> ## Psalm 23
>
> The Lord is my shepherd, I lack nothing.\
>  He makes me lie down in green pastures,\
> he leads me beside quiet waters.\
>  True to your word,\
> you refresh my soul\
>  and send me in the right direction..
>
> Even when the way\
>  goes through Death Valley,\
> I will fear no evil,\
>  for you are with me;\
> your rod and your staff,\
>  they comfort me.
>
> You prepare a table before me\
>  in the presence of my enemies.\
> You anoint my head with oil;\
>  my cup overflows.\
> Surely your goodness and love will follow me\
>  all the days of my life,\
> and I will dwell in the house of the [Lord]{.smallcaps} forever.
>
> [*Psalm 23*](https://www.bible.com/bible/111/PSA.23.NIV?parallel=97)
> *(blend of NIV and The Message versions)*

## Looking back

Medical items

:   Sam continues to have regular visits at the clinic. Various blood
    tests to ensure the various medications that Sam is on are at
    appropriate levels. Most of the discussion with the medical team is
    in preparation to leave! This includes weaning Sam off of the
    medications. To date, everything with the BMT is going well and Sam
    is ahead of the anticipated schedule. Various members of the medical
    team have said they are amazed at how well Sam is doing.


Christmas 

:   Christmas was... extravagant! We spent the morning sharing gifts and the evening meal and games wth family.  



Life beyond the hospital

:   It is exciting that we ar having more an more life beyond the bounds
    of the hospital campus! Including:

-   Visits with family Langley and in White Rock
-   A great Townsend-side buffet meal to celebrate *Tina's birthday*.  All but one of Sam's cousins from that side of the family were able to make it.  
-   A new years party at with Nana, Uncle Kevin and Auntie Shannon, and all of their children plus partners.  Including the newlyweds Kurt and Marielle. 





## Upcoming

-   Medical appointments will continue as Sam remains under a watchful eye from the team.  

-   Medicines will gradually be removed 

-   There is talk of removing Sam's central line (in a couple weeks)!

-   All of the pre-BMT baseline tests will be completed

## Victories and concerns

-   Our first challenge of 2024 seems to have been exposure to a flu.  Sam has been feeling rough, with higher pain levels, and lots of fatigue.  We initially attributed this as a response to increased activity levels ... but then Tina and I started battling colds.  The good thing is that Sam is now has an immune system to fight for him.  

-   We have had an great holiday season celebrating Christmas, Tina's birthday, and New Years with family in the area.  

-   We are no longer having medical discussions about upcoming treatments.  Discussions are now about weaning medications, removing the central line, and preparations to return home! 

-   Sam continues to regain strength. 

-   New blood cells in Sam's body are all from the donor! Sam's bone
    marrow is pumping-out/generating new blood! The engraftment process
    is working! We have seen Sam's numbers come up and now stabilize!

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.  A PET scan will be done in February to evaluate how the cancer has been impacted by all the treatments.  The expectation is that any remaining cancer, following the chemo and radiation therapies, will be removed by the newly transplanted immune system. 
