---
title: "Remembrance of Papa Gord"
description: "This past week we had to say goodbye to Papa Gord"
author: Colin C.
date: 2023-10-02
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

## Last goodbyes

Last week was hard but beautiful.

On Friday Sept. 29 at 11:00am Papa Gord (Tina's Dad) passed on to
eternity. He was surrounded by his family: Mary, Cal & Tricia, Shannon &
Kevin, and Tina. Sam and I had to stay here at the RMH but we were also
able to have final conversations, express our love, and say our goodbyes
with Gord (via FaceTime). The other grandchildren were able to say
goodbye via facetime as well.

Mary and Gord have given us an incredible legacy of love and commitment.
It is and will be hard losing Gord though it was beautiful to share in
the love of the family as they were able to spend a number of days with
Gord before the end.

### The week in review

Tuesday -- a whirlwind of day.

:   It started with a big clinic day including lots of time with Dr.
    Jacob, the team lead of the BMT team, providing us a review of the
    process going forward. During this conversation Tina was fielding
    various communications regarding her dad, that he was in ER in
    Prince George.

:   Great news from this day was that there is a bone marrow donor for
    Sam, and the donor is willing to undergo the bone marrow extraction
    process. This is great news for Sam's path of healing.

:   By mid-afternoon flights were booked and in the evening Tina's
    brother Cal and his wife Tricia picked Tina up to head for the
    airport where they met Tina's sister Shannon and her husband Kevin
    -- the five of them travelled to Prince George to see Gord. While
    they were en route Sam and I had a good FaceTime conversation with
    Papa Gord.

Wednesday -- Thursday

:   Gord, though responsive, was not going to recover. By the end of day
    on Wed. he was transferred to Hospice. The siblings and Tina's mom
    Mary, spent great quality time with Gord -- sharing loving memories.

:   Back at the RMH Sam and I kept going with medications, pain control,
    and connected with the family in Prince George. Mucositis was really
    bad these days.

Friday

:   The family had a few more hours with Gord and at \~11:00am he
    entered eternity.

:   Here in Vancouver, Sam and I were in clinic, including meetings with
    different doctors and a blood transfusion, when we received word
    about Papa's passing.

    Sam is happy, though with tears, for Papa to be free of his declining body.  Sam spoke words of hope to Papa, about seeing him again in heaven and sharing great experiences there (e.g. fishing and golfing together).  Gord's beautiful strong and gentle soul will be missed here.

Saturday -- Sunday

:   The Prince George team made final arrangements for Gord and began
    their travels back to the lower mainland, bringing Mary with them to
    stay at Shannon's home and be near family. Tina got back to us on
    Sunday afternoon.

:   Saturday night was a rough one for Sam and I. Sam hit the limit on
    what I was allowed to give him for pain control. Help was just a
    phone-call away. The on-call oncologist provided me additional pain
    control instructions and I was so glad to hear Sam gently snoring by
    early morning. Plans were also put in place to visit the hospital
    during the day -- Sam got a blood transfusion.


## Upcoming

This week includes:

-   regular clinic visits -- and likely more blood products
-   more planning for the BMT
-   Some medical imaging as the medical teams create a baseline of Sam
    -- essential for determining impacts of the radiation and BMT
    process.

## Victories and concerns

-   Thankful that Tina and her siblings were able to make it back home
    and spend quality time with Papa Gord. Please keep the family in
    mind.

-   Thankful that Sam has been able to connect with a number of friends
    from back home via online discussion tools and games.

-   Thankful that when things do get difficult (e.g. pain management and
    low blood levels) help is only a phone call away. The medical team
    here at BC Childrens continue to be amazing.

-   Chemotherapy continues to take its toll. His energy levels are lower
    with each round. As with previous rounds Sam's blood counts are
    falling and mucositis has set in. We hope that that these side
    effects will be less intense and that they can be short lived --
    that Sam does not have to feel gross.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  We are thankful for a donor who is a match for Sam and that they
        are willing to undergo the full bone marrow extraction process!
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team have a huge coordination task ahead of them.
        All the pieces need to fall into place for the best timing
        possible.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.