---
title: "The BMT plan"
description: "Highlights from this past week and plans for a bone marrow transplant."
author: Colin C.
date: 2023-09-04
categories: [regular, plans]
draft: false
editor: 
  markdown: 
    wrap: 72
---


Day 139, we are at the Ronald McDonald House as the impacts of the latest chemo-drug deliveries take hold.  Once again we are heading into the valley.  Each round gets harder as Sam is continually beat down by this treatment regime.  Truth be told at this point the treatment seems as bad as the disease, but we must push on.  Mucositis is worse again with intense nausea.  Sam has been experiencing pain deep in his bones as his body works so hard (based on his last PET scan his bone density is falling).  We are doing 'ok' in the management of these symptoms by utilizing higher doses of morphine and nausea control medications. 

## Highlights from this past week 

Despite low energy levels, Sam has been able to rise and join in on life a number of times as family and friends have come to visit. 

-   Little cousin Jayme delivered donuts

-   Sam had a good couple hours with the Fricker family and in particular with cousin Kaden. 
-   Nana returned home.  Mary, thank you for all of your love and support.
-   Rob D. was able to have a short visit with Tina and I.  Thanks for coming to see us. 
-   This past weekend Hunter and Brian L. made the trip from PG to be with Sam.  Many thanks for your friendship.
-   In addition, Sam has been able to connect with friends online a few times.


## BMT Plan 

_BMT: Bone Marrow Transplant_\

::: callout-warning
## Disclaimer 

I feel I need a quick disclaimer here as I am not sure I have all of this right.  In addition, the following dates are rough estimates from the medical team.  In broad strokes I think most of the items below are pretty much there ... dates and details are likely to change.  
:::


During last week's clinic visits we gained some more clarity on the planned treatment for Sam.  

1.  Sam will complete the full six rounds of his initial chemotherapy.\
There had been some discussion about skipping the 6^th^ round and going straight to bone-marrow-transplant  (BMT) but there was just too many moving parts.  The team needed more time to line everything up.  This means we have about six weeks remaining in this treatment regime before pivoting to BMT. 

2.  In preparation for BMT Sam will see numerous specialists throughout BC Childrens and the BC Cancer Clinic.  The goal will be to create a strong baseline of Sam's health going into BMT. 

3.  Bone Marrow Transplant: Day zero is estimated to be _Nov. 2_ .\
Following the current chemotherapy we will transition to BMT.  The medical team refers to the actual transplant day as day 0.  Activities prior to this day are count-down days and then the days following start counting up.  
    -   _Days -12 to -8_ (~Oct. 16): Radiation targeting whatever cancerous masses remain.  The goal is to set the cancer back as hard as they can.
    -   _Days -7 to -2_: Chemotherapy to suppress and remove Sam's own immune system.
  
    -   _Day -1_: General full body radiation to ensure Sam's own immune system is completely removed -- in preparation for replacing with the transplant/ graft immune system. 
    -   _Day zero_, currently planned for Nov. 2, Sam should receive the transplant.  This is actually quite simple -- like receiving a blood transfusion. The team will hang the bag of bone marrow products and pump it into Sam's body via his central line. 
    -   _Days 0 to 30_ Sam will be in an isolation room with strict protocols.  Tina and I, along with the medical team will be allowed in.  
    -   _Days 31 through 90_: If all goes well Sam will be allowed out of the hospital but is to remain close for regular check-ins.





## Concerns and victories

-   We are all exhausted.  Sam has to carry the greatest burden with undergoing this treatment.  Tina and I are there to walk with him each step of the way and to provide all the parental care and also practical nursing care.  I don't think I look to see the end of this storm anymore ... rather I just hold on. 

-   We are thankful that there is a plan. However:\
The challenge with all of these plans is that we are in unknown territory.  I stated early on that Sam's cancer is very rare.  The reality is that it is essentially unknown.  In the world, there has been only one other documented case of this form of cancer. So, all of these plans are based in professional judgement/ best-guess.  We are thankful for our medical team that is able provide guidance, but we recognize that there is no standard protocol for Sam's cancer. 

-   We have a long list of new concerns which I am yet to process.  Top of mind: 
    1.   Although it seems there are good matches for Sam, a donor needs to be willing to make a donation, and all the logistics of timing and delivery need to come together.
    2.   Side effects both immediate and long-term would be limited. _Ideally, that there would be no measurable side effects_. 
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.

-   We are thankful for willing donors who are good matches for Sam.

-   We are thankful for the support of family and friends.  Please keep your notes of encouragement coming -- they can really bolster us. 

-   We are thankful for Sam's school who are looking forward to his return and who are willing to work with us once Sam is able.  

-   There is always concern that the cancer remains.   We long for the day when Sam is clear of this disease.

