---
title: "A day of relief"
description: "A day with energy.  Amazing what some fresh blood can do."
author: Colin C.
date: 2023-09-05
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---


Yesterday morning we wheeled Sam over to one of his clinic visits.  We often use a wheelchair to go back and forth to the hospital as Sam's energy is so low.  He still has the strength to walk but not the energy.  During these visits Sam's blood levels are checked as the chemotherapy drugs knock them back, and we need to be sure he does not get knocked back too hard.  The results of the tests came back and his hemoglobin and platelet numbers were low enough that he would have to spend an addition three hours in clinic receiving transfusions... but this time was worth it.  

It is amazing what some additional blood can do.  Following the clinic Sam walked most of the way back to the RMH.  He took the stairs. He enjoyed dinner. He wanted to wrestle and he spent lots of energy teasing us.  ... So good to see our Sam be himself! 




## Concerns and victories

-   We are all exhausted.  Sam has to carry the greatest burden with undergoing this treatment.  Tina and I are there to walk with him each step of the way and to provide all the parental care and also practical nursing care.  I don't think I look to see the end of this storm anymore ... rather I just hold on. 
    -   _Yesterday provided some relief from our fatigue -- So good to see Sam have some energy again._

-   We are thankful that there is a plan. However:\
The challenge with all of these plans is that we are in unknown territory.  I stated early on that Sam's cancer is very rare.  The reality is that it is essentially unknown.  In the world, there has been only one other documented case of this form of cancer. So, all of these plans are based in professional judgement/ best-guess.  We are thankful for our medical team that is able provide guidance, but we recognize that there is no standard protocol for Sam's cancer. 

-   We have a long list of new concerns which I am yet to process.  Top of mind: 
    1.   Although it seems there are good matches for Sam, a donor needs to be willing to make a donation, and all the logistics of timing and delivery need to come together.
    2.   Side effects both immediate and long-term would be limited. _Ideally, that there would be no measurable side effects_. 
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.

-   We are thankful for willing donors who are good matches for Sam.

-   We are thankful for the support of family and friends.  Please keep your notes of encouragement coming -- they can really bolster us. 

-   We are thankful for Sam's school who are looking forward to his return and who are willing to work with us once Sam is able.  

-   There is always concern that the cancer remains.   We long for the day when Sam is clear of this disease.

