---
title: "Completing round six's treatment phase"
description: "Chemotherapy drug delivery days are almost complete."
author: Colin C.
date: 2023-09-23
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

It is early Saturday morning, day 5 of Sam's chemotherapy, Sam and Tina are sleeping.  Today is the last chemo-drug delivery day for this sixth round.  Today is the last drug delivery day for this current treatment regime.  Thanks to our medical team here, by adjusting chemo delivery times a little each day we will get out of the hospital and back to the RMH by mid-afternoon -- much better than having to spend another night which is more the standard.  

Sam continues to take on this challenge well.  He is determined and has made the most of his time here.  Specifically, this time, he made choices to simply get out of the hospital room.  We spent hours sitting on the terrace/deck and in the family lounge reading and playing cards -- I finally beat Sam at crib though I expect this victory will be short lived. 

The realities of not going home after this treatment,  and of not starting school with his friends, are setting in and it is hard.  Sam misses home, his friends, and our life there. This is hard for him.  

We also choose hope and courage.  There is a plan and the next steps are laid out ahead of us.  We can do this. 

## Upcoming 

-    Regular check-ins at clinic. 

-    Tuesday we will also meet with the BMT team to review how their planning are going.  
-    In the weeks ahead there will be numerous baseline tests before starting radiation and BMT therapies.  I have these next steps outlined in [_The Plan_](/plan.qmd).


## Victories and concerns

-    Thankful for the care and connections with other families here at the RMH.  We are all walking our own journeys with our children in need.  Although each story is unique we find solidarity and some levels of comfort and council in the sharing of similar experiences. Over time these families are becoming friends.     

-   Sam remains in good spirits about the upcoming process (i.e. bone-marrow-transplant).  He knows it will be tough but he also knows that there is hope in completing this plan.  It is hard to see him carry all of this.  He has lots of hard days where he feels gross and with low energy, but he remains determined and even encouraged. 

-   Chemotherapy continues to take its toll.  His energy levels are lower with each round. The next phase of this round of chemotherapy will see his blood counts fall, an mucositis will likely set in.  We hope that that these impacts are not as strong as the last couple times and that Sam does not need to feel as gross. 

-   Sam will need strength for the BMT journey ahead.

-   In preparation for the BMT there are numerous items that need to come together:  
    1.   We are thankful for donors who are good matches for Sam.  We need one of them to agree to undergo the marrow extraction process.  One option is to just receive blood but the better option is to receive marrow.  The latter, receiving marrow, is far better for Sam but involves a intense procedure for the donor. 
    2.   Side effects both immediate and long-term would be limited. _Ideally, that there would be no measurable side effects_. 
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.

-   We are thankful for the support of family and friends.  Thank you for your notes of encouragement.

-   We are thankful for Sam's school who are looking forward to his return and who are willing to work with us once Sam is able.  We are thankful for his classmates who wrote him and sent him gifts. 

-   There is always concern as the cancer remains.   We long for the day when Sam is clear of this disease.

