---
title: "Much to be thankful for"
description: "Thanks-giving Day: though this journey is hard there is much to be thankful for."
author: Colin C.
date: 2023-10-09
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

![A Supercars event at the RMH. We got to explore and ride in some
amazing
cars](https://samsstory.s3.ca-central-1.amazonaws.com/supercars.jpg)

## Giving thanks

It is early morning here at BC Children's hospital and my family is
sleeping peacefully. This has been a long hard journey but we have much
to be thankful for. Top of my mind:

-   We are here and we have access to an incredible medical team and
    facility.

-   We are able to walk this journey as a family. Support from work,
    family and friends, church, and the local community allows us to be
    here without having to worry about life and responsibilities back
    home. Thank you!

-   The Ronald McDonald House provides us a home away from home.

-   Sam has been able to connect with friends -- especially in the last
    couple weeks. They talked or talked while playing online games.

-   Visitors: We have family in the area that come by on a regular basis
    to support us. We have friends that make extra efforts to some and
    see us.

### Highlights from this past week

Baseline tests and clinic days

:   As we begin to wrap up round 6 and pivot to bone-marrow transplant
    there are many medical appointments. This week was full with regular
    clinic visits plus the addition of baseline tests.

Thursday Nana and Kevin visit

:   Kevin and I got away -- we roamed around downtown and grabbed
    dinner. It was great to away from the hospital campus for a few
    hours.

:   Nana visited with Sam and Tina at the Ronald McDonald House.
    Following the loss of Gord, Mary has moved south where she is
    surrounded by family and can access Sam. She in a suite attached to
    Kevin and Shannon's.

Friday's fever

:   It was a normal clinic visit on Friday morning. We had gone in
    expecting to review blood levels and then return to the RMH.
    However, Sam spiked a fever. In a normal non-cancer scenario any of
    us would just sleep it off, but Sam's immune system is compromised.
    Antibiotics were started, tests and bacterial cultures were ordered,
    and plans were made to admit Sam to the ward for this past weekend.
    We are hoping/expecting to be discharged later today to return to
    the RMH.

:   Dave and Louise SP, friends of ours working in SE Asia were able to stop by before catching their flight back.  Great to catch up with and be encouraged by them. 

Supercars Saturday

:   One of the other parents at the RMH was able to connect with a group
    of Supercar owners. We thought we might miss-out but the doctor here
    gave Sam an afternoon pass to take part. We were able to talk with
    the owners, look at, sit in, and got for some quick rides in these
    beautiful cars. Makes included Ferrari, Lamborghini, McLaren, and
    Mercedes. I think whenever I see one of these cars on the road I
    will always remember the joy on all the families faces and the
    hospitality of all the owners.

## Upcoming

This week is very full includes:

-   Clinic check-ins

-   Tuesday: Bone marrow biopsy and Lumbar puncture -- to confirm that
    cancer continues to not be present in Sam's bones or central nervous
    system

-   Wednesday will start with a consult with a radiation oncologist
    (doctor specializing in the use of radiation therapy to combat
    cancer). This will be followed by Resporatory function and hearing
    tests -- to establish baseline metrics before the bone marrow
    transplant

-   Friday: PET Scan to determine the current state of Sam's cancer --
    though the results will not be available until the following week.
    \\

    This will be followed by an ultrasound of Sam's neck where heavy
    blood clotting was found associated with the cancer. It is expected
    that these clots have been reduced.

## Victories and concerns

-   Although we did not want to be in-hospital over this weekend we are glad that Sam's health is so well guarded by the team here. 

-   We are closing off this first major chapter in Sam's treatment.  With the completion of this last/ sixth round of chemotherapy we will pivot to the bone marrow treatment plan.  

-   That we would have enough strength/stamina, especially for Sam, as we are booked solid preparing for the BMT. 

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  We are thankful for a donor who is a match for Sam and that they
        are willing to undergo the full bone marrow extraction process!
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team have a huge coordination task ahead of them.
        All the pieces need to fall into place for the best timing
        possible.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.