---
title: "Targeted Radiation"
description: "Counting down the days towards the BMT"
author: Colin C.
date: 2023-10-30
categories: [regular, BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

It is *Day -15* as we count down the days towards Sam's bone marrow
transplant (BMT).

## This past week

### Treatment

Sam is currently in his targeted radiation phase, which is intended to
directly attack the main mass of cancer in his body. Each day this past
week we went to the BC Cancer clinic at Vancouver General Hospital
(VGH). During each visit the technician would use a mold of Sam to get
him into position. The mold extends from below his shoulders up over his
head and they use it to literally pin him to the treatment table
ensuring that he is in the exact same position each time -- thereby
ensuring the radiation focuses on the intended area.

Sam is doing well with it all. Sam is now over thirty days away from the
previous chemo-drug treatments and his strength is returning. He is a
generally healthy young man, but with cancer. This is where we want him
to be -- as healthy and as strong as possible before starting the BMT.

So far the only side effect from the radiation therapy has been fatigue.
It is different than chemo-fatigue which caused him to not have any
energy, be nauseated, and caused brain fog. This radiation induced
fatigue is the need to sleep, but once awake Sam usually has energy to
go for walks and enjoy his life.

### Visitors

We had a good number of family and friends visiting with us this past
week. Not everyone got to see Sam as he is being very cautious about
seeing people -- he is also training Tina and I to do the same as we all
mask up more and more. Visitors included:

-   Gram and Papa spent some great time with Sam prior to heading home
    this past Monday

-   Nana, now living in the area, was able to come by for the Thursday
    afternoon.

-   Uncle Kevin and cousin Kaden were able to be here for a few hours. I
    love it when Sam and Kaden have a chance to hang out.

-   Friday morning I had a great visit with Aaron W.

-   Friday afternoon we spent some good time, Colin with Rob, and Tina
    with Leanne D. They also delivered some great messages of support
    from our church family in Prince George – thank you all!

-   Yesterday evening we were able to get away from the RMH and spend
    the evening with family out in Langley – celebrating our nieces
    birthdays. We are so fortunate to have family close by.

## Upcoming

Today Sam returns to his targeted radiation therapy. It highly likely
that the impacts of this treatment will become more distinct with
increasing levels of fatigue and potentially skin and esophagus
irritation.

Next week after will be more difficult as Sam will have more intense
treatments to condition his body for the BMT – all the gains that have
been made in returning Sam to feeling healthy will likely be ripped out
from under him. These treatments include:

-   Total body radiation
-   BMT Chemotherapy -- intense chemo-drug therapy
-   Immune suppression drugs
-   The BMT transplant

See the [previous post](/posts/2309/2023-09-19_courage-and-despair.qmd)
or [The Plan](/plan.qmd) for the details.

## Victories and concerns

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It has been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity.

-   We have completed a major chapter in Sam's treatment. With the
    completion of this last/ sixth round of chemotherapy we now pivot to
    the bone marrow treatment plan -- this next treatment brings hope of
    removal of the disease but also anxiety about both the challenging
    process and the potential for long term side effects.

-   It is the beginning of flu season and covid is still out there. In
    the weeks ahead, as a family, we will be more cautious to reduce our
    risk of getting ill. If any of us get sick in the weeks ahead it
    will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   We are continually thankful for our medical teams here. They
    continue to provide incredible care. They are always open to
    conversation and answering questions. They have been incredibly
    pro-active and I am glad we are prepared for the next steps.

-   Thankful that the chemotherapy has been effective at initially
    reducing the cancer and lately keeping the cancer contained (as
    indicated by the PET scan). Thankful that these results allow us to
    move forward.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Due to some timing and logistics we have had to change donors.
        We are thankful for this current donor who will provide a
        peripheral blood sample and is a good match for Sam.
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team has a huge coordination task ahead of them.
        From out meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.