---
title: "Round 6 results and next steps"
description: "PET scan results confirm the current medical direction."
author: Colin C.
date: 2023-10-15
categories: [regular, results, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

This past Friday Sam had a number of appointments, starting with a PET
scan first thing in the morning. A PET scan provides 3-dimensional
imagery of where the cancer is in the body, and metrics of how
metabolically active the cancer is. We have been anxious for the results
of this scan as the data would provide direction for the next steps in
Sam's treatment. At clinic, in the afternoon, the results were back --
and confirmed the direction that we are going.

## Good results?

For Tina and I, and likely many of you, we hoped for a miraculously good
results -- that following these latest two rounds of chemotherapy the
cancerous mass would finally collapse and be non-detectable. We do not
have that result.

At the end of August, following the completion of round four, the
medical team communicated their plans to pivot towards a bone marrow
transplant[^1]. At that time it seemed evident that the cancer would not
fully respond to the planned six rounds of chemotherapy. This is the
result we have.

[^1]: See [Aug. 26
    post](/posts/2308/2023-08-26_results-and-recommendations.qmd) for
    the round 4 results


1.  The last two rounds of chemotherapy have held the cancer. The mass
    is stable -- it has not grown and it has not spread anywhere new.
    ... Although the cancer has not had any significant decrease in size, the
    chemotherapy regime that Sam has been under has been effective at
    holding the cancer back long enough to prepare the BMT process.  We also know that the BMT process is the next best step as the now completed chemotherapy was no longer effective at reducing the disease.

2.  The result are what the medical team hoped and planned for. Plans
    were initiated over seven weeks ago to prepare for this outcome.
    If the cancer had grown or spread our conversations with the medical
    team could have been very different.

The results are good -- as they support [the plan](/plan.qmd).\
The results are also challenging as a hard road lays ahead.

## Highlights from this past week

### Appointments

Lots of tests and appointments this past week.

```{r}
#| tbl-cap: Tests and appointments completed this past week.  Most of these were to create baseline measurements of Sam before starting the BMT treatment protocols. 
library(tidyverse)
library(lubridate)
library(knitr)
library(kableExtra)

dat <- 
  readxl::read_xlsx(path = "../../data/events-and-gifts.xlsx",
                    sheet = "BMT-planning"
  )


dat <- dat %>% 
  dplyr::select(Category,Day, Date2, Activity, Complete, Activity)

dat$Complete[is.na(dat$Complete)] <- ""


base <- dat %>% filter(Category == "Baseline") %>% 
    select(-Category) %>% 
    mutate(Date2 = date(Date2)) %>% 
    rename(Date = Date2)


base %>%
  select(Activity, Complete) %>% 
#   group_by(Day) %>% 
#   mutate(Day = replace(Day, duplicated(Day), " ")) %>% 
#   ungroup() %>% 
#   group_by(Date) %>% 
#   mutate(Date = as.character(Date)) %>% 
#   mutate(Date = replace(Date, duplicated(Date), " ")) %>% 
#   ungroup() %>% 

  kbl() %>% 
  kable_styling(bootstrap_options = "striped")


```

### Visits

Sam has been able to connect with friends online.

Friday afternoon Sam and his Uncle Cal had a great connection
remembering and celebrating Papa Gord together.

## Upcoming

For the most part Sam may have much of this coming week off. There will
be clinic visits but the intent of the medical team is to give his body
a break and get him as strong as we can before the BMT process starts.

We are looking forward to visits with friends and family.

## Victories and concerns

-   We have finished the week strong -- despite a long list of bookings
    we made it through and Sam is in good spirits.

-   We have completed a major chapter in Sam's treatment. With the
    completion of this last/ sixth round of chemotherapy we now pivot to
    the bone marrow treatment plan.

-   It is the beginning of flu season and covid is still out there. In
    the weeks ahead, as a family, we will be very cautious to reduce our
    risk of getting ill. If any of us get sick in the weeks ahead it
    will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   I am continually thankful for our medical teams here. They continue
    to provide incredible care. They are always open to conversation and
    answering questions. They have been incredibly pro-active and I am
    glad we are prepared for the next steps.

-   Thankful that the chemotherapy has been effective at initially
    reducing the cancer and lately keeping the cancer contained (as
    indicated by the PET scan). Thankful that these results allow us to
    move forward.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Due to some timing and logistics we have had to change donors.
        We are thankful for this current donor who will provide a
        peripheral blood sample and is a good match for Sam.
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team have a huge coordination task ahead of them.
        All the pieces need to fall into place for the best timing
        possible.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.