---
title: "Courage and Despair"
description: "My, Colin/Dad's confrontation with despair. "
author: Colin C.
date: 2023-09-19
categories: [regular, meditation]
draft: false
editor: 
  markdown: 
    wrap: 72
---



::: callout-note
## Definitions

::: {layout-ncol="2"}


::: {.courage}
### cour·age
_/ˈkərij/_

: the ability to do something that frightens one.\
"she called on all her courage to face the ordeal"

: strength in the face of pain or grief.\
"he fought his illness with great courage"
:::

::: {.despair}

### de·spair
_/dəˈsper/_

: the complete loss or absence of hope.\
"in despair, I hit the bottle"

:::

:::

<span style="font-size: 80%">_Google definitions powered by Oxford Languages_</span>
:::

This morning I am writing from the RMH dining hall as my family sleeps upstairs. It is the morning of day 154, and day 1 of round 6 should start later today.  This has been a hard and long journey. If all had gone as hoped this would be a day to celebrate as it would be the beginning of the last round of therapy.  But things have not gone as planned, and this is just one more step in the effort to rid Sam's body of cancer. 

## Courage
I have often told Sam that, though we may not get to choose our circumstances, we can always choose how we respond to them.  Will we respond courageously and act rightly/ virtuously? Or do we react in frustration -- and further fuel the storm^[I think I have said this better here then I have every said it to him]?  Sam has been incredibly courageous.  Facing this storm, this terrifying storm, and he has chosen courage.  Not that he has never felt fear.  Rather, courage is not the absence of fear, it is choosing to face it.  

## Facing Despair
This past week I was exhausted -- mentally and emotionally exhausted, and it was starting to take a toll on me physically.  I was not only wrestling with this cancer storm, I wrestled with my worldview at the core of my being; the foundations of how I interpret life have been shaken to the core.  I wrestled with God -- where is my God who saves.  I have faced Despair and I had moments where I felt that beast would take me. 

I am no longer there.  I have faced the beast Despair.  And I now walk with new energy and freedom.   It is not by my own power that I have overcome.  I am still processing all the layers that have come together to provide this victory^[I may write more on this in the weeks ahead]. Numerous pieces have come together including snippets of conversations, the example of another family, concepts from a good book, and some additional experiences.  

A simplification of some lessons learned: 

a.  Cancer is evil.
b.  God is good. 
c.  There is hope. 
d.  Despite this storm we are able to _live the good life_.\
I am intentionally leaving this undefined for now, and leave it for you to wrestle with.  


## Highlights from this past week

Wed. and Thursday 
: Quiet days at the RMH.  Lots of rest as Sam's numbers continued to return.  Tina and I got out to Cambie Village for a coffee together.

Friday
: Cal was able to visit.  We are grateful for his care and compassion, and conversations with Cal always thought provoking. 
: Gram and Papa C. arrived and visited here at the RMH.  Great to receive their love and the love of Buddy.

Saturday through Monday 
: We had a number of good visits with my parents.  This included them visiting us here and us making a couple trips out to their trailer in Ft. Langley to enjoy the last of summer camping.  One afternoon while Sam had time with his grandparents Tina and I had some time to roam Ft. Langley together.  Another afternoon I took Buddy for a short hike to Tavistock View Point on McMillan Island. 
: Yesterday evening Tina was filled with joy having a chance to play with her nieces Jane, Amanda, and great-niece Jayme (Amanda's daughter), at the campsite playground.


## Victories and concerns

-    Thankful for the care and connections with other families here at the RMH.  We are all walking our own journeys with our children in need.  Although each story is unique we find solidarity and some levels of comfort and council in the sharing of similarities in the struggle. Over time these families are becoming friends.     

-   Sam remains in good spirits about the upcoming process (i.e. bone-marrow-transplant).  He knows it will be tough but he also knows that there is hope in completing this plan.  It is hard to see him carry all of this.  He has lots of hard days where he feels gross and with low energy, but he remains determined and even encouraged. 

-   Chemotherapy continues to take its toll.  His energy levels are lower with each round. As we enter round 6 Sam's strength has been diminished.  He needs strength for the journey ahead.

-   In preparation for the BMT there are numerous items that need to come together:  
    1.   We are thankful for donors who are good matches for Sam.  We need one of them to agree to undergo the marrow extraction process.  One option is to just receive blood but the better option is to receive marrow.  The latter, receiving marrow, is far better for Sam but involves a intense procedure for the donor. 
    2.   Side effects both immediate and long-term would be limited. _Ideally, that there would be no measurable side effects_. 
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.

-   We are thankful for the support of family and friends.  Thank you for your notes of encouragement.

-   We are thankful for Sam's school who are looking forward to his return and who are willing to work with us once Sam is able.  We are thankful for his classmates who wrote him and sent him gifts. 

-   There is always concern as the cancer remains.   We long for the day when Sam is clear of this disease.

