---
title: "PET this morning"
description: "PET scan results will direct next steps."
author: Colin C.
date: 2023-10-13
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---


## PET Scan

Sam has a PET scan first thing this morning.  This scan is the best tool for imaging the state of his cancer and how his chemotherapy has progressed.  Decisions moving forward will be based on the results of this scan.  

Needless to say, all of us, including the medical team, are anxious for the results.  Preliminary findings may be available by the end of the day but the full report will not be available until next week.


## Victories and concerns

-   Although we did not want to be in-hospital over this weekend we are glad that Sam's health is so well guarded by the team here. 

-   We are closing off this first major chapter in Sam's treatment.  With the completion of this last/ sixth round of chemotherapy we will pivot to the bone marrow treatment plan.  

-   That we would have enough strength/stamina, especially for Sam, as we are booked solid preparing for the BMT. 

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  We are thankful for a donor who is a match for Sam and that they
        are willing to undergo the full bone marrow extraction process!
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team have a huge coordination task ahead of them.
        All the pieces need to fall into place for the best timing
        possible.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.