---
title: "Round 5: Thru the valley"
description: "By the numbers we have crossed the round 5 valley"
author: Colin C.
date: 2023-09-12
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---


Yesterday, we were in clinic.  Sam's blood levels indicate that he is starting to climb out of the round 5 chemo-valley.  He is through the worst of this round. 


## This past week

-   Most of a day at the BC Cancer clinic to begin planning for radiation treatments.
-   Clinic visits at BC Children's including additional blood transfusions to bolster Sam through through the chemo-valley.

-   We snuck Tina home for a few days so that she could take care of some of her own medical needs.  She came back to us with her heart-bucket filled having connected with family and a few friends. 
-   Sam has able to connect with friends online and with a new friends here at the RMH. 
-   The Frickers visited on Sunday.  I love seeing Sam's face brighten as he spends time with his cousin Kaden. 
-   Last night David and Krista C. were able to visit.  So good to catch up with friends and have normal conversation.  They also brought personal care-card from Sam's classmates which he loved.  Krista also gifted her with her cookies -- dangerously good.

## Upcoming

-   Clinic appointments including a fairly routine lumbar puncture this Friday.

-   We are looking forward to a weekend.  Sam should be out of the chemo-valley.  An opportunity to feel good for a few days before we do it all again.  

-   Gram and Papa C. along with Buddy will be down for this weekend.

-   Round 6 will start next Tuesday.  



## Concerns and victories

-   We are thankful to be through the valley of round five. 

-   Sam is in good spirits about the upcoming process (i.e. bone-marrow-transplant).  He knows it will be tough but he also knows that it has an end.  It is hard to see him carry all of this.  He has lots of hard days where he feels gross and with low energy, but he remains determined and even encouraged.  

-   In preparation for the BMT there are numerous items that need to come together.  Top of mind: 
    1.   We are thankful for donors who are good matches for Sam.  We need one of them to agree to undergo the marrow extraction process.  One option is to just receive blood but the better option is to receive marrow.  The latter, receiving marrow, is far better for Sam but involves a intense procedure for the donor. 
    2.   Side effects both immediate and long-term would be limited. _Ideally, that there would be no measurable side effects_. 
    3.   The medical team have a huge coordination task ahead of them.  That all the pieces fall into place for the best timing possible.



-   We are thankful for the support of family and friends.  Thank you for your notes of encouragement -- they really do bolster us. 

-   We are thankful for Sam's school who are looking forward to his return and who are willing to work with us once Sam is able.  We are thankful for his classmates who wrote him and sent him gifts. 

-   There is always concern as the cancer remains.   We long for the day when Sam is clear of this disease.

