---
title: "Other followers"
description: "Jesus's team is bigger than the disciples think."
author: Colin C.
date: 2023-10-12
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 9: 38 - 41](https://www.bible.com/bible/111/MRK.9.NIV)

> “Teacher,” said John, “we saw someone driving out demons in your name and we told him to stop, because he was not one of us.”\
> “Do not stop him,”Jesus said. “For no one who does a miracle in my name can in the next moment say anything bad about me, for whoever is not against us is for us.  Truly I tell you, anyone who gives you a cup of water in my name because you belong to the Messiah will certainly not lose their reward.

### Thoughts and questions 

I had to think about this one for a day.  Why is this important to Jesus' story.  Sure "_whoever is not against us is for us_" seems pretty straight forward.  

This passage makes me think Jesus' message is not complicated.  Someone probably made it to some of his teaching sessions, watched what Jesus did -- or watched what the disciples did and then chose to walk in their footsteps.  

It makes me wonder what barriers do we put up that block people from not only hearing about Jesus but also acting in his ways.  

Are there barriers that you have in not acting out what Jesus did? 

Finally, let's keep an open mind to allow Jesus to meet and empower people.  Let's be faithful to love as he loved, and to encourage and support anyone that would choose Him.

### Prayer

Lord may I never get in your way.  May my life be a beacon of hope that shines for other -- showing your love and compassion.  Help me to see how you are at work in others lives! 