---
title: "There are no 'ifs'"
description: "Jesus heals the impossible"
author: Colin C.
date: 2023-10-06 
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 9: 14 - 29](https://www.bible.com/bible/111/MRK.9.NIV)

> When they came to the other disciples, they saw a large crowd around them and the teachers of the law arguing with them. As soon as all the people saw Jesus, they were overwhelmed with wonder and ran to greet him.\
> “What are you arguing with them about?” he asked.\
> A man in the crowd answered, “Teacher, I brought you my son, who is possessed by a spirit that has robbed him of speech. Whenever it seizes him, it throws him to the ground. He foams at the mouth, gnashes his teeth and becomes rigid. I asked your disciples to drive out the spirit, but they could not.”\
> “You unbelieving generation,”Jesus replied, “how long shall I stay with you? How long shall I put up with you? Bring the boy to me.”\
> So they brought him. When the spirit saw Jesus, it immediately threw the boy into a convulsion. He fell to the ground and rolled around, foaming at the mouth.\
> Jesus asked the boy’s father, “How long has he been like this?”\
> “From childhood,” he answered. “It has often thrown him into fire or water to kill him. But if you can do anything, take pity on us and help us.”\
> “ ‘If you can’?” said Jesus. “Everything is possible for one who believes.”\
> Immediately the boy’s father exclaimed, “I do believe; help me overcome my unbelief!”\
> When Jesus saw that a crowd was running to the scene, he rebuked the impure spirit. “You deaf and mute spirit,” he said, “I command you, come out of him and never enter him again.”\
> The spirit shrieked, convulsed him violently and came out. The boy looked so much like a corpse that many said, “He’s dead.” But Jesus took him by the hand and lifted him to his feet, and he stood up.\
> After Jesus had gone indoors, his disciples asked him privately, “Why couldn’t we drive it out?”\
> He replied, “This kind can come out only by prayer.”


### Thoughts and questions 

Jesus' disciples were out in the community doing what Jesus asked them to do.  From back in Mark 6:12 Jesus delegated his disciples to do the work 

> They went out and preached that people should repent. They drove out many demons and anointed many sick people with oil and healed them.\
_see also our [Mark 8:1-12 post](../mark_08/mark-08-01.qmd)_

So we know Jesus had given his the disciples the power and authority to cast out demons.  But they could't do it this time.  This one would only come out through prayer.  

There are clues in this this passage that point to a disease known as epilepsy it starts in childhood and causes seizers like the father describes.  As far as I know it there is still no cure for this disease.  But Jesus cured it!  He didn't stop and pray, it seemed he was even in a rush to do it before the crowd arrived see what was happening.  He simply commanded and it happened.

> “Everything is possible for one who believes.”

### Prayer

Lord God, I choose to believe, but me overcome that which is in me that doubts.  Help be to believe entirely.  Help be transform my weak belief to a strong belief. 

Bring health and healing in its entirety.  Please! Remove this cancer and bring fully healing.

I trust you.  Help me when my doubts arise. 

