---
title: "Jesus the servant-leader"
description: "Jesus predicts his death and calls his followers to be servants."
author: Colin C.
date: 2023-10-08
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 9: 30 - 37](https://www.bible.com/bible/111/MRK.9.NIV)

> They left that place and passed through Galilee. Jesus did not want anyone to know where they were, because he was teaching his disciples. He said to them, “The Son of Man is going to be delivered into the hands of men. They will kill him, and after three days he will rise.” But they did not understand what he meant and were afraid to ask him about it.\
> They came to Capernaum. When he was in the house, he asked them, “What were you arguing about on the road?” But they kept quiet because on the way they had argued about who was the greatest.
Sitting down, Jesus called the Twelve and said, “Anyone who wants to be first must be the very last, and the servant of all.”\
> He took a little child whom he placed among them. Taking the child in his arms, he said to them, “Whoever welcomes one of these little children in my name welcomes me; and whoever welcomes me does not welcome me but the one who sent me.”

### Thoughts and questions 

Jesus actually gets away from the crowds in these verses.  He needed to teach his disciples -- not the crowd.  Looking backwards, in retrospect, his message seems quite straight forward.  He is telling them exactly what is about to happen.  Putting yourself in the discipls shoes -- would we have understood what Jesus was teaching.  I think these words about death would seem ridiculous or like something out of a myth or fairy tale.  

I really like how Jesus' predictions of his death are coupled with the verse about the first being last and that if you want to be first you must be a _servant to all_.  The reality is that Jesus is first in God's kingdom, and this is exactly what he does -- he serves us. 

The final verse about the little child seems like a random addon to this passage ... What is the point? Again, Jesus is demonstrating servant leadership -- providing loving care to the weak the vulnerable.  In contrast, by worldly standards of striving to be the best, I don't think people looking for success give much thought to children -- they can't get anything from them; they can't support the striving for success.  

### Prayer

Lord God, help me to love, serve, and welcome people that I might show them a glimpse of you.  

Thank you that you are the best example to us -- serving and loving us even unto your crucifixion.  Thank you that you have conquered death -- that it has no hold on you and that we have the promise to be with you.  

Give us strength and courage for our lives to show your compassion to others. 