---
title: "Kingdom come -- all you need is Jesus"
description: "Peter, James, and John get to see Jesus' kingdom in power"
author: Colin C.
date: 2023-09-26    
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 9: 1 - 13](https://www.bible.com/bible/111/MRK.8.NIV)

> And he said to them, “Truly I tell you, some who are standing here will not taste death before they see that the kingdom of God has come with power.”\
>
> After six days Jesus took Peter, James and John with him and led them up a high mountain, where they were all alone. There he was transfigured before them. His clothes became dazzling white, whiter than anyone in the world could bleach them. And there appeared before them Elijah and Moses, who were talking with Jesus.\ 
> Peter said to Jesus, “Rabbi, it is good for us to be here. Let us put up three shelters—one for you, one for Moses and one for Elijah.” (He did not know what to say, they were so frightened.)\
> Then a cloud appeared and covered them, and a voice came from the cloud: “This is my Son, whom I love. Listen to him!”\
> Suddenly, when they looked around, they no longer saw anyone with them except Jesus.\
> As they were coming down the mountain, Jesus gave them orders not to tell anyone what they had seen until the Son of Man had risen from the dead. They kept the matter to themselves, discussing what “rising from the dead” meant.\
> And they asked him, “Why do the teachers of the law say that Elijah must come first?”\
> Jesus replied, “To be sure, Elijah does come first, and restores all things. Why then is it written that the Son of Man must suffer much and be rejected? But I tell you, Elijah has come, and they have done to him everything they wished, just as it is written about him.”

### Thoughts and questions 

Though I trust that these experiences truly happened there is also deep symbolism in this story.  
-   Moses -- represents the law given to the people of God
-   Elijah -- represents the prophets who called people to God and gave them promises for the future.

God gave people the law to live by -- to teach them his ways, and that they would know the difference between right and wrong. A central aspect in the law is also the means of reconcilement with God -- the need for sacrifice. Then He sent the prophets to remind them, and call them back to live rightly.  He also used the prophets for make promises regarding the future -- a Messiah, and the establishing the kingdom of God. 

> _This is my Son, whom I love.  Listen to him._

At the end of this story we are left with Jesus -- he is the fulfillment.  Listen to him.  You don't need the law, you don't need the prophets, because Jesus is the fulfillment of them both.  Listen to Jesus.  Live the way that Jesus calls you to live. 

### Prayer

Lord Jesus, guide us and teach us.  May my life reflect your ways.  As I know your love and mercy, may my life reflect your love and compassion to others.  My hope and my confidence are in you. 

