---
title: "Keeping the faith"
description: "Strengthening our faith in community"
author: Colin C.
date: 2023-10-19
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 9: 42 - 50](https://www.bible.com/bible/111/MRK.9.NIV)

> “If anyone causes one of these little ones—those who believe in me—to stumble, it would be better for them if a large millstone were hung around their neck and they were thrown into the sea. If your hand causes you to stumble, cut it off. It is better for you to enter life maimed than with two hands to go into hell, where the fire never goes out. And if your foot causes you to stumble, cut it off. It is better for you to enter life crippled than to have two feet and be thrown into hell. And if your eye causes you to stumble, pluck it out. It is better for you to enter the kingdom of God with one eye than to have two eyes and be thrown into hell, where\
> “ ‘the worms that eat them do not die,\
> and the fire is not quenched.’\
> Everyone will be salted with fire.\
> “Salt is good, but if it loses its saltiness, how can you make it salty again? Have salt among yourselves, and be at peace with each other.”

### Thoughts and questions 

Who are the little ones?  I read the same passage in _The Message_ translation, which interprets them to be the new believers that were casting out demons in Jesus' name -- but were not part of the core group of disciples.  I think the point is -- don't squash someones faith because they are not fully trained the way that you are expecting.  

The rest of passage seems to be about self reflection and removing parts of your life that separate you from God. I like this because in the first verses the disciples are told not to judge new believers and this is immediately followed up by evaluating yourself, and taking actions to make yourself better.  This passage may also be used to emphasis Jesus' desire to not judge the young believer.  Would you really cut off parts of your own body -- likewise treat the young believer well. 

What about salt?  Salt, especially in ancient times was used as a preservative -- to keep food from going bad.  Examples of this today could include pickles or salted meats.  I think ths verse aligns well with the previous -- that we need to preserve one another in our faith. 


### Prayer

Lord, may I always be an encouragement to others who follow you.  Let my life and my faith bolster theirs and as we share stories may they be of how good you are, and how good it is to walk in your ways.  Help me guard my thoughts and action that they would always be pleasing to you.  

