---
title: "Scan results"
description: "Sam is tolerating the latest medications well and the latest scan results are encouraging."
author: Colin C.
date: 2024-07-09
# date-modified: 2024-06-21
categories: [regular, results]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Happy Anniversary -- Tina and I celebrate 28 years.
-   Pain management for Sam (again).
-   Sam is able to continue with the latest mix of medications.
-   MRI results indicate no growth in the cancer!
-   Other family challenges.
-   Going home!
:::

```{=html}
<!-- ::: {#photo}
![On May 29^th^ we checked out of the Ronald McDonald House for the
first time since starting this cancer battle! We took a ten day break
home -- it was amazing to be
there!](https://samsstory.s3.ca-central-1.amazonaws.com/2024-05-29_rmh-checkout.jpg)
::: -->
```
It has been a week-and-a-half since my last post. Despite some
challenges the overall picture is good as Sam's body has tolerated this
new combination of medications. In addition, the MRI scan showed that
the cancer has not grown since the previous scan.

## Challenges

### June 29^th^

We have had a few challenges since I last wrote -- I am glad they are
not all focused on Sam.

The last weekend of June was tough. Tina and I celebrated our 28^th^
anniversary (love you Tina!) while visiting family in White Rock. Sam
had received his dose of Nivolumab a week earlier and what we now know/
remember is that it takes about a week for effects and corresponding
pains to set in. One of the hardest things in this whole journey is to
watch your child when they are in pain and to not understand what is
causing it. Over the next couple days we were able to get his pain under
control allowing to feel himself again.

Also that weekend, Nana Mary was having some heart related symptoms that
gave us a scare -- she seems to be good now.

To celebrate our anniversary, instead of going out for dinner, Tina and
I chose to stay in and eat with our beloved Sam and mother Mary. It was
a really good evening.

### July 6 - 8

One reason that this post is a few days late coming is this past weekend
I was laid flat. A head cold took all my energy for the better part of
Saturday through Monday.

## Current medical situation

Sam's medical situation over the last couple weeks is generally good
news!

First, Sam's body is tolerating the latest mix of medications --
specifically,
[Nivolumab](http://www.bccancer.bc.ca/drug-database-site/Drug%20Index/Nivolumab_monograph.pdf)
and
[Ruxolitinib](http://www.bccancer.bc.ca/drug-database-site/Drug%20Index/Ruxolitinib_monograph.pdf).
The initial attempt to use Nivolumab, at the end of Feb., did not go
well and resulted in lost time recovering from side effects (primarily
liver inflammation). Currently, the combination of these two drugs seems
to be working well -- specifically metrics related to Sam's liver are
stable and even in normal ranges.

Sam also had an MRI of his chest last week the results of which were
encouraging. Though it is too soon tell, or to relate the scan to the
latest drug regime, the results indicated that the cancerous mass had
not grown (in contrast to the previous PET scan). We are once again
hopeful that the cancer can be held back/ controlled. The MRI also
provided incredible details of Sam's upper body and the medical team
will continue to review this latest set of images to evaluate future
treatment options.

## Looking forward

It is hard to believe, but a pattern to life may be starting to emerge.
We are now making plans with our medical team that extend beyond the
next clinic visit. Given that Sam is tolerating the medications we are
starting to look to the weeks ahead.

1.  Sam will need to be in Vancouver every two weeks to receive the dose
    of Nivolumab.
2.  Coupled with this approximately every four weeks he will have some
    sort of scan (likely alternating between PET and CT)

Sam received his latest does this past Friday and yesterday's numbers
looked good.

Given that there is nothing to do here in Vancouver until the 19^th^ we
will head for home tomorrow!

## Victories and concerns

-   Sam's immune therapy plan is going forward. The medical team is
    keeping a close eye on Sam to ensure that he does not have any
    adverse side effects. Following two weeks of Nivolumab Sam has not
    had any adverse side effects!

-   Results from the July 4^th^ MRI indicate that the cancer has not
    grown!

-   Thankful that we can look ahead and that we can make it home again!

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We long for the day when Sam is clear of this disease.