---
title: "Home Again"
description: "We are tentative, but it is starting to feel like a pattern to life seems to be starting to emerge."
author: Colin C.
date: 2024-07-26
# date-modified: 2024-06-21
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   We are home again! We got home on the 23^rd^ following a short
    medical trip to Vancouver (July 18 - 22).
-   Sam has successfully received his latest dose of Nivolumab and his
    body continues to tolerate this set of medications.
-   Sam is scheduled for a PET scan on August 2^nd^.
:::


::: {#photo}
![Enjoying some hours at Crescent Beach! Great visit with Nana Mary and
the Frickers.](https://samsstory.s3.ca-central-1.amazonaws.com/2024-07-21_chisholm-cresent-beach.jpg)
:::

I can understand it if you were feeling like you were missing our on our
lives and wondering what is going on – it has been over two weeks since
I last wrote.

In that time we were at home, travelled to Vancouver, and returned home
again. During our times at home, we had some good visits with a number
of our friends here, and I started to feel that I was maybe beginning to
recover from burnout. Sam, of course, despite often feeling physically
exhausted from it all, continues to be amazing, maintaining his positive
attitude throughout this long journey.

## Looking back

Most recently, last Thursday, July 18, we made a roadtrip down to BC
Children's. We chose to drive as it allows for more flexible timing and
gives us some freedom while there. On that Friday, there was a minor
question-mark related to some of Sam's bloodwork and the team chose: to
adjust some of Sam's supporting medications[^1], and to wait out a cold
that he had.

[^1]: Supporting meds being the switch from prednisone to hydrocortisone
    for increased adrenal support. Note that weaning off of prednisone
    seemed to not provide enough adrenal support, including support to
    effectively battle the cold he had.

Over the weekend we were able to have a visit with the Frickers and Nana
including a nice afternoon watching the tide come in at Crescent Beach.

The next Monday Sam's cold and bloodwork had improved and he was able to
receive another dose of Nivolumab. In addition an echocardiogram showed
that there were no significant negative impacts on Sam's heart. Despite
not leaving the clinic until 4:30 that afternoon we decided to start our
trip home. We made it to Kamloops that night and the rest of the way on
Tuesday.

This last trip down marks our shortest visit to BC Children's Hospital
and the Ronald McDonald house. It is our hope that this will become a
more normal pattern. Yet it is too soon to discuss patterns or plans for
life.

## Looking forward

On August 2^nd^ Sam is due back in Vancouver. We will spend several days
there as he is scheduled for a PET scan, an ultrasound, and another dose
of Nivolumab.

In the meantime we have just over a week at home. We are loving it here
– however in some ways it is a strange adjustment (including not having
Tina's parents here). Many thanks to whoever mowed our backyard! In this
time we will celebrate birthdays, I will get to work for some part days,
and we hope to continue reconnecting with our Prince George friends and
family.

## Victories and concerns

-   Sam's immune therapy plan continues to move forward. Following three
    doses of Nivolumab Sam has not had any severe adverse side effects!

-   Results from the July 4^th^ MRI indicated that the cancer mass in
    Sam's chest has not grown!

-   Thankful that we can look ahead a little and that we can be home
    again!

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We long for the day when Sam is free of this disease.