---
title: "Spreading the good news"
description: "Jesus delegates, and the disciples start doing the work"
author: Colin C.
date: 2023-08-01
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 6 - 12](https://www.bible.com/bible/111/MRK.6.NIV)

> Then Jesus went around teaching from village to village. Calling the Twelve to him, he began to send them out two by two and gave them authority over impure spirits.\
> These were his instructions: “Take nothing for the journey except a staff—no bread, no bag, no money in your belts. Wear sandals but not an extra shirt. Whenever you enter a house, stay there until you leave that town.  And if any place will not welcome you or listen to you, leave that place and shake the dust off your feet as a testimony against them.”\
> They went out and preached that people should repent. They drove out many demons and anointed many sick people with oil and healed them.

### Thoughts and questions 

Jesus and the disciples leave his home town, teach, and bring healing to the people in many other communities.  He we also see a major shift -- as Jesus gets his disciples to start doing the work.  

What is their message? 

1.   Repent.  Turn to God.  I think the why is implied.  The previous chapters have highlighted that God's kingdom is here (the good news).  So repent and prepare to be a part of His kingdom.
2.   I think it is also awesome that Jesus gives the authority to heal and free people from spiritual oppression (i.e. demons).  I have always been taught that oil is significant -- as it was the only medicine that people had at the time.  I am sure there were supernatural/ God powered healings, but there was also the use of medicine.  

I also love how Jesus prepared them.  That a\) they should not worry about their provisions (food and lodging), and b\) that the should preach where they are welcomed -- don't waste time and effort but move on to where people are open to the message.


### Prayer

Lord, you are the healer.  You have the power.  Please bring healing here.  Please shape our hearts and minds to align with your will -- let your will be done. 

When we are presented with opportunities to share your good news -- that you love and what all people.  Give us the words, courage, and inspiration fo share your life and message. 