---
title: "The sick child ... dead child"
description: "Jesus is never too late"
author: Colin C.
date: 2023-07-21
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 1 - 6](https://www.bible.com/bible/111/MRK.6.NIV)

> Jesus left there and went to his hometown, accompanied by his disciples. When the Sabbath came, he began to teach in the synagogue, and many who heard him were amazed.\
> “Where did this man get these things?” they asked. “What’s this wisdom that has been given him? What are these remarkable miracles he is performing? Isn’t this the carpenter? Isn’t this Mary’s son and the brother of James, Joseph, Judas and Simon? Aren’t his sisters here with us?” And they took offense at him.\
> Jesus said to them, “A prophet is not without honor except in his own town, among his relatives and in his own home.” He could not do any miracles there, except lay his hands on a few sick people and heal them. He was amazed at their lack of faith.

### Thoughts and questions 

I struggle with this story.  Why did Mark include it?  There are definitely a couple phrases that jump out at me.  They jump out at me, almost like warnings.  

a.    _He was amazed at their lack of faith._  This strikes me as Jesus' power to work is somehow linked to their ability to have faith.  
b.    _They took offense at him._  I can't help but think that our culture seems to take offense at Jesus, or perhaps they take offense at how Jesus has been presented to them. ... I am not sure if it is a problem with the culture of our nation or the culture of our churches.  ... It is likely both.  

So what do we do with this?  How am I to respond? 

1.  I need to guard my heart -- that I choose to honor Jesus.  This raises another question of what does it look like to honor him. 
2.  I need to trust Him, continually put my faith in Him.  Again this is a choice, and not one that I made once but one that I should make daily.  

### Prayer

Lord Jesus, I choose to place my faith in you today.  I choose to trust you everyday.  Forgive me when I falter.  Forgive me when my actions fail to honor you.  Correct me and guide me.  Be at work in my life.  I need you, we need you.  