---
title: "Be careful what you promise"
description: "King Herod, feeling guilt, thinks Jesus is John the Baptist back from the dead"
author: Colin C.
date: 2023-08-03
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 14 - 29](https://www.bible.com/bible/111/MRK.6.NIV)

> King Herod heard about this, for Jesus’ name had become well known. Some were saying, “John the Baptist has been raised from the dead, and that is why miraculous powers are at work in him.”
> Others said, “He is Elijah.”\
> And still others claimed, “He is a prophet, like one of the prophets of long ago.”\
> But when Herod heard this, he said, “John, whom I beheaded, has been raised from the dead!”\
> For Herod himself had given orders to have John arrested, and he had him bound and put in prison. He did this because of Herodias, his brother Philip’s wife, whom he had married. For John had been saying to Herod, “It is not lawful for you to have your brother’s wife.” So Herodias nursed a grudge against John and wanted to kill him. But she was not able to, because Herod feared John and protected him, knowing him to be a righteous and holy man. When Herod heard John, he was greatly puzzled; yet he liked to listen to him.\
> Finally the opportune time came. On his birthday Herod gave a banquet for his high officials and military commanders and the leading men of Galilee. When the daughter of Herodias came in and danced, she pleased Herod and his dinner guests.\
> The king said to the girl, “Ask me for anything you want, and I’ll give it to you.” And he promised her with an oath, “Whatever you ask I will give you, up to half my kingdom.”\
> She went out and said to her mother, “What shall I ask for?”\
> “The head of John the Baptist,” she answered.\
> At once the girl hurried in to the king with the request: “I want you to give me right now the head of John the Baptist on a platter.”\
> The king was greatly distressed, but because of his oaths and his dinner guests, he did not want to refuse her. So he immediately sent an executioner with orders to bring John’s head. The man went, beheaded John in the prison, and brought back his head on a platter. He presented it to the girl, and she gave it to her mother. On hearing of this, John’s disciples came and took his body and laid it in a tomb.

### Thoughts and questions 

There is movie level twisted drama in Herod's family.  Herod is married to Herodias, who was his brother Philip's wife.  I think that it is Herod's step-daughter that dances for him and all his guests (as the text says Herodias' daughter, not Herod's).  

I think the main point of this story is to convey the history of what happened to John the Baptist.  ... I do not see a main point of teaching / take-home message here.  But there are definite life-warnings in this passage.  

1.   Be careful what you promise, and even how you promise. 
2.   I think this extend to be careful who you make promises to.  

One more thought on this passage.  I think this story also conveys how famous Jesus had become.  He was not some unknown name preaching out in the countryside.  He was the talk of the nation.  Who is this guy and how is he doing these miricles.  For those in power, they were likely scared that he would take their power away. 

### Prayer

Lord Jesus, you life upset the status-quo. Through your life we are called to turn from evil ways, we are called to lives demonstrating your love and compassion, we are called to be your followers, true followers of God.  Guide our minds and hearts that we would know how to follow you.  May your power be at work in our lives.  Thank you that as we turn to you we are forgiven.  Let us also forgive others.  Let us understand your will and join in your purposes.  