---
title: "You feed them"
description: "The people are desperate to hear from Jesus; and he has compassion on them."
author: Colin C.
date: 2023-08-05
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 30 - 45](https://www.bible.com/bible/111/MRK.6.NIV)

> The apostles gathered around Jesus and reported to him all they had done and taught. Then, because so many people were coming and going that they did not even have a chance to eat, he said to them, “Come with me by yourselves to a quiet place and get some rest.”\
> So they went away by themselves in a boat to a solitary place. But many who saw them leaving recognized them and ran on foot from all the towns and got there ahead of them. When Jesus landed and saw a large crowd, he had compassion on them, because they were like sheep without a shepherd. So he began teaching them many things.\
> By this time it was late in the day, so his disciples came to him. “This is a remote place,” they said, “and it’s already very late. Send the people away so that they can go to the surrounding countryside and villages and buy themselves something to eat.”\
> But he answered, “You give them something to eat.”\
> They said to him, “That would take more than half a year’s wages! Are we to go and spend that much on bread and give it to them to eat?”\
> “How many loaves do you have?”he asked. “Go and see.”\
> When they found out, they said, “Five—and two fish.”\
> Then Jesus directed them to have all the people sit down in groups on the green grass. So they sat down in groups of hundreds and fifties. Taking the five loaves and the two fish and looking up to heaven, he gave thanks and broke the loaves. Then he gave them to his disciples to distribute to the people. He also divided the two fish among them all. They all ate and were satisfied, 43and the disciples picked up twelve basketfuls of broken pieces of bread and fish. The number of the men who had eaten was five thousand.
> Immediately Jesus made his disciples get into the boat and go on ahead of him to Bethsaida, while he dismissed the crowd.


### Thoughts and questions 

Initial intent was that Jesus was getting away with his disciples to have some time of quiet, to take time to simply eat together. 
But the people saw and recognized them, and ran to them -- so desperate was their need to hear from Jesus.  ...  I love how Jesus' is to have compassion on them.  

He taught them, _many things_.  Was he teaching all day?   By evening the disciples, likely hungry themselves, suggested sending everyone back to their homes.  Jesus says _you feed them_.  Was this because he wanted them to actually do it? Or was this to highlight the point that they could not possibly do it?  But with God there is always a way.  Jesus blessed the loaves and fish and fed thousands of people.  

Following dinner, Jesus sent his disciples on, and he spent more time with the people, dismissing them to their homes.  

_Do I:_

-   trust that Jesus can meet my needs? 
-   long to hear Jesus' teaching?  I would do this through reading the scriptures and spending time in prayer.

### Prayer

Change my heart Lord, to yearn for your word.  
Change my heart Jesus, to trust that you will meet all my needs. 
Have compassion on us God.  We are in need. 