---
title: "Jesus recognized"
description: "Really -- he had to have been the talk in all the towns"
author: Colin C.
date: 2023-08-17
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 53 - 56](https://www.bible.com/bible/111/MRK.6.NIV)

> When they had crossed over, they landed at Gennesaret and anchored there. As soon as they got out of the boat, people recognized Jesus. They ran throughout that whole region and carried the sick on mats to wherever they heard he was. And wherever he went—into villages, towns or countryside—they placed the sick in the marketplaces. They begged him to let them touch even the edge of his cloak, and all who touched it were healed.


### Thoughts and questions 

Following the calming of the storm.  They set anchor and start travelling around.  It think it is amazing that he is recognized everywhere.  This is not modern day ... you can't just put his face on the news or YouTube or social media.  People knew about Jesus because the entire countryside must have been talking about him.  The people were excited to see him and their hopes of healing were fulfilled!  The people the nation were excited about Jesus! 

### Prayer

Jesus, I long for days when our nation would be excited for you.  The love and healing that you brought to the people.  Forgive us for any barriers to you that we cause -- we are flawed and we need your wisdom and strength.  We also need you to demonstrate your power in our lives.  I choose you.  Please work in me and through me that people would see and know your love.  



