---
title: "Jesus calms the storm"
description: "Following a huge day of ministry Jesus spends time and prayer and then walks out to his struggling disciples."
author: Colin C.
date: 2023-08-16
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 6: 47 - 51](https://www.bible.com/bible/111/MRK.6.NIV)

> Later that night, the boat was in the middle of the lake, and he was alone on land. He saw the disciples straining at the oars, because the wind was against them. Shortly before dawn he went out to them, walking on the lake. He was about to pass by them, 49but when they saw him walking on the lake, they thought he was a ghost. They cried out, because they all saw him and were terrified.\
> Immediately he spoke to them and said, “Take courage! It is I. Don’t be afraid.” Then he climbed into the boat with them, and the wind died down. They were completely amazed, for they had not understood about the loaves; their hearts were hardened.


### Thoughts and questions 

Jesus is non-stop and unstoppable! 

Let's not forget the previous passages of a huge day travelling to get away from the crowds but then spending the entire day with the people and performing the miracle of feeding them all.  Finally, Jesus gets his opportunity to spend time in prayer ... I think that was his initial goal.  Then he goes to catch up with his disciples who are battle a storm ... men familiar with the sea but struggling.  What does Jesus do? 

He walks out! Walks across the water.  I think I wold be terrified!  But Jesus is reassuring -- _No worries, it just me, what's the big deal?_ Once he reaches them the storm immediately calms down.  

### Prayer

Lord God there are many days that I feel like I am in a storm.  That I am not getting anywhere and that the storm  might take me under.  Thank you that no storm is too big for you.  That you are the one in control.  Please come to me and reassure me.  Take control of my situation.  Be my strength and my peace. 

