---
title: "Graft versus host"
description: "Immune therapy seems to be causing increased GVHD"
author: Colin C.
date: 2024-03-20
categories: [regular, new-sites]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Immune therapy treatment was initiated on Feb 29^th^. It took about
    10 days before symptoms of Graft versus host disease started to
    present themselves. It is our hope that the Graft versus disease
    processes (i.e. destruction of cancer cells) is even stronger.
-   Targeted radiation therapy for the new disease sites, discovered on
    the Feb. 14^th^ PET scan, is ongoing and will be complete by the end
    of this week.
:::

## Recap of the last week

### Cancer war

It has been over a week since I last wrote and we have been continuing
along two lines of attack against the cancer in Sam's body.

Radiation Therapy

:   Each weekday we have made a trip down to the BC Cancer Centre, about
    a 10 minute drive away. Sam is/has undergone targeted radiation for
    the three new disease sites discovered last month. These visits are
    fairly quick with about 15 minutes needed per site and most of that
    time is simply setting up/positioning Sam to target the sites the
    same way each time. Last week treatment of the sites below his knee
    and on his hip were completed -- as these were not near critical
    organs they received higher doses of radiation per treatment.
    Treatment of the disease on Sam's back will be completed at the end
    of this week. Evaluation of how well the treatments worked will not
    be for a minimum of 2-3 weeks.

Immune therapy

:   Last Thursday, Sam was due to have another dose of
    [Nivolumab](http://www.bccancer.bc.ca/drug-database-site/Drug%20Index/Nivolumab_handout.pdf)
    two weeks following his initial dose. However, this second dose was
    delayed as his bloodwork suggested that his liver was inflamed and
    as such it could be dangerous to give another dose. It was a good
    decision! Over this past weekend Sam has much stronger symptoms of
    Graft Versus Host Disease (GVHD) than we have seen the entire time
    since receiving his bone marrow transplant (BMT).

:   As a reminder, the intent of the BMT was to give Sam a new immune
    system that would recognize the cancer and destroy it. The weeks
    following the transplant Sam was on a medication to keep the new
    immune system in-check and reduce symptoms of GVHD. Now that we know
    that there is more cancer, steps are being taken to release the new
    immune system to be more aggressive. Essentially, using different
    drugs, we went from applying the brakes to the immune system to
    adding fuel to it. The goal: activate/jump-start the immune system
    to attack the cancer. Of course doing this has the potential to
    unleash the immune system to also attack Sam's healthy tissues.

:   This past weekend Sam had intense rashes and evidence that the GVHD
    was not only active on the outside of his body but also the inside
    (e.g. loss of taste, increased liver enzymes). The GVHD seemed to
    reach a peak on the weekend. Recent bloodwork seems to align with
    the symptoms we have been observing. If Sam's immune system
    continues to settle back down we will likely continue with this line
    of treatment.

### General living

Sam's life is pretty simple: watching too much YouTube, and when he has
more energy, he reads, plays video games (only rarely able to sit up to
play on his PC), and occasionally reviews some studies. Lately, his
activity has been limited to short walks, mostly around the RMH. He also
enjoys visiting with people, though his capacity can often be low
causing visits to be short (e.g. 30 minutes). Despite the length of this
journey and current challenges Sam still maintains a positive attitude
with statements like: *"I love my life.", "I am so happy"*, *"We have a
great family".*

Our parental pride swelled earlier this week. A boy here at the RMH,
I'll call him B., is about five years old and has looked up to Sam. B.
was having a hard week and mad at the world – Sam decided to brighten
his day. Sam chose a lego set which I purchased when I was out. Sam was
able to give it to him the next day and also spent some time helping him
assemble it. B. was thrilled! So great that Sam took the opportunity to
care for this young man!

We continue to enjoy visits with family. Tina's family members, who live
in the region, try to make a point of being here each week. We look
forward to seeing them on their usual days.

We also love to see friends as they are able to come through. This past
week it was great to see Jess and John with Kate and John (Jr.).

## Victories and concerns

-   Sam's energy and capacity for simple living have swung up and down
    over the last two weeks. Currently, his energy levels are low –
    mostly likely related to the ongoing treatments.

-   This is a long journey and all of our energy levels are tapped
    (physically and emotionally). Part of the challenge is the
    ambiguity. We are now in a third period (we call it "era") of
    treatment (i.e. 1: chemotherapy, 2: BMT, 3:immune-therapy). The
    previous therapies had protocols to follow and expected end dates.
    The current therapy is day-by-day, becoming week-by-week... there is
    no clear timeline ...

-   Thankful that Sam's pain levels have been stable and generally easy
    to manage. The main challenges are related to the GVHD, specifically
    with rashes, which are not painful but are at times very itchy and
    hot.

-   Sam has a cold. It has now been identified as common cold that he
    would have had as a young child. The upside is he has a new immune
    system to battle it. The downside, his new immune system is like
    that of a newborn -- needing to create antibodies for all of the
    diseases that Sam has already seen through life.

-   New battle strategies against the cancer have been developed but
    carry some higher risks.

    -   The new immunotherapy drugs seems to have released Sam's immune
        system to hit harder. Though we look forward to this pushing the
        cancer back, side effects of the new immune system attacking
        healthy tissues are also big concern (i.e. GVHD).\
        \
        Sam has had some adverse effects and we need to allow these to
        resolve before proceeding with new treatments.

    -   Targeted radiation therapy began last week and will complete
        this week. We are thankful this tool can be used to reduce the
        burden of disease on Sam. However, radiation also comes with
        risks.

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation We cannot thank
    you enough.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   The cancer remains and has spread to new areas in Sam's body. The
    sites are a mass in the center of his chest (the original), and
    newer sites in his back (T3 vertebrae), his hip (right ilium), and
    left shin (tibia just below the knee).

-   We long for the day when Sam is clear of this disease.