---
title: "Sam is a Champion"
description: "Sam has endured so much and now will take on possibly his greatest challenge yet."
author: Colin C.
date: 2023-11-06
categories: [regular, BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

![The Chisholm family at the Ronald McDonald House. Fall
2023[^1].](https://samsstory.s3.ca-central-1.amazonaws.com/Chisholm2023-oliveandbeanphoto-9_sml.jpg)

[^1]: Photography facilitated by the Ronald McDonald House taken by
    [Olive and Bean Photography](https://www.oliveandbeanphoto.com)

Sam is a courageous champion! He has now endured and completed two types of 
cancer treatment, and is ready to take-on the upcoming bone marrow
transplant (BMT). Over the past six months Sam's treatments have focused
on attacking the cancer cells within his body. He received six rounds of
chemical chemotherapy between May and Oct. Over the last two weeks,
following the completion of the initial chemotherapy treatment, tactics
were changed to use radiation therapy against the largest detectable
cancerous mass that remains in the center of his chest. The upcoming BMT
will mark a significant change in strategy for removing the cancer.
Instead of attacking the cancer directly the BMT will provide a
long-term indirect assault on the cancer (long-term being life-long).
This process will replace Sam's immune system – removing his current
native immune defenses and replacing them with a donated immune system.
Where Sam's immune system was not effective at detecting and attacking
the cancer it is expected that the new immune system will. This process
is not easy and Sam may face his greatest challenges to date. However, he is
looking forward to completing these next phases.

There are currently 8 days until Sam receives the actual transplant.
However, there are numerous steps/procedures to be completed to prepare
his body for this process. This Wednesday he starts these steps.

## This past week

### Treatment

It is amazing to me how a short medical appointment can dominate an
entire day. Monday through Friday this past week marked Sam's second and
final week of targeted radiation therapy to directly attack the main
mass of cancer in his body. The actual procedure was usually not more
than 15 minutes but it would dominate out entire day. Each day we would
get ready, load up and head down to the BC Cancer clinic, a short drive
away. Tina and Sam would check in while I attempted to find parking --
there were a few days where Sam was done before I was able to park the
van. Following treatment we would return to the RMH. Sam has generally
felt well though with increasing fatigue. His medical team is happy with
his current health: *He is an otherwise healthy young man, but with
cancer.*

We may never know the full impact that the radiation will have on the
cancer. The radiation therapy can take weeks to show measurable impacts
but by that point we will be well into the BMT process. I expect next
scans to evaluate the various treatments and the state of the cancer
will not be feasible until into the new year.

### Visitors

We were able to visit with and be encouraged by some family and friends this past week. Aunt Tricia put
on an amazing meal. Uncle Cal paid a visit. Sam was able to have some
time hanging out with cousin Kaden, while Tina and I visited with Kevin,
Shannon, and Nana.  Yesterday John, Jess, Kate, and John Jr. stopped by for a few hours.  Tina was able to have and afternoon away visiting with her cousins in Abbotsford. 

## Upcoming

This coming week will mark a point-of-no-return as Sam will have intense
treatments to condition his body for the BMT – all the gains that have
been made in returning Sam to feeling healthy will likely be ripped out
from under him. These treatments include:

-   Total body radiation
-   BMT Chemotherapy -- intense chemo-drug therapy
-   Immune suppression drugs
-   The BMT transplant

See the [previous post](/posts/2309/2023-09-19_courage-and-despair.qmd)
or [The Plan](/plan.qmd) for the details.

Following the BMT medical efforts will focus on managing Sam's
day-to-day health and finding the balance of facilitating successful
engraftment while suppressing graft-versus-host-disease impacts. To
complicate matters symptoms of graft-versus-host-disease are easily
confused or even synonymous with the flu, colds, or other infections
which he will also be highly susceptible to – the medical team will have
to be highly vigilant.

## Victories and concerns

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It has been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity.

-   We have completed a major chapter in Sam's treatment. With the
    completion of this last/ sixth round of chemotherapy and targeted radiation. We now pivot to
    the bone marrow transplant -- this next treatment brings hope of
    removal of the disease but also anxiety about both the challenging
    process and the potential for long term side effects.  We hope and pray that this treatment will be effective in beating the cancer for life. 

-   It is flu season and covid is still out there. In
    the weeks ahead, as a family, we will be more cautious to reduce our
    risk of getting ill. If any of us get sick in the weeks ahead it
    will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   We are continually thankful for our medical teams here. They
    continue to provide incredible care. They are always open to
    conversation and answering questions. They have been incredibly
    pro-active and I am glad we are prepared for the next steps.

-   Thankful that the chemotherapy has been effective at initially
    reducing the cancer and keeping the cancer contained (as
    indicated by the PET scan). Thankful that these results allow us to
    move forward.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Due to some timing and logistics we have had to change donors.
        We are thankful for this current donor who will provide a
        peripheral blood sample and is a good match for Sam.
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team has a huge coordination task ahead of them.
        From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.