---
title: "Immune and chemo therapies"
description: "A big IV tower and lots of drugs ..."
author: Colin C.
date: 2023-11-12
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

It is the middle of the night / early morning, Day minus 2 until Sam's
BMT. Sam is finally asleep. I don't think he realized the level of pain
he was in and it has taken about three hours to get a cap on it.
Today will be another big day of immune therapy and chemotherapy drugs.

## Last couple days

Friday last day of radiation (day -4)

:   Sam completed his radiation therapy. This third day was much better
    then the days prior -- no pain or nausea. Sam even had a burst of hyper
    energy in the evening and literally ran around the ward - excited to
    have completed the radiation phase.

:   Nana, Kevin, Shannon, and Kaden were able to come by for a visit.
    Nana is staying with Tina at the RMH for a few days -- great to have
    her support!

Saturday fist day of immune and chemo therapies (day -3)

:   Sam's immune suppression therapy began. It started with bringing in
    the big IV tower -- it currently has 8 IV pumps with room to expand.
    Sam will have to push, pull, and drag this thing around for the next
    month or more. With the IV tower in place the immune therapy began.
    Numerous drugs were administered through the day. Later in the
    evening Sam received his chemotherapy drugs. So what's all this mean
    for Sam?\
    \
    New therapies bring new and weird sensations. All of it causes
    fatigue. The return to chemotherapy is a hard reminder of how these
    drugs make his body ache and pain management becomes more
    challenging. I also recognize that while outside of the hospital we
    had incredible flexibility in pain management. The medical team at
    Canuck Place were able to consult with us at any time and had given
    us a lot of tools to manage pain. Here at the hospital it is more
    difficult as specific orders need to be written and the nurses are
    generally restricted to those orders. ... changing them in the
    middle of the night on a long weekend can be done. It just not very
    easy.


## Upcoming 

A couple of Sam's friends are planning to pay a visit before he goes into
isolation!  It will be so good for Sam to see them.  This whole process 
can be very isolating and it important for him to know that his friends are still there for him.  

This Tuesday Sam should receive the transplant! The weeks following will focus on facilitating engraftment and managing his day to day health.  None of this will be very easy especially given that he will have no immune defenses for a number of weeks. 



## Victories and concerns

-   Thankful that Sam's radiation sickness was brought under control. By
    the last day Sam was actually feeling great!

-   It has been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We have completed a major chapter in Sam's treatment. With the
    completion of this last/ sixth round of chemotherapy and targeted
    radiation. We now pivot to the bone marrow transplant -- this
    current and upcoming treatments brings hope of removal of the
    disease but also anxiety about both the challenging process and the
    potential for long term side effects. We hope and pray that this
    treatment will be effective in beating the cancer for life.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   We are continually thankful for our medical teams here. They
    continue to provide incredible care. They are always open to
    conversation and answering questions. They have been incredibly
    pro-active and I am glad we are prepared for the next steps.

-   Thankful that the chemotherapy has been effective at initially
    reducing the cancer and keeping the cancer contained (as indicated
    by the PET scan). Thankful that these results allow us to move
    forward.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Due to some timing and logistics we have had to change donors.
        We are thankful for this current donor who will provide a
        peripheral blood sample and is a good match for Sam.
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team has a huge coordination task ahead of them.
        From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.
    4.  These last days leading up to the BMT are very busy with lots of
        drugs running all day. Concerns during this time are that
        everything is able to be delivered as planned and that Sam does
        not have any overly negative reactions to any of this.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.