---
title: "First Indicators of a New Immune System?"
description: "Sam spiked a fever -- potential first indicators of the engraftment process? Or just an infection?"
author: Colin C.
date: 2023-11-22
categories: [regular, BMT, hospital]
draft: true
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

First indicators of a new immune system? Sam spiked a fever -- potential
first indicator of the engraftment process? Or just an infection?

Yesterday was a good day for Sam. He had focus and energy to sit up in
bed. We enjoyed watching him play a Spiderman video game. in the
mid-afternoon he wanted me to take his temperature and noted that a red
area on his face felt hot. About five minutes later we called nurse Pam
following a quick inspection of our boy she hit the virtual alarm and
the team jumped into action. Sam had spiked a fever and had mild rashes
move around his body. There is a good chance that this could be the
first signs of engraftment. For the first hour Tina, Sam and I were
actually excited and what this could mean -- the body starting to adjust
to engraft the new immune system. The hours following... were busy.
Given that the symptoms of engraftment and infection are basically
identical the team jumped into action collecting blood to be cultured in
the lab, and antibiotics were started to prevent the spread of infection
if that was what was going on.

We are hopeful yesterday's fever is a first positive sign that the BMT
process is working. This last week, Sam has not felt great, low energy,
periods of nausea, episodes where his pain medications just did not keep
up with the amount of pain that he had. BMTs are not easy. Yet, despite
the challenges, everything that he has experienced has been in the
normal range of expectations for a BMT. Dr. Jacob, Sam's BMT doctor, was
by earlier in the day and conveyed that things were going well.

So was this the first indicators of the BMT working? We don't know yet.
As bloodwoork continues to come in over the next few days we may be able
to say 'yes'.

## Victories and concerns

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   Thankful that what Sam has experienced so far is within the normal
    for a BMT and that he has not had any complications. Although it is
    all in the 'normal', it is not all easy:

    -   Impacts from the pre-treatment, chemotherapy and radiation,
        remain strong. These cause deep bone and muscle pain, along with
        nausea.
    -   Pain management is constantly under revision.
    -   Nutrition is received by TPN (IV), NG tube, and minorly by
        mouth.
    -   Energy levels are low -- it is great to see Sam have energy to
        sit up and play when he can.

-   There will be ongoing concern as many known and unknown pitfalls
    that may present themselves during the BMT process. Potential
    illness, establishment/engraftment of the donated bone-marrow/ stem
    cells. Numerous other potential complications.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   We are thankful that it seems Sam's pain management is now mostly
    under control, including options to address any spikes in pain.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he is in a
    phase where he has no immune system for the next few weeks.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Done! Thank you! ~~Due to some timing and logistics we have had
        to change donors. We are thankful for this current donor who
        will provide a peripheral blood sample and is a good match for
        Sam.~~
    2.  Continuing: We are desiring that side effects both immediate and
        long-term would be limited. *Ideally, that there would be no
        measurable side effects long term*.
    3.  Done! ~~The medical team has a huge coordination task ahead of
        them. From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.~~
    4.  Done! Although it was rough at points the BMT conditioning was
        successful! ~~These last days leading up to the BMT are very
        busy with lots of drugs running all day. Concerns during this
        time are that everything is able to be delivered as planned and
        that Sam does not have any overly negative reactions to any of
        this.~~

-   We are thankful for the support of family and friends.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.