---
title: "Last chemo"
description: "Glad to see the end of chemotherapy and looking forward to a time when the memories of it fade."
author: Colin C.
date: 2023-11-13
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

Monday morning, Sam is in a deep and restful sleep. Today is his last
day before the BMT, and yesterday was his last dose of chemotherapy. It
all goes as planned this will have been his last dose ever, and I look
forward to a time when the memories of chemotherapy fade. Chemo sucks.

Yesterday was going really well for Sam. He woke up with a bright
attitude and energy to take on the day. He really enjoyed his visit with
his friends Chase and Caleb C. Ahh so good to see friends -- what a
bright highlight to our day! Following this visit Sam had a big nap.

Unfortunately, Sam woke up shortly after shift change in piecing pain --
the side effects of chemo had set in while he had slept. When he woke
mucositis had had left his mouth as an open wound, raw and full of
sores. I am sure as many of you know from your own experiences it is
hard to watch your child in pain. It took some time to get new orders
but solutions were found. We had to wait an abnormal amount of time for
the pain specialist team... we had to wait because they were helping
some other poor child with their pain.

Between 10pm and 1am we had some needed victories:

1.  Sam, knowing that the mucositis will only get worse in the days
    ahead, requested a NG\^Nasogastric tube to facilitate pumping feed
    into Sam's stomach\^ feeding tube. We all knew this would be needed
    and this was likely last best chance to install it without much
    difficulty. Our nursing team was successful at doing this.

2.  The oncologist on-call was able to find a temporary pain solution.

3.  The pain specialist team changed his main pain relieve medication
    and placed it on a constant infusion. Sam will also have a limited
    amount of addition pain relief available at the push of a button.

A special thanks to our nursing team who advocated for Sam and took on
all of the additional task needed to get Sam comfortable. Thank you
especially to Ana and Molly.

## Upcoming today

This morning we will prepare all of our stuff for the transition into
the BMT isolation room. It all needs to be cleaned and stored following
special protocols. The medical and cleaning teams here at the hospital
will ensure that Sam's room is spotless. We will need to make sure that
anything we bring in does not contaminate it.

Sam should also be able to have one last outside visitor before the move
into isolation.

We expect the actual move into isolation will be sometime in the
mid-afternoon.

## Victories and concerns

-   There are many known and unknown concerns that will present
    themselves during the BMT process. Potential illness,
    establishment/engraftment of the donated bone-marrow/ stem cells.
    Numerous potential complications. We are thankful for a medical team
    that has a plan for all of it.

-   We are thankful that it seems Sam's pain management is now under
    control, including options to address any spikes in pain.

-   We are thankful for friends that are able to visit.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We have completed a major chapter in Sam's treatment. With the
    completion of this last/ sixth round of chemotherapy and targeted
    radiation. We now pivot to the bone marrow transplant -- this
    current and upcoming treatments brings hope of removal of the
    disease but also anxiety about both the challenging process and the
    potential for long term side effects. We hope and pray that this
    treatment will be effective in beating the cancer for life.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   We are continually thankful for our medical teams here. They
    continue to provide incredible care. They are always open to
    conversation and answering questions. They have been incredibly
    pro-active and I am glad we are prepared for the next steps.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Due to some timing and logistics we have had to change donors.
        We are thankful for this current donor who will provide a
        peripheral blood sample and is a good match for Sam.
    2.  We are desiring that side effects both immediate and long-term
        would be limited. *Ideally, that there would be no measurable
        side effects long term*.
    3.  The medical team has a huge coordination task ahead of them.
        From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.
    4.  These last days leading up to the BMT are very busy with lots of
        drugs running all day. Concerns during this time are that
        everything is able to be delivered as planned and that Sam does
        not have any overly negative reactions to any of this.

-   We are thankful for the support of family and friends. Thank you for
    your notes of encouragement.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.