---
title: "The Wait Continues"
description: "Waiting can also be busy"
author: Colin C.
date: 2023-11-19
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

I am writing from Sam's room as my family sleeps. It was a good night
last night as all of us slept the majority of it away.

We are now in the waiting period. Waiting for indications that the BMT
is establishing in Sam's body. In our instant world this is a long wait
– 2-3 weeks of anticipation. This morning, knowing that many of you are
wondering how we are doing -- waiting in solidarity with us, I thought I
would pass on a snapshot of what this waiting looks like.

Although in the big picture of Sam's treatment we are waiting. In the
day-to-day or hour-by-hour there can be a lot going on.

## Regular check-ins

-   BMT and Oncology Doctors come and check on Sam daily and often twice
    daily and adjust orders as needed. They are satisfied with how Sam
    is doing as everything seems to be progressing normally. Medical
    orders from this team tend to address issues with:

    -   blood -- as blood counts will continually drop until the graft
        takes. Sam has received and will receive numerous transfusions
        in the weeks ahead.
    -   bowels -- mucositis has once again and as expected impacted
        Sam's entire digestive track. However, where things were
        previously too slow now they are too fast.
    -   They also keep a watchful eye with daily physical exams.

-   The Acute Pain Services (APS) doctors visits 1-2 times per day. By
    the end of the previous six rounds of chemotherapy the suite of
    drugs was causing a lot of pain deep in Sam's bones and muscles. In
    preparation, for the BMT Sam received higher doses of chemotherapy
    than he ever had previously. The APS ensures Sam is as comfortable
    as possible. Often his base pain management drugs are increased to
    match increasing pain levels.

-   A Nutritionist is here usually daily on weekdays. Sam receives his
    nutrition in a variety of ways. Eating is limited due to side
    effects of all the treatments but he still gets a little down. NG
    food delivery took a little while to get going but is going well
    now. Sam also receives TPN which is nutrition in a bag pumped
    directly into his bloodstream.

-   Physiotherapy regularly visits through the week. Providing exercises
    that are suited to how well Sam is feeling. Exercises range from
    squats and stretches outside the bed to simple muscle activations
    when he is too tired to leave the bed.

## Incredible Nurses

It is the nurses that carry the weight of hour-by-hour activity. They
ensure all of the orders from the various specialists are implemented.
Sam now has over a dozen different pumps available to push drugs and
nutrition into his body, and sometimes they are all running at the same
time. On a regular basis alarms are going off (e.g. completion of a drug
delivery, air-in-line). In addition, to ensuring everything is
technically working, and that all the medical orders are being
delivered, the nursing team is constantly available to trouble shoot
with us and when needed advocate for changes to medical orders.

## Mom, Dad, and Sam

What are we doing during all of these different activities? Given that
Sam is living this experience and Tina and I are the ones constantly
observing, the three of us are very much a part of each visit and
conversation with the specialists. Tina and I are also Sam's first line
of assistance -- calling nurses when alarms sound, and assisting Sam in
an out of bed. Sam's big task for each day is to have complete his
shower. This is a chore and he needs to bring his IV system with him and
it can burn the majority of his available energy.

When there are no task to do and when Sam is awake we are simply there
to be with him: sit beside him, watch a show together, talk, and Sam
often asks for prayer. Yesterday, Sam was able to enjoy watching the
Vancouver vs. Seattle hockey game.

How are we doing?  I think... tired but hopeful.  This journey is exhausting 
at many levels and for Sam most of all.  But we are also encouraged with how 
everything is progressing.  It is like when you are on a long journey
and the last hours of that journey seem to always take the longest.  Or 
if you are hiking through the mountains, when you cross the final ridge and you can see home
but is is still a long way to get there.  The big tasks have now been done. 
We look forward, knowing that we will get back, but there are many miles 
still ahead. 


## Victories and concerns

-   Thankful that what Sam has experienced so far is within the normal
    for a BMT and that he has not had any complications.

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   We are thankful that it seems Sam's pain management is now mostly
    under control, including options to address any spikes in pain.

-   There will be ongoing concern are many known and unknown pitfalls
    that may present themselves during the BMT process. Potential
    illness, establishment/engraftment of the donated bone-marrow/ stem
    cells. Numerous potential complications.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Done! Thank you! ~~Due to some timing and logistics we have had
        to change donors. We are thankful for this current donor who
        will provide a peripheral blood sample and is a good match for
        Sam.~~
    2.  Continuing: We are desiring that side effects both immediate and
        long-term would be limited. *Ideally, that there would be no
        measurable side effects long term*.
    3.  Done! ~~The medical team has a huge coordination task ahead of
        them. From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.~~
    4.  Done! Although it was rough at points the BMT conditioning was
        successful! ~~These last days leading up to the BMT are very
        busy with lots of drugs running all day. Concerns during this
        time are that everything is able to be delivered as planned and
        that Sam does not have any overly negative reactions to any of
        this.~~

-   We are thankful for the support of family and friends.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.