---
title: "The Wait Begins"
description: "Sam received his BMT yesterday.  Now we wait for it to take hold."
author: Colin C.
date: 2023-11-15
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

As I begin writing it is 6:30am, Day +1 of Sam's BMT. This morning I am sitting
beside Sam's bed, to protect him I am all gowned up and masked. Tina and
I spent the night in the room and all things considered he is doing
well.

At 5:06pm Nov. 14, 2023 Sam started to received his new bone-marrow stem
cells. Two hours later the IV drip was complete and the donated cells
had been received. As hoped receiving the donor cells was very
uneventful. Sam had been pre-medicated with numerous drugs to facilitate
receiving these foreign cells. A good number of those drugs also cause
drowsiness -- so Sam slept through most of the procedure. Although there
were many hands ready to jump into action should something go wrong,
nothing did! Sam's vitals were and continue to remain within stable
limits. Now we wait.

So far things have gone as well as we could hope but it is still not
easy on Sam. His body aches. He often has nausea. Although he is hungry
very little appetites him. The pain and anti-nausea meds help but not
entirely. Sam has gone through a lot and the most recent steps have
literally taken a lot out of him. With organ-transplants surgeons cut
out the existing organ and incredibly put in the donated one. With a
BMT, it is a mind-trip, but we had to kill a part of Sam to make way for
the transplant material. With the way made and the new cells received,
we now wait.

In this period of waiting a silent battle wages inside Sam's body.
Vitals (e.g. blood pressure, heart and respiratory rates) are monitored.
Chemical metrics are monitored through regular bodily fluids (blood and
urine). Over the next weeks the transplant material should establish.
The team here has been excellent at passing on information as it come in
so we will learn more as we go. Metrics indicating the successful
engraftment/establishment of the stem cells are not expected for 2-3
weeks.

## Victories and concerns

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   We are thankful that it seems Sam's pain management is now mostly
    under control, including options to address any spikes in pain.

-   There will be ongoing concern are many known and unknown pitfalls
    that may present themselves during the BMT process. Potential
    illness, establishment/engraftment of the donated bone-marrow/ stem
    cells. Numerous potential complications.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he will be
    entering a phase where he has no immune system for weeks.

-   In preparation for the BMT there are numerous items that need to
    come together:

    1.  Done! Thank you! ~~Due to some timing and logistics we have had
        to change donors. We are thankful for this current donor who
        will provide a peripheral blood sample and is a good match for
        Sam.~~
    2.  Continuing: We are desiring that side effects both immediate and
        long-term would be limited. *Ideally, that there would be no
        measurable side effects long term*.
    3.  Done! ~~The medical team has a huge coordination task ahead of
        them. From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.~~
    4.  Done! Although it was rough at points the BMT conditioning was
        successful! ~~These last days leading up to the BMT are very
        busy with lots of drugs running all day. Concerns during this
        time are that everything is able to be delivered as planned and
        that Sam does not have any overly negative reactions to any of
        this.~~

-   We are thankful for the support of family and friends.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.