---
title: "Best Birthday Present!"
description: "Sam celebrates 15 years! And we celebrate that indicators are that the BMT is taking hold"
author: Colin C.
date: 2023-11-26
categories: [regular, BMT, hospital]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

## Yesterday, Sam's birthday

### By the numbers

While attempting to secretly decorate Sam's room in the early morning
hours Sam's nurse provided me with the results of that night's bloodwork
-- the numbers were exciting. Sam was hoping that on his birthday there
would be some indication that the BMT was taking hold. Two days ago the
bloodwork hinted that something was happening. For Sam's birthday the
bloodwork numbers were more than we hoped. Our hope was that his ANC, a
metric of immune system strength, would hit 0.1. All week it had been \<
0.1 (essentially non-detectable) and for Sam's birthday it jumped to
0.3!

This is exciting news! The numbers indicate that engraftment is
happening, that the BMT is taking hold, though it will not be considered
definitive until the ANC exceeds 0.5 for a three consecutive days and
some additional tests are run.

### A great birthday

Sam had a great day. The ANC of 0.3 had everyone excited, the three of
us, the nurses, and the doctors, and this set a great tone for the day.
Sam's body is working overtime generating new blood so he rested a lot,
pain and nausea have been under control for the last 48 hours.

Sam was able to have video-calls with his grandparents. Thoughout the
afternoon, as a family, we loved reviewing messages, and video messages
with birthday greetings. The nurses on shift all piled into the anteroom
to sing Sam happy birthday and deliver a cake -- he was even able to eat
some of it! Of course there were presents which Sam took his time
opening, reading the cards and enjoying every word written and gift
sent. Thank you!

## Next steps

We will get more clarity on the next steps in the days ahead. Here is
what I currently understand:

-   We will be watching for the day the BMT is officially considered
    engrafted (3 consecutive days of ANC $\geq 0.5$).

-   Sam will begin a step-down process as his body heals from the
    intense chemotherapy and radiation therapy that was used to
    condition his body to receive the transplant. Currently, he
    receiving significant external supports: nutrition is being
    delivered via NG tube and TPN (IV delivery), and he is on a
    continuous schedule of numerous drugs. In the step down process
    these supports will slowly be removed, and drugs will be converted
    to oral delivery.

-   Over the next couple months Sam will be watched closely for signs of
    Graft versus Host Disease (GVHD)-- essentially that the new immune
    system does not harm Sam.

-   We should be out of hospital and back the Ronald McDonald House
    before Christmas.

## Victories and concerns

-   What an incredible birthday present. Sam's ANC blood metric went
    from non-detectable to 0.3. A strong indicator that the transplant
    is taking hold!

-   We are thankful that Sam has felt the love of his community around
    him – especially on his birthday.

-   We very thankful for the successful delivery of the donated stems
    cells! To whoever made this donation *I cannot thank you enough*.

-   Thankful that what Sam has experienced so far is within the normal
    for a BMT and that he has not had any complications. Although it is
    all in the 'normal', it is not all easy:

    -   Impacts from the pre-treatment, chemotherapy and radiation,
        remain strong. These cause deep bone and muscle pain, along with
        nausea.
    -   Pain management is constantly under revision. *Update: We seem
        to have the right mix. Pain and nausea are currently under
        control*
    -   Nutrition is received by TPN (IV), NG tube, and minority by
        mouth.
    -   Energy levels are low -- it is great to see Sam have energy to
        sit up and play when he can.

-   There will be ongoing concern as many known and unknown pitfalls
    that may present themselves during the BMT process. Potential
    illness, establishment/engraftment of the donated bone-marrow/ stem
    cells. Numerous other potential complications.

    -   *Update: Sam did have an infection earlier this week. Within
        about 45 minutes of detection he was on antibiotics and was
        cleared out quickly. The team here says that this happens to
        everyone going through a BMT.*

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   We are thankful for all of the messages of encouragement and
    solidarity that we have received from all of you.

-   We are thankful that it seems Sam's pain management is now mostly
    under control, including options to address any spikes in pain.

-   It had been amazing to see Sam out from under the influence of
    chemotherapy. To see him return to strength of mind and to have
    capacity for more activity. It is hard to see him have this strength
    pulled away from him.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   It is flu season and covid is still out there. If any of us get sick
    it will add challenges to Sam and the BMT process as he is in a
    phase where he has no immune system for the next few weeks.

-   In preparation for the BMT there are numerous items that had to come
    together:

    1.  Done! Thank you! ~~Due to some timing and logistics we have had
        to change donors. We are thankful for this current donor who
        will provide a peripheral blood sample and is a good match for
        Sam.~~
    2.  Continuing: We are desiring that side effects both immediate and
        long-term would be limited. *Ideally, that there would be no
        measurable side effects long term*.
    3.  Done! ~~The medical team has a huge coordination task ahead of
        them. From our meetings with them it seems all of the pieces are
        coming together, but with so many moving parts it is easy for
        things go wrong.~~
    4.  Done! Although it was rough at points the BMT conditioning was
        successful! ~~These last days leading up to the BMT are very
        busy with lots of drugs running all day. Concerns during this
        time are that everything is able to be delivered as planned and
        that Sam does not have any overly negative reactions to any of
        this.~~

-   We are thankful for the support of family and friends.

-   There is always concern as the cancer remains. We long for the day
    when Sam is clear of this disease.