---
title: "We have had a real break"
description: "We have had a real break, making it home for a week!"
author: Colin C.
date: 2024-06-11
# date-modified: 2024-04-18
categories: [regular, results]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Liver numbers were good, giving us a 'green-light' to go home
-   We made it home for ten days
-   Sam lived life to the fullest with the time and energy he had!
-   We are now back in Vancouver for planned scans
-   Next steps all depend on PET scan tomorrow

:::

::: {#photo}
![On May 29^th^ we checked out of the Ronald McDonald House for the
first time since starting this cancer battle! We took a ten day break
home -- it was amazing to be
there!](https://samsstory.s3.ca-central-1.amazonaws.com/2024-05-29_rmh-checkout.jpg)
:::

It has been just over two weeks since my last post and in that time we
have had an amazing break!

## Current medical situation

Two weeks ago Sam's regular blood work confirmed that his liver numbers
were continuing to drop. This allowed us to continue to test if his new
immune system would be effective, on its own, to battle the cancer. Sam
was off all immune system suppressants for just over three weeks (May
15 - June 6). However, bloodwork at the Prince George clinic showed that
liver inflammation was starting again. This past Friday Sam started on a
lower dose of immune suppressant in an attempt to find a balance of
allowing the immune system to do its work while protecting his liver.

Currently, we are near the end of this wait-and-see period with a PET
scan scheduled for tomorrow.

The earlier improved liver enzyme numbers, coupled with the results of
the previous CT scan, also meant that we had what the medical team
considered a safe window of time to return home! On May 29 we checked
out of the Ronald McDonald House and made the drive back to Prince
George! It was an amazing break!

## Living life

I can't express how good it was to get back home -- to be in our own
space, and to connect with some of our Prince George friends and family
(though not near enough time to see everyone). We spent the first couple
of days at my parents home where it was great to see them and for Sam to
be reunited with Buddy. After a couple of days our own home was ready to
return to.

During this break it was most encouraging for me to simply watch our
boy! He loved being home and jumped full into life there:

-   Sam loved connecting with friends.
-   He chose to jump right back into school despite having missed the
    last third of grade 9 and almost all of grade 10. Many thanks to the
    staff and students at [Cedars](https://cedars.bc.ca) who welcomed
    Sam back in and allowed him to engage with his academics.
-   He pushed hard to catch up on a couple topics often spending 2-3
    hours a day on homework. ... Honestly he had seemed to have more
    energy than I did.
-   This last Friday, after writing a three hour math test during the
    day, Sam even attended the school dance. His muscles are still sore
    from having had a great time with friends and dancing the evening
    away!

Tina and I were able to connect with various friends. So good to see you
and we look forward to our next return!

## Upcoming

We are now back at the RMH having finished our latest drive down
yesterday. Tomorrow morning Sam will have a PET Scan at the BC Cancer
clinic. Preliminary results may be available in clinic that afternoon
though the full report may have to wait until Friday. Results of this
scan will dictate next steps. If the results are positive then we can
proceed with our preferred treatment option: to simply keep doing what
we have been doing over the last number of weeks -- let the immune
system do its work and wait-and-see. If results are more challenging we
will discuss options with the team here at BC Children's.

## Victories and concerns

-   Thankful for a great break at home and time to connect with friends
    and family! Thankful that Sam was able to connect with his friends
    and jump back into school work.

-   We celebrate that the cancer has not shown any significant signs of
    growth/progress since Feb. 14^th^. A PET scan tomorrow, June 12,
    will reveal the current state of the cancer. Scan days always carry
    some stress.

-   We celebrate that Sam was able to be off immune suppression for over
    three weeks. Recently, his liver started to become inflamed again.
    He is currently on a lower dose of immune suppression with the hope
    of finding a balance of protecting his liver while allowing the
    immune system to attack the cancer.

-   Thankful that the three new disease centers, treated using targeted
    radiation, have been removed (confirmed by April 5^th^ PET scan).

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We long for the day when Sam is clear of this disease.