---
title: "Safety Delay"
description: "Immunotherapy treatments have been delayed to protect Sam's heart"
author: Colin C.
date: 2024-06-19
# date-modified: 2024-04-18
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Sam's immunotherapy treatment has been delayed. We hope to see this
    treatment start by the end of this week.
-   GVHD effects have continued since Sam received his BMT. One effect
    of GVHD is that fluid has accumulated around his heart making it
    unsafe with other treatments until that is dealt with.
:::

```{=html}
<!-- ::: {#photo}
![On May 29^th^ we checked out of the Ronald McDonald House for the
first time since starting this cancer battle! We took a ten day break
home -- it was amazing to be
there!](https://samsstory.s3.ca-central-1.amazonaws.com/2024-05-29_rmh-checkout.jpg)
::: -->
```
## Medical plans

We had to know if Sam's new immune system from the BMT would be able to
stop the cancer – we now know that it cannot. The results of the
June^12th^ PET scan simply sucked -- the cancer had grown, and likely
spread into two lymph nodes close by.

So we pivot and move onto the next plan which will be a combination of
different immunotherapy drugs. Past research suggest that these drugs
could be effective at 1) interrupting a key metabolic pathway in the
cancer cells, and 2) disable some of the cancer's defenses that allow it
to hide from the immune system.

Last Friday we were hoping to see Sam start on this modified
immunotherapy drug treatment plan, but it was not safe to do so. Since
receiving his BMT[^1] Sam has had some level of GVHD[^2]. One ongoing
effect of GVHD is that fluid has built up around his heart (measured
using an echocardiogram). To date this has not impacted his heart
function. The challenge and safety concern is that the new immunotherapy
treatment will likely intensify GVHD impacts that could put his heart at
risk.

[^1]: bone marrow transplant -- providing his new immune system

[^2]: graft versus host disease

So instead of treating the cancer, last week Sam was started on a
steroid to reduce GVHD effects. Yesterday, a repeat echocardiogram and
blood metrics suggest that this GVHD treatment is working and this
should allow Sam to start on the immunetherapy/cancer-treatment later
this week.

## Life together

We have all had our moments this past week. It has been emotionally
challenging and at times each of us has had to confront our fears. We
have also had beautiful times as we have been able to do that together.

We have received many notes of support and encouragement – thank you!

We have also enjoyed watching the hockey playoffs with family in the
area. Uncle Cal also did his faithful visit after teaching in Richmond.

## Victories and concerns

-   We are concerned as cancer treatments have been delayed. The effects
    of GVHD caused fluid build-up around Sam's heart making it unsafe to
    proceed with immunotherapy.\
    At the same time we are thankful that Sam's medical team continues
    to be diligent and thorough to protect him and to bring him to a
    healthier/safer place before starting this next treatment.

-   Results from the latest PET scan are challenging. The cancer has
    grown. Though we remain thankful that it has not spread to other
    areas of Sam's body.

-   Thankful for a great break at home and time to connect with friends
    and family! Thankful that Sam was able to connect with his friends
    and jump back into school work .

-   Thankful that the three new disease centers, treated using targeted
    radiation, have been removed (confirmed by April 5^th^ PET scan).

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We long for the day when Sam is clear of this disease.