---
title: "Unfavourable Results"
description: "Results of the latest PET scan are challenging."
author: Colin C.
date: 2024-06-14
# date-modified: 2024-04-18
categories: [regular, results]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

```{=html}
<!-- ::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}



::: -->
```
```{=html}
<!-- ::: {#photo}
![On May 29^th^ we checked out of the Ronald McDonald House for the
first time since starting this cancer battle! We took a ten day break
home -- it was amazing to be
there!](https://samsstory.s3.ca-central-1.amazonaws.com/2024-05-29_rmh-checkout.jpg)
::: -->
```

Two days ago, Wednesday June 12, Sam had his latest PET scan. Yesterday
afternoon the three of us met with Sam's doctor to review the results.

The results are unfavourable -- they are not what we want. Sam is still
in the fight and there are still medical options to pursue. So, despite
taking a hit, we hold hope and prepare for the next steps.

## Results

The latest scan showed growth of the central mass in Sam's chest. The
cancer has expanded, it is not by a lot but it is distinct and beyond
any possible measurement errors. In addition, two lymph-nodes in close
proximity to the cancer show increased activity -- we have to assume
that the disease is now there as well.

## Plans

The last few weeks have been a test to determine if Sam's new immune
system could battle the cancer on its own. Unfortunately, this test
failed. During that time Sam has also had some of his best living. We
were able to be home and he was able to enjoy his life, time with
friends, and time learning at school.

Moving forward, Sam's treatment plan will involve the re-introduction of
some immune-therapy drugs. Nivomulab is an check-point-inhibitor will be
given at a lower dose than previous. Other medications will be
introduced in an attempt to reduce the more intense graft-versus-host
impacts that Nivomulab has caused in the past.

Sam will also be closely monitored utilizing an alternating schedule of
contrast-CT and PET scans.

## Victories and concerns

-   Results from the latest PET scan are challenging. The cancer has
    grown. Though we remain thankful that it has not spread to other
    areas of Sam's body.

-   Thankful for a great break at home and time to connect with friends
    and family! Thankful that Sam was able to connect with his friends
    and jump back into school work.

-   Thankful that the three new disease centers, treated using targeted
    radiation, have been removed (confirmed by April 5^th^ PET scan).

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   We long for the day when Sam is clear of this disease.