---
title: "Round 3 hospital time and release"
description: "Sam has completed the chemo-drug delivery phase of this round and is now back at he RMH"
author: Colin C.
date: 2023-07-10
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

We are now all back at the RMH. These last few days Sam was in hospital
to receive the chemical delivery of ths current round of chemotherapy.
All-in-all this round seems to be going well. Sam has such a great
understanding of the process and because of that he asked to get his
drugs pushed a little earlier each day. He had a goal in mind and with
the assistance of the medical team he was able to achieve it. It was a
simple goal -- *Get out on Saturday*. And that is exactly what we did...
it was a little late but it was worth it. We left the hospital a little
before midnight and had a good sleep -- without interruptions.

## The last few days

Tuesday, July 4

:   Clinic day and start of round 3 of chemo.

July 5 - 8

:   Days in hospital for chemo drug delivery. Sam received a variety of
    different drugs. Generally, he had anywhere from two to four lines
    of medication including additional hydration running the whole time
    we were in hospital. The additional hydration was to ensure that his
    body not only received the chemicals but was able to process them
    without damaging his liver or kidneys. The inconvenience of
    hydration is that Sam was up every \~2.5 hours (day and night; I was
    up with him).

:   Nana was here and had great visits. Tina and her mom spent the much
    of their time at the RMH with visits to Sam. On the Friday Cal,
    Tricia, and Jane visited as well. Nana returned home on Saturday.

Sunday, July 9

:   Our first full day out. So far the only side effect that Sam has
    felt is fatigue but even this fatigue is better then his best days
    from a couple months ago. Kevin was able to come by and we hosted
    him with a BBQ here.

## Upcoming

Clinic appointments to monitor Sam's ongoing health and blood levels.
With each treatment his immune system is expected to crash. If the
pattern from the previous rounds hold Sam should have a 3-4 more days of
grace before he is left without immune defenses. He will have around a
week where we will have to be careful and keep him away from any
potential disease.

In a week-and-a-half my parents will be back down and they have arranged
to bring Buddy with them.

## Concerns and victories

-   Thankful that family for such a supportive family.

-   We are thankful for the successful completion of round three's drug
    delivery phase!

-   Thankful that Sam has not had significant side effects from this
    round ... though concern that they may yet arise.

-   We miss home: our friends and family there, our house, the
    neighborhood... \
    I miss my work, my team, the forest, and the work itself.

-   There is always concern that it remains effective to fully remove
    the cancer.