---
title: "Quiet waiting"
description: "Things are quiet as we wait for Sam's blood levels to recover."
author: Colin C.
date: 2023-07-27
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Sam has completed round 3 of his chemotherapy. This marks half way
through the current treatment plan. However, we are delayed in starting
round 4. With each round of chemo Sam's immune system is knocked back
and metrics monitoring this drop to zero. Before he is able to start the
next round his body needs to recover. This time the recovery is slow...
so we wait. With low levels Sam is also low energy and life has been
fairly quiet.

## Highlights from the last few days

-   Last Friday Sam had transfusions that lifted his energy for a couple
    days. We went out to Ft. Langley to visit with my parents and Buddy.

-   A surprise party to celebrated my 50^th^ with family!

-   My parents came to us here at the RMH bringing Buddy with them.

-   Quiet days at the RMH allowing Sam to recover from chemo

## Concerns and victories

-   Today marks 100 days of this marathon.  I am exhausted.  I think we are all exhausted.  Perhaps it is these quieter days that give us enough space to feel and not just do the work of managing it all. 

-   We are thankful for the successful completion of round three.
    Recovery from this round is taking a little longer. Round 4 should
    start next week.

-   We hope that there will not be a need for the contingency plan
    ([bone marrow
    transplant](/posts/2307/2023-07-17_contigency-plan.qmd)), yet we
    need to prepare ourselves for it, and all the additional experiences
    and time that it may bring with it.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.