---
title: "Treatment progress and the start of round 3"
description: "Yesterday we received the results of the PET scan and Sam returned to the hospital to start round three."
author: Colin C.
date: 2023-07-05
categories: [daily, results, treatment]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Sam's clinic appointment went as expected yesterday: bloodwork confirmed that his body was ready to start round 3.  We were also able to discuss results of last week's PET scan and lumbar puncture.  

-   Last Thursday Sam had a lumbar puncture.  A small amount of spinal fluid was removed and an equal amount of chemo-drugs was inserted.  Analysis of the spinal fluid confirmed that there is no cancer in the central nervous system! 

-   PET scan results -- the treatment is working! Sam has two main cancerous masses one in his chest, and a smaller one in his neck.  Results from the PET scan indicate that:
    -   Both masses are smaller then in the previous scan
    -   The activity level of the cancer in the body is reduced
    -   No new locations of cancer have been detected (i.e. it has not moved to other locations in the body)

_Note: Sam is receiving additional monitoring (i.e. more scans) then normal because his case is ... not a normal cancer case.  Since so little is known about this form of cancer additional monitoring is taking place.  I expect this is for two purposes.  First to confirm that the treatment is working. Second, to document that the treatment is working -- adding to the pool of knowledge on cancer._


## Upcoming 

The next number of days will be here at the hospital while Sam receives his treatment.  I will be with him through the nights.  Tina and her mom will join us through the day.  Tina and I may even get away for some additional time together while Nana visits.

This round of chemo includes some nastier drugs, though Sam is in a much stronger place then the last time he experienced them.  Potential side effects are likely to include pain, nausea, GI sores, and further hair loss.  


## Concerns and victories

-   We are thankful for positive results -- that the treatment is working! 

-   There is always concern that it remains effective to fully remove the cancer.

-   Specific more immediate concerns are the side effects from this current round of chemotherapy.