---
title: "Round 3 out-patient life"
description: "A glimpse into life as an out-patient"
author: Colin C.
date: 2023-07-14
categories: [regular]
draft: false
editor: 
  markdown: 
    wrap: 72
---

There have been too many new-normals over the last number of years.  Covid and post-covid transitions being the most obvious in our collective consciousness.  It seems that we are finding another new-normal here as patterns of life are established. At the 3-4 week scale we have the pattern of hospital in-patient period of ~5 days (drug-delivery) followed by out-patient life.  

Out patient life is where life begins to feel most normal, with meals, and activities.  I am still amazed that activities are possible and that we have seen such a good return of Sam's health. This week we had some unexpected encounters that brought some home-normality to life. 

## The last few days

July 10 - 13

:   Tuesday was the first clinic day following this round of chemo's drug delivery.  We also had a chance to review the results of the latest PET scan in more detail with Dr. C.  Great to see the imagery of how the cancer is being reduced, and how Sam's heart and lungs are now clear.  

:   We bumped into a classmate of Sam's on our way out of the hospital.  Tyler was here to have a check-up.  Sam had a great visit him.  Lisa and Tina had a great connection.  

:   Shoshanna is here with her family.  Great to catch up with them and plays some family games. 

:   Ronald McDonald House provided a trip to Science World -- we spent a couple hours there yesterday.

:   Another regular life item:  our van is in the shop ... usual stuff: brakes and fluid leak repairs.  

## Upcoming

Clinic appointments to monitor Sam's ongoing health and blood levels.


## Concerns and victories

-   We are thankful for the successful completion of round three's drug
    delivery phase!  So far the side effects have been minimal with intermittent nausea and general fatigue.

-   Great to have some visits with our Prince George people.

-   We are thankful for BC Children's and the medical team here.  Amazing that Sam is returning to health! 

-   There is always concern that the cancer remains.  We long for the day when Sam is clear of this disease. 