---
title: "PET Scan Results -- Cancer War"
description: "PET scan results are not what we hoped for and a renewed war on the cancer will begin."
author: Colin C.
date: 2024-02-16
categories: [regular, post-BMT, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

![Despite challenging news we had a great family day. Here we are
pictured with the sea otters of the Vancouver aquarium – they are
definitely a
favorite.](https://samsstory.s3.ca-central-1.amazonaws.com/240215_vancouver-aquarium-family.jpg)

The afternoon of the 14^th^ Tina and I met with Sam's doctor to discuss
the results Sam's PET scan – completed earlier in the day. The results
were not what we hoped for – the cancer remains and has spread. Though
we were initially shocked, disappointed, and honestly scared, the three
of us have rallied and are preparing to take on this next fight.

## Feb 15 – recap

Yesterday morning started with a good friend sending us this beautiful
prayer:

> Gracious God, when we cry to you and feel as if you do not hear us,\
> grant us a tangible reminder of your promise to never leave us alone.
>
> When we feel ground to dust, unable to sing your praises or whisper a
> prayer,\
> surround us with others who will sit with us, pray for us, and be the
> hands and feet and face of Christ to us.
>
> When the night has past and we see the coming dawn,\
> help us to bear the light of Christ to those who still sit in deep
> darkness\
>   until we all shout alleluia on Easter morning.
>
> Amen.
>
> *from Jill Duffield's "Lent in Plain Sight: A Devotion through Ten
> Objects"
> ([Amazon](https://www.amazon.ca/gp/product/0664265464/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1))*

The previous night and into that morning I felt it. I felt
*ground-to-dust*. And yet notes of support and care started to roll in.
When you reach out and express your care, your solidarity, and your
prayers, you are the *hands and feet and face of Christ to us*.

Please continue to reach out to us – we need you. Please ask your
children to reach out to Sam so that he knows he is not alone. Let him
know that he is missed and that they are praying/ caring for him despite
the physical distance. Many thanks to those who have reached out already
and especially to Sam's friends for reaching out to him.

The initial feeling of having our world rocked have shifted. As a family
we have spent time encouraging each other and praying together. We have
rallied – we are ready to take on this next cancer battle.

## PET scan results

Although busy with regular clinic check-ins, we have had to bide our
time since Sam received his bone marrow transplant – 93 days ago.
Imaging has had to wait as there was so much going on in Sam's body it
was not possible to get a new image of the state of the cancer. Our
assumptions and our hopes were that the prior treatments would have set
the cancer back and that the new immune system would then attack
anything that remains. However, the PET scan revealed a more complex
picture.

### Original cancerous mass

Imagery of the original mass suggested that the radiation therapy
destroyed much of the cancer and likely that there is an on-going war
between Sam's new immune system and the remaining disease. The imagery
of this site looks like a solar eclipse -- with no activity in the
middle, where the radiation focused, but with high activity/avidity
around the edges.

### New sites

Perhaps more alarming is that cancer is now active in new areas of Sam's
body. There are three new locations, all of which appear to be within
bones (something we have not seen before). Working bottom-up, new sites
of cancer are located in Sam's

-   left shin (tibia) slightly below his knee
-   hip (right ilium)
-   back (T3 vertebrae, between his shoulder blades)

None of these are currently causing any additional impacts (e.g. bones
are still strong, and no nerve impacts). Sam does have some back pain
which is likely related to the spot there. These new sites raise
questions and there will be a flurry of activity as plans of attack are
made.

## Next steps

The first question that is being asked is *what kind of cancer is this?*
It is likely that it is the same cancer in a new location but the teams
needs to know definitively. The next questions to be answered are
related to how to treat the cancer. The medical team is jumping into
high gear to start answering these questions. Next up:

-   *Completed*, Feb 16 morning: CT scan of the T3 vertebrae to assess
    risk and provide imaging that will assist with treatment planning.
-   *Competed*, Feb 16: Discussion with with the Orthopedic surgery team
    to discuss/plan a biopsy of the cancer in Sam's shin (the easiest of
    the new sites to access). This was completed by our medical team and
    it was determined that this biopsy would not be feasible.
-   Feb 22: An alternate option is scheduled to biopsy the new cancer in
    Sam's back.
-   *Completed*, Feb 16: Discussion with Radiation Oncologist to discuss
    new radiation based treatments. Our medical team has been in
    communication with them and the Radiation team is ready when and if
    needed.
-   *Ongoing*: reduce medications that have kept Graft versus Host
    Disease (GVHD) in-check. Increasing GVHD may help in the battle to
    kill the cancer ... though this will need to be monitored closely to
    ensure Sam's good tissues are not damaged.

It has not even been 48 hours since we received the PET scan results and
I hope you can sense that things are moving quickly – action is being
taken.

Although there is a lot going on we were also able to get out and enjoy
life.

## A great day together

Despite these challenging PET scan results yesterday was a great family
day – starting the Family Day holiday weekend off a little early. Yes,
we had a big clinic visit in the morning where many of our questions
were answered. In the afternoon we had a wonderful time at the Vancouver
Aquarium! Watching some very cute creatures and exploring the long
history of life on the planet through the various exhibits. Afterwards,
we shared dinner together in our room (taco night at the RMH) and took
in the Vancouver vs. Detroit hockey game.

## Victories and concerns

-   The cancer remains and has spread to new areas in Sam's body. There
    are many questions that need to be answered and new battle
    strategies that need to be developed. The medical team has shifted
    into high gear once again.

-   We are thankful that we have access to such incredible tools to show
    where the disease is in Sam's body.

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.