---
title: "Happy Valentine's Day -- PET Scan"
description: "This should be Sam's last scan before going home"
author: Colin C.
date: 2024-02-14
categories: [regular, post-BMT]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

*9:30am*

This morning I am writing from the BC Cancer clinic where Sam will have
a PET scan (the previous scan was done prior to the radiation and BMT).
Today’s scan should show the current state of cancer in his body.
Ideally the cancer is gone but I will also take reduced and not anywhere new. I am not
sure how long it would take the new immune system to clean up the last
of the disease … of course we are looking forward to having the results
but there are waves of anxiety/ fear regarding potential alternative
outcomes.

We expect to have initial results back later today when we meet with
Sam’s medical team back at BC Children’s hospital.

Thank you for all of your thoughts, care, and prayers.

## Victories and concerns

-   Sam, having been bed-ridden for much of the year, must rebuild his
    strength and stamina/ energy levels. This is been a slow process and
    it is likely we had not recognized how low down he was.

-   We have a big, and exciting transition, ahead of us: the return to
    home, family, and friends. A return to work and school – though
    these responsibilities will likely need plans and modifications.
    There are many practical steps and details to be sorted out. One
    step at a time!

-   We are no longer having medical discussions about upcoming
    treatments. Discussions are now about weaning medications, removing
    the central line, completing baseline tests for comparison with the
    pre-BMT testing, and preparations to return home!

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease. A PET scan will be done in late
    February to evaluate how the cancer has been impacted by all the
    treatments. The expectation is that any remaining cancer, following
    the chemo and radiation therapies, will be removed by the newly
    transplanted immune system.