---
title: "Cancer war -- new battle strategies"
description: "Biopsy results are back and new battle plans are in place."
author: Colin C.
date: 2024-02-29
categories: [regular, new-sites]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   The cancer remains and has spread to three new areas in Sam's body
    (now four centers of disease)
-   A combination of radiation and drug therapy will be used to combat
    the cancer
-   Today Sam will start a new drug treatment and radiation planning
    will begin tomorrow
:::

## This past week's medical journey

It has been a whirlwind of a week filled with anxious waiting, clinic
visits most days, pain management, prayers, and the love of family.

It was one week ago today that Sam had a biopsy of one of the new
disease sites. That procedure went exactly as planned and the tissue was
sent to the BC Cancer lab for analysis -- though we would not hear about
the results until after the weekend.

Friday we were in clinic for a regular blood levels check and a quick
exam. At the time, I was asked if Sam's symptoms had changed and all I
could say was 'No, he seems to be doing well'. However, that would
change over the following days as new pains mounted. I think of these as
pain-spikes as they would come on quickly and cause changes in his pain
management regime (i.e. drug doses were increased). We are thankful that
we have such access to medical advice -- though Sam and Tina deserve
direct credit for sorting out the latest pain-spike.

### The Finding and The Plan

<!-- Monday Tina and I met with Jacob, Julianna, and Nicole to review the options. -->

During Tuesday's visit Dr. Jacob let us all know about the results of
the biopsy. The new disease sites are the same cancer (primarily
characterized by its `INI1` protein deletion). This information was
critical to know in order to determine what treatments would be
available for Sam. To be honest, the medical toolkit is getting low in
options, but at least we still do have options:

-   Further chemotherapy is *not* an option. This cancer has become
    resistant and that line of therapy would put Sam's new immune system
    at risk.\

-   Radiation can be applied but is not a long term solution. We will
    use it to reduce the burden-of-disease on Sam. In particular it will
    be used on his T3-vertebrae to prevent potential growth at that site
    from impinging on Sam's nerves.

-   A drug therapy for Sam has been approved.
    [Nivolumab](http://www.bccancer.bc.ca/drug-database-site/Drug%20Index/Nivolumab_handout.pdf)
    is used for immunotherapy, though special approval was needed to use
    it on a BMT recipient. In general terms, this drug will
    take-the-brakes off Sam's immune system. Specifically, and as I
    understand it, this drug disables proteins on the cancer cells that
    allow them to remain invisible to the immune system. This is a very
    similar philosophy of treatment as the BMT -- to enable the immune
    system, and in Sam's case to support his new immune system, to
    identify and destroy the cancer.\
    The challenge is, until recently we have done the opposite, keeping
    the immune system brakes on so that the new immune system will not
    harm Sam's healthy tissues. The medical team will be watching him
    closely. The goal: release the immune system to attack while
    watching for signs that the immune system does not harm Sam -- it
    will be a fine balance.

There are risks but we are excited to move forward with this
option/opportunity to destroy this disease. Sam is excited and these
options and expected hospital times, depending on how he tolerates the
treatment, could be less difficult than he had imagined.

Today Sam will start this new immunotherapy treatment. He will be
in-hospital for several days to ensure there are no complications.
Assuming there are none we will be back at the RMH early next week.

Tomorrow Sam will also make a trip to the BC Cancer Clinic at VGH to
have a CT scan which will provide the radiation oncology team the data
that they need to complete the planning of their treatments.

## Faith, Hope and Love

I am so proud of my son. He is a young man full of courage and faith. He
continues to face his own mortality choosing courage over fear. My
favourite quotes come from him on a near daily basis: "I have an amazing
life" or "I am so happy". His challenges are beyond my wildest
nightmares but he remains strong, and full of hope. He is surrounded by
the love of his family. He knows you are out there supporting him and we
regularly share notes of encouragements as a family.

This past week we have received incredible support, following the news
of more cancer when we had thought there would be less. Tina's family
has been close by and have been able to visit. My parents travelled down
and were able to be here, support us, and spend some great time with Sam
over several days.

## Victories and concerns

-   The cancer remains and has spread to new areas in Sam's body.

-   New battle strategies have been developed but carry some higher
    risks. The new immunotherapy drugs will release Sam's immune system
    to hit harder. Though we look forward to this pushing the cancer
    back, side effects of the new immune system attacking healthy
    tissues are also big concern.

-   We are thankful that we have access to such incredible tools to show
    where the disease is in Sam's body.

-   We very thankful for the successful delivery and engraftment of the
    donated stems cells! To whoever made this donation *I cannot thank
    you enough*.

-   We are thankful to the medical team who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and care give us great
    confidence.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   There is always concern that the cancer remains. We long for the day
    when Sam is clear of this disease.