---
title: "Parable of the lamp stand"
description: "How will you respond to the good news."
author: Colin C.
date: 2023-07-07
search: false
categories: [Mark, parable, teachings]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 4: 21 - 25](https://www.bible.com/bible/111/MRK.4.NIV)

> He said to them, “Do you bring in a lamp to put it under a bowl or a bed? Instead, don’t you put it on its stand? For whatever is hidden is meant to be disclosed, and whatever is concealed is meant to be brought out into the open. If anyone has ears to hear, let them hear.”\
> “Consider carefully what you hear,”he continued. “With the measure you use, it will be measured to you — and even more. Whoever has will be given more; whoever does not have, even what they have will be taken from them.


### Thoughts and questions

The lamp stand portion of this parable makes sense to me.  The light is meant to expose what is hidden. I use my flashlight all the time to find things in the dark.  My understanding of these first verses is that Jesus teachings on the kingdom of God are to be preached -- not hidden.  That the truth of the kingdom of God will give light.  When you have light ... obviously you do not have to stumble around in the dark. 

I had a little trouble with the next verses.  What is Jesus saying here?  How does it fit in with the versus around it. Why would those that have more receive more and those that do not have lose more.  

I looked at a bible commentary to see what others thought ([studylight.org](https://www.studylight.org/commentaries/eng/pet/mark-4.html)).  How they interpret this makes good sense to me.  That Jesus is asking people to hear him, to hear the gospel.  As they hear it and receive it more good news will be given to them.  If they reject the good news, as religious leaders did, their minds would darked to the words of Jesus.   



### Prayer

Lord, I want your word in my life.  That I would see clearly, that I would understand more.  That I would act as you would act.  Give me your Holy Spirit to empower me.  May I always be receptive to you.  That I would receive more of you.  Let you life shine in mine. 