---
title: "Jesus calms the storm"
description: "Jesus is sleeping during the storm and simply says a word to calm it."
author: Colin C.
date: 2023-07-12
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 4: 26 - 29](https://www.bible.com/bible/111/MRK.4.NIV)

> That day when evening came, he said to his disciples, “Let us go over to the other side.”36Leaving the crowd behind, they took him along, just as he was, in the boat. There were also other boats with him. A furious squall came up, and the waves broke over the boat, so that it was nearly swamped. Jesus was in the stern, sleeping on a cushion. The disciples woke him and said to him, “Teacher, don’t you care if we drown?”\
> He got up, rebuked the wind and said to the waves, “Quiet! Be still!”Then the wind died down and it was completely calm.
He said to his disciples, “Why are you so afraid? Do you still have no faith?”\
> They were terrified and asked each other, “Who is this? Even the wind and the waves obey him!”

### Thoughts and questions 

One point that is commonly pointed out is that a good number of Jesus' disciples were fishermen.  They knew boating.  They knew what it was to be out on the water and they had probably been caught in storms before.  However, this storm has them scared!  This is a big one.  

Then there is Jesus -- asleep.  I wonder is he sleeping because he knows there is nothing to worry about, or because he is exhausted.  He has been with the people teaching, healing, when tired continuing to show compassion to them.  Did Jesus wake up rebuke the storm and go back to bed? 

Marks gospel continually shows us the power and authority of Christ. 

- Intellectual authority -- teaching and confronting religious leaders to focus on the things God wants. 
- Spiritual authority -- casting out demons.  Bringing spiritual healing 
- Emotional care -- having compassion on the people and the sick
- Authority over the body.  Bringing physical healing 
- Authority over the physical word -- calming the storm.


### Prayer

Lord you have the power to do anything.  Have compassion on us.  Please, show us your power and bring complete healing.  Help us to trust in your ways and purposes in this.  Help us to show love and compassion to one another and the other families in this place. 