---
title: "Parable of the sower"
description: "The word is spread like seed and falls in various locations -- some good and some bad."
author: Colin C.
date: 2023-07-05
search: false
categories: [Mark, parable]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 4: 1 - 20](https://www.bible.com/bible/111/MRK.4.NIV)

> Again Jesus began to teach by the lake. The crowd that gathered around him was so large that he got into a boat and sat in it out on the lake, while all the people were along the shore at the water’s edge. He taught them many things by parables, and in his teaching said: “Listen! A farmer went out to sow his seed. As he was scattering the seed, some fell along the path, and the birds came and ate it up. Some fell on rocky places, where it did not have much soil. It sprang up quickly, because the soil was shallow. But when the sun came up, the plants were scorched, and they withered because they had no root. Other seed fell among thorns, which grew up and choked the plants, so that they did not bear grain. Still other seed fell on good soil. It came up, grew and produced a crop, some multiplying thirty, some sixty, some a hundred times.”\
> Then Jesus said, “Whoever has ears to hear, let them hear.”\
> When he was alone, the Twelve and the others around him asked him about the parables. He told them, “The secret of the kingdom of God has been given to you. But to those on the outside everything is said in parables so that,\
> \
> “ ‘they may be ever seeing but never perceiving,
and ever hearing but never understanding;
otherwise they might turn and be forgiven!’ ”\
> \
> Then Jesus said to them, “Don’t you understand this parable? How then will you understand any parable? The farmer sows the word. Some people are like seed along the path, where the word is sown. As soon as they hear it, Satan comes and takes away the word that was sown in them. Others, like seed sown on rocky places, hear the word and at once receive it with joy. But since they have no root, they last only a short time. When trouble or persecution comes because of the word, they quickly fall away. Still others, like seed sown among thorns, hear the word; but the worries of this life, the deceitfulness of wealth and the desires for other things come in and choke the word, making it unfruitful. Others, like seed sown on good soil, hear the word, accept it, and produce a crop—some thirty, some sixty, some a hundred times what was sown.”


### Thoughts and questions

I think there is something freeing and beautiful about this passage.  I have heard many people speak on this passage and suggest that it is important to keep the weeds out of your life, to make sure that the soil you are in is deep -- that you take care to be nurtured and to help nurture others.  These are good thoughts, but they can be a guilt trip.  This line of thinking can put pressure on -- that somehow it is somehow my responsibility to garden other people's lives. 

I think what is freeing is 

1.  I should be responsible for my own heart.  Is my heart able to receive the word and let it flourish in me. 
2.  Worry and cares, or distractions of this world should be cast off. ... though I admit this is easier said then done.
3.  When spreading the word -- it is not the responsibility of the farmer to ensure every seed is planted in good soil.  It is the farmer's responsibility to spread the seed. 

### Prayer

Jesus, let my heart be receptive to your word, your will in my life.  Help me to forget worry and trouble and to trust in you. 