---
title: "Parable of the lamp stand"
description: "How will you respond to the good news."
author: Colin C.
date: 2023-07-10
search: false
categories: [Mark, parable, teachings]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 4: 26 - 29](https://www.bible.com/bible/111/MRK.4.NIV)

> He also said, “This is what the kingdom of God is like. A man scatters seed on the ground. Night and day, whether he sleeps or gets up, the seed sprouts and grows, though he does not know how. All by itself the soil produces grain—first the stalk, then the head, then the full kernel in the head. As soon as the grain is ripe, he puts the sickle to it, because the harvest has come.
> \
> Again he said, “What shall we say the kingdom of God is like, or what parable shall we use to describe it? It is like a mustard seed, which is the smallest of all seeds on earth. Yet when planted, it grows and becomes the largest of all garden plants, with such big branches that the birds can perch in its shade.”

### Thoughts and questions

The kingdom of God will grow! We may not understand how the Kingdom of God grows -- but it will produce (analogies of grain and mustard plant)!  I have to wonder if Jesus using this story to prepare his disciples, and thereby all of us, for the work ahead -- a few passages ahead he sends out his disciples.  But what is the work that we are called to? Following the analogy 

1. We are responsible for sowing the seed
2. God is responsible for growing the plants
3. We benefit from the growth -- perhaps we have a responsibility for bringing in the harvest.

Practically, what does this look like in our lives?  Definitely, when there is opportunity to share the love of God.  Honestly, I think this requires some prayer and consideration on what God is calling you to.




### Prayer

God, thank-you that you cause people to grow.  Help me to be faithful in sharing your love with others.  But how do you want me to do this.  How are you calling me specifically?  Grow my heart and bear fruit in me so that I may best serve you. 