---
title: Waiting and Welcome Guests
description: We are in a waiting period, and as results from Sam's biopsies trickle in, we have some knowledge of what the disease is not.  Our hearts are peaceful and we have been filled with messages of love and prayer from around the world! 
date: 2023-04-22
author: Colin C.
---

### TLDR

We are in a waiting period, and as results from Sam's biopsies trickle in, we have some knowledge of what the disease is not. Our hearts are peaceful and we have been filled with messages of love and prayer from around the world!

### Reflections on April 21, 2023

How long have we been here? As I write this, it is only the beginning of day four and I am writing about day 3, so much has happened.

Yesterday, was ... a beautiful day. Sam was far more comfortable, being another day away from his biopsy surgery. It was wonderful to watch him sleep and nap on and off through the day. This time of rest also powered him up to visit with family. It was also great to see Tina catch up on some much-needed sleep.

#### Physical Health

Medically, it was generally a quiet day. No new tests, just the routine of checking vitals, checking blood chemistry, and taking medicines (e.g. pain management from the previous surgery). We are in waiting phase. The lab has not finished processing the tissue samples taken April 20th. Despite not knowing much yet the medical team continues to communicate. The best news was that we now know that the disease is: 

- *not* in the central nervous system 
- *not* in his bones.


It might be a quiet weekend as lab results may not come back until mid-next week. So we wait as a family, and the medical team waits with us. One might think this is frustrating, but it is not, rather it is a peaceful and strategic waiting. Once the tests come back the doctors will be very intentional on how to manage Sam's health. So we wait, for the right understanding, and the subsequent right treatment plan.

#### Soul Health


Wow, what a good day! We have heard from so many friends, family, some of whom we have not connected with for years, but this challenging time is pulling our people together. Thank you for reaching out to us, conveying your care, telling us your stories, or simply what is happening in your world. We are supported by your words, your love, and your prayers.

People around the world are praying -- it's awesome. Friends, family, and their friends and families, bible study and prayer groups; from Prince George, across the province, across the continent, and as far away as Zambia!

We have also had some amazing face-to-face visits/care.

-   A friend anticipated our needs and showed up with a bag of groceries and goodies picked especially for Tina and her dietary neerequirements.
-   A providential visit with the Schellenbergs with whom we have shared so much life and adventure. What are the chances that they just happened to be in the area this weekend! For those who don't know them, they live in Saskatchewan.
-   Sam had a great visit with his cousin Chris, Uncle Cal, and Auntie Tricia.

To wrap up this post, please know that we feel cared for in soul and body. Although we do not know what treatment for Sam will look like, we are in a peaceful place. That might change, we may have challenges ahead, but we bolstered by your love, we are carried.

Love to you all!

Colin
