---
title: An Alarming X-ray
date: 2023-04-20
description: The last 48 hours have been a whirlwind, and we are where we need to be. Sam is now at BC Children's hospital 
---


Hi friends,

The last 48 hours have been a whirlwind, and we are where we need to be.

Sam is now at BC Children's hospital, and Tina and I are able to stay in the room with him. Steps are being taken to manage what all indications suggest is lymphoma. Staff here have been amazing in: providing care, communicating what is happening and next steps, and conveying a sense that 'this is serious' mixed with a calming confidence.

The process: Yesterday, tests were run -- the primary one being a CT scan of his chest. Today, Sam will start the day with a surgery to complete a series of biopsies, the primary one being one of his lymph nodes at the base of his neck. By the end of the day, we should have firmer answers as to what exactly is happening and a treatment plan.

Sam's friends and classmates have been amazing. They have been in direct communication with him via Snapchat and hearing from them has been really encouraging to him, also to Tina and I -- it is amazing to see friends rally behind him.

Thank you for your support and prayers,

Colin and Tina
