---
title: "Pharisees Debate"
description: "Gamaliel convinces the other leaders to leave the apostles alone -- expecting that the apostles will fail."
author: Colin C.
date: 2024-06-20
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 5: 33 - 42](https://www.bible.com/bible/2016/ACT.5.NRSV)

> When they heard this, they were enraged and wanted to kill them. But a Pharisee in the council named Gamaliel, a teacher of the law, respected by all the people, stood up and ordered the men to be put outside for a short time. Then he said to them, “Fellow Israelites, consider carefully what you propose to do to these men. For some time ago Theudas rose up, claiming to be somebody, and a number of men, about four hundred, joined him; but he was killed, and all who followed him were dispersed and disappeared. After him Judas the Galilean rose up at the time of the census and got people to follow him; he also perished, and all who followed him were scattered. So in the present case, I tell you, keep away from these men and let them alone; because if this plan or this undertaking is of human origin, it will fail; but if it is of God, you will not be able to overthrow them—in that case you may even be found fighting against God!”
>
> They were convinced by him, and when they had called in the apostles, they had them flogged. Then they ordered them not to speak in the name of Jesus, and let them go. As they left the council, they rejoiced that they were considered worthy to suffer dishonor for the sake of the name. And every day in the temple and at home they did not cease to teach and proclaim Jesus as the Messiah.

<!-- ## Terms and Notes -->

## Thoughts and questions

I love the logic of Gamaliel's argument. It also seemed to make good sense at the time to the other temple leaders.  I wonder if they continued to think the same way as the apostles continued to teach and more and more people kept following Jesus.  In the passages ahead we will see that this waiting for the church to fail would not last.  

## Prayer

Lord God, I pray that I would never stand in the way of your will.

By your grace, may my life speak of you!\
Let me live as you taught us.\

Let your will be done.
