---
title: "Peter preaches to the common people (I)"
description: "Peter preaches _you killed the Author of life..._"
author: Colin C.
date: 2024-03-26
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 3: 11 - 16](https://www.bible.com/bible/2016/ACT.3.NRSV)

> While he clung to Peter and John, all the people ran together to them in the portico called Solomon's Portico, utterly astonished. When Peter saw it, he addressed the people, “You Israelites, why do you wonder at this, or why do you stare at us, as though by our own power or piety we had made him walk? The God of Abraham, the God of Isaac, and the God of Jacob, the God of our ancestors has glorified his servant Jesus, whom you handed over and rejected in the presence of Pilate, though he had decided to release him. But you rejected the Holy and Righteous One and asked to have a murderer given to you, and you killed the Author of life, whom God raised from the dead. To this we are witnesses. And by faith in his name, his name itself has made this man strong, whom you see and know; and the faith that is through Jesus has given him this perfect health in the presence of all of you.


<!-- ## Terms and Notes -->


## Thoughts and questions

Peter preaches to the common people -- those that recognize or at least are trying to understand the miracle that has just happened.  Peter and John are apostles -- those that bare witness.  This is a great example of how they did it.  Explaining to the people who Jesus is, how as a people/nation they have responsibility/guilt for killing, and the fact that Jesus has been glorified by God.  Peter highlights that it was though Jesus that the lame man was healed. That there is power in Jesus name. The lame man, really not knowing much simply accepted the gift offered to him (simple faith).  The author highlights that it was this man's faith in Jesus' name and through Jesus himself that he was healed.  

One phrase really strikes me in this passage: _... you killed the Author of life..._  

This statement seems to have layers of meaning. What is meant by this phrase and in the context?  One could say that Jesus being God is the author of all life -- that he created life itself (true).  In addition, being the author of life, highlights that having been crucified he did not remain dead but was resurrected -- life stronger than death (true).    

Although I believe the previous statements about Jesus, I am not convinced that this fits the context here nor was the full intent of the author.  The word translated _Author_ here could also have been interpreted as _founder_ or _pioneer_.  I think Peter is highlighting that Jesus is the founder/pioneer of a new way of living. This perspective fits really well with Jesus preaching about God's kingdom come.  It also demands more of a personal response from us.  

Jesus as creator and as resurrected are facts about him -- our response could/should be praise or could be limited to _that's interesting_.  However, Jesus as author/pioneer of a new way of living means that we, as his followers, should live the way that he taught.  Our response needs to be to change the way we live -- to live what he taught, to follow Jesus into his new way of living. 



## Prayer

_Jesus,\
Name above all names\
Blessed Redeemer\
Glorious Lord^[from the [Hymn](https://digitalsongsandhymns.com/songs/8651)]_

I praise you that you are the Author of life\
I praise you, as God, creator\
I praise you, that through you, \
&nbsp; death has been defeated.  

Show me Lord how to live\
&nbsp; according to your ways,\
&nbsp; that my life would demonstrate your love to this world. 

May I have a simple faith\
To respond to you\
To trust that your name will have power in my life.