---
title: "Paul on the Run"
description: "Saul the persecuter becomes persecuted "
author: Colin C.
date: 2024-09-07
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 9:23 - 31](https://www.bible.com/bible/2016/ACT.9.NRSV)

> After some time had passed, the Jews plotted to kill him, but their plot became known to Saul. They were watching the gates day and night so that they might kill him; but his disciples took him by night and let him down through an opening in the wall, lowering him in a basket.
>
> When he had come to Jerusalem, he attempted to join the disciples; and they were all afraid of him, for they did not believe that he was a disciple. But Barnabas took him, brought him to the apostles, and described for them how on the road he had seen the Lord, who had spoken to him, and how in Damascus he had spoken boldly in the name of Jesus. So he went in and out among them in Jerusalem, speaking boldly in the name of the Lord. He spoke and argued with the Hellenists; but they were attempting to kill him. When the believers learned of it, they brought him down to Caesarea and sent him off to Tarsus.
Meanwhile the church throughout Judea, Galilee, and Samaria had peace and was built up. Living in the fear of the Lord and in the comfort of the Holy Spirit, it increased in numbers.


<!-- ## Terms and Notes -->


## Thoughts and questions

In the previous passage Saul was preaching and winning arguments explaining that Jesus was the Christ/ Messiah.  It shouldn't be surprising that Saul would now become the persecuted one.  He is forced to flee the city of Damascus under cover-of-darkness.  It makes be think of a group of men using a pulley to lower Paul down the side of the city wall. 

Where does Saul go? To Jerusalem, the centre of it all!  If I was in the place of the apostles I would also have a hard time believing that Saul was trustworthy. However, Barnabas is a friend, he is mentioned briefly back in chapter four where he is known to encourage the apostles.  

Again, Saul gets himself into trouble. This time his arguments with the [Hellenists](https://www.oxfordreference.com/display/10.1093/oi/authority.20110803095929406#:~:text=A%20group%20of%20Jews%20who,spoke%20Greek%20rather%20than%20Aramaic.), Jewish people who spoke greek, lead once again to death threats and once again Saul was on-the-run.  

Despite death threats and persecution the church in the surrounding regions continued to grow. Here it does strike me as an odd usage of words: _Meanwhile the church throughout Judea, Galilee, and Samaria had peace and was built up_.  They had peace? Really? How did they have peace when it seemed there was so much persecution? Your thoughts? 
   


## Prayer

God I praise you that you have built your church\
\ \ that you encouraged your people. 

Grant us wisdom today. To speak boldly of Jesus\
\ \ and the kingdom of God.\

Grant us peace! \
Life can be hard\
Help me to start with You each day\
Be my rock, my strength,\
\ \ my peace.




<!-- Grant me the grace to accept it.  -->