---
title: "Peter preaches to the leaders"
description: "The leaders make weak efforts to understand and then reject Peter's witness."
author: Colin C.
date: 2024-04-15
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 4: 5 - 22](https://www.bible.com/bible/2016/ACT.4.NRSV)

> The next day their rulers, elders, and scribes assembled in
> Jerusalem, with Annas the high priest, Caiaphas, John, and
> Alexander, and all who were of the high-priestly family. When they
> had made the prisoners stand in their midst, they inquired, “By what
> power or by what name did you do this?” Then Peter, filled with the
> Holy Spirit, said to them, “Rulers of the people and elders, if we
> are questioned today because of a good deed done to someone who was
> sick and are asked how this man has been healed, let it be known to
> all of you, and to all the people of Israel, that this man is
> standing before you in good health by the name of Jesus Christ of
> Nazareth, whom you crucified, whom God raised from the dead. This
> Jesus is
>
> *‘the stone that was rejected by you, the builders;* *it has become
> the cornerstone.’*
>
> There is salvation in no one else, for there is no other name under
> heaven given among mortals by which we must be saved.”
>
> Now when they saw the boldness of Peter and John and realized that
> they were uneducated and ordinary men, they were amazed and
> recognized them as companions of Jesus. When they saw the man who
> had been cured standing beside them, they had nothing to say in
> opposition. So they ordered them to leave the council while they
> discussed the matter with one another. They said, “What will we do
> with them? For it is obvious to all who live in Jerusalem that a
> notable sign has been done through them; we cannot deny it. But to
> keep it from spreading further among the people, let us warn them to
> speak no more to anyone in this name.” So they called them and
> ordered them not to speak or teach at all in the name of Jesus.
> But Peter and John answered them, “Whether it is right in God's
> sight to listen to you rather than to God, you must judge; for we
> cannot keep from speaking about what we have seen and heard.”
> After threatening them again, they let them go, finding no way to
> punish them because of the people, for all of them praised God for
> what had happened. For the man on whom this sign of healing had
> been performed was more than forty years old.

## Terms and Notes

Luke the author has Peter quoting Psalm 118:22. Alternately or in
    addition, the author could be referring to their earlier work in
    the Gospel of Luke where it seems Jesus is questioning the
    Pharisees about Psalm 118.

::: {layout-ncol="2"}
::: {#ps118}

[Psalm 118:22](https://www.bible.com/bible/2016/PSA.118.NRSV)

:   > The stone that the builders rejected\
    > has become the chief cornerstone.
:::

::: {#luke20}

[Luke 20:17](https://www.bible.com/bible/2016/LUK.20.NRSV)

:   > But he looked at them and said, “What then does this text mean:
    >
    > 'The stone that the builders rejected \
    > has become the cornerstone’?
:::
:::


### Cornerstone

From the encyclopiedia [Britannica](https://www.britannica.com/technology/cornerstone) 

> Early customs connected with cornerstones were related to study of the stars and their religious significance. Buildings were laid out with astronomical precision in relation to points of the compass, with emphasis on corners. Cornerstones symbolized “seeds” from which buildings would germinate and rise.


## Thoughts and questions

The story continues,  Peter and John had been arrested by the temple officials and have spent the night in jail.  The next day they are brought before the main leadership -- they are not speaking to some lower officials.  From the author's account they are speaking to _the big leaders_.  

There is beautiful irony to how this his whole story pivots on the quote around the cornerstone as in buildings of the day -- everything was done in reference to a cornerstone.  

Here Peter tells the leaders that Jesus is the cornerstone -- the one they rejected.  Once again, following some discussion, the leaders reject Jesus, the cornerstone on which the church would be built.  In rejecting the witness of Peter, all they seem to be able to manage is (my paraphrase): _We are the leaders -- the authority on God for the people.  By the authority of this council you are not permitted to speak about this further._  In rebuttal Peter simple speaks of how he is unable to stay silent.  He knows what he has seen and heard.  He knows that salvation comes from no one but Jesus. 

A further irony is that in the Luke passage Jesus states that: _"Everyone who falls on that stone will be broken to pieces; and it will crush anyone on whom it falls.”_ The scribes and Pharisees understood this as Jesus speaking out against them and from that point on they looked for ways to oppose him (see [Luke 20:18 - 20](https://www.bible.com/bible/2016/LUK.20.NRSV)).  


## Prayer

Thank you Jesus

You are our firm foundation,\
&nbsp; our cornerstone. 

We can stand firm on you.  

We can have confidence in your love,\
&nbsp; In your salvation. 

Rescue us Jesus. \
Save us from our distress.  

Let your will be done. 