---
title: "Peter and John report back to his friends"
description: "Following their release Peter and John tell of their experiences"
author: Colin C.
date: 2024-05-12
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 4: 23 - 31](https://www.bible.com/bible/2016/ACT.4.NRSV)

> After they were released, they went to their friends and reported what the chief priests and the elders had said to them. When they heard it, they raised their voices together to God and said, “Sovereign Lord, who made the heaven and the earth, the sea, and everything in them, it is you who said by the Holy Spirit through our ancestor David, your servant:
>
> ‘Why did the Gentiles rage,\
> and the peoples imagine vain things?\
> The kings of the earth took their stand,\
> and the rulers have gathered together\
> against the Lord and against his Messiah.’
>
> For in this city, in fact, both Herod and Pontius Pilate, with the Gentiles and the peoples of Israel, gathered together against your holy servant Jesus, whom you anointed, to do whatever your hand and your plan had predestined to take place. And now, Lord, look at their threats, and grant to your servants to speak your word with all boldness, while you stretch out your hand to heal, and signs and wonders are performed through the name of your holy servant Jesus.” When they had prayed, the place in which they were gathered together was shaken; and they were all filled with the Holy Spirit and spoke the word of God with boldness.

## Terms and Notes

The author quotes [Psalm 2: 1-2](https://www.bible.com/bible/2016/PSA.2.NRSV)

> Why do the nations conspire,\
> and the peoples plot in vain?\
> The kings of the earth set themselves,\
> and the rulers take counsel together,\
> against the Lord and his anointed, saying,


## Thoughts and questions

Reading this story I am struck with the importance of sharing our experiences with God. Faith experiences and stories encourage others in their faith.  In this passage Peter and John shared their story of being arrested and how God gave them the words to stay.  Their friends responded in praise and prayer.  Their prayer highlights that despite how that authorities, Roman and Jewish, are against them that God is still accomplishing His purposes.  

Their prayer request, despite being told to do otherwise by the authorities, is: _grant to your servants to speak your word with boldness_. 

In this case God answers immediately, granting their request, as they are filled with the Holy Spirit who empowered them to speak boldly. 

These early events must have been so encouraging to the early church -- that God strongly affirmed their actions and answered their prayers.  In contrast, As I read about the prophets in the Old Testament and even some of Paul's letters there are often times when God's people are waiting.  However, it also their stories of waiting that are an encouragement to my faith.  


## Prayer

Lord God, I long for you to move in power.\
For you to shake my world to demonstrate your strength, your love, your healing.

When I am weak bring me encouragement.\
Let me hear of your great power. 

Help me Lord to remember how you are at work in my life.\
May I speak of your great works and may my story encourage others.  

