---
title: "Healing and Life"
description: "God works incredible miracles through Peter"
author: Colin C.
date: 2024-09-09
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 9:32 - 43](https://www.bible.com/bible/2016/ACT.9.NRSV)

> Now as Peter went here and there among all the believers, he came down also to the saints living in Lydda. There he found a man named Aeneas, who had been bedridden for eight years, for he was paralyzed. Peter said to him, “Aeneas, Jesus Christ heals you; get up and make your bed!” And immediately he got up. And all the residents of Lydda and Sharon saw him and turned to the Lord.
>
> Now in Joppa there was a disciple whose name was Tabitha, which in Greek is Dorcas. She was devoted to good works and acts of charity. At that time she became ill and died. When they had washed her, they laid her in a room upstairs. Since Lydda was near Joppa, the disciples, who heard that Peter was there, sent two men to him with the request, “Please come to us without delay.” So Peter got up and went with them; and when he arrived, they took him to the room upstairs. All the widows stood beside him, weeping and showing tunics and other clothing that Dorcas had made while she was with them. Peter put all of them outside, and then he knelt down and prayed. He turned to the body and said, “Tabitha, get up.” Then she opened her eyes, and seeing Peter, she sat up. He gave her his hand and helped her up. Then calling the saints and widows, he showed her to be alive. This became known throughout Joppa, and many believed in the Lord. Meanwhile he stayed in Joppa for some time with a certain Simon, a tanner.

<!-- ## Terms and Notes -->


## Thoughts and questions

For now we leave Paul behind and focus on the ministry of Peter.  

At this point it seems that Peter is _the head_ of the early church.  It seems his stories are often filled with miracles.  It is amazing! Aeneas, in the town of Lydda, is healed from a long term paralysis.  In Joppa,Tabitha, a believer who was active in her community became ill and died, and Peter prays and she is raised to life!  The results of these miracles are life an health for those that receive them.  It is also transformation for communities as they place their faith in Jesus. 

I have to wonder if our world would be different if miracles like this were seen.  To be clear -- these miracles were not kept secret.  Rather Peter actively showed people and whole communities chose to follow Jesus.  

This all seemed so easy.  Yet there were many who were followers of Jesus there.  God chose to work through Peter.  One question I have for God is why does he not work through others like this.  There were lots of other believers there could not one of them have prayed.  This gift to heal or rather to have authority over health and life seems so rare in the church.  
   


## Prayer

God it is amazing that you have worked in the world\
\ \ demonstrating your power\
\ \ granting life and health.  

Yet God we need you today.\
\ \ Please work amongst your people today.\
\ \ Demonstrate your power. 

Lord Jesus 
\ \ Heal us.\
\ \ Free us.

Let us see your might hand.\
Let your will be done.




<!-- Grant me the grace to accept it.  -->