---
title: "Phillip in Samaria"
description: "The Samarians put their faith in Jesus."
author: Colin C.
date: 2024-08-09
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 8:5 - 8:13](https://www.bible.com/bible/2016/ACT.8.NRSV)

> Now those who were scattered went from place to place, proclaiming the word. Philip went down to the city of Samaria and proclaimed the Messiah to them. The crowds with one accord listened eagerly to what was said by Philip, hearing and seeing the signs that he did, for unclean spirits, crying with loud shrieks, came out of many who were possessed; and many others who were paralyzed or lame were cured. So there was great joy in that city.
>
> Now a certain man named Simon had previously practiced magic in the city and amazed the people of Samaria, saying that he was someone great. All of them, from the least to the greatest, listened to him eagerly, saying, “This man is the power of God that is called Great.” And they listened eagerly to him because for a long time he had amazed them with his magic. But when they believed Philip, who was proclaiming the good news about the kingdom of God and the name of Jesus Christ, they were baptized, both men and women. Even Simon himself believed. After being baptized, he stayed constantly with Philip and was amazed when he saw the signs and great miracles that took place.

<!-- ## Terms and Notes -->

## Thoughts and questions

In the previous passage Stephen had been killed.  Starting here the story of Acts changes from Isreal and the Jews to spreading the good news of Jesus to the rest of the known world.  I think what we also see in these stories are major paradigm shifts.  As the people encounter Jesus through Philip, and the powerful signs they placed their faith in Jesus.  

It is hard for me to imagine -- can you do it?  Imagine a city filled with joy as they experience the power of Jesus and see their people freed from spiritual bondage, and paralyzed and lame were healed.  

Even those who seem to have power like Simon the magician chose to follow Jesus! Though Simon will have some issues to work through.  

This passage is also really hard.  Where is the power of God today?  Here we sit surrounded by people that need hope and healing -- a hospital full children needing hope -- needing salvation.  


## Prayer

Jesus I long for your salvation!\
I long for you to make the world right

God please break through into our lives.\
Let your power be known\
Bring healing, bring hope, bring life. 

That we would be able to proclaim of your great love.\
That the people could know the power of your salvation! 

My hope is in you alone.\
Let your will be done.