---
title: "Good News for All (II)"
description: "Peter presents the good news of Jesus -- no rituals needed."
author: Colin C.
date: 2024-09-18
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 10:34 - 48](https://www.bible.com/bible/2016/ACT.10.NRSV)

> Then Peter began to speak to them: “I truly understand that God shows no partiality, but in every nation anyone who fears him and does what is right is acceptable to him. You know the message he sent to the people of Israel, preaching peace by Jesus Christ—he is Lord of all. That message spread throughout Judea, beginning in Galilee after the baptism that John announced: how God anointed Jesus of Nazareth with the Holy Spirit and with power; how he went about doing good and healing all who were oppressed by the devil, for God was with him. We are witnesses to all that he did both in Judea and in Jerusalem. They put him to death by hanging him on a tree; but God raised him on the third day and allowed him to appear, not to all the people but to us who were chosen by God as witnesses, and who ate and drank with him after he rose from the dead. He commanded us to preach to the people and to testify that he is the one ordained by God as judge of the living and the dead. All the prophets testify about him that everyone who believes in him receives forgiveness of sins through his name.”
>
> While Peter was still speaking, the Holy Spirit fell upon all who heard the word. The circumcised believers who had come with Peter were astounded that the gift of the Holy Spirit had been poured out even on the Gentiles, for they heard them speaking in tongues and extolling God. Then Peter said, “Can anyone withhold the water for baptizing these people who have received the Holy Spirit just as we have?” So he ordered them to be baptized in the name of Jesus Christ. Then they invited him to stay for several days.

<!-- ## Terms and Notes -->


## Thoughts and questions

This passage repeats the themes presented in the story of Cornelius ([previous](./acts_10_01.qmd)). That the message of Jesus is not just for the Jews but also for the gentiles as confirmed by the Holy Spirit.  

1.   Clearly the message of Jesus is for all people not just the Jews -- _everyone who believes in him receives forgiveness of sins._ 
2.   Core aspects are Jewish practice are set aside -- it is better to share the gospel than demand religious practice. Key ritual aspects are set aside.  Circumcision, a must in the minds of the Jews was ignored.  I have to wonder if baptism was even starting to become a ritual practice in the early church.  The Holy Spirit came on these people before they were baptized -- again God does not need our practices.  God extends his love to all people freely. 

I have two thoughts/ questions: 

First, What does this passage teach us about Jesus? There is the synopsis of his ministry before heading to the cross -- how God anointed him, how he had authority to heal and free people physically and spiritually.  I am also struck by the statement that he is judge of _living and the dead_.  When I hear judge or judgement my mind switches to fear -- for deep inside I know I deserve judgement.  However, this is Jesus -- healer; God who accepts all people even as he did even in this passage.  It is a beautiful thing that Jesus is judge for who better knows that my sins have been covered.  There is no fear of judgement for my judge has already accepted me.

Second, the call to belief seems to be everywhere in Acts and but for some reason as I write this I am struck with considering _what does it means to believe?_ To believe is to trust; to accept as true [def](https://www.britannica.com/dictionary/believe).  Now if I believe Jesus is who he says he is and that I his teachings are true (which I do) -- in my mind it is not enough to simply state that I believe it.  Rather, I must also try to live the ways that he instructed. My life in Jesus starts with believing he is who he said he was but continues with living as he lived/taught. 

## Prayer

Lord God thank you,\
\ \ that you do not demand ritual.

Lord God thank you that you\
\ \ simply love people!\
\ \ And call people to yourself.

Jesus, thank you,\
\ \ You have rescued me from darkness.\
\ \ You are my redeemer and judge.\

Help me God to enact my belief each day.\
\ \ That my life would reflect your life.\

Help me to love people as you love people.





