---
title: "Good News for All"
description: "Cornelius and Peter meet.  Jewish custom is set aside for the sake of the gospel."
author: Colin C.
date: 2024-09-11
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 10:1 - 34](https://www.bible.com/bible/2016/ACT.10.NRSV)

> In Caesarea there was a man named Cornelius, a centurion of the Italian Cohort, as it was called. He was a devout man who feared God with all his household; he gave alms generously to the people and prayed constantly to God. One afternoon at about three o'clock he had a vision in which he clearly saw an angel of God coming in and saying to him, “Cornelius.” He stared at him in terror and said, “What is it, Lord?” He answered, “Your prayers and your alms have ascended as a memorial before God. 5Now send men to Joppa for a certain Simon who is called Peter; he is lodging with Simon, a tanner, whose house is by the seaside.” When the angel who spoke to him had left, he called two of his slaves and a devout soldier from the ranks of those who served him, and after telling them everything, he sent them to Joppa.
>
> About noon the next day, as they were on their journey and approaching the city, Peter went up on the roof to pray. He became hungry and wanted something to eat; and while it was being prepared, he fell into a trance. He saw the heaven opened and something like a large sheet coming down, being lowered to the ground by its four corners. In it were all kinds of four-footed creatures and reptiles and birds of the air. Then he heard a voice saying, “Get up, Peter; kill and eat.” But Peter said, “By no means, Lord; for I have never eaten anything that is profane or unclean.” The voice said to him again, a second time, “What God has made clean, you must not call profane.” This happened three times, and the thing was suddenly taken up to heaven.
>
> Now while Peter was greatly puzzled about what to make of the vision that he had seen, suddenly the men sent by Cornelius appeared. They were asking for Simon's house and were standing by the gate. They called out to ask whether Simon, who was called Peter, was staying there. While Peter was still thinking about the vision, the Spirit said to him, “Look, three men are searching for you. Now get up, go down, and go with them without hesitation; for I have sent them.” So Peter went down to the men and said, “I am the one you are looking for; what is the reason for your coming?” They answered, “Cornelius, a centurion, an upright and God-fearing man, who is well spoken of by the whole Jewish nation, was directed by a holy angel to send for you to come to his house and to hear what you have to say.” So Peter invited them in and gave them lodging.
>
> The next day he got up and went with them, and some of the believers from Joppa accompanied him. The following day they came to Caesarea. Cornelius was expecting them and had called together his relatives and close friends. On Peter's arrival Cornelius met him, and falling at his feet, worshiped him. But Peter made him get up, saying, “Stand up; I am only a mortal.” And as he talked with him, he went in and found that many had assembled; and he said to them, “You yourselves know that it is unlawful for a Jew to associate with or to visit a Gentile; but God has shown me that I should not call anyone profane or unclean. So when I was sent for, I came without objection. Now may I ask why you sent for me?”
>
> Cornelius replied, “Four days ago at this very hour, at three o'clock, I was praying in my house when suddenly a man in dazzling clothes stood before me. He said, ‘Cornelius, your prayer has been heard and your alms have been remembered before God. Send therefore to Joppa and ask for Simon, who is called Peter; he is staying in the home of Simon, a tanner, by the sea.’ Therefore I sent for you immediately, and you have been kind enough to come. So now all of us are here in the presence of God to listen to all that the Lord has commanded you to say.”
>
> Then Peter began to speak to them: “I truly understand that God shows no partiality, 35but in every nation anyone who fears him and does what is right is acceptable to him...

<!-- ## Terms and Notes -->


## Thoughts and questions

This is such a key chapter in the history of the church.  It is a major pivot point and from the exclusivity of God for the Jews, to God for all people.  Not only that but the rules of religious practice are changed.  For Peter, for any Jew, from a young age they were all instructed on what was good and acceptable to eat and their food practices one way that they were distinct from other peoples.  They were also taught that they should not even associate with gentiles but God, through the dream, has prepared Peter to set aside his biases and training.  

The story of Cornelius is amazing.  

1.   Cornelius is not just a gentile, but a Roman soldier.  He represents the oppressors of God's people.  Yet clearly the message of Jesus is for him too. 
2.   Core aspects are Jewish practice are set aside -- it is better to share the gospel than demand religious practice. 

Following this example, in no way should the gospel be withheld from anyone for religious reasons.  The good news is for all people.  God wants people to know of his incredible love -- not to be burdened by religious rules. 


## Prayer

Lord I praise you that you came to bring good news to all people!

Let my life reflect your good news.\
That you love all people. \
That your grace has been extended to all peoples.

Help us to live as you desired.\
To live lives of compassion.\
To remove oppression.\
To have hearts that are for God first;\
\ \ setting aside religious expectations. 

Help me to know your grace in my life.\
Help me to extend your grace to others. 





