---
title: "Go!"
description: "Last instructions of the resurrected Jesus."
author: Colin C.
date: 2024-03-04
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Acts 1: 1 - 11](https://www.bible.com/bible/2016/ACT.1.NRSV)

>  In the first book, Theophilus, I wrote about all that Jesus did and taught from the beginning until the day when he was taken up to heaven, after giving instructions through the Holy Spirit to the apostles whom he had chosen. After his suffering he presented himself alive to them by many convincing proofs, appearing to them during forty days and speaking about the kingdom of God. While staying with them, he ordered them not to leave Jerusalem, but to wait there for the promise of the Father. “This,” he said, “is what you have heard from me; for John baptized with water, but you will be baptized with the Holy Spirit not many days from now.”
>
> So when they had come together, they asked him, “Lord, is this the time when you will restore the kingdom to Israel?” He replied, “It is not for you to know the times or periods that the Father has set by his own authority. But you will receive power when the Holy Spirit has come upon you; and you will be my witnesses in Jerusalem, in all Judea and Samaria, and to the ends of the earth.” When he had said this, as they were watching, he was lifted up, and a cloud took him out of their sight. While he was going and they were gazing up toward heaven, suddenly two men in white robes stood by them. They said, “Men of Galilee, why do you stand looking up toward heaven? This Jesus, who has been taken up from you into heaven, will come in the same way as you saw him go into heaven.”


### Thoughts and questions 

I think it is great that, as out last devo in Mark ended with _Go!_, our first devo in Acts starts with _Go!_.  

This first passage provides a short recap of Jesus' teaching following his resurrection.  How He has defeated death and spends time with his disciples to reinforce his teachings and demonstrate the power of God.  

It seems that his disciples were still looking for a political revolution.  But Jesus give them a different mission/focus.  Go throughout the world and bear-witness -- testify/ preach/ tell people about what I have done. But I am getting ahead of myself.  Something very significant would happen first.  They were to receive the power of the Holy Spirit.  



### Prayer

Lord Jesus, I thank you.\
Once again I am reminded that you defeated death!\
Once again I am reminded that you are the one that empowers us!

As the Holy Spirit would come and empower the disciples to bear witness to Jesus.\
God send your Spirit to me.\
Heal me. Strengthen me.\
Empower me do bear witness of your great love. 



