---
title: "Peter preaches to the common people (II)"
description: "Peter concludes his sermon -- it was all for a purpose!"
author: Colin C.
date: 2024-04-04
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 3: 17 - 26](https://www.bible.com/bible/2016/ACT.3.NRSV)

> “And now, friends, I know that you acted in ignorance, as did also your rulers. In this way God fulfilled what he had foretold through all the prophets, that his Messiah would suffer. Repent therefore, and turn to God so that your sins may be wiped out, so that times of refreshing may come from the presence of the Lord, and that he may send the Messiah appointed for you, that is, Jesus, who must remain in heaven until the time of universal restoration that God announced long ago through his holy prophets. Moses said, ‘The Lord your God will raise up for you from your own people a prophet like me. You must listen to whatever he tells you. And it will be that everyone who does not listen to that prophet will be utterly rooted out of the people.’ And all the prophets, as many as have spoken, from Samuel and those after him, also predicted these days. You are the descendants of the prophets and of the covenant that God gave to your ancestors, saying to Abraham, ‘And in your descendants all the families of the earth shall be blessed.’ When God raised up his servant, he sent him first to you, to bless you by turning each of you from your wicked ways.”

## Terms and Notes

Peter references [Deuteronomy 18:15-19](https://www.bible.com/bible/2016/DEU.18.NRSV).  Specifically verses 15 and 19 (italicized below).

> *The Lord your God will raise up for you a prophet like me from among your own people; you shall heed such a prophet.* This is what you requested of the Lord your God at Horeb on the day of the assembly when you said: “If I hear the voice of the Lord my God any more, or ever again see this great fire, I will die.” Then the Lord replied to me: “They are right in what they have said. I will raise up for them a prophet like you from among their own people; I will put my words in the mouth of the prophet, who shall speak to them everything that I command. *Anyone who does not heed the words that the prophet shall speak in my name, I myself will hold accountable.* 

## Thoughts and questions

In [part 1](./acts_03-11.qmd) of this sermon Peter highlighted how the Jewish people had killed/crucified Jesus.  As we continue, Peter makes it clear to the people that this was all part of God's plan and that this was done to fulfill the scriptures as evidenced by the prophecies in the Old Testament found in the law of Moses and in the prophets.  Not only does it fulfill the prophecies -- Jesus' death and resurrection renews God's promise to rescue his people.  Peter highlights that the promise is for all people -- _all the earth shall be blessed_. 

### What should we take away from this? 

1.  This was all part of God's plan
1.  We must listen to him! 


## Prayer

Jesus,\
Thank you that your suffering\
and your death\
had such a planned purpose 

I praise you,\
That death could not hold you.\
That you resurrected! 

Help me to learn your ways\
To apply your teachings\
To follow your example

To listen to your Holy Spirit!
