---
title: "The good news for the Ethiopians"
description: "Peter shares the good news of Jesus with an Ethiopian official."
author: Colin C.
date: 2024-08-31
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 8:26 - 8:40](https://www.bible.com/bible/2016/ACT.8.NRSV)

> Then an angel of the Lord said to Philip, “Get up and go toward the south to the road that goes down from Jerusalem to Gaza.” (This is a wilderness road.) So he got up and went. Now there was an Ethiopian eunuch, a court official of the Candace, queen of the Ethiopians, in charge of her entire treasury. He had come to Jerusalem to worship and was returning home; seated in his chariot, he was reading the prophet Isaiah. Then the Spirit said to Philip, “Go over to this chariot and join it.” So Philip ran up to it and heard him reading the prophet Isaiah. He asked, “Do you understand what you are reading?” He replied, “How can I, unless someone guides me?” And he invited Philip to get in and sit beside him. Now the passage of the scripture that he was reading was this:
> 
> “Like a sheep he was led to the slaughter,\
> and like a lamb silent before its shearer,\
> so he does not open his mouth.\
> In his humiliation justice was denied him.\
> Who can describe his generation?\
> For his life is taken away from the earth.”
> 
> The eunuch asked Philip, “About whom, may I ask you, does the prophet say this, about himself or about someone else?” Then Philip began to speak, and starting with this scripture, he proclaimed to him the good news about Jesus. As they were going along the road, they came to some water; and the eunuch said, “Look, here is water! What is to prevent me from being baptized?” He commanded the chariot to stop, and both of them, Philip and the eunuch, went down into the water, and Philip baptized him. When they came up out of the water, the Spirit of the Lord snatched Philip away; the eunuch saw him no more, and went on his way rejoicing. But Philip found himself at Azotus, and as he was passing through the region, he proclaimed the good news to all the towns until he came to Caesarea.

## Terms and Notes

The passage the Ethiopian official was [Isaiah 53:7 - 8](https://www.bible.com/bible/2016/ISA.53.NRSV) is quoted. 

## Thoughts and questions

Who is the good news of Jesus for?  In the last passage we saw how the good news of Jesus extended from the Jews to the Samaritans. Now the passage is extended internationally -- to Ethiopia through this official from the Ethiopian courts.  

### Listening to the Spirit

I love how in this part of the story how Phillip is listening to the guidance of the Holy Spirit -- simply following (i.e. *head to the South Road*). Another prompting: *go over to that chariot*.  At this point the opportunity to speak seems to be orchestrated and Phillip has a great launching point as he explains how Jesus is the fulfillment of Isaiah's prophecy.  Looking at more of the Isaiah passage also describes how Jesus would bear the sins of us all. 

During times in my life I have occasionally sensed the Spirit's prompting to talk with people to go certain places, sometimes to wait where I was.  Rarely have these promptings been strong or distinct -- rather they have been gentle even quiet. However, the majority of the time I do not had any explicitly God directed sense of direction.  Sometimes this is frustrating.  Other times I am consoled with a sense of that I simply need to keep moving forward through life with the assurance that God is there.  I do think that God continues to guide, teach, and direct my steps despite that I may not be distinctly aware of His gentle guidance. 

### Response

I love how open and ready the Ethiopian was to receiving the good news of Jesus and that he wanted to demonstrate this commitment through baptism.  Again, here in Acts, the Spirit of God directly affirms that the good news is for all people.


### Question

How do you define the good news of Jesus?  How would you explain it to today?  Should God ask you to walk to the end of the street and talk with someone there.  How would you share?

## Prayer

Lord Jesus --Thank You!\
\ \ That you came for us all
\ \ That your message of hope is for all people

Lord God -- Thank you\
\ \ That you sent your son
\ \ That he took on the sins of us all

Precious Father\
\ \ By your Spirit direct me
\ \ Assure me 
\ \ Be my peace 

Holy Spirit\
\ \ Call me\
\ \ Direct my ways\
\ \ Guide me that I might 
\ \ \ share of your love. 

God be my confidence and be my peace.