---
title: "God's power demonstrated"
description: "God's power is demonstrated as many signs and wonders were done through the apostles"
author: Colin C.
date: 2024-06-06
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 5:12 - 16](https://www.bible.com/bible/2016/ACT.4.NRSV)

> Now many signs and wonders were done among the people through the apostles. And they were all together in Solomon's Portico. None of the rest dared to join them, but the people held them in high esteem. Yet more than ever believers were added to the Lord, great numbers of both men and women, so that they even carried out the sick into the streets, and laid them on cots and mats, in order that Peter's shadow might fall on some of them as he came by. A great number of people would also gather from the towns around Jerusalem, bringing the sick and those tormented by unclean spirits, and they were all cured.


<!-- ## Terms and Notes -->


## Thoughts and questions

The previous passage was a little scary as Ananias and Sapphira died after trying to lie to God and the church leaders.  This passage shifts the focus from the scary to the amazing and miraculous works that was done through the apostles.  

Solomon's Portico's is a specific location in the Temple grounds.  Obviously the apostles kept teaching despite the imperative from the Jewish leaders that they stop.  They not only taught, God's power at work through them.  People believed!  The sick and the oppressed found healing and freedom! 

Just the idea of Peter walking by and people is his shadow were being healed is amazing! 

## Prayer

God I long to see your power at work!\
My heart yearns for your healing. 

Save us!\
Heal us!\
Free us!

Please God.\
Let Your will be done! 