---
title: "Early Church Leadership"
description: "Prayers and re-establishing the leadership team."
author: Colin C.
date: 2024-03-06
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

### [Acts 1: 12 - 26](https://www.bible.com/bible/2016/ACT.1.NRSV)

> Then they returned to Jerusalem from the mount called Olivet, which
> is near Jerusalem, a sabbath day's journey away. When they had
> entered the city, they went to the room upstairs where they were
> staying, Peter, and John, and James, and Andrew, Philip and Thomas,
> Bartholomew and Matthew, James son of Alphaeus, and Simon the
> Zealot, and Judas son of James. All these were constantly devoting
> themselves to prayer, together with certain women, including Mary
> the mother of Jesus, as well as his brothers.
>
> In those days Peter stood up among the believers (together the crowd
> numbered about one hundred twenty persons) and said, “Friends, the
> scripture had to be fulfilled, which the Holy Spirit through David
> foretold concerning Judas, who became a guide for those who arrested
> Jesus — for he was numbered among us and was allotted his share in
> this ministry.” (Now this man acquired a field with the reward of
> his wickedness; and falling headlong, he burst open in the middle
> and all his bowels gushed out. This became known to all the
> residents of Jerusalem, so that the field was called in their
> language Hakeldama, that is, Field of Blood.) “For it is written in
> the book of Psalms,
>
> ‘Let his homestead become desolate,\
> and let there be no one to live in it’;\
> and\
> ‘Let another take his position of overseer.’
>
> So one of the men who have accompanied us during all the time that
> the Lord Jesus went in and out among us, beginning from the baptism
> of John until the day when he was taken up from us—one of these must
> become a witness with us to his resurrection.” So they proposed two,
> Joseph called Barsabbas, who was also known as Justus, and Matthias.
> Then they prayed and said, “Lord, you know everyone's heart. Show us
> which one of these two you have chosen to take the place in this
> ministry and apostleship from which Judas turned aside to go to his
> own place.” And they cast lots for them, and the lot fell on
> Matthias; and he was added to the eleven apostles.

### Thoughts and questions

What does the author want us to know:

1.  The church was founded by Jesus' original disciples.
2.  Judas and his betrayal was known -- prophesied
3.  Church leadership, through the apostles, needed to be maintained
    -- a 12^th^ apostle was needed.

This was the beginning of Christianity -- those that would follow
Christ! Of course we have the original remaining eleven disciples/
apostles, the women, with Peter taking the lead.

I love how they devote themselves to prayer. I hope I would too -- it
would have been a crazy time: Jesus was crucified, rose from the dead,
and had told them to wait in Jerusalem.

One of the first decisions was that the leadership team had to be
restored. What struck me as I read this is that Jesus had not been
simply roaming around with the twelve and the women who joined them.

No, he was followed by a crowd and it was the twelve that he was
closest with and likely used to give leadership to the crowd. The
twelve apostles seemed to have a special responsibility to be
witnesses of Christ. 

From this text we know that from the larger group
some of them had been following Jesus since Jesus' baptism by John. I
assume that Joseph (Barsabbas) and Matthias were selected based on
their past service and reputation. We don't know if there was no clear
choice between these too, or I suspect, if culturally they needed to
leave the final decision to God through the casting of lots
(effectively rolling dice). ... which seems to me to be a strange way
to discern God's will, but this was a common cultural practice.

### Prayer

God thank you that you love your church.

Thank you for the men and women who have the courage to stand up for
you – bear witness to you. \
I pray that you would build in me the courage and confidence to be
counted among them.

In my life, grant me the opportunity to share your love and compassion
with the people around me. \
May I live it. May I speak it. Help me to bear witness to you.