---
title: "Results of Peter's sermon"
description: "When you speak out there are consequences -- good and bad."
author: Colin C.
date: 2024-04-10
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 4: 1 - 4](https://www.bible.com/bible/2016/ACT.3.NRSV)

> While Peter and John were speaking to the people, the priests, the captain of the temple, and the Sadducees came to them, much annoyed because they were teaching the people and proclaiming that in Jesus there is the resurrection of the dead. So they arrested them and put them in custody until the next day, for it was already evening. But many of those who heard the word believed; and they numbered about five thousand.

<!-- ## Terms and Notes -->


## Thoughts and questions

When you speak out there are always consequences -- good and bad.  The good here is really good as so many people chose to believe the testimony -- the witness that Peter provided about Jesus.  The bad is is more of a slight challenge.  For Peter and John were challenging the power structure of the Jewish people. The temple leaders, and in particular the Sadducees, who did not believe in the resurrection of the dead, were challenged.  As the leaders of the temple they felt they had to get things under control and to stop what they would have perceived as false teaching from Peter. 

I wonder how many Sadducees were devout in their commitment to God?  It could be challenging to leave one's devout religious practice to follow Jesus -- to change from religious practices to accepting the power of the Holy Spirit at work.  



## Prayer

Jesus thank you for raising up men like Peter and John.\
They took in your teachings\
They testified of your mighty works.  

Lord let your Holy Spirit work in me\
That I would understand your teachings\
&nbsp; The Sprit would teach me.\

That by your Spirit I would be raised up to\
&nbsp; testify of you. 

Let my life be a testimony to you.\
Let your will be done. 