---
title: "Peter heals a lame man"
description: "The people are filled with winder and amazement"
author: Colin C.
date: 2024-03-23
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 3: 1 - 10](https://www.bible.com/bible/2016/ACT.2.NRSV)

> One day Peter and John were going up to the temple at the hour of prayer, at three o'clock in the afternoon. And a man lame from birth was being carried in. People would lay him daily at the gate of the temple called the Beautiful Gate so that he could ask for alms from those entering the temple. When he saw Peter and John about to go into the temple, he asked them for alms. Peter looked intently at him, as did John, and said, “Look at us.” And he fixed his attention on them, expecting to receive something from them. But Peter said, “I have no silver or gold, but what I have I give you; in the name of Jesus Christ of Nazareth, stand up and walk.” And he took him by the right hand and raised him up; and immediately his feet and ankles were made strong. Jumping up, he stood and began to walk, and he entered the temple with them, walking and leaping and praising God. All the people saw him walking and praising God, and they recognized him as the one who used to sit and ask for alms at the Beautiful Gate of the temple; and they were filled with wonder and amazement at what had happened to him.


<!-- ## Terms and Notes -->


## Thoughts and questions

I have to wonder, did Peter and John have performing a miracle in mind as they were on their way to the temple?  Did they simply choose to have compassion on this man? Were they prompted by the Spirit to act?  We are not given the answer to these questions but through this story, this passage and those following, we too can be amazed.    

I do not want to discount this miracle -- it is amazing that this man is healed from his life-long disability... 
I just can't help but wonder why this man at this time, and what about other people with injury or lameness/disability? Perhaps the answer is in the fruit -- that which resulted from the miracle.  

Three things result from this miracle: 

1.  Of course the man is healed -- amazing! Although this remains an anchor point for the next passages the healing is not the main focus. 
2.  The people are _filled with wonder and amazement_.  
3.  Peter and John will preach, be imprisoned, and preach again -- sharing the good news of Jesus (next passages)

Perhaps the fruit is more important than the miracle.  The miracle is but a seed.


## Prayer

Lord, forgive me.\
My mind instantly says: 
&nbsp; _What about me? 
&nbsp; When will you rescue me?_

Yet, not my will, but let yours be done.\
And through my story may your story be known.  

Let people know of your great love and faithfulness,\
Let my life bring people to you.\
May people be in awe of you because of what you do in me.\
Let me have opportunity to speak of your great love.

I continue to wait, to ask, to beg,\
I will not stop -- _Rescue me. Heal Me._

