---
title: "One heart and soul"
description: "The early church cared for one another"
author: Colin C.
date: 2024-05-18
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 4: 32 - 35](https://www.bible.com/bible/2016/ACT.4.NRSV)

> Now the whole group of those who believed were of one heart and soul, and no one claimed private ownership of any possessions, but everything they owned was held in common. With great power the apostles gave their testimony to the resurrection of the Lord Jesus, and great grace was upon them all. There was not a needy person among them, for as many as owned lands or houses sold them and brought the proceeds of what was sold. They laid it at the apostles' feet, and it was distributed to each as any had need. 

<!-- ## Terms and Notes -->



## Thoughts and questions

This passage provides a segue/link to the next part of the story.  It provides a beautiful summary of what was happening in the church community where the passages following will expand the details further.  

The apostles continued to preach/witness to the power God -- through the resurrection of Jesus. Now that this early church was growing the witness of how people were changed and how the community cared for one another must have also been incredible. 

I do love the practical means in which the people cared for one another:  They pooled their money, placing their financial resources in the care of the leaders, and people received funds as there was need.  What an incredible witness that must have been!  

...

Being separated from our church community, for over a year, has been hard.  Yet we have also seen such incredible support from them.  So many have given to us in our time of need.  

## Prayer

Lord God, I thank you for your people!\ 
Those who have your heart\
\ \ providing love and care 

Lord, grant me a generous heart,\
\ \ one that sees a need and\
\ \ freely gives.

Lord, help me to bear witness to your great works.

