---
title: "Meeting Practical Needs"
description: "Gamaliel convinces the other leaders to leave the apostles alone -- expecting that the apostles will fail."
author: Colin C.
date: 2024-06-24
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 6: 1 - 7](https://www.bible.com/bible/2016/ACT.6.NRSV)

> Now during those days, when the disciples were increasing in number, the Hellenists complained against the Hebrews because their widows were being neglected in the daily distribution of food. And the twelve called together the whole community of the disciples and said, “It is not right that we should neglect the word of God in order to wait on tables. Therefore, friends, select from among yourselves seven men of good standing, full of the Spirit and of wisdom, whom we may appoint to this task, while we, for our part, will devote ourselves to prayer and to serving the word.” What they said pleased the whole community, and they chose Stephen, a man full of faith and the Holy Spirit, together with Philip, Prochorus, Nicanor, Timon, Parmenas, and Nicolaus, a proselyte of Antioch. They had these men stand before the apostles, who prayed and laid their hands on them.
> 
> The word of God continued to spread; the number of the disciples increased greatly in Jerusalem, and a great many of the priests became obedient to the faith.

<!-- ## Terms and Notes -->

## Thoughts and questions

I really like how the author does not skip over the practical needs of the early church community.  Even in the early church there were practical needs of taking care of people.  There was also ethnic/ cultural tensions between people groups.  I love the wise actions that were taken by th apostles.  

First, they have their priorities straight.  Their job was to share the good news of Jesus.  At the same time they did not fail to see that practical needs had to be met within the community.  The answer, was to find someone that could give leadership to that job.  Caring for the people pulled them together.  

I also love that last sentence -- that religious leaders also started to follow -- they came to recognize that all of this was of God.  From the previous passage they chose to not fight against God. 


## Prayer

God you know the needs of your people. \
It also seems that you choose to your people\
\ to be the answer to those needs. 

God please show me how I can be an answer\
\ to another's need.  

Please raise up others to address the needs\
\ that I have. 

May we all praise you all the more for\
\ the love that you have given us.
\ the love you gave us to share.