---
title: "Attempted deception"
description: "Ananias and Sapphira attempt to deceive the leaders"
author: Colin C.
date: 2024-05-20
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 4:36 - 5:11](https://www.bible.com/bible/2016/ACT.4.NRSV)

> There was a Levite, a native of Cyprus, Joseph, to whom the apostles gave the name Barnabas (which means “son of encouragement”). He sold a field that belonged to him, then brought the money, and laid it at the apostles' feet.
>
> But a man named Ananias, with the consent of his wife Sapphira, sold a piece of property; with his wife's knowledge, he kept back some of the proceeds, and brought only a part and laid it at the apostles' feet. “Ananias,” Peter asked, “why has Satan filled your heart to lie to the Holy Spirit and to keep back part of the proceeds of the land? While it remained unsold, did it not remain your own? And after it was sold, were not the proceeds at your disposal? How is it that you have contrived this deed in your heart? You did not lie to us but to God!” Now when Ananias heard these words, he fell down and died. And great fear seized all who heard of it. The young men came and wrapped up his body, then carried him out and buried him.
>
> After an interval of about three hours his wife came in, not knowing what had happened. Peter said to her, “Tell me whether you and your husband sold the land for such and such a price.” And she said, “Yes, that was the price.” Then Peter said to her, “How is it that you have agreed together to put the Spirit of the Lord to the test? Look, the feet of those who have buried your husband are at the door, and they will carry you out.” Immediately she fell down at his feet and died. When the young men came in they found her dead, so they carried her out and buried her beside her husband. And great fear seized the whole church and all who heard of these things.


## Terms and Notes

From our last devo.  Acts 4:32

> Now the whole group of those who believed were of one heart and soul, and no one claimed private ownership of any possessions, but everything they owned was held in common.


## Thoughts and questions

Ok ... the previous passage (Acts 4:32), taken on its own, suggests that everything was amazing in the early church and that they shared everything.  The current passage starts to get into some of the details.  Obviously not everything was as simple as the general statement in verse 32.

We start with Barnabas.  He is the one that set the example. He sells all of his possessions and gives the wealth to the leaders for the benefit of the community of believers.  Emphasis is made that his is someone who encouraged the community.\
(Note: He becomes an important figure through Acts starting in chapter 9).

The next two paragraphs emphasis how lying to the church leaders and specifically to God has drastic consequences.  Ananias and Sapphira didn't simply lie they created scheme, and made up a story together.  The passage is not clear on their motivation and there are lots of options: Two that seem the most obvious to me are popularity with the church community, or simply not willing to go fully-in on their new faith (this is speculation).  The author of Acts definitely wants readers to know that you should not lie to the church and God.  

In the Ananias paragraph the I like how Peter highlights that the property and then the proceeds of the sale belonged to Ananias -- this highlights that there was no obligation to give all of the money to the community of believers.  However, it was not that Ananias withheld funds, it was that he and Sapphira chose to intentionally lie about it.  

Why have a whole second paragraph on Sapphira?  I think this paragraph emphasizes the message of _don't lie to God_.  Also, I think there is some important justice going on.  The leaders are not willing to condemn Sapphira because of what could simply be her husband's deception -- they take the time to confirm that Sapphira is also a conspirator. 

\
There is a part of me that likes this story as justice is rolled out.  However, another part of me is more like "Whoa, that seemed a little harsh.  God just struck them dead?".    I struggle with is how does this passage fit with the message of God's grace and forgiveness through Jesus.  The only unsatisfactory thing I can think of is: Perhaps, this was needed in the establishment of the early church. What do you think?

## Prayer

God, thank you that you love your people,\ 
\ \ Your church.

I have been blesses by your people,\
\ \ as they have sent their love and\
\ \ care.

Lord, continue your work to build your church.\
Lord, may I be used in that work.\
As Barnabas was, help me to be an encouragement. 

