---
title: "The early church's generosity and goodwill"
description: "How the early believes cared and demonstrated Christ's kingdom come"
author: Colin C.
date: 2024-03-17
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 2: 43 - 47](https://www.bible.com/bible/2016/ACT.2.NRSV)

> Awe came upon everyone, because many wonders and signs were being done by the apostles. All who believed were together and had all things in common; they would sell their possessions and goods and distribute the proceeds to all, as any had need. Day by day, as they spent much time together in the temple, they broke bread at home and ate their food with glad and generous hearts, praising God and having the goodwill of all the people. And day by day the Lord added to their number those who were being saved.


<!-- ## Terms and Notes -->


## Thoughts and questions

If any passage should call the church of today back-to-basics I think it is this one! 

Definitely, amazing things were happening.  There were signs and wonders and we will read more about these in the story ahead.  In some ways a more amazing wonder is that the people cared for one another.  Was this a first socialism?  _All who belived were together and had all things in common_.  Whenever anyone was in need, _They would sell their possessions and goods and distribute the proceeds to all_.  They worshipped God (in the temple), they went home and ate, here I expect they were practicing hospitality, as they ate with glad and generous hearts. They had goodwill to the people, not just the believers, but the people in general.  

This is the type of action that transforms the world -- sincere and active displays of compassion and generosity.  

It does beg the question -- how can I, in my circumstance, show compassion and generosity? I praise God that I have received it.  Now how do I share it?


## Prayer

Lord Jesus, it is beautiful how those first followers cared for the world around them.

They heard your message and began to live your kingdom, showing how your kingdom, your rule can come into our lives transforming lives in our neighborhood.

Lord, today, raise up your church to be generous and have goodwill for the people. 

Let your kingdom come. 