---
title: "Arrested again"
description: "Arrested again the theme of obeying God rather than human authority is played out again."
author: Colin C.
date: 2024-06-13
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 5: 17 - 32](https://www.bible.com/bible/2016/ACT.5.NRSV)

> Then the high priest took action; he and all who were with him (that
> is, the sect of the Sadducees), being filled with jealousy, rested
> the apostles and put them in the public prison. But during the night
> an angel of the Lord opened the prison doors, brought them out, and
> said, “Go, stand in the temple and tell the people the whole message
> about this life.” When they heard this, they entered the temple at
> daybreak and went on with their teaching.
>
> When the high priest and those with him arrived, they called
> together the council and the whole body of the elders of Israel, and
> sent to the prison to have them brought. But when the temple police
> went there, they did not find them in the prison; so they returned
> and reported, “We found the prison securely locked and the guards
> standing at the doors, but when we opened them, we found no one
> inside.” Now when the captain of the temple and the chief priests
> heard these words, they were perplexed about them, wondering what
> might be going on. Then someone arrived and announced, “Look, the
> men whom you put in prison are standing in the temple and teaching
> the people!” Then the captain went with the temple police and
> brought them, but without violence, for they were afraid of being
> stoned by the people.
>
> When they had brought them, they had them stand before the council.
> The high priest questioned them, saying, “We gave you strict orders
> not to teach in this name, yet here you have filled Jerusalem with
> your teaching and you are determined to bring this man's blood on
> us.” But Peter and the apostles answered, “We must obey God rather
> than any human authority. The God of our ancestors raised up Jesus,
> whom you had killed by hanging him on a tree. God exalted him at his
> right hand as Leader and Savior that he might give repentance to
> Israel and forgiveness of sins. And we are witnesses to these
> things, and so is the Holy Spirit whom God has given to those who
> obey him.”

<!-- ## Terms and Notes -->

## Thoughts and questions

This passage starts with *Then*. We have to remember the context --
that the apostles had apparently never stopped preaching in the
temple. In the last passage the apostles were preaching in Solomon's
Portico within the temple complex/campus.

So the temple leaders attempt to take control and they put them in
jail ... again. But God is actively supporting His apostles and they
are releasedand given the instruction to keep preaching about *this
life*. My understanding of *this life*, is the life Jesus and they way
of life that he taught.

I think the second paragraph above should start with *Meanwhile...* as
the scene changes from the prison to the council of the temple
leaders. In this scene the religious leaders are perplexed and perhaps
dumbfounded. So what is there response? Go arrest the apostles again
-- bringing the apostles to them (also away from the common people).

Peter's response is the same as when he was arrested back in chapter
4: *We must obey God rather any human authority*. I love how Peter
seems so fearless. Was he always so fearless or rather so courageous?
Did he learn this through his faithfulness and through seeing God at
work? I expect the latter -- it takes courage to step out in faith and
with each act of courage it might become a little easier.

## Prayer

God help me

When I am faced with adversity\
When life does not go my way\
When people come against me\
Or when there is simple opportunity\
 to speak your truth.

Grant me strength and courage\
To act\
 demonstrating and sharing of *this life*,\
 Christ's life and teachings.