---
title: "Peter's sermon"
description: "Peter explains the baptism of the Spirit and calls people to repent."
author: Colin C.
date: 2024-03-15
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 2: 11 - 42](https://www.bible.com/bible/2016/ACT.2.NRSV)

> ... Cretans and Arabs—in our own languages we hear them speaking
> about God's deeds of power.” All were amazed and perplexed, saying
> to one another, “What does this mean?” But others sneered and said,
> “They are filled with new wine.”
>
> But Peter, standing with the eleven, raised his voice and addressed
> them, “Men of Judea and all who live in Jerusalem, let this be known
> to you, and listen to what I say. Indeed, these are not drunk, as
> you suppose, for it is only nine o'clock in the morning. No, this is
> what was spoken through the prophet Joel:
>
> *‘In the last days it will be, God declares,\
> that I will pour out my Spirit upon all flesh,\
> and your sons and your daughters shall prophesy,\
> and your young men shall see visions,\
> and your old men shall dream dreams.\
> Even upon my slaves, both men and women,\
> in those days I will pour out my Spirit;\
> and they shall prophesy.*
>
> *And I will show portents in the heaven above\
> and signs on the earth below,\
> blood, and fire, and smoky mist.\
> The sun shall be turned to darkness\
> and the moon to blood,\
> before the coming of the Lord's great and glorious day.\
> Then everyone who calls on the name of the Lord shall be saved.’*
>
> “You that are Israelites, listen to what I have to say: Jesus of
> Nazareth, a man attested to you by God with deeds of power, wonders,
> and signs that God did through him among you, as you yourselves
> know— this man, handed over to you according to the definite plan
> and foreknowledge of God, you crucified and killed by the hands of
> those outside the law. But God raised him up, having freed him from
> death, because it was impossible for him to be held in its power.
> For David says concerning him,
>
> *‘I saw the Lord always before me,\
> for he is at my right hand so that I will not be shaken;\
> therefore my heart was glad, and my tongue rejoiced; moreover my
> flesh will live in hope.\
> For you will not abandon my soul to Hades,\
> or let your Holy One experience corruption.\
> You have made known to me the ways of life;\
> you will make me full of gladness with your presence.’*
>
> “Fellow Israelites, I may say to you confidently of our ancestor
> David that he both died and was buried, and his tomb is with us to
> this day. Since he was a prophet, he knew that God had sworn with an
> oath to him that he would put one of his descendants on his throne.
> Foreseeing this, David spoke of the resurrection of the Messiah,
> saying,
>
> ‘*He was not abandoned to Hades,\
> nor did his flesh experience corruption.’*
>
> This Jesus God raised up, and of that all of us are witnesses. Being
> therefore exalted at the right hand of God, and having received from
> the Father the promise of the Holy Spirit, he has poured out this
> that you both see and hear. For David did not ascend into the
> heavens, but he himself says,
>
> *‘The Lord said to my Lord,\
> “Sit at my right hand,\
> until I make your enemies your footstool.” ’*
>
> Therefore let the entire house of Israel know with certainty that
> God has made him both Lord and Messiah, this Jesus whom you
> crucified.”
>
> Now when they heard this, they were cut to the heart and said to
> Peter and to the other apostles, “Brothers, what should we do?”
> Peter said to them, “Repent, and be baptized every one of you in the
> name of Jesus Christ so that your sins may be forgiven; and you will
> receive the gift of the Holy Spirit. For the promise is for you, for
> your children, and for all who are far away, everyone whom the Lord
> our God calls to him.” And he testified with many other arguments
> and exhorted them, saying, “Save yourselves from this corrupt
> generation.” So those who welcomed his message were baptized, and
> that day about three thousand persons were added. They devoted
> themselves to the apostles' teaching and fellowship, to the breaking
> of bread and the prayers.

## Terms and Notes

Peter quotes three passages from the Hebrew Scriptures all italicized
above:

-   First, from the prophet [*Joel 2:
    28-32*](https://www.bible.com/bible/2016/JOL.2.NRSV)
-   Second, from the [*Psalms 16: 8 -
    11*](https://www.bible.com/bible/2016/PSA.16.NRSV)
-   Finally, from [*Psalms
    110:1*](https://www.bible.com/bible/2016/PSA.110.NRSV)

## Thoughts and questions

A longer passage than we normally tackle but I think it was important
to keep it in a single coherent chunk.

This event was like nothing the people have ever experienced! God had
moved in power in their midst and naturally there was confusion.
People from all over the region were there -- Jews and Gentiles. I
wonder how I would have reacted. Would I have been skeptical? Would I
have been filled with wonder?

Peter tells the crowd what has/is happening and the people respond. As
I read it I see three main points:

1.  They are in the end times that the prophet Joel spoke about. The
    Spirit moving amongst them is evidence of that. The signs and
    wonders that Jesus did are evidence of this.
2.  Jesus is God's man, the prophesied descendant of David, the
    Messiah. His resurrection proves this -- God raised him up!
3.  The people respond -- what do we do? In particular the Jews as a
    people have killed God's Messiah. As I think about this the guilt
    could have been terrifying.\
    Peter's solution is simple -- repent, be baptized and your sins
    will be forgiven! I love this -- this is such a break from the
    Jewish temple system. The forgiveness of sins is graciously given
    by God through Jesus -- as declared, in this case, by a fisherman
    (Peter).

A central theme that comes out its that -- *All that call on the Lord
will be saved*. It does not matter the people's background or to what
nation that they belong. All who call on God will be saved.

Awesome, 3000 people took Peter's message to heart and started
following the way of Jesus that day! People of different tribes and
nations. Note: not everyone, but those *those that welcomed his
message*.

...

What does the author what the readers to know? How is the author
wanting the people to be encouraged? These what I think their key
points are:

-   The church was founded by the power of God
-   The message focused on the Jews but was preached to a broader
    group of people.

## Prayer

Lord God, it is you who builds your church.\
It is you who calls us to follow.

Yet, we long for people to know you.\
We long for people to understand You: \
Creator God,\
Saviour,\
Redeemer,\
For them to know that You love them.

May our hearts be open to hear the direction of your Spirit in our
lives.\
\
Lord please move in power. \
Show your wonders. \
Let people see a glimpse of you even through me.