---
title: "Peter and John visit Samaria"
description: "The Samarians receive the Holy Spirit"
author: Colin C.
date: 2024-08-14
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 8:14 - 8:25](https://www.bible.com/bible/2016/ACT.8.NRSV)

> Now when the apostles at Jerusalem heard that Samaria had accepted
> the word of God, they sent Peter and John to them. The two went down
> and prayed for them that they might receive the Holy Spirit (for as
> yet the Spirit had not come upon any of them; they had only been
> baptized in the name of the Lord Jesus). Then Peter and John laid
> their hands on them, and they received the Holy Spirit. Now when
> Simon saw that the Spirit was given through the laying on of the
> apostles' hands, he offered them money, saying, “Give me also this
> power so that anyone on whom I lay my hands may receive the Holy
> Spirit.” But Peter said to him, “May your silver perish with you,
> because you thought you could obtain God's gift with money! You have
> no part or share in this, for your heart is not right before God.
> Repent therefore of this wickedness of yours, and pray to the Lord
> that, if possible, the intent of your heart may be forgiven you. For
> I see that you are in the gall of bitterness and the chains of
> wickedness.” Simon answered, “Pray for me to the Lord, that nothing
> of what you have said may happen to me.”
>
> Now after Peter and John had testified and spoken the word of the
> Lord, they returned to Jerusalem, proclaiming the good news to many
> villages of the Samaritans.

<!-- ## Terms and Notes -->

## Thoughts and questions

As I read this passage there a few questions that pop out at me:

1.  Why do Peter and John need to visit Samaria? Phillip was there --
    wasn't he enough?
2.  The Holy Spirit was given to the Samaritans? How? Why? What is the
    significance?
3.  Simon the magician is scolded. What was his error?

To here is what I think – through the entire book of Acts the author
is being deliberate – they are trying to communicate specific things.
Likely, it is less about historical sequence than the key outcome of
different events.

Peter and John visit

:   Peter and John are the heads of the church. As the church leaders
    they have authority. They are the new religious leaders – without
    Jesus present I suggest they are essentially the acting priests.
    However, in contrast to the religious leaders that crucified Jesus
    – the Pharisees and Sadducees that held strict rules about how God
    works. Peter and John show up to a people group that has been
    traditionally hated by the Jews (i.e. Samaritans were not God's
    people). However, Peter and John, place their hands on these new
    Samaritan Christians and receive the Holy Spirit. But hang on ...
    wasn't Phillip enough. He was a disciple why could he bless and
    see the Samaritans receive the Holy Spirit? It is significant that
    the Spirit is received when Peter and John come.

The Holy Spirit

:   Wow I think there are some layers here... Why was it only through
    Peter and John that the Holy Spirit was given? Again, I think this
    has to do with Peter and John being, for lack of better words, the
    new high priests. They were the head of this Jesus movement. As
    the head of the church it seems they have the authority to bless
    these new believers. I think more importantly, Peter and John see
    how the Samaritans, a people once excluded from the blessings of
    God are now included! The Holy Spirit affirmed these people as His
    people. This is a first example that the definition of God's
    People is expanding!

Simons error

:   Simon definitely got it wrong. I think this story echos that of
    Ananias and Sapphira's story. Now Simon is not struck dead but he
    is definitely scolded. You can't buy God (or the church leaders).

## Prayer

Lord God thank you!\
  That you came for all people.\
  That because of Jesus I am part of your people.\
  That I am a child of God.

Lord God guide me!\
  Help me make right choices.\
  Help me extend your love to all people.

Lord God comfort me.\
  Life can be hard.\
  Send me your Spirit to.\
  Strengthen and encourage me.

I wait for you.