---
title: "Converted Saul"
description: "Saul's story is a dramatic conversion"
author: Colin C.
date: 2024-09-06
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 9:19 - 22](https://www.bible.com/bible/2016/ACT.9.NRSV)

> For several days he was with the disciples in Damascus, and immediately he began to proclaim Jesus in the synagogues, saying, “He is the Son of God.” All who heard him were amazed and said, “Is not this the man who made havoc in Jerusalem among those who invoked this name? And has he not come here for the purpose of bringing them bound before the chief priests?” Saul became increasingly more powerful and confounded the Jews who lived in Damascus by proving that Jesus was the Messiah.


<!-- ## Terms and Notes -->


## Thoughts and questions

Saul's story is such a dramatic conversion.  He completely changes the direction of his life.  From pursuing and persecuting followers of Jesus to preaching his name in the synagogues.  Saul was trained in the ways of the religious leaders -- he understood how they interpreted scripture, how they lived their lives in apparent devotion to God.  Now as a follower of Jesus he knew how to effectively argue, and prove/demonstrate that Jesus was the Messiah! 

Sometimes I have trouble with Paul's story.  Where is the justice in it? Yet it seems God is more about mercy than justice.  God showed mercy to Paul.  Paul would then be used to spread the love of God to the known world sharing God's love through Jesus to multitudes, and even through the generations to come -- through the letters he would write that would become our scriptures. 

## Prayer

Lord, your ways are greater!

My lowly demands for justice would have wanted\
\ \ to see Paul suffer for the \
\ \ suffering he had caused.  

Lord, how arrogant I am to think\
\ \ I know your ways.

Forgive me, I want my desires to be your priority.\
\ \ Yet is this wrong?\
\ \ Please God hear my prayers.\

Please God\
Answer me in my distress and\
\ \ be merciful to me.  

Yet not my will be done\
\ \ Let your will be done.\


<!-- Grant me the grace to accept it.  -->