---
title: "Stephen brought to trial"
description: "False witnesses are set up to bring Stephen to trial."
author: Colin C.
date: 2024-06-28
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 6:8 - 7:1](https://www.bible.com/bible/2016/ACT.6.NRSV)

> Stephen, full of grace and power, did great wonders and signs among the people. Then some of those who belonged to the synagogue of the Freedmen (as it was called), Cyrenians, Alexandrians, and others of those from Cilicia and Asia, stood up and argued with Stephen. But they could not withstand the wisdom and the Spirit with which he spoke. Then they secretly instigated some men to say, “We have heard him speak blasphemous words against Moses and God.” They stirred up the people as well as the elders and the scribes; then they suddenly confronted him, seized him, and brought him before the council. They set up false witnesses who said, “This man never stops saying things against this holy place and the law; for we have heard him say that this Jesus of Nazareth will destroy this place and will change the customs that Moses handed on to us.” And all who sat in the council looked intently at him, and they saw that his face was like the face of an angel.
>
> Then the high priest asked him, “Are these things so?” 

<!-- ## Terms and Notes -->

## Thoughts and questions

The story of Stephen is a major pivot point in the book of Acts.  

The religious leaders up to this point have tolerated the early church.  As we have read, they have not been happy about it but they chose to let it continue in hopes that it would fail.  They were also loosing ground as priest were choosing to follow Jesus.

Stephen had been organizing the church to ensure that the people's practical needs had been met.  From this passage it is evident that he was doing more than ensuring the widows were fed.  The author attributes great wonders and signs that happened through him -- though no details are given the passage suggests that God was working through Stephen in a similar way as He did through the apostles.  

I have to wonder if the religious leaders were still too afraid to attack the apostles directly so here they go after Stephen.  But in order to make their accusations stick they had to find people to make false witnesses against him.  

So now in this passage Stephen is on trial.  _Are these things so?_

What would your answer be?  



## Prayer

Lord, be my strength and confidence!\
Let my life speak to your great love. 

Empower me to witness of you and your ways.\
Send your Spirit that I might have wisdom to speak. 

Lord you know my needs.\
You know how I need healing.\
You know my fears.\

Lord please, bring me strength,\
\ bring me health, 
\ be my peace. 

Let your will be done.