---
title: "Baptism of the Holy Spirit"
description: "The day of Pentacost"
author: Colin C.
date: 2024-03-11
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 2: 1 - 12](https://www.bible.com/bible/2016/ACT.2.NRSV)

> When the day of Pentecost had come, they were all together in one place. And suddenly from heaven there came a sound like the rush of a violent wind, and it filled the entire house where they were sitting. Divided tongues, as of fire, appeared among them, and a tongue rested on each of them. 4All of them were filled with the Holy Spirit and began to speak in other languages, as the Spirit gave them ability.
>
> Now there were devout Jews from every nation under heaven living in Jerusalem. And at this sound the crowd gathered and was bewildered, because each one heard them speaking in the native language of each. Amazed and astonished, they asked, “Are not all these who are speaking Galileans? And how is it that we hear, each of us, in our own native language? Parthians, Medes, Elamites, and residents of Mesopotamia, Judea and Cappadocia, Pontus and Asia, Phrygia and Pamphylia, Egypt and the parts of Libya belonging to Cyrene, and visitors from Rome, both Jews and proselytes, Cretans and Arabs—in our own languages we hear them speaking about God's deeds of power.” All were amazed and perplexed, saying to one another, “What does this mean?”


## Terms and Notes 

Pentacost
: A Jewish Holy Day, 50 days after Passover.  Traditionally this is when the law was given to Moses on Mt. Sinai.

Tongues of fire and being filled with the Holy Spirit
:  This is in fulfillment of John the Baptist's prophecy that Jesus would baptize with the Spirit and Fire.  Matthew and Luke state Spirit and fire.  [Mark](/devos/mark_00/mark-01-05.qmd) and John's accounts say Spirit, omitting fire. 

## Thoughts and questions

Jesus told his disciples that they would receive the Holy Spirit and that they would be his witnesses.  The gospels often portrayed the disciples as not really getting Jesus ... or at least not immediately understanding Him.  

How were they to understand Jesus in this?  Did they discuss it -- _So what are we waiting for?  What did Jesus mean?_.  

How could anyone imagine!  The whole event seems so strange/fantastic even now.  What an event!  The Holy Spirit came in power and people spoke in languages they did not know! There was wind and what seemed like  tongues of fire.  This was something that Jesus' followers experienced and many others witnessed.  

For Jesus' followers this could only have been an incredible confirmation of their faith.  For those witnessing the event -- _What can this mean?!_ 

For the first readers of the book of Acts, and also for us today, this should be a great encouragement that the God, through His Holy Spirit encourages his people, empowers them, and caused those that do not know him to as _what is going on!_


On a different track of thinking, I think that it is also significant that this is the day of Pentacost.  On th day that the Jews celebrate receiving the law as Christians we can celebrate that we have received God Himself!  We are given the Spirit of God -- we do not live by the law but we are to live empowered and directed by the Holy Spirit. 

## Prayer


Lord Jesus please be with me by your Holy Spirit\
Encourage me\
Strengthen me\
Heal me\

Teach me your ways\
Empower me to witness of your great love for this world. 