---
title: "The Persecution of the Church"
description: "The blood of the martyrs is the seed of the church"
author: Colin C.
date: 2024-07-17
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 8:1 - 8:4](https://www.bible.com/bible/2016/ACT.8.NRSV)

> And Saul approved of their killing him.
>
> That day a severe persecution began against the church in Jerusalem,
> and all except the apostles were scattered throughout the
> countryside of Judea and Samaria. Devout men buried Stephen and made
> loud lamentation over him. But Saul was ravaging the church by
> entering house after house; dragging off both men and women, he
> committed them to prison.
>
> Now those who were scattered went from place to place, proclaiming
> the word.

<!-- ## Terms and Notes -->

## Thoughts and questions

::: callout-note
## Tertullian

Tertullian was one of the 'church fathers' from the second century.  He lived during a time when the was extensive persecution of the church.  He is [creditted with the saying](https://www.gotquestions.org/blood-martyrs-seed-church.html):  

> The blood of the martyrs is the seed of the church
:::


Following the execution of stephen must have been such and shock and an intense time for the church. The believers
had to transition from the loving community where the power of God was
being demonstrated by miracles and everyone was full of hope in Jesus
the Messiah. To all of a sudden they are being gathered up and thrown
in jail while others fled the city. Though people mourned Stephen the
text suggests that this was very rushed as Saul was so quickly
arresting people.

Yet the people were not deterred. Even as they left their homes and
their comforts they still had incredible hope in Jesus and proclaimed
His story and teachings where ever they went. I am reminded of a verse
from Jesus' sermon on the mount in Matthew:

> Blessed are you when people revile you and persecute you and speak
> all kinds of evil against you falsely, on account of me. Rejoice and
> be glad, for great is your reward in heaven, for in the same way the
> treated the prophets who came before you.





## Prayer

Lord, none of us want to face trials. \
We all want to be liked.\
It hurts when people speak against us.

Lord, fill be with courage. \
Let your teachings/ your ways become deeply ingrained in me\
That I might share of your great love.\
No matter what I might face.

Let your will be done.