---
title: "Jesus Confronts Saul"
description: "Saul in his devotion was arresting followers of Jesus"
author: Colin C.
date: 2024-09-04
search: false
categories: [Acts]
draft: false
editor: 
  markdown: 
    wrap: 70
---

## [Acts 9:1 - 9:9](https://www.bible.com/bible/2016/ACT.9.NRSV)

> Meanwhile Saul, still breathing threats and murder against the disciples of the Lord, went to the high priest and asked him for letters to the synagogues at Damascus, so that if he found any who belonged to the Way, men or women, he might bring them bound to Jerusalem. Now as he was going along and approaching Damascus, suddenly a light from heaven flashed around him. He fell to the ground and heard a voice saying to him, “Saul, Saul, why do you persecute me?” He asked, “Who are you, Lord?” The reply came, “I am Jesus, whom you are persecuting. But get up and enter the city, and you will be told what you are to do.” The men who were traveling with him stood speechless because they heard the voice but saw no one. Saul got up from the ground, and though his eyes were open, he could see nothing; so they led him by the hand and brought him into Damascus. For three days he was without sight, and neither ate nor drank.
>
> Now there was a disciple in Damascus named Ananias. The Lord said to him in a vision, “Ananias.” He answered, “Here I am, Lord.” The Lord said to him, “Get up and go to the street called Straight, and at the house of Judas look for a man of Tarsus named Saul. At this moment he is praying, and he has seen in a vision a man named Ananias come in and lay his hands on him so that he might regain his sight.” But Ananias answered, “Lord, I have heard from many about this man, how much evil he has done to your saints in Jerusalem; and here he has authority from the chief priests to bind all who invoke your name.” But the Lord said to him, “Go, for he is an instrument whom I have chosen to bring my name before Gentiles and kings and before the people of Israel; I myself will show him how much he must suffer for the sake of my name.” So Ananias went and entered the house. He laid his hands on Saul and said, “Brother Saul, the Lord Jesus, who appeared to you on your way here, has sent me so that you may regain your sight and be filled with the Holy Spirit.” And immediately something like scales fell from his eyes, and his sight was restored. Then he got up and was baptized, and after taking some food, he regained his strength.


<!-- ## Terms and Notes -->


## Thoughts and questions

We first hear of Saul when Stephen is stoned to death for speaking about Jesus and the religious leaders had acted in opposition to God.  It was Saul who supervised Stephen's execution ([Acts 7:58](https://www.bible.com/bible/2016/ACT.7.NRSV)).  In his religious fervour Saul continued in the persecution of people following the Way of Jesus. This persecution ended in the arrest many and likely execution of some of those.  Why would Jesus call him?  Isn't he a murderer?

In reading the story, in knowing the outcome, I am still struck that God would call someone so vehemently opposed to Jesus.  My mind wants to find a reason -- perhaps it is because he was so devoted to God ... willing to do anything for God, but that is just me guessing -- we are not actually given a reason. Whatever the reason Jesus knew him and chose him.  Jesus' confrontation forced Saul to take his first step of obedience to Jesus.  

Meanwhile Ananias also had to take his own steps of obedience.  Paraphrasing: _Are you sure about this Lord?  From what I hear Saul is nasty_.  Ananias, despite his moments of doubt ans skepticism trusts and is obedient.  

The bulk this book of Acts will describe how Saul, renamed Paul, will preach the gospel throughout the known world. 





## Prayer

Lord Jesus I confess. \
Sometimes your ways confuse me. \
Many times I just want to understand 'why'\

Yet I will place my trust in you. \
You are my hope. \
Your ways are the best ways. 

Be gracious to me. \
Bring me to deeper trust.\
That my life would better reflect your ways!