---
title: "The sick child, and a sick woman"
description: "Jesus on his way to help a sick child meets a sick woman"
author: Colin C.
date: 2023-07-16
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 5: 21 - 34](https://www.bible.com/bible/111/MRK.5.NIV)

> When Jesus had again crossed over by boat to the other side of the lake, a large crowd gathered around him while he was by the lake. Then one of the synagogue leaders, named Jairus, came, and when he saw Jesus, he fell at his feet. He pleaded earnestly with him, “My little daughter is dying. Please come and put your hands on her so that she will be healed and live.” So Jesus went with him.\
> A large crowd followed and pressed around him. And a woman was there who had been subject to bleeding for twelve years. She had suffered a great deal under the care of many doctors and had spent all she had, yet instead of getting better she grew worse. When she heard about Jesus, she came up behind him in the crowd and touched his cloak, because she thought, “If I just touch his clothes, I will be healed.” Immediately her bleeding stopped and she felt in her body that she was freed from her suffering.\
> At once Jesus realized that power had gone out from him. He turned around in the crowd and asked, “Who touched my clothes?”\
> “You see the people crowding against you,” his disciples answered, “and yet you can ask, ‘Who touched me?’”\
> But Jesus kept looking around to see who had done it. Then the woman, knowing what had happened to her, came and fell at his feet and, trembling with fear, told him the whole truth. He said to her, “Daughter, your faith has healed you. Go in peace and be freed from your suffering.”\
> While Jesus was still speaking, some people came from the house of Jairus, the synagogue leader. “Your daughter is dead,” they said. “Why bother the teacher anymore?”


### Thoughts and questions 

We will come back to Jairus... Well actually, Jesus gets back to Jairus.  The man has asked Jesus to come and heal his daughter but Jesus has other work to do along the way.  They are on their way to Jairus' house when Jesus stops to have compassion and healing on someone else.  I think what strikes me from this passage, and this is a bit of a reflection on myself, is that Jesus is not just focused on the next task.  He is ready to respond to all in need, despite it appearing to be a delay or distraction from the task at hand.  

Of course it is amazing that Jesus brings healing to this woman who simply reached out to him.  Jesus also takes time to reach her heart.  He does not let this miricle be 'stolen', which could result in guilt, but he speaks to the woman and affirms her faith.  

Apparently, this delay has caused Jesus to be too late ... Jesus is never too late.

### Prayer

Lord God, your ways are higher tha our ways.  Your purposes are beyond us.  Yet, you give us glimpses, including us in your plan.  As I go about my days help me to know your will and call me to act.  Help me to remember that taking time to give compassion is more important than sticking to a plan.
