---
title: "The strong man"
description: "Jesus frees the strong man from insanity."
author: Colin C.
date: 2023-07-14
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 5: 1 - 20](https://www.bible.com/bible/111/MRK.5.NIV)

> They went across the lake to the region of the Gerasenes. When Jesus got out of the boat, a man with an impure spirit came from the tombs to meet him. This man lived in the tombs, and no one could bind him anymore, not even with a chain. For he had often been chained hand and foot, but he tore the chains apart and broke the irons on his feet. No one was strong enough to subdue him. Night and day among the tombs and in the hills he would cry out and cut himself with stones.\
> When he saw Jesus from a distance, he ran and fell on his knees in front of him. He shouted at the top of his voice, “What do you want with me, Jesus, Son of the Most High God? In God’s name don’t torture me!” For Jesus had said to him, “Come out of this man, you impure spirit!”\
> Then Jesus asked him, “What is your name?”\
> “My name is Legion,” he replied, “for we are many.” And he begged Jesus again and again not to send them out of the area.
A large herd of pigs was feeding on the nearby hillside. The demons begged Jesus, “Send us among the pigs; allow us to go into them.” He gave them permission, and the impure spirits came out and went into the pigs. The herd, about two thousand in number, rushed down the steep bank into the lake and were drowned.\
Those tending the pigs ran off and reported this in the town and countryside, and the people went out to see what had happened. When they came to Jesus, they saw the man who had been possessed by the legion of demons, sitting there, dressed and in his right mind; and they were afraid. Those who had seen it told the people what had happened to the demon-possessed man—and told about the pigs as well. Then the people began to plead with Jesus to leave their region.\
As Jesus was getting into the boat, the man who had been demon-possessed begged to go with him. 19Jesus did not let him, but said, “Go home to your own people and tell them how much the Lord has done for you, and how he has had mercy on you.” So the man went away and began to tell in the Decapolis how much Jesus had done for him. And all the people were amazed.

### Thoughts and questions 

We are not told why Jesus went across the lake.  I would have to assume it was to preach, teach, and tell the people about the kingdom of God.  There is a lot going on in this story.  

-   The insane, strong man, afflicted by many evil spirits.  I can't help thinking this would be someone I would be afraid to encounter. I would by default do whatever I could to avoid him.  But Jesus doesn't!  It is amazing how Jesus engages everyone.  IT is also awesome that Jesus brings healing to man.  Makes me wonder, who should I be engaging, showing compassion and friendship to that I would, by human nature, avoid?

-   Again Jesus shows his authority over the spiritual world.  I don't understand why Jesus would allow the destruction of the pig herd.  The only explanation I can come up with is that Jesus might have been calling the people of this region back to God's ways -- this would have been a huge wake-up-call.  Pigs were unclean by Old Testament law.  Yet a herd of that size would have been a significant financial investment. 

-   Jesus doesn't allow the strong man to come with him.  But tells him to spread the word of what God has done.  Which seems to be what he did! 

### Prayer

I love your compassion Lord.  How you reach into broken lives and bring healing.  How you reach into lives that others are afraid to approach.  Help me to show that kind of love to people.