---
title: "The sick child ... dead child"
description: "Jesus is never too late"
author: Colin C.
date: 2023-07-21
search: false
categories: [Mark, authority]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 5: 35 - 43](https://www.bible.com/bible/111/MRK.5.NIV)

> While Jesus was still speaking, some people came from the house of Jairus, the synagogue leader. “Your daughter is dead,” they said. “Why bother the teacher anymore?”\
> Overhearing what they said, Jesus told him, “Don’t be afraid; just believe.”\
> He did not let anyone follow him except Peter, James and John the brother of James. When they came to the home of the synagogue leader, Jesus saw a commotion, with people crying and wailing loudly. He went in and said to them, “Why all this commotion and wailing? The child is not dead but asleep.” But they laughed at him.\
> After he put them all out, he took the child’s father and mother and the disciples who were with him, and went in where the child was. He took her by the hand and said to her, *“Talitha koum!”* (which means “Little girl, I say to you, get up!”). Immediately the girl stood up and began to walk around (she was twelve years old). At this they were completely astonished. He gave strict orders not to let anyone know about this, and told them to give her something to eat.


### Thoughts and questions 

Remember from the previous passage that Jesus was delayed while on the way to Jairus' house.  But I love that it is never too late for Jesus.  

I found it interesting that Jairus has two sets of voices speaking to him.  The religious leaders, who are telling him that his daughter has died and Jesus.  I have to wonder at the religious leaders -- they were likely there to assist the family in their grief.  What were they thinking when Jairus went out to find Jesus?  They were definitely not impressed with Jesus, who they mocked/laughed at... I imagine them saying _Are you stupid, the girl is dead -- not asleep_. 

Jesus shows them all.  He is the one with the power.  It is never too late for him.  Jesus is not showy, rather the time is intimate. He allows the mom, dad, and his disciples to witness his healing of the girl.  More than healing.  Here Jesus his demonstrates his authority over life and death.  

### Prayer

Lord come to this place,  come to our family.  We seek your healing. Remove this cancer.