---
title: "Go!"
description: "The responsibility of being a disciple is made explicit."
author: Colin C.
date: 2024-03-02
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 16: 9 - 20](https://www.bible.com/bible/111/MRK.16.NIV)

>  When Jesus rose early on the first day of the week, he appeared first to Mary Magdalene, out of whom he had driven seven demons. She went and told those who had been with him and who were mourning and weeping. When they heard that Jesus was alive and that she had seen him, they did not believe it.
>
> Afterward Jesus appeared in a different form to two of them while they were walking in the country. These returned and reported it to the rest; but they did not believe them either.
>
> Later Jesus appeared to the Eleven as they were eating; he rebuked them for their lack of faith and their stubborn refusal to believe those who had seen him after he had risen.
>
> He said to them, “Go into all the world and preach the gospel to all creation. Whoever believes and is baptized will be saved, but whoever does not believe will be condemned.  And these signs will accompany those who believe: In my name they will drive out demons; they will speak in new tongues; they will pick up snakes with their hands; and when they drink deadly poison, it will not hurt them at all; they will place their hands on sick people, and they will get well.”
>
> After the Lord Jesus had spoken to them, he was taken up into heaven and he sat at the right hand of God. Then the disciples went out and preached everywhere, and the Lord worked with them and confirmed his word by the signs that accompanied it.

### Thoughts and questions 

Based on review of all the old manuscripts scholars have come to a general consensus that this last passage was added to the gospel likely by another author or authors.  So we have the original ending of Mark stopping with 

> ...‘He is going ahead of you into Galilee. There you will see him, just as he told you.’ ”
> 
> Trembling and bewildered, the women went out and fled from the tomb. They said nothing to anyone, because they were afraid.

It left us hanging.  We know that Jesus is risen and that he will see his disciples in Galilee.  However, it seems that some people felt that this ending was not enough and that some additional detail needed to be added.  So later manuscripts added this ending to provide detail of what Jesus would tell his disciples -- aligning with the other gospel stories. 

What does this additional ending tell us?  What additional information did the later authors what to emphasis?  

Definitely, they wanted to reinforce that Jesus did rise and interact with his disciples.  They also want to ensure people understood the imperative/ instruction Jesus gave his disciples: _Go into all the world and preach the good news._ It would not be enough to simply believe in Jesus but Jesus also instructed them to spread the good news.  The passage also highlights that Jesus would provide supernatural power as signs confirming he is with those who believe.  Finally, Jesus was taken up into heaven.  

The main thing that I take from this passage is the instruction to _Go_.  Though I am left wondering... is it enough to preach the good news?  Rather, I wonder from the teachings of Jesus earlier in the gospel, if doing what Jesus taught is more important... perhaps the authors also meant this when they said _preach the good news_.  

### Prayer

Lord Jesus, how am I to preach the good news in my world today? \
Should I be preaching or living your word? \
Allow the words that I speak match the actions that I take.

Guide my interactions. \
As you guide me I will speak the love that you have given me.

Let my life reflect your glory and goodness. \
May even a few know you more because of your work in me. 


