---
title: "Risen!"
description: "He is risen. He is not here."
author: Colin C.
date: 2024-02-28
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 16: 1 - 8](https://www.bible.com/bible/111/MRK.15.NIV)

>  When the Sabbath was over, Mary Magdalene, Mary the mother of James, and Salome bought spices so that they might go to anoint Jesus’ body. Very early on the first day of the week, just after sunrise, they were on their way to the tomb and they asked each other, “Who will roll the stone away from the entrance of the tomb?”
>
> But when they looked up, they saw that the stone, which was very large, had been rolled away. As they entered the tomb, they saw a young man dressed in a white robe sitting on the right side, and they were alarmed.
> 
> “Don’t be alarmed,” he said. “You are looking for Jesus the Nazarene, who was crucified. He has risen! He is not here. See the place where they laid him. But go, tell his disciples and Peter, ‘He is going ahead of you into Galilee. There you will see him, just as he told you.’ ”
>
> Trembling and bewildered, the women went out and fled from the tomb. They said nothing to anyone, because they were afraid.

### Thoughts and questions 

_He is risen! He is not here._  

So early morning the women were made plans and headed to the tomb.  From what I have read it was customary to place spices in the clothing of the deceased person to reduce the smell, and I would guess to simply honor them. They were doing this on the third day as they could not do anything during passover or on the Sabbath.  They were definitely wondering how their plans would work given that there was a massive stone blocking the way.  Of course they were in for a shock! 

It was beyond their comprehension that Jesus would rise!  They had watched him die.  They had watched his entombment.  

_Go tell his disciples... He is going ahead of your into Galilee_


### Prayer

Lord Jesus, your's is a story of the impossible!\
Yet with you all things are possible!! 

You demonstrated power to overcome disease and disabilities during your ministry.\
You demonstrated that death had no hold on you through your resurrection.  

Please Lord demonstrate your power in my life!\
Let you authority and power be shown.\
Heal me. Save me!\
Allow my life to reflect your love and compassion.
