---
title: "Threats -- Scan Results"
description: "Following a long and anxious weekend we received the results from last week's scan -- not good."
author: Colin C.
date: 2024-08-07
# date-modified: 2024-06-21
categories: [regular, results]
draft: false
editor: 
  markdown: 
    wrap: 72
knitr: 
  opts_chunk: 
    eval: true
    message: false
    warning: false
    echo: false
---

::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Scan results show that the cancerous mass in Sam's chest has grown.
-   The cancer is impacting Sam's vascular system and threatens his
    heart.
-   Sam is on the ward to receive a higher dose of Nivolumab.
:::

```{=html}
<!---
::: {#photo}
![Sam had an amazing week serving on the Ness Lake Team! Here Dave
Horton presented Sam with a team shirt, and coveted Ness Lake button
awards.](https://samsstory.s3.ca-central-1.amazonaws.com/2024-07-31_dave-sam-buttons-ness-lake.jpg)
:::
--->
```
This past weekend was filled with the love of family and friends but it
carried an underlying inescapable anxiety as we waited for scan results.
Yesterday, the fears we battled through the weekend were realized -- the
cancer has grown. Today Sam received an elevated dose of Nivolumab in an
effort to get the cancer under control and again we wait, hope, and pray
that one of these treatments will finally work.

## An anxious weekend

Last Friday was filled with numerous appointments the most important
being a PET scan to determine the current extent of Sam's cancer.
However, it is a rare day that we get the results on the same day -- so
we had to wait-out this past long/holiday weekend before getting the
results.

In addition, given that Sam has been on morphine for such a long time,
on Saturday we attempted a plan (suggested by our doctors) to switch him
over to methadone (i.e. start replacing morphine with methadone). I do
not fully understand why it did not work but by mid-day-Saturday Sam was
writhing in pain. It would take another 36 hours before he would start
feeling himself again. During this time we were able be with with Nana
and the Fricker family (Saturday and Sunday). We would have loved for
Sam to take part more with the family but the medication switch had
taken him down -- he was able to see everyone but he had very limited
capacity to be with the family.

By Monday Sam was feeling better, having returned to his regular drug
regime. Mid-day we had a nice visit/lunch with friends, Donna and Ciaro,
whom we had met through RMH. In the evening we saw the Townsends. It was
great to see Sam feeling better and he was even able to enjoy a game
with his cousins. We were back at the RMH for the night as we had clinic
the next morning.

## Scan results

It had been a long wait through the weekend to finally get to clinic
yesterday and hear the results of last week's scans. As always our
medical team was amazing, especially given the hard task before them.
The results are not what any of us wanted. The cancer had grown again.
In retrospect, now that we have enough scans of the same type (i.e. not
mixing results from different types of scans), it seems that the cancer
has grown fairly consistently and none of the medicinal treatments have
had measurable impacts at slowing the disease. Additional concerns were
also raised as this disease is having further impacts on Sam's vascular
system as it grows into and around some of Sam's major vessels and
heart. The left and right [brachiocephalic
veins](https://en.wikipedia.org/wiki/Brachiocephalic_vein) are blocked
by impacts of the disease (the main veins transporting blood from Sam's
head to his heart). Sam's body has adapted as he has an extensive
network of smaller/collateral vessels that move the blood around this
blockage. Flow is also partially restricted in the [superior vena
cava](https://en.wikipedia.org/wiki/Superior_vena_cava), the major
collection chamber for blood returning to the heart from the upper body
-- again caused by the cancer.

## Next steps

Today, Sam received a dose of Nivolumab at a rate 4-times what he has
received previously. This increased dose was done in effort to find a
level that may show some effect. However, in doing so we recognize that
this may also cause side effects that we have been hoping to avoid. He
will remain in hospital for monitoring overnight and if he remains
stable he may be discharged to the RMH over the weekend.

Next week Sam will have another contrast-CT in an attempt to image if
any impacts can be measured.

So how are we doing through all of this you ask? It would be a lie to say we are not scared.  The disease has been a constant threat and now more than ever.  However, there are great moments of joy.  It is impossible not to smile when Sam wakes from a nap with a big smile on his face saying "*I'm so happy.*"  
::: {.callout-note icon="false"}
## TL;DR [Too long didn't read (i.e. the short version)]{.small}

-   Scan results show that the cancerous mass in Sam's chest has grown.
-   The cancer is impacting Sam's vascular system and threatens his
    heart.
-   Sam is on the ward to receive a higher dose of Nivolumab.
:::

```{=html}
<!---
::: {#photo}
![Sam had an amazing week serving on the Ness Lake Team! Here Dave
Horton presented Sam with a team shirt, and coveted Ness Lake button
awards.](https://samsstory.s3.ca-central-1.amazonaws.com/2024-07-31_dave-sam-buttons-ness-lake.jpg)
:::
--->
```
This past weekend was filled with the love of family and friends but it
carried an underlying inescapable anxiety as we waited for scan results.
Yesterday, the fears we battled through the weekend were realized -- the
cancer has grown. Today Sam received an elevated dose of Nivolumab in an
effort to get the cancer under control and again we wait, hope, and pray
that one of these treatments will finally work.

## An anxious weekend

Last Friday was filled with numerous appointments the most important
being a PET scan to determine the current extent of Sam's cancer.
However, it is a rare day that we get the results on the same day -- so
we had to wait-out this past long/holiday weekend before getting the
results.

In addition, given that Sam has been on morphine for such a long time,
on Saturday we attempted a plan (suggested by our doctors) to switch him
over to methadone (i.e. start replacing morphine with methadone). I do
not fully understand why it did not work but by mid-day-Saturday Sam was
writhing in pain. It would take another 36 hours before he would start
feeling himself again. During this time we were able be with with Nana
and the Fricker family (Saturday and Sunday). We would have loved for
Sam to take part more with the family but the medication switch had
taken him down -- he was able to see everyone but he had very limited
capacity to be with the family.

By Monday Sam was feeling better, having returned to his regular drug
regime. Mid-day we had a nice visit/lunch with friends, Donna and Ciaro,
whom we had met through RMH. In the evening we saw the Townsends. It was
great to see Sam feeling better and he was even able to enjoy a game
with his cousins. We were back at the RMH for the night as we had clinic
the next morning.

## Scan results

It had been a long wait through the weekend to finally get to clinic
yesterday and hear the results of last week's scans. As always our
medical team was amazing, especially given the hard task before them.
The results are not what any of us wanted. The cancer had grown again.
In retrospect, now that we have enough scans of the same type (i.e. not
mixing results from different types of scans), it seems that the cancer
has grown fairly consistently and none of the medicinal treatments have
had measurable impacts at slowing the disease. Additional concerns were
also raised as this disease is having further impacts on Sam's vascular
system as it grows into and around some of Sam's major vessels and
heart. The left and right [brachiocephalic
veins](https://en.wikipedia.org/wiki/Brachiocephalic_vein) are blocked
by impacts of the disease (the main veins transporting blood from Sam's
head to his heart). Sam's body has adapted as he has an extensive
network of smaller/collateral vessels that move the blood around this
blockage. Flow is also partially restricted in the [superior vena
cava](https://en.wikipedia.org/wiki/Superior_vena_cava), the major
collection chamber for blood returning to the heart from the upper body
-- again caused by the cancer.

## Next steps

Today, Sam received a dose of Nivolumab at a rate 4-times what he has
received previously. This increased dose was done in effort to find a
level that may show some effect. However, in doing so we recognize that
this may also cause side effects that we have been hoping to avoid. He
will remain in hospital for monitoring overnight and if he remains
stable he may be discharged to the RMH over the weekend.

Next week Sam will have another contrast-CT in an attempt to image if
any impacts can be measured.

So how are we doing through all of this you ask? It would be a lie to say we are not scared.  The disease has been a constant threat and now more than ever.  However, there are great moments of joy.  It is impossible not to smile when Sam wakes from a nap with a big smile on his face saying "*I'm so happy.*"  He is happy -- he knows he is cared for and he knows that he is loved.

## Victories and concerns

-   The cancer has grown and the impacts of the disease are threatening
    Sam's vascular system and thereby his life.

-   To date medicines have not had any significant effect at controlling
    this disease. We need something that will work. We need a miracle.

-   It was amazing to see Sam join the [Ness Lake Bible
    Camp](https://www.nesslakebiblecamp.com) team (July 28 - 31) . He
    served, ran, talked, played -- he got to be fully there! Many thanks
    to the NLBC team who welcomed him in.

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam (we are also thankful for everyone praying for Sam whereever you are). If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   Thankful for such supportive family and friends caring for us all through this journey. 

-   We long for the day when Sam is free of this disease.

## Victories and concerns

-   The cancer has grown and the impacts of the disease are threatening
    Sam's vascular system and thereby his life.

-   To date medicines have not had any significant effect at controlling
    this disease. We need something that will work. We need a miracle.

-   It was amazing to see Sam join the [Ness Lake Bible
    Camp](https://www.nesslakebiblecamp.com) team (July 28 - 31) . He
    served, ran, talked, played -- he got to be fully there! Many thanks
    to the NLBC team who welcomed him in.

-   We are thankful to the medical team here at [BC Childrens'
    Hospital](http://www.bcchildrens.ca) who have explained things
    incredibly well and who have worked professionally and confidently.
    Your clear communication, compassion, and medical care give us great
    confidence.

-   We are thankful for the gift of a place to stay so close to where
    Sam is receiving his care. The [Ronald McDonald House
    (RMH)](https://rmhbc.ca) has provided us a home away from home. This
    place is an amazing example of charity at work.

-   Thankful for friends who have chosen to meet regularly to pray for
    Sam. If you would like to join them talk with Beth H., Krista C., or
    contact the [Westwood Church](https://westwoodchurch.bc.ca) office.

-   Thankful for such supportive family caring for us in all through
    this journey.

-   We long for the day when Sam is free of this disease.