---
title: "The current pattern"
description: "The activities of a 'typical day' for us."
author: Colin C.
date: 2023-05-16
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Yesterday evening Kevin, my brother-in-law and soul-brother, checked in with me.
With everything going on we kept it to a text-based conversation. He asked
a simple question of how was today? I was going to write something
simple, to say that it went well and I had to catch myself as I realized
our normal here just is not normal. Generally, it was a good day, we are
carrying on with the plan. Generally, it was a lower stress day. Below I
refine and expand on my original text to give you a glimpse at how our
days are:

-   The day started early, or perhaps there was not night. Given the
    amount of fluids being pumped into Sam we were up every 1.5 - 2
    hours. So we start the day sleep deprived.

-   Every hour something was going on with Sam's medications and or tube
    feed. This included numerous chemo drug deliveries.

-   Several blood and fluid tests -- checking chemistries and how those
    may impact the delivery of chemo.

-   The IV team was in to change one of his dressings -- the one on the
    PICC on his arm which he received last week. FYI Sam is down to two
    sets of blood connections. The PICC on his arm, which is not
    centrally located, and the Hickman which is being used to deliver
    the chemo.

-   Sam is on a tube feed. He is still eating regularly, but with all
    the potential impacts from chemo the desire is to supplement his
    nutrition, and give him every chance to regain or retain weight.

-   Dr. Peggy W. came by for her usual check-in, clarified a few of our
    questions, but no concerns -- all is going as planned

-   The nurses were training on a new protocol for hooking up the IV
    system. ... they are moving to a quick connect/release system.

-   During much of the above Sam and I watched a movie, obviously with a
    good number of pauses -- I think the 2-hour movie took closer to
    five.

-   I got out --- took a nap and had a shower over at the Ronald McD
    House.  When I got back Sam and Tina were also able to nap -- so helpful is restoring our short nights.

-   We have a small fridge in the room, and with recent meals it was a
    left-over night. On the food front, we are very pleased that we have
    not struggled to keep Tina in food despite all her food
    sensitivities.
    
    
## Victories and concerns

-   Thankful for visits with friends and family

-   Thankful that Tina has had good food.

-   Concern for the current round of treatment. We are expecting side
    effects. To date, we have not seen very little.  A little soreness in the mouth but this has been very manageable.

-   Concern for potential longer lasting and high impact side effects.
    These can include damage to bodily organ or secondary cancers.

-   Ultimately, we are concerned that the treatment is effective and
    that the cancer is removed entirely from Sam's body.
