---
title: "Visits and a date"
description: "A number of good visits, a date for Tina and I, and goodbye to Nana."
author: Colin C.
date: 2023-05-31
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

## Reflections on May 29 and 30

Medically, the last couple days for Sam have been mostly positive as we
see his numbers come back and see him gain energy back, be mostly over
his cold/flu. The chemo-side-effects have presented themselves further
as Sam has begun to lose his hair, I discuss additional challenges in
the concerns below.

During this time, it has been great to have Nana here to visit with all
of us but especially with Sam. Her time here also allowed Tina and I to
get out together for a few hours away from the hospital. Vancouver has
been good to us in that we have not struggled to find good food for
Tina. However, most of this has been ordered in. On the 29^th^ we were
able go out for some good food -- to have a date. We took the Skytrain
into Yaletown, walked the neighbourhood and had a meal together. I know
this is shocking to many -- I don't think we took one picture on our
date... if we had I would have posted something.

The 30^th^ is marked as being Nana's last day visiting with us -- we
expect she will be back in a number of weeks. Uncle Cal, and cousins
Amanda and Chris were also able to stop by for a quick visit. Nana and
the family left in the evening. Sam also had a friend stop by, David H.
spent the evening with him, while Aria and Tina visited. An additional
visit earlier today, Tina and I had a great catch-up with Sam, Nick and
Elara G.

## Concerns and victories

-   Thankful for visits from Nana, local family, and friends.

-   Thankful to see Sam's blood counts returning to normal including the
    numbers indicating the strengthening of hi immune system.

-   Challenges of side-effects. Sam, although have a return of energy,
    is becoming physically exhausted. This whole regime, and being
    bed-bound for a full week has led to parts of his system being bound
    -- constipation is significant issue. It will pass but likely not
    without pain. GI sores from the chemotherapy also complicate this.

-   Concern, a recent scan flagged a the potential for a problematic
    kidney stone.

-   Upcoming, this Friday June 2, Sam is books for a PET scans. The
    purpose of this scan is to determine to current state of the cancer.
    We look forward to knowing the results. We are excited that previous
    scans suggest significant reductions in the cancer and that this
    scan should confirm that. As always, we will remain concerned about
    any cancer in his system.
