---
title: "PICCs and other procedures"
description: "Quick review of Sam's procedures yesterday. Tina gets out with a good friend."
author: Colin C.
date: 2023-05-09
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Sam and I are both up. Sam is in good spirits having had a sound sleep
last night. It must have been a quality sleep because it certainly was
not a long one ... we should both take naps today. Last night we watched
a very disappointing hockey game and then had a gaming session. I
confess it got later than it should and Tina was not here to put a stop
to it. She went to have a full night sleep at the
[RMDH](https://rmhbc.ca) and I hope that she is able to sleep well into
the morning. As I write this Sam is reading a classic -- if you know
that the answer is `42` then you know the series he just started.

## Reflections on May 8

To start the day we thought it would be rather simple and that the
afternoon would be relaxed... It wasn't all bad though there are some
concerning elements, it just did not all go as planned. The bulk of the
day

1.  To start Sam did go under general anesthetic to adjust his
    [PICC-line](http://www.cw.bc.ca/library/pdf/pamphlets/BCCH1552_PICC.pdf)
    and complete a lumbar puncture. The PICC procedure did not go the
    way the medical team had hoped. The plan was simply to adjust the
    position of the existing line, but they were not able to do this so
    they pulled that line and attempted a new line on the other arm.
    This new line also did not go as planned, as they were not able to
    centrally locate the outlet. This is where there is some concern,
    attempts to (re)position the previous or locate the current line
    failed due to blood clots in Sam's system. No one is very clear as
    to why he has clots so frequently in his blood vessels (to be clear
    this is not because they are keeping anything from us ... it is just
    they do not know). We know that some of the clots are an effect of
    the cancer -- as the body tried to fight it; alternately, this
    clotting could be somehow related to the previous chemotherapy. The
    fact is there is clotting in Sam's blood vessels, and there is more
    clotting than a couple weeks ago despite taking blood thinners twice
    a day.

2.  The lumbar puncture went as planned.

3.  The quiet afternoon turned into an additional procedure. The
    previous scans had focused on the upper chest and neck. This
    ultrasound was done to evaluate the potential of clotting in the
    abdomen and legs. Results are pending.

We were finally back to the room by about 4pm. Time for dinner. I had
left overs. A friend had brought poke bowls yesterday and the left over
one as almost as good as the first. Sam had a hospital dinner
supplemented with snacks from Safeway. Tina was off on her own
adventure.

I am so happy for Tina as she was able to get away yesterday afternoon.
Senga was here and she took her out to a local park and then out for a
Tina-friendly meal.

## Concerns and victories

-   Sam has a new PICC, despite not being placed idealy it should work.

-   Concerns around clotting in Sam's blood vessels. He is on blood
    thinners but there appear be more clots than a couple weeks ago.

-   We are expecting to meet with the Dr. Cheng this afternoon to
    discuss recent results and plans for Sam's next round of
    chemotherapy -- which may start tomorrow.

-   Joyful for connections with friends -- in person and through
    communication.
