---
title: "Preliminary findings"
description: "Preliminary findings -- we are headed in the right direction!"
author: Colin C.
date: 2023-05-25
categories: [daily, results]
draft: false
editor: 
  markdown: 
    wrap: 72
---

The days have been blurring together in this time-warp experience here
at BC Children's hospital. This morning is the beginning of day 37 --
now just over five weeks since our arrival. This current round of
chemotherapy will come to an end in another ten days. In some ways it
feels like we are on a long waiting period, yet everyday brings its own
challenges or occasional bits of news. Each day we:

-   get updates on Sam's blood counts
-   manage pain related to the effects of chemo
-   try to stay active
-   try to play a game or read ... but often the energy/concentration
    level is not there so there is a lot of TV. *\
    We would love some recommendations of shows or movies that you have
    enjoyed.*

## Findings from an X-ray

Two days ago Tina and I had a good conversation with Dr. S. Cheng. We
love how honest she is with us, that she shares what she knows and how
she lets us know what she does not know. In our meeting, she told us
about Sam's latest chest X-ray -- the purpose of which was to rule out
the potential for pneumonia related to Sam's cold. There was also enough
information in the image that Dr. Cheng could provide a preliminary
report: the tumour is smaller than shown in the previous CT scan (taken
after round 1 of chemo). We are headed in the right direction -- round 1
saw a reduction in the cancerous mass, and round 2 appears to be doing
the same! We will know better in with the next scan in a couple weeks
when a scan will be done to image the cancer itself.

As to what the next steps will be following this round of chemo -- that
is simply unknown.

## Reflections on May 23 and 24

The 23^rd^ was a day filled with the love from friends and family. The
three of us had a good visit with Craig and Lisa R, followed by Tina and
I having time with them. Nana spent much of the day sitting with Sam,
and much of the evening with Tina. Yesterday, was quieter in Sam's room.
As per doctor's recommendations we reduced his visitor hours. I spent
most of the day with Sam, less a couple hours, when Nana sat with him.
Outside the room, Tina and Mary (Nana) had a great visit with Tina's
nieces Amanda and Jayme, and Jane, and her brother Cal.

## Concerns and victories

-   Thankful for friends and family supporting us.

-   The medical team here continues to be amazing.

-   Side effects of the chemo-therapy. No hair loss yet, but significant
    muscle pain, and pains related to sores in the GI track[^1].

-   The constant cancer concern. We will not know how the cancer has
    responded to this treatment for another week-and-a-half. Once the
    full therapy cycle is complete the team here will scan for changes.

-   Homesickness and boredom. Sam has been a champ making the best of
    his time here. Yesterday, Sam and I had a great conversation about
    home, that we miss it, and we imagined/ dreamed of what we love
    about home from simple things of regular life, to friends, to
    dreaming of what we would like to do when we return. Longing for
    home and feeling trapped in this hospital ward may become
    significant challenges in the days ahead.

[^1]: Gastrointestinal track -- from the mouth all the way through and
    out of the digestive system
