---
title: "In preparation for chemotherapy -- waiting"
description: "A brief list of concerns and victories as we approach round two of chemotherapy."
author: Colin C.
date: 2023-05-11
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

We are in a waiting period. The next round of chemo cannot begin until
the new central line is established. Over the last couple days:

-   We have had visits with various doctors to discuss the next steps
    (e.g. procedure for central line and chemotherapy treatments).

-   To ensure that Sam gets the nutrition that he needs in the weeks
    ahead he had a new NG tube installed -- allowing for supplemental
    food to be pumped to his stomach via a tube going in his nose and
    down to the stomach.

-   Sam has good energy these days and we have been walking around the
    hospital and Sam is looking at his schoolwork via google-classrooms
    -- getting excited about finishing grade nine.

-   Yesterday evening my parents arrived. Sam and Papa enjoyed watching
    the hockey game together while Tina and I got away together for a
    good dinner a few blocks away on Main St.

## Concerns and victories

*repeated from yesterday*

1.  We are very thankful for the entire medical team here. The care-aid
    and nurses take on the day-to-day care, each with their own style of
    care but all doing a great job of addressing needs as they arise.
    The support teams including IV, nutrition, and physio. The cleaning
    staff who are so polite. Sam's doctors who are excellent
    communicators and are gracious in allowing time for dialogue and
    answering our questions when they have answers, and are straight
    with us when they do not know.

2.  There are a lot of unknowns going forward. Sam's form of cancer is
    mostly unknown. As such, the treatment plan / chemotherapy will be
    to hit it with the largest hammer available. This will be hard on
    Sam's body and we hope much harder on the cancer.

3.  In preparation, another attempt to establish a central-line will be
    made. As the clotting in the chest blocking access via the arms
    towards the heart a line will be attempted through the vessels in
    one of Sams's legs, to approach the heart from below. Once this line
    is established chemotherapy will begin. Timing will be based on the
    next available time... this may be as late as Friday.
