---
title: "Nana is here!"
description: "Tina's mom arrives while Sam fights the flu"
author: Colin C.
date: 2023-05-23
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---


Although I am wiped out from a short night of sleep, I have joy. Sam is
awake beside me acting himself. I do hope that he takes a nap later --
but this is good to see. He has energy to play a game -- something he
simply has not had the concentration power to do. Last night had
actually been a hard one. I am not sure it was the flu or other effects
of the chemo but his sleep had been interupted and thereby mine was as
well.

## Reflections on May 22

Medically, yesterday was a day of discomfort. Sam had the flu, a result
of the chemo taking out his immune system, and with this illness he had
quite a bit of muscle pain. Blood tests also showed his counts were down
again. In response, Sam received transfusions in the afternoon.

The highlight of the day was the happy reunion of Sam and Nana in the
early afternoon! I had taken the skytrain out to the airport and we
travelled straight back to the see Tina and Sam. Tina and her mom were
also able to spend some good times catching up. Hopefully they are
having a good sleep-in over at the RMH.

## Concerns and victories

-   Thankful for Nana

-   The medical team here continues to be amazing.

-   The constant cancer concern. We will not know how the cancer has
    responded to this treatment for another week-and-a-half. Once the
    full therapy cycle is complete the team here will scan for changes.
