---
title: "Cytarabine aka Cyterrible"
description: "A hard 48 hours.  On side effects and considering all possibiliites."
author: Colin C.
date: 2023-05-18
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

This morning the sun is shining, my family is sleeping peacefully. It
seems that we have Sam's health management under control. My outlook
today is one of hope. The previous two days were definitely more
challenging.

## Reflections on May 16 and 17

Yesterday morning, as I was considering what to convey, the day started
with a challenge... I will get to that, but before I do I actually need
to back up two days.

Two days ago we had a meeting with our medical team. It was a fairly
standard check-in but one that shook Tina and I to the core. We were
both, individually, in own personal funks for much of the day before we
had an opportunity to discuss it together. During the meeting we were
introduced to members of the medical team from Canuck Place. They let us
know some of the services that they provide including potential future
options respite from the hospital experience. What shook us to the core
was the main purpose of [Canuck Place](https://www.canuckplace.org) --
palliative care. To be clear, we are not going down that road, but not
knowing what the future holds, it is within the realm of possibility and
I suspect that the medical team here had a ethical obligation to ensure
this connection was made. We have known this, but the meeting forced us
to confront the possibility more directly -- again, re-opening this
wound/fear.

Two days ago was also the fifth of five days of the heavy chemical
delivery for this current round of chemotherapy. The remaining 16 days
of this chemo round are in place for the chemicals to complete their
work, and to allow Sam to recover from it. As of that evening we had not
seen much for side effects. Yesterday morning, that would change.

Yesterday, as I was considering what to write, Sam's day began with a
strong wave of nausea and pain. The previous two nights one of the drugs
that Sam was given was Cytarabine. I'll blame that one, though it could
been side effects from the whole set. It took several hours to get Sam
comfortable, and by the afternoon he was feeling ok, tired but ok. And,
though I am exhausted as well, Sam's fatigue is beyond the lack of sleep
we have been having as is a product of the treatment the chemo. In
addition the chemotherapy medications will reduce Sam's blood counts --
reducing the capacity of his blood to: provide him energy/oxygen
(hemoglobin/ red blood cells), protect him from injury (platelets), and
protect him from disease (white blood cells).

Some positive highlights:

-   Tina and Erin S. were able to spend some time together (2 days ago)

-   A relaxed and enjoyable visit with Uncle Cal and cousin Jane
    (yesterday)

-   Coffee and treats sent to by friends.

## Concerns and victories

-   The heavy dosing of this round of chemotherapy drugs is now complete

-   From what we are told, we are entering the valley of chemo side
    effects. Sam, seems ok this am. My hope is that the side effects
    will be minimal for him.

-   Although a rough start to yesterday, Sam now has a medication regime
    that seems to be working to curb the feelings of side effects
    causing nausea and pain.

-   We remain concerned that this treatment is ultimately successful at
    removing the cancer from Sam's body.
