---
title: "Response to the first round of chemotherapy"
description: "Results of the first round of chemotherapy and plans for the next."
author: Colin C.
date: 2023-05-06T07:00
categories: [daily, results, milestones]
draft: true
editor: 
  markdown: 
    wrap: 72
---

Yesterday, Sam finished his first round of chemotherapy his final round
of drugs. Mid-morning he had a CT scan. In the afternoon we had a visit
with Dr. Cheng to discuss the results and the next steps. Being that
Sam's cancer is very rare we did not know if it would respond to the
chemotherapy. I am so glad to say that it has.

-   The size of the main tumor in Sam's chest has seen an estimated 40%
    reduction in size.

This is excellent news -- though there is much work to be done. It has
been amazing to see Sam's body respond so well this past week and to
know that the cancer was reduced in size. With these results in, the
beginnings of a plan can be made, and we have an idea of what the next
couple weeks will look like.

-   This coming Monday Sam will have two procedures.

    -   Adjustments to his PICC line. Initial problems with the PICC
        resolved -- how or why remain unclear, but the result was that
        regular blood tests (on average about every 8 hours) were taken
        easily via the PICC line. Going forward, the PICC need some
        re-positioning to allow for the safe delivery of the next round
        of chemotherapy.
    -   A lumbar puncture to confirm that the caner continues to not be
        in the central nervous system (there is some concern that this
        form of cancer could migrate there). Dr. will also inject
        chemotherapy medications into the spinal fluid as a preventative
        measure.

-   Tuesday, Dr. Cheng will be presenting Sam's case and consulting with
    other experts in the field. That afternoon, the we should know the
    plan for the next round of chemotherapy.

-   Wednesday, the next week of chemotherapy should begin.

## Victories and concerns

-   Excellent results from the first week of chemotherapy.

-   On the flip-side, there is much work to be done to further reduce
    and ultimately remove the cancer. There is always a possibility that
    the disease adapts and stops responding

-   We are thankful for an amazing community of people around us. We
    have been encouraged and gifted beyond what we could have ever
    expected.

-   Yesterday we spent time as a family simply listing things that we
    are thankful for. It was a beautiful time.
