---
title: "Extended days of freedom!"
description: "Bonus days away from the hospital!"
author: Colin C.
date: 2023-06-15
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

This morning I am writing from our room at the RMH -- because we are all
still here!

Two days ago Sam went in for his clinic appointment. We had expected
that he would be admitted, as his blood counts would be falling. But we
received great news! Although his counts had dropped they had not
dropped as to cause any concern. The result is we got a bonus 72 hours
away from hospital admission. Sam has a clinic appointment tomorrow am
-- likley he will need to be admitted then.

## The last couple days

Tuesday, June 13

:   Following the clinic appointment in the morning we had relaxed
    afternoon at the Ronald McDonald House. I got out for a bike ride.
    Margaret and Daniel joined us for the evening. It warmed my heart to
    see the cousins chatting together!

Wednesday, June 14

:   I drove Margaret and Daniel to the airport using our van (my sister
    drove the van down and then flew home). In the afternoon, the three
    of had a good time playing family games. Of note: *Connect 4* the
    card game is far better than the original. For Tina, we also made a
    gluten-free-goods run to the [Gluten-Free
    Epicurean](https://www.glutenfreeepicurean.ca).

## Concerns and victories

-   Thankful for a weekend away and additional days this week! This days
    were a welcome surprise. I hope this can be part of the pattern
    going forward -- we will take each day as it comes.

-   Thankful for visits with family.

-   Thankful for a video from the Westwood youth group. Great to see
    familiar faces. Thank you for sending your care and friendship.

-   Again, we are thankful that Sam is not feeling the effects of this
    chemotherapy round ... yet.\
    Concern, Sam's blood levels are dropping and the days ahead could
    feel gross as the effects of the chemotherapy take hold.

-   We are thankful that the treatment is working. There is also concern
    that it is effective to remove the cancer fully!
