---
title: "Freedom from hospital life"
description: "Sam completed his second round of chemotherapy, and we are free from hospital life for the next number of days!"
author: Colin C.
date: 2023-06-03
categories: [daily, procedures, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Good morning! \
Here we are having a good morning as we are experience a good level of
freedom. All three of us are currently at the Ronald McDonald House. This
am, Sam and I have had breakfast together, and as I write this Tina is
sleeping in.

Sam made it through, we made it through this last round of chemotherapy!

## Reflections on June 1 and 2

*June 1* Sam was still in hospital. In consultation with the medical
team most all of Sam's meds moved from a) being on a delivery schedule
to list as take-as-needed, b) changed from IV delivery to oral. The
purpose of this day was to prepare us to get out -- to give us control
of Sam's care.

*June 2*, yesterday, was very full with procedures and our transition
out of the hospital. Forty-five days prior we made the emergency move
from Prince George to the hospital. We have lived there full time and
now we had the day to prepare to leave.

-   The day started with trip to the BC Cancer Clinic for a PET and CT
    scan. This was much easier than the last trip. Last time the
    Ambulance service transported Sam which was needed given the state
    of his health at that time. This time, the three of us went
    downstairs, got in a taxi, and walked into the clinic.

-   Next were the steps to leave including:

-   A trip to the pharmacy -- to collect all of Sam's medications. This
    was actually simple, as the pharmacy is just downstairs. I would
    realize hours later, well after closing that I bought the wrong
    needles for Sam's blood thinner...

-   Trips to move our lives over to the RMH[^1]. In our time here we
    have lived full-time at the hospital with minor respite at the RMD.
    During our time here we have only added materials to our lives as we
    bought or people brought us life-essentials, and gifts arrived. We
    are blessed to have all that we need and more. I did spend a couple
    hours moving our things -- very glad that the RMD had utility wagon
    that we could borrow.

-   Trip to the Red Cross -- to get some hardware for Sam. He has some
    strength to regain so in moments of weakness or fatigue he can fall
    back to the wheelchair or shower-transfer-bench.

[^1]: Ronald McDonald House

We were fully here by 7:00pm. We are loving it! The feelings this
morning are almost reminiscent of family vacations that we have had in
the past. We are not home but we are free to be ourselves!

## Concerns and victories

-   Thankful for this opportunity to get out for a few days.

-   Upcoming we have to return to the hospital on Tuesday, June 6 when
    we will hear the results of the PET and CT scans and likely be
    admitted to start the next round of chemotherapy.

-   Thankful, for the amazing care Sam received at BC Children's Also
    thankful that we have a break from it -- that we can sleep through
    the night without the need to take vitals, take blood, deliver
    medications, or listen to alarms.

-   Challenges of side-effects have mostly resolved! I will need to go
    in search of a vacuum cleaner as Sam's hair rains from his head.

-   Concern, a recent scan flagged a the potential for a problematic
    kidney stone.

-   As always, we will remain concerned about any cancer in his system.
