---
title: "Reality Check: Things are not good"
description: "This is a raw post... it hurt to write, and it will likely hurt to read."
author: Colin C.
date: 2023-04-27
draft: false
---

It is early morning, the start of day 9, here at BC Children's Hospital. This morning, I write so that you might better know what we are experiencing. In writing this, I am throwing caution out and exposing you to our pain... I do not expect you to read this ... and perhaps you shouldn't.

::: panel-tabset
### \...

... *I leave it to you to choose to enter our pain (i.e. click the Pain tab).*

### Pain

Why share this? You are our friends and family. This is the truth of where we are at.

1.  Tina and I have wept, we have wailed. It comes in waves -- releases of love, pain, and grief from a depth of my being that I never before knew existed. The reality is, we might lose our boy.

2.  Sam is sick, he has cancer, treatment has not begun and he continues to get sicker.

3.  We do not know what kind of cancer this is. Cancer in children is rare, and Sam's cancer, is extremely rare -- the disease specialists have not been able to identify it.

4.  We do not know if this cancer is treatable. It is so unknown; treatment might be simple... but it also may not be possible. We just do not know.
:::

### Recent and next steps

1.  Sam had is PET scan yesterday -- we do not know the results.
2.  Sam received a feeding tube. His nausea had been debilitating, and he has eaten very little in the last weeks.
3.  We continue to wait for a treatment plan.

### What can you do?

1.  Pray.
2.  Continue to send us your care. We are bolstered by your notes of encouragement, love, and support.
3.  We have been blessed with visits from friends and family.\
    If you would like to see us, please contact me first, and I will try to work something out. Please be aware that as we move forward, ideally into treatment, visits with Sam may be highly restricted.
