---
title: "Pending decisions"
description: "We continue to wait.  Diagnosis is still pending. Decisions need to be made."
author: Colin C.
date: 2023-04-28
draft: false
---

Thank-you!  We have received so many notes of solidarity, encouragement, and prayer.  The community of support around us, all of you, is amazing!

## Reflections on April 27^th^. 

I'm going to keep this one quick ... we are in a state of hyper-vigilance for Sam, staying in the room with him. This is something that is essential for now, though not sustainable... we are stressed and exhausted. 

- My parents, Earle and Dorothy, are here with us.  Great to have their support. Thanks to the many who are also supporting them.
- Recent scans confirm where the cancer is.  No new surprises, though the impact of the cancer on Sam is stronger than previously known. 
- Cancer diagnosis is still pending. It is expected that BC Cancer Clinic will be able to identify the disease. 
- However, we may not be able to wait.  Initial treatment steps may need to be taken before the diagnosis is in.  From the medical perspective this is about managing risk.  Starting treatment without diagnosis may impact longer term effectiveness of the treatments; not starting could allow the cancer to impact Sam in the now. 



