---
title: "Results and returning for round 2"
description: "Results of treatment so far, and a return to the hospital to start the next round of chemotherapy."
author: Colin C.
date: 2023-06-07
categories: [daily, milestones, results]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Once again I am writing from Sam's bedside here at BC Children's
Hospital -- our second arrival. Compared with the first, this is so much
easier. Sam's health has dramatically improved and it is much easier to
be in hospital when you plan to go there. We are also returning to
people that know and care for Sam.

## Reflections on June 7

Yesterday was a business day. Sam's return to the hospital. We checked
into the Oncology day-clinic, Sam had a few tests, we met with Dr. Cheng
to discuss the progress made and the plans moving forward. In the
afternoon Sam would receive his first chemical doses of chemo round
2[^1].

[^1]: This is the actual round 2. What I referred to previously as round
    to was actually round 1, and the very first week of chemo ... well
    they don't actually count that one.

### Results

We had an opportunity to look at before and after imagery from Sam's PET
scans. I am glad I had not seen the first scans until now. The
difference is dramatic.

1.  The size and density to the cancerous mass is greatly reduced
2.  The impacts on Sam's other organs has been removed -- or is minimal.
    The first scans showed high impacts on Sam's lungs heart -- mostly
    causing high levels of fluid build up and pressure. Now his lungs
    are now clear of fluid and only a residual amount of fluid remains
    around the heart -- this is expected to resolve over time. 3.
    Currently Sam has two main masses of cancer. The main one in his
    chest and a smaller one in his neck. They are greatly reduced since
    our arrival seven weeks ago. I need to get a copy of the results
    again so I can quantify the amount of reduction.

This is exciting -- the cancer is responding to treatment.

### Plans

It is exciting to see such progress. In moments of weakness it is also
terrifying. The remains a lot of work to be done these cancerous masses
are measurable in centimetres -- there are billions of cancerous cells
to be removed[^2].  

[^2]: *cell densities in human tissues are on the order of 1 billion to
    3 billion cells/ml*.\
    McClelland, Randall E., Robert Dennis,
    Lola M. Reid, Jan P. Stegemann, Bernard Palsson, and Jeffrey M.
    Macdonald. "Chapter 6 - Tissue Engineering." In Introduction to
    Biomedical Engineering (Third Edition), edited by John D. Enderle
    and Joseph D. Bronzino, 273--357. Boston: Academic Press, 2012.
    https://doi.org/10.1016/B978-0-12-374979-6.00006-X.
    
Despite the challenges, for the first time we actually have a plan! Until now, none of us have known what the plan would be.  Sam's cancer is extremely rare, and how it would respond to treatment was not known.  Now that we know the treatment is working.  We will move forward with a treatment regime.  The plan is to complete six rounds of chemotherapy with on-going evaluation to adapt the plan as needed. 

## Concerns and victories

-   We are thankful for positive results and that Sam is doing so well. 

-   We are thankful for a plan, though we need to gear ourselves for a marathon. We have heard it said around here numerous times that this cancer journey is both a roller-coaster and a marathon.

-   