---
title: "Out-patient life"
description: "Sam has made it through the valley of round 2 and remains living out-of-hospital."
author: Colin C.
date: 2023-06-24
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

![Tina and I got out on bikes to the neighborhood of
Kerrisdale.](https://samsstory.s3.ca-central-1.amazonaws.com/bike_kerrisdale.jpg)

Over a month ago one of our nurses told us that Sam would become an
out-patient. At the time it seemed impossible. We were in the middle of
round one, Sam was weak and sick, but it seems we have arrived at
out-patient status. This morning marks day 19 of this round of
chemotherapy -- Sam has made it through the chemo-valley without the
need of hospital time (his numbers are starting to recover). What a
difference!

It is really weird as it seems we stumbled our way into this out-patient
status. With the exception of four nights, when Sam received the
chemo-chemicals, he has been out of the hospital for this round. Sam has
had clinic appointments twice a week, and at each one we half-expected
that he may need to be admitted. We know now that, even with dropping
blood levels, if Sam keeps feeling good there was no need to return to
the hospital. Living on the hospital campus makes out-patient life
feasible as in the event Sam got sick (e.g. due to his chemo-compromised
immune) we would simply visit the ER here and follow the oncology
patient protocols.

## Looking back

The week as been a quiet one. Sam was in the valley where his blood
levels were lowest. Yet his time there was dramatically better then last
time. His energy levels were low and given that his immune system was at
its weakest point he hid out for much of the week. A few highlights from
this past week:

-   Playing cards with Minecraft with Sam

-   Slurpee-run therapy walks -- the local corner store is about six
    blocks away. Sam is getting closer to walking all of the way there.

-   A couple outings for Tina and I. Including a bike ride to
    Kerrisdale.

## Looking ahead

The week ahead will include:

-   Continued recovery from this last round of chemo

-   Tests to monitor the state of the cancer in Sam's body -- to confirm
    it is still being reduced and that we can continue without having to
    adjust the treatment regime.

## Concerns and victories

-   Thankful that it Sam has made it through the second round of chemo
    as an out-patient.

-   We are thankful for the Ronald McDonald House, all the generosity
    supporting it, and all the volunteers serving here. This place makes
    living through this journey ... almost feel like normal life.

-   Currently, one of our greatest challenges is that we have been away
    for over two months and it hard to stay connected with home. We miss
    you. We are thankful that Sam has been able to connect with friends
    on-line. We are thankful for visits and notes. However, despite
    these interactions, the nature of this cancer journey can feel
    isolating -- for all of us.

-   We are thankful that we are getting to know some families here.

-   We are thankful that Sam has made it through round two!

-   We are thankful that the treatment is working. There is also concern
    that it is effective to remove the cancer fully.