---
title: "Weekend Review"
description: "A simple weekend"
author: Colin C.
date: 2023-05-29
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---


I am writing this am simply to keep the updates coming.  Perhaps it is a good thing that there is little of significance to communicate as this past weekend was much of the same -- generally holding a pattern and continuing on with the chemotherapy -- now day 17 of 21. 

## Weekend highlights

-   Nana is here and has spent some good time with Sam.  I am especially thankful that Tina has had some great visits with her mom.

-   I got out for a couples hours to ride around the city. 

-   Sam has struggled with secondary illness -- basically he has a cold.  He started a different antibiotic and was starting to feel better by Sunday afternoon. 

## Concerns and victories 

-   Friends in PG did a major yard clean-up for us -- thank-you!

-   We are starting to see Sam's blood counts return to normal ... though his immune system has not recovered yet.

-   We are thankful that early indications are that the cancer is being removed from Sam's body.  Though we choose to hope and trust that he will see complete return to health, we will remain concerned that any cancer persists in his body. 

