---
title: "Chemo, friends, family, and mothers day"
description: "A full weekend with visits from Gram and Papa C, friends, mothers day, and chemotherapy."
author: Colin C.
date: 2023-05-15
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

![Sam and John B. Long time friends
reunited.](https://samsstory.s3.ca-central-1.amazonaws.com/2023-05-13_sam-john.jpg){fig-align="center"}

As I write this morning the morning sun lights the room sneaking past
the edges of the blind. I need this light to wake me as it has been a
weekend where sleep has been highly interrupted. My family is sleeping
peacefully. We are now starting day 4 of Sam's latest chemo treatment.
Over this past weekend Sam has had a lot of intense 'medicines' pushed
into him. I put this in quotes as if we weren't tackling cancer these
medicines would be considered poisons. Along with the medication has
been a lot of fluid -- resulting in the need to put a lot of fluid out.
Sam and I have been awake through the nights every 1-3 hours... I am so
glad to see him resting now.

## Friends and family visits

For a second weekend in a row were were able to visit with Friends from
Prince George as the Bandstras made a special trip. Sam and John had a
great time hanging out and playing games. Jess and Kate took Tina out
for Saturday afternoon. John (Sr) and I did a few errands. We also had a
family movie night, and managed to get in a couple rounds of
[Coup](https://boardgamegeek.com/boardgame/131357/coup) before they had
to make the return trip. So great to have some normal family fun.

My parents also had some good time, simply being with Sam, and giving
Tina and I some time to get away. I was able to get away to have dinner
with them the night before they left.

## Mothers day

I will try to sum this up for Tina but to be clear these are my thoughts
not hers. This mothers day was challenging and yet beautiful. The
challenge of course is where we are and why we are here. Some hours are
just simply hard as we are forced to look into the abyss -- to
contemplate the mortality of our precious boy. The day was also
beautiful. The charities supporting oncology families, and the Ronald
McDonald House, have showered Tina with presents; practical and
extravagant -- who doesn't like Purdy's. Tina and I were also able to
have a beautiful conversation where she heart-received the message that
she is a wonderful mother and that we would, together, continue to love
our boy through whatever challenges present themselves.

## Victories and concerns

-   Thankful for visits with friends and family

-   Thankful for a beautiful mothers day.

-   Concern for the current round of treatment. We are expecting side
    effects. Yesterday we started to see signs of them as Sam had his
    first mouth sore -- it is expected that his entire digestive system
    from mouth, all the way through, and out will become sensitive if
    not raw and just generally cause him to feel gross. Hair loss is
    also expected. It cn be described as descending into a valley of
    pain and then climbing back out.

-   Concern for potential longer lasting and high impact side effects.
    These can include damage to bodily organ or secondary cancers.

-   Ultimately, we are concerned that the treatment is effective and
    that the cancer is removed entirely from Sam's body.
