---
title: "Got some rest"
description: "Over the last 24 hours we have gotten some muchh needed rest."
author: Colin C.
date: 2023-05-20
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

![Vancouver in the morning. A view from from Queen Elizabeth Park during
my morning
ride.](https://samsstory.s3.ca-central-1.amazonaws.com/2023-05-20_van-from-qep.jpg)

This morning we are in the calm, my family is sleeping, and as usual I
am up with the sun. I am actually back at my chair following a morning
bikeride through Queen Elizabeth Park and the surrounding neighbourhood.
It was great to get some fresh morning air... from waht I understand
that is pretty hard to come by in much of BC and Alberta these days.

## Reflections on May 19

Actually, a calm day. Sam had some mild nausea in the morning and with
the assistance of some additional medication was able to get through it
and sleep much of the morning. There were the usual visits by the
medical team but these were not as frequent as the previous phases of
this chemotherapy run. Tina had spent the night at the Ronald McDonald
House and she was able to sleep in. I was not able to sleep in the
morning but after Tina arrived I had a solid nap.

## Concerns and victories

-   Thankful for rest, in the forms of sleep and activities that
    rejuvenate (e.g. bike ride for Colin)

-   Thankful for the medical team here that are taking great care of our
    boy.

-   Thankful that it is easy for us to stay with him

-   We are looking forward to seeing some friends this weekend.

-   We are ever-concerned that the chemotherapy will be effective
