---
title: "An update and a meditation: _Psalm 91_"
description: "Quick update on the process.  Psalm 91 has been passed on to us by several people."
author: Colin C.
date: 2023-05-27
categories: [daily, meditation]
draft: false
editor: 
  markdown: 
    wrap: 72
---

The Psalms are a great place to read and be inspired. The writers pour
out their hearts in song and prayer providing beautiful expressions from
the heart that can cover a broad range of emotion from pain and
frustration to hope and praise. Several people have given Psalm 91 to us
to read, meditate on, and pray through. I encourage you to read this
Psalm, and pray it for Sam!

## Therapy update

Before you do just a few quick points to update you on how his journey
is going and the next steps as we know them:

-   We are currently just past the halfway mark in round 2 of
    chemotherapy. The heavy chemical part of the treatment is over and
    now Sam's body has to work through the effects. Effects include
    (these are generally expected):
    -   collapse of the immune system: Sam's blood counts are monitored
        daily. Over the last number of days drops in the red and
        platelet cells have been managed with transfusions. We need to
        simply wait for the white cells to come back. It seems Sam may
        be through the worst of this part as cell counts are beginning
        to return on their own.

    -   sores in the GI system. Sam had some sores in his mouth earlier
        in this process. They have healed but he has other much further
        on in the system that are painful. These will heal in time.

    -   Most of Sam's time is spent in bed ... his body is doing a lot
        of work. The downside of being in bed this long is that he is
        stiff and sore; he has a lot of muscle tension and very little
        energy to stretch it out or move to loosen it up. We will get
        there but there is work to be done.

Next steps and current state of the cancer:

-   The truth is the next steps are very much unknown. The treatment
    plan will depend on how the cancer has responded to this latest
    round of therapy.

-   We are encouraged, Sam had an X-ray to rule out that the flu he had
    was not causing a pneumonia. This scan confirmed that he did not
    have pneumonia. What was unexpected, is that the scan also gave us a
    glimpse at the state of his cancer, and the doctors confirmed that
    the cancer-mass has shrunk.

-   Once this current therapy is complete on June 2^nd^ Sam will be
    booked for a scan. Once the results of the scan are known a new plan
    will be made.

## Meditation [Psalm 91](https://www.bible.com/bible/111/PSA.91.NIV)

Thank you for journeying with us. May this Psalm inspire your thoughts
and prayers:

> Whoever dwells in the shelter of the Most High
>
> will rest in the shadow of the Almighty.
>
> I will say of the [Lord]{.smallcaps}, "He is my refuge and my
> fortress,
>
> my God, in whom I trust."
>
> \
> Surely he will save you
>
> from the fowler's snare
>
> and from the deadly pestilence.
>
> He will cover you with his feathers,
>
> and under his wings you will find refuge;
>
> his faithfulness will be your shield and rampart.
>
> You will not fear the terror of night,
>
> nor the arrow that flies by day,
>
> nor the pestilence that stalks in the darkness,
>
> nor the plague that destroys at midday.
>
> A thousand may fall at your side,
>
> ten thousand at your right hand,
>
> but it will not come near you.
>
> You will only observe with your eyes
>
> and see the punishment of the wicked.
>
> \
> If you say, "The [Lord]{.smallcaps} is my refuge,"
>
> and you make the Most High your dwelling,
>
> no harm will overtake you,
>
> no disaster will come near your tent.
>
> For he will command his angels concerning you
>
> to guard you in all your ways;
>
> they will lift you up in their hands,
>
> so that you will not strike your foot against a stone.
>
> You will tread on the lion and the cobra;
>
> you will trample the great lion and the serpent.
>
> \
> "Because he loves me," says the [Lord]{.smallcaps}, "I will rescue
> him;
>
> I will protect him, for he acknowledges my name.
>
> He will call on me, and I will answer him;
>
> I will be with him in trouble,
>
> I will deliver him and honor him.
>
> With long life I will satisfy him
>
> and show him my salvation."
