---
title: "Diagnosis and the initiation of treatment"
description: "Yesterday was intense. Sam has an extremely rare cancer. Treatment of the disease has now started."  
author: Colin C.
date: 2023-04-27
draft: true
editor: 
  markdown: 
    wrap: 72
---

My morning has started with an encouraging time with my boy. I managed
to get some sleep over at the Ronald McDonald House and came back to
Sam's room for 5:00 (these days that is sleeping in for me). Shortly
after I got here Sam woke up. Despite the intensity of the previous day,
despite the pains in his body, he was full of faith and joy. He
celebrated that his PICC worked for the latest blood-work (currently
running at every four hours). We chatted for a bit, I rubbed his back,
wrapped him in a warm blanket, and then tucked him back in. Currently he
is sleeping soundly.

## Reflections on April 28

This date will be significant to use for the rest of our lives -- that
day we received a diagnosis and the initiation of treatment.

### Diagnosis and Treatment

In the morning the lead care team (Oncologist, Clinical Care Nurse, and
Social Worker) met with us -- the three of us to start, and then Tina
and I for the details. Finally we have a diagnosis, Sam's cancer has
been identified. We have been looking forward to this as a diagnosis
leads to a plan ... if you know what it is, you can know how to treat
it. We all wish it was that simple.

Sam has an extremely rare form of cancer. It is a blood-based cancer
mostly located in the lymphatic system. The name of the disease is
almost as long as the first two sentences in this paragraph. We know
what to call it, we know where it is, the team will treat it. However,
the treatment plan will be week-to-week, and as treatment phases are
completed, additional steps will be taken to evaluate the
response/impact on the disease.

Phase 1 of treatment has started, a round of chemotherapy, and we know
the plan for this week.

I have to add that Sam is a champ! Today's needle count tallied to 4
including the addition a new IV line.

### Surrounded by love

-   My Mom and Dad were here and were have to have a good time talking
    with Sam while Tina and I met with the medical team. I am glad they
    were here. It was good to share tears with them.

-   Rhoda and Dave, had a great conversation with Sam, and gifted him
    with comics and games

-   Tina had a great call with sister.

-   Many thanks to all of you for your notes of support, well-wishes,
    and prayers! Your words, stories, encouragement, and solidarity with
    us are amazing.

### Needs, concerns and victories

-   We are all walking in the dark. Our family and the Drs. Pray for
    wisdom to simply see the next step.

-   We need to see the cancer respond to the treatment. It is unknown,
    how this cancer will respond, or how it may adapt/ resist.

-   Chemotherapy, is intense, and some of the chemicals are literally
    poison. We have entered a world of trade-offs. The disease must die,
    but the treatment has dangers and significant potential
    side-effects.

We will count the small victories and joys

-   Sam took on numerous pokes/needles like a champ.

-   Sam's PICC worked ... most of the time.

-   Out of bed. Sam' has been sick and mostly bed-ridden. He enjoyed
    some time out of bed sitting up in a chair.

-   It was a puppy therapy day today. If you know Sam you know he loves
    dogs.

### Meditation

There are two passages of scripture that are constantly in my mind. Two
passages that reflect in-part where I am at.

> He guides me along the right paths for his name's sake. Even though I
> walk through the darkest valley, I will fear no evil, for you are with
> me; [Psalm 23](https://www.bible.com/bible/111/PSA.23.NIV)

> if you can do anything, take pity on us and help us." " 'If you
> can'?"said Jesus. "Everything is possible for one who believes."
> Immediately the boy's father exclaimed, "I do believe; help me
> overcome my unbelief!" [Mark
> 9:14f](https://www.bible.com/bible/111/MRK.9.NIV)
