---
title: "A good day, but a rough night..."
description: "We celebrate the little things but sometimes the little things go wrong."
author: Colin C.
date: 2023-05-01
draft: true
editor: 
  markdown: 
    wrap: 72
---

It is currently just after 7:00am here. Sam is currently sleeping
soundly, and I hope that Tina is having a good and lengthy sleep. Tina
took a turn to sleep at our room at the Ronald McDonald House -- her
first night away from Sam since coming to Vancouver. Honestly it was a
good night to miss... nothing major, just problems with the little
things.

## Reflections on April 30

Yesterday, was mostly quiet. Almost like we are entering into a routine.
Sam was full of energy to start the day, feeling better than he had for
months. We got out of the room, taking a tour of the ward, and checking
out the youth room where we discovered options for art, music, a library
of games (digital and board), movies, and video games. We made plans to
start a Harry Potter movie marathon.

Sam was hungry again and I biked down to Broadway to grab a pizza (a
great outing for me). It is weird, but life felt ... normal. Our normal,
now includes regular check-ins with nurses and doctors who are doing
their routines of checking vitals, taking blood, loading Sam's
supplemental feeding, adjusting oxygen... *this is normal? this is
routine?* Yes, it seems to be... and it was all going well until it
wasn't.

It is amazing how one tiny little thing can mess up your routine
Something jammed up Sam's NG-tube[^1]. Attempts to clear it resulted in
spillage and literally hours of frustration and extra work by the
nurses. Sam has been patient through most all of it, and lost some
significant time for sleeping... it is still not cleared.

[^1]: Nasogasteric feeding tube (i.e. through the nose to the gut)

<!-- What I did not talk about was all of the extra alarms: obstructed lines, -->
<!-- sensors alarming regarding heart rates, or O~2~ -->

## Needs, concerns, and victories

1.  We are thankful to see Sam feeling so much better. We hope that this
    means he is getting better, but we will not know until Sam has his
    next scan which is not for about a week.

2.  The little things matter in life -- for all of us. Even though the
    little things may be issues in a larger storm they have a strong
    influence on life. I am thankful for the little-graces. I am
    learning to not take them for granted. I also hope for little graces
    in this journey ahead.

3.  We are thankful for the medical team for all their hard work and
    care.

4.  We also cannot forget the larger issue. We are in a major storm of
    life. Sam has cancer. His prognosis is unknown. We choose hope, but
    that does not mean waves of fear to not threaten to swamp us. We hope and pray for his healing. That the cancer would respond to treatment.  That we would be able to go home together.
