---
title: "Another extension to our days of freedom!"
description: "Sam's bloodwork is holding! Additional bonus days away from the hospital!"
author: Colin C.
date: 2023-06-17
categories: [daily, outings]
draft: false
editor: 
  markdown: 
    wrap: 72
---

![Freedom!! We spent the evening exploring the Richmond Night
Market.](https://samsstory.s3.ca-central-1.amazonaws.com/richmond-night-market.jpg)

Wow!

It is currently sixty days since we started this journey, and day twelve
of the current/ 2^nd^ round of chemotherapy. Today is also marks 7 days
of not being in the hospital!

Dr. Cheng has told us a number of times that we need to remain flexible
on this journey as each round of chemo is different. There are different
sets of chemotherapy drugs in each round. With each round Sam is also
different. Starting this round Sam has had a amazing return of his
health as compared with the first. A few points to compare:

-   Sam's lungs and heart are clear of fluids
-   The cancerous mass has been reduced in size and density
-   Our boy has his appetite back
-   Sam is gaining his physical strength back

I thank God. I thank all of you for your care. I thank the medical team
for all their great work.

## The last couple days

Thursday, June 15

:   A relaxed day at the RMH. The simple and normal things of life:
    chores, meals, playing cards, strumming a guitar. Sam and I started
    playing crib again.

:   In the afternoon, Cal T. paid us a visit. We had a great talks and
    Sam had a new challenger for crib. Yes, Sam beat both Cal and I.

Friday, June 16

:   We had an appointment at the oncology-day-clinic. Checked Sam's
    blood levels, cleaning and dressing changes for Sam's central-line.
    The lab is fast -- blood levels were back levels are dropping, but
    again they are still above any levels of concern.

:   I clarified with the doctor, wondering if it was possible to skip
    the valley caused by chemotherapy. As I understand it:

    1.  The valley will come. Sam's immune system will collapse to zero
        (as indicated by the ANC[^1] metric). ... Yes, I have created a
        graph for this.
    2.  Be flexible, each round of chemo is different. Some rounds the
        valley is short. Some the valley is long. Be flexible, as it is
        not possible to know.

    In the afternoon, we had a great visits Chris and Jane, and David C.
    We all took Dave to the airport, and based on Hunter's
    recommendation from over a month ago we shared a meal at the
    Fairmont -- delicious!

    The evening was a shock. Tina and I were not ready for this. Sam,
    energized by a great meal was not done. As many of you know, Tina
    often starts to come alive as the sun gets low. So we were off to
    the \[Richmond Night Market\](https://richmondnightmarket.com). We
    spent over two hours exploring the booths. Sam loved it! Tina loved
    it!

    We are all stunned by how well Sam is doing!

[^1]: ANC: absolute neutrophil count, a measure indicative of the body's
    immune system. Measured via a blood test.
    [see](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/absolute-neutrophil-count)

## Concerns and victories

-   Thankful for regular days! I encourage you to do the same. Take joy
    in all the little moments. They may seem simple but they are times
    of grace.

-   Again! Celebrating and addition to our additional days of freedom.
    This days were a welcome surprise. I hope this can be part of the
    pattern going forward -- we will take each day as it comes.

-   Thankful for visits with friends and family.

-   Again, we are thankful that Sam is not feeling the effects of this
    chemotherapy round ... yet. The pending valley-of-gross seems to be
    getting smaller and smaller. Of course there is some concern as
    Sam's blood levels continue to drop. Some days in hospital are
    expected.

-   We are thankful that the treatment is working. There is also concern
    that it is effective to remove the cancer fully.
