---
title: "Anticipation of next steps"
description: "Short post anticipating our next steps and victories from the previous day"
author: Colin C.
date: 2023-05-05
draft: true
categories: [daily, procedures]
editor:
  markdown:
    wrap: 72
---

This morning's run of pills will mark the end of Sam's first round of chemotherapy.  At 9:30 Sam is scheduled for a CT scan and we will wait in anticipation for the results, as the scan will help inform our next steps including: 1) the need (or not) of a new central line for drug delivery, and 2) response of the cancer so far and a strategy moving forward.

## Reflection on May 4

Sam was full of energy and he was determined to show the physiotherapist all that he could do.  We went for a couple of walks including getting off the floor and getting outside. Sam was also able to be disconnected from his IV and we are all loving the freedom that comes with that.

## Concerns and victories

-   CT scan today, the information will be used to determine next steps.

-   Sam is mobile and regaining strength.  So great to have a break from IV line.

-   Concern that the cancer responds well to the treatment and wisdom for the next steps.
