---
title: "Well managed days"
description: "Learning to manage side effects."
author: Colin C.
date: 2023-05-19
categories: [daily]
draft: true
editor: 
  markdown: 
    wrap: 72
---

It is nice to provide a quick, low-intensity post. To all reading, thank
you again for journeying with us.

I wonder if I ever read this again what my experience will be. I expect,
that it will be an emotional roller coaster and perhaps this is your
experience reading along. This last month has been the most intense of
our lives, some days are just plain difficult and painful, others are
quiet as we wait for next steps, new phases of experience. In all the
days I think I live in a constant state of vigilance, my guard is always
up, until something knocks me over. Yesterday, was a quiet day, a day of
calm in this storm. My hope is that today will be as well.

## Reflections on May 18

Learning lessons from the day before the current medication plan for Sam
is working. He has not had anymore nausea, and when he has some pain
(e.g. muscle ache, headaches) we are on it quickly and medicines are
quickly made available. All-in-all, it was a quiet day. We played some
video games, got down the hall for a walk, and played a board game.

## Concerns and victories

-   Rest: we all need it. Last night was far better than the previous
    days as fluids are not being pushed on Sam. We still need to find
    more rest.

-   Side effects: we have have learned some lessons and are managing
    current side effects well-enough. Other side effects are expected. I
    expect that Sam's mouth will be more sensitive as sores develop,
    these sores could extend all they way through his digestive track.
    Chemo-balding is also expected.

-   Potential for secondary infection: One of the effects of the
    chemotherapy is a reduction in Sam's blood counts. The medical team
    can manage reductions in red cells and platelets, but they cannot
    manage reduced white cell counts. As such, Sam will be more
    susceptible to colds, flus, or whatever is floating around. We will
    likely move to a mask-up and wash-up protocol before entering the
    room.

-   Ultimately, that this intense treatment is effective at removing the
    cancer from Sam's body.
