---
title: Post Biopsies
description: Yesterday was a big day for Sam. He had the surgery to complete a series of biopsies. These included the removal of a lymph node at the base of his neck, a lumbar puncture, a bone marrow sample from the top of his hip, and
date: 2023-04-21
author: Colin C.
draft: false

---

### TLDR (short version)

Yesterday: surgery for tissue samples followed by pain management. In the weeks to come, Sam will be here at BC Children Hospital as he is treated for what is assumed to be lymphoma.

\--

### Full version

Hi all,

Yesterday was a big day for Sam. He had the surgery to complete a series of biopsies. These included the removal of a lymph node at the base of his neck, a lumbar puncture, a bone marrow sample from the top of his hip, and establishing a PICC ([described here](http://www.cw.bc.ca/library/pdf/pamphlets/BCCH1552_PICC.pdf)) to facilitate ongoing blood work and upcoming intravenous drug delivery. All the procedures went well. Dr. Webber, completed the lymph node removal and said it went "Perfectly". This was all done before noon. The biggest challenge of the day has been pain management, but Sam has been a trooper.

The staff here continue to be amazing, always taking the time to answer any of Sam's questions, and making complex biology and bio-chemistry understandable. It is honestly amazing to hear Sam explain his disease to others -- he gets it, understands it, and given the situation is very glad to be here.

Next steps are not totally clear. We are working with the understanding/assumption that Sam ~~has lymphoma ([one possibility described here](http://www.bcchildrens.ca/Oncology-Site/Documents/Non-Hodgkin%20Lymphoma.pdf))~~ _As of April 23, we still do not know what type of cancer this is_. The signs all point that way (e.g. X-ray and CT scan), but this will not be totally confirmed until the tissue samples are processed. Here is what we are currently expecting:

1.  Sam will start a round of drug treatment, as soon as later today, and specific treatments will be refined following the analysis of his tissue samples
2.  Sam is currently in the ICU, and we expect him to be here for the next number of days after which, he will be transferred to the oncology unit just a few floors above where he will remain a patient for three weeks or so (timing of stay will all depend on tests).
3.  Tina and I will be able to check into the Ronald McDonald House here on hospital campus on Sunday. This will give us a home base, we will also be able to continue staying in the room with Sam.

Many thanks to all of Sam's friends and teachers, and all of our friends and family. We love to hear from you. We may not get back to you right away but know your messages are encouraging to us. If you have any questions, please feel free to ask, and I will try to answer them either directly or in a following update.

### Q&A

How is Tina doing?

:   She is actually great. She has been working so hard advocating for Sam's health over the last months, trying to get the bottom of why he has been sick. Now, she can relax as Sam is where he needs to be, receiving the medical care that he needs. She also loves the medical world, she is in her element here. Our biggest challenge for Tina will be to ensure she is properly fed, especially given her dietary restrictions. We will need to find a new normal here.

How can we help / Let us know if we can help.

:   Hearing from you is currently the best. As noted, we might not be able to get back to you right away, but all of your notes are encouraging. Tina and I have literally had tears-of-joy reading them.

Thanks again for your prayers and support,

Colin and Tina
