---
title: "What does a round of chemo look like? An overview"
description: "Review of what we expect most rounds of chemotherapy to look like. A bried recap of our last couple days."
author: Colin C.
date: 2023-06-09
categories: [daily, info]
draft: false
editor: 
  markdown: 
    wrap: 72
---

We are back at BC Children's Hospital, once again receiving the amazing
care that this place provides. Sam has just started his second round of
chemotherapy. Today I thought I would provide a brief sketch of what
Sam's chemotherapy looks like -- there is no one method for
chemotherapy, rather plans are tailored to each circumstance. As such,
though there may be some similarities with other chemotherapies this is
Sam's -- and really it is the only one that I can speak to.

Considering chemotherapy in days and weeks:

-   A round of chemotherapy is 21 days long.
-   The first five days are intensly chemical. Numerous does of various
    chemotherapy specific drugs, along with drugs to help Sam not feel
    sick from receiving the prior are delivered. These days Sam is
    attached to the IV pole and has anywhere from 2-5 lines delivering
    chemical treatment to him via his central line (Hickman CVC[^1]).
-   The following \~10 days are the valley, the chemicals take effect
    and life gets gross. Chemotherapy is intense. It hammers actively
    growing cells, in hammers your immune system. The benefit is that it
    hammers the caner the hardest. Over this time:
    -   Blood counts will drop and there may be need for transfusions.
    -   Sam's immune system will be entirely wiped out leaving him with
        no defences and secondary infections are a risk.
    -   In addition, he will likely experience some level of mucositis
        where sores can develop in the mouth and possibly anywhere in
        the GI[^2] system.
    -   Drugs during this phase are generally for pain and nausea
        control with additional drugs, as needed, for secondary
        infection management.
-   The final days of the treatment are when we expect to see Sam's body
    recover from treatment with a return to normal blood counts and life
    starts to feel better again.

[^1]: Central venous catheter

[^2]: gastrointestinal

Following a round of chemotherapy Sam, well all of us, will get a few
days of a break ... before starting this pattern all over again.

This is written on day 4 of 21. In the 2^nd^ round of treatment -- a day
or two before we start into the valley.

## Reflections on June 7 and 8

The 7^th^ was our first full day back at the hospital and day 2 of this
round chemotherapy. There were many visits by the various members of the
medical team -- making it feel like a day of interruptions, but this is
the work of getting well. 

Nurses trained me how to change Sam's dressing
-- a clear bandage protecting his central line. Even now, when home
seems so far away, they are preparing us to be there. Maybe it is weird
but I enjoyed this -- taking on a new challenge and also caring for my
boy.

V., Sam's physiotherapist, is thrilled with how improved he is, and the
strength that he is regaining. She has provided additional tools to keep
him moving -- a stationary bike, and the next day some resistance bands
and weights.

The next morning was more routine filled with various drug deliveries
and fluids testing. In the afternoon: Tina and I got away, stocked her
up on food that she can eat, after we returned, we had a good visit with
Cal and Tricia.

## Concerns and victories

-   Thankful for the team here at BC Childrens's Hospital. For their
    expertise, the hard work that they do, and also the personal care
    they invest.

-   Thankful for the care of friends and family. Many thanks to for
    encouraging notes received through this site, email, and FaceBook.\
    *Note: if you ever feel that you do not want to bother us -- please
    ignore that feeling and send us a note. Hearing from you is always
    encouraging.*

-   Concern, that Sam seems to be losing weight, despite eating well. We
    may have to supplement his diet sooner than we had hoped (i.e. a new
    NG tube)

-   Concern as we head into the valley and life for Sam will feel gross
    (mucositis/GI sores, nausea...).

-   Concern that the cancer will be fully removed and that it will
    continue to respond to the treatment.
