---
title: "Assembling at the chemotherapy starting line (round 2)"
description: "Today round two of chemotherapy should start "
author: Colin C.
date: 2023-05-12
categories: [daily, procedures, milestones]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Today our waiting period should be ending. We will have a few last hours
of anticipation before Sam heads down to surgery for a third attempt to
establish a central line. Assuming all goes as planned he will begin
round two of chemotherapy. This next round is likely what we all think
about when it comes to chemotherapy as the medicines used are so intense
that Sam will likely lose his hair. The full therapy session is 21 days,
with the first five being the medicinal treatment and the following 16
being for recovery. We are expecting by mid-next week Sam might be
feeling pretty rough.

## Reflections on May 10

Yesterday was fairly calm with the usual visits by doctors and nurses.
Gram and Papa were here and their presence allowed Tina and I to get
away. I even had a couple hours on my own. My brother-in-law has lent me
his electric bike and I went exploring the great network of bike lanes
through numerous neighbourhoods across Vancouver (17km ride). This trip
included some stops to pick up essential supplies including a stop at a
gluten-free bakery for Tina.

The level of care continues to be amazing. Sam had a headache in the
afternoon and given that the he does have some blood clots the doctors
have reason to monitor this as a concern and ordered an MRI which he
received hours later. Sam definitely has his humor back stating to the
doctor that *we will set your mind at ease by looking at my mind*.

As a family we had a relaxing evening. We walked out to the deck where
Sam and I played a [hive
pocket](https://boardgamegeek.com/boardgame/154597/hive-pocket). Sam
destroyed me the first time we played but I managed a win yesterday --
though my brain hurt. A solid strategy game that does not take that long
to play.

## Concerns and victories

-   Sam goes into surgery in the late morning -- scheduled for 11:30.
    This line will be inserted in the leg and travel up to the inferior
    vena cava -- just below the heart. In addition, instead of having
    the lines dangling from his leg the surgeon wants to create an
    outlet in Sam's abdomen, above the belt-line, which will allow him
    to remain mobile.

-   Chemotherapy should begin this afternoon. This brings with it a
    couple main concerns.

    -   That this treatment is effective a removing cancer from Sam's
        body
    -   There are common side effects such as hair loss, temporary
        impacts on Sam's immune system, generally feeling gross, and the
        potential for others. We don't expect anything symptoms of these
        in the next 24-48 hours but they will come.

-   We are thankful for all of the support we have received, your care
    and prayers, messages, visits, and gifts. We are blessed to have
    such a community around us.

## Meditation

> He gives strength to the weary\
> and increases the power of the weak.\
> Even youths grow tired and weary,\
> and young men stumble and fall;\
> but those who hope in the Lord[^1]\
> will renew their strength.\
> They will soar on wings like eagles;\
> they will run and not grow weary,\
> they will walk and not be faint.
>
> Isaiah. 40 v. 29-31 NIV translation

[^1]: alternately: those who wait on the Lord (ESV)
