---
title: "Have Mercy on Me"
description: "Bartimeaus calls out, through the crowd, to Jesus."
author: Colin C.
date: 2023-12-17
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 46 - 52](https://www.bible.com/bible/111/MRK.10.NIV)

> Then they came to Jericho. As Jesus and his disciples, together with a large crowd, were leaving the city, a blind man, Bartimaeus (which means “son of Timaeus”), was sitting by the roadside begging. When he heard that it was Jesus of Nazareth, he began to shout, “Jesus, Son of David, have mercy on me!”\
> Many rebuked him and told him to be quiet, but he shouted all the more, “Son of David, have mercy on me!”\
> Jesus stopped and said, “Call him.”\
> So they called to the blind man, “Cheer up! On your feet! He’s calling you.” Throwing his cloak aside, he jumped to his feet and came to Jesus.\
> “What do you want me to do for you?” Jesus asked him.\
> The blind man said, “Rabbi, I want to see.”\
> “Go,” said Jesus, “your faith has healed you.” Immediately he received his sight and followed Jesus along the road.


### Thoughts and questions 

I think what can be missed as we read this story is the momentum that Jesus' ministry is having.  People are following him.  He is surrounded by crowds.  The people all want to hear what he as to say.  I can imagine Jesus walking and talking and in the background, beyond all the voices, a call for "help!, have mercy on me".  The people are annoyed by this.  They want to hear Jesus -- they don't need some poor blind man wrecking their experience.  But Jesus, changes the focus and shows mercy to Bartimaeus -- his faith has healed him.  I also love how Bartimeaus immediately starts to follow!  


### Prayer

Jesus, may the poor and the needy never be an inconvenience to me.  Let my heart be soft to bring care and mercy to those that need you.  Stengthen your church so that we act to show your mercy and that people would choose to follow having received your mercy and grace.  