---
title: "The little children"
description: "Jesus blesses the little children"
author: Colin C.
date: 2023-10-31
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 13 - 16](https://www.bible.com/bible/111/MRK.10.NIV)

> People were bringing little children to Jesus for him to place his hands on them, but the disciples rebuked them. When Jesus saw this, he was indignant. He said to them, “Let the little children come to me, and do not hinder them, for the kingdom of God belongs to such as these. Truly I tell you, anyone who will not receive the kingdom of God like a little child will never enter it.” And he took the children in his arms, placed his hands on them and blessed them.

### Thoughts and questions 

What do you think it means to come to Jesus as a little child? 

Some ideas: 

-  Trusting 
-  Fearless -- not worried that Jesus will hurt them
-  Curious 
-  Not trying to get something out of the relationship (e.g. profit, networking)
-  Coming with joy
-  Children don't come with conditions.  


### Prayer

Lord, thank you that you love the little children.  Help me to come to you that way.  Trusting and ready to receive your love and care.  

You know my pains, my worries, my struggles.  Help me. As a child says a simple help me to their parents, I ask you to help me, knowing that you understand what I need. 

