---
title: "Upside-down Kingdom"
description: "Jesus' kingdom is upside down, where the leaders serve and sacrifice."
author: Colin C.
date: 2023-12-05
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 35 - 45](https://www.bible.com/bible/111/MRK.10.NIV)

> Then James and John, the sons of Zebedee, came to him. “Teacher,” they said, “we want you to do for us whatever we ask.”\
“What do you want me to do for you?”he asked.\
They replied, “Let one of us sit at your right and the other at your left in your glory.”\
“You don’t know what you are asking,”Jesus said. “Can you drink the cup I drink or be baptized with the baptism I am baptized with?”\
“We can,” they answered.\
Jesus said to them, “You will drink the cup I drink and be baptized with the baptism I am baptized with,but to sit at my right or left is not for me to grant. These places belong to those for whom they have been prepared.”\
When the ten heard about this, they became indignant with James and John. Jesus called them together and said, “You know that those who are regarded as rulers of the Gentiles lord it over them, and their high officials exercise authority over them. Not so with you. Instead, whoever wants to become great among you must be your servant, and whoever wants to be first must be slave of all. For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.”


### Thoughts and questions 

James and John make such a bold request.  I don't think the text is clear around whether they understood their request entirely.  What I do know is that Jesus used the request to teach a key principle about his vision of leadership and authority.  

Jesus vision of leadership and authority is inverse to the world around us.  And being that it is Jesus' vision of leadership and authority it is the eternally true way that authority will be -- not the broken way that we have it.  In Jesus' vision the rich will not get rich off the backs of the poor, those in power will not subjugate the people.  No, those in authority will serve, and their riches will be measured in how they have given not how they have received.  


### Prayer

Jesus, it is amazing to me that for you to be _Lord_ of my life that it does not mean that your will dominates me.  Thank-you, that you call me to live by your example.  Help me to serve as you served.  To love as you loved.  Guard me Lord, especially should I be given responsibility or authority, that I would use it well and care, love, and serve those that I am responsible for.  