---
title: "He knew the plan"
description: "Jesus approached Jerusalem with confidence, knowing the plan would lead to his execution."
author: Colin C.
date: 2023-12-01
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 32 - 34](https://www.bible.com/bible/111/MRK.10.NIV)

> They were on their way up to Jerusalem, with Jesus leading the way, and the disciples were astonished, while those who followed were afraid. Again he took the Twelve aside and told them what was going to happen to him. “We are going up to Jerusalem,” he said, “and the Son of Man will be delivered over to the chief priests and the teachers of the law. They will condemn him to death and will hand him over to the Gentiles, who will mock him and spit on him, flog him and kill him. Three days later he will rise.”

### Thoughts and questions 

I am almost always struck by this passage, and fact that Jesus knew exactly what was going to happen.  Yet, he approaches his death with confidence -- he knows what lies ahead and that there is an eternal purpose to it.  This will be the culmination of God's redemptive plan for humanity.  Jesus knew his purpose.  Do we know ours?  What are we called to?  Generally, to follow in his footsteps, to do the things that he would do, to love people the way that he did, to bring hope and freedom to people.  

What about specifically?  In my experience, I have had periods where I have felt a specific purpose.  While other times I have not.  ... I wonder, if Jesus, in his humanity, had this too.  Definitely, he had a clear purpose in this passage, but was that always the case?  From his example, we know that he he spent time with God regularly, and in that discipline I would suggest knowing God's will for our lives can become clear. 


### Prayer

Lord, that you that you are courageous.  That you approached your purpose with obedience and that you accomplished it!  Thank you for the redemption, hope, and freedom that you have brought to the world.  Help me in my life to reflect your ways.  To reflect your love.  To demonstrate your ways to the people around me.  