---
title: "Nothing is impossible for God"
description: "How much of you does God want?"
author: Colin C.
date: 2023-11-04
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 17 - 31](https://www.bible.com/bible/111/MRK.10.NIV)

> As Jesus started on his way, a man ran up to him and fell on his knees before him. “Good teacher,” he asked, “what must I do to inherit eternal life?”\
> “Why do you call me good?” Jesus answered. “No one is good—except God alone.19You know the commandments: ‘You shall not murder, you shall not commit adultery, you shall not steal, you shall not give false testimony, you shall not defraud, honor your father and mother.’”\
> “Teacher,” he declared, “all these I have kept since I was a boy.”\
> Jesus looked at him and loved him. “One thing you lack,”he said. “Go, sell everything you have and give to the poor, and you will have treasure in heaven. Then come, follow me.”\
> At this the man’s face fell. He went away sad, because he had great wealth.\
> Jesus looked around and said to his disciples, “How hard it is for the rich to enter the kingdom of God!”\
> The disciples were amazed at his words. But Jesus said again, “Children, how hard it is to enter the kingdom of God! It is easier for a camel to go through the eye of a needle than for someone who is rich to enter the kingdom of God.”\
> The disciples were even more amazed, and said to each other, “Who then can be saved?”\
> Jesus looked at them and said, “With man this is impossible, but not with God; all things are possible with God.”\
> Then Peter spoke up, “We have left everything to follow you!”\
> “Truly I tell you,”Jesus replied, “no one who has left home or brothers or sisters or mother or father or children or fields for me and the gospel will fail to receive a hundred times as much in this present age: homes, brothers, sisters, mothers, children and fields—along with persecutions—and in the age to come eternal life. But many who are first will be last, and the last first.”

### Thoughts and questions 

When I read this passage today I was struck by this question: _How much of you does God want?_

I think the answer is pretty clear:  God wants all of you!


Sure saying this answer is easy enough.  But how hard is it to do.  It was not enough that the man in this passage had upheld all of the rest of the law (hard to do!).  He also had to sell everything he owned before coming to Jesus.  Why?  

I think because wealth was a priority in his life.  That his wealth would stand between him and Jesus.  But Jesus want full devotion -- he is not about a half-way lifestyle.  He wants all of us.  It this man was truly ready to follow Jesus -- he would have gladly sold his possessions.  


Thoughts on the _camel and the eye of the needle_

:  I have heard various interpretations on this. One that Jesus is talking about a real needle, the other interpretation being that Jesus was referring to a Gate into the city of Jerusalem that was named the eye of the needle because it was small and camels would not go through.  So we have Jesus using hyperbole or alternately pointing at something that was well known in the region.

:  I don't think it actually matters.  I think it rather that camels are stubborn animals... much like people.  Are we willing to take direction -- we do not to go or do things that don't appeal to us.  In the same way it is very difficult to let go of wealth -- which can bring worldly comfort.  


### Prayer

Lord, show me how I am being camel.  Give me the strength to change; the will to do always put you first; to choose your ways instead of my comforts.  

Lord, what do I need to give up to follow you and be your disciple?  Teach me your ways. 

