---
title: "Faithful marriage"
description: "Therefore what God has joined together, let no one separate."
author: Colin C.
date: 2023-10-25
search: false
categories: [Mark, teaching]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 10: 1 - 12](https://www.bible.com/bible/111/MRK.10.NIV)

> Jesus then left that place and went into the region of Judea and across the Jordan. Again crowds of people came to him, and as was his custom, he taught them.\
> Some Pharisees came and tested him by asking, “Is it lawful for a man to divorce his wife?”\
> “What did Moses command you?”he replied.\
> They said, “Moses permitted a man to write a certificate of divorce and send her away.”
> “It was because your hearts were hard that Moses wrote you this law,”Jesus replied. “But at the beginning of creation God ‘made them male and female.’ ‘For this reason a man will leave his father and mother and be united to his wife, 8and the two will become one flesh.’ So they are no longer two, but one flesh. Therefore what God has joined together, let no one separate.”\
> When they were in the house again, the disciples asked Jesus about this. He answered, “Anyone who divorces his wife and marries another woman commits adultery against her. And if she divorces her husband and marries another man, she commits adultery.”

### Thoughts and questions 

I love Jesus simplifies the issue of marriage and divorce.  Divorce is so common in the world, and no less common among people in the church.  

Are there time when divorce could be the right thing?  Some people are abused by their spouse (e.g. physically attacked).  This is not treating your spouse in a loving manner.  Perhaps this would be a reason.  But it is definitely not the intent that God gave his creation. 

But Jesus boils it down to the original intent: 

_Therefore what God has joined together, let no one separate._

He also clarifies that to marry another is adultery.  From what I understand the religious leaders of the day were fine with people obeying the letter and divorce became easy -- just provide a certificate and send your spouse away.  This legalistic mechanism made it far to easy to simple divorce one's wife and marry another -- Jesus highlights that this is simply justifying adultery. 

### Prayer

Lord, may my heart always be faithful to choose love and cherish my wife.  Guard my mind and thoughts that I would always build up my marriage and never tear it down.  Let no one separate the marriage that you bless me with.  

