---
title: "Round 2 complete and some family fun"
description: "Round 2 is officially complete.  Some family fun over the last few days."
author: Colin C.
date: 2023-06-28
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

Chemo round 2 officially ended on the weekend and it has felt like a
great success. Aside from 4 nights during the initial chemical delivery
days and several clinic days, Sam spent the remainder of the time out of hospital. The
majority of the days have been within the hospital campus, and over the last week
we were able to spread our wings a little further as Sam's immune system
strengthened.

Though the lived experience of this round felt better, tests this week
will determine what the unseen impacts were on the cancer. Sam will have
a lumbar puncture and a PET scan over the next few days.

Next week Sam will return for some hospital days to begin round 3 of chemotherapy which, given
it's chemical makeup, may be harder on him then this last round.

## Highlights from the past few days

This past weekend we have had good time as a family and with the
extended family.

-   We were able to celebrate little Jayme's birthday. Though Auntie
    Tricia and Uncle Cal also took the chance to spoil our boy --
    providing him a huge steak, which he enjoyed immensely.

-   Uncle Kevin started his new position in Delta and so we have been
    able to connect with them more. We spent an afternoon with Kevin and
    Kaden at Granville Island. Over the last few years Sam, Tina and I
    have made it there a number of times and have our favourite spots
    for snacks.

-   What do you do if your immune system is low and you want to go to
    the movies. The drive-in is a great option. The three of us had a
    great night taking in a double header ... though we paid for it the
    following day.

## Concerns and victories

-   Thankful that Sam has completed his second round of chemo
    as an out-patient.

-   Thankful that we have family in the area.

-   We are thankful that we are getting to know some families here.

-   Round 3 starts next week.  It has a different drug delivery regime then the last round and impacts will likely it will feel stronger.K

-   We are thankful that the treatment is working. There is also concern
    that it is effective to remove the cancer fully.