---
title: "A second weekend at the RMH"
description: "Our second weekend in a row -- away from the hospital.  Visits with Gram and Papa C. "
author: Colin C.
date: 2023-06-19
categories: [daily]
draft: false
editor: 
  markdown: 
    wrap: 72
---

I am not writing as often as, simply, there is not as much to say. Our
days are normal*ish* -- a good thing! Currently, we are not trying to understand what is
happening, or what is next. It is good to have the stress level come
down and have some time for mental recovery.

## The last couple days

This weekend has been at the Ronald McDonald House (RMH) -- our home
away from home. On Saturday my parents got into town. It has been great
to share meals and visit with them. A few quick highlights:

-   Card games. Including Sam's ongoing winning streak in crib. ... I
    will attempt to humble him, if I can, in the week ahead.
-   A walk and ice cream. We continue to be encouraged with how Sam's
    strength is returning.\
-   A coffee date with Tina while Sam visited with his grandparents.
-   Father's Day BBQ hosted by the RMH.

## Upcoming

Tomorrow, June 20, we will have a fourth clinic appointment to evaluate
how Sam's blood-levels are doing and if his immune system is holding. 

## Concerns and victories

-   Thankful for normal*ish* days.

-   Thankful for time with my parents.

-   Again, we are thankful that Sam is not feeling the effects of this
    chemotherapy round. The pending valley-of-gross appears to be
    getting smaller and smaller. Of course there is some concern as
    Sam's blood levels continue to drop. Some days in hospital are still
    expected.

-   We are thankful that the treatment is working. There is also concern
    that it is effective to remove the cancer fully.