---
title: "Mocked and Abused"
description: "Roman soldiers take custody of Jesus and spend time mocking him"
author: Colin C.
date: 2024-02-22
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 15: 16 - 20](https://www.bible.com/bible/111/MRK.15.NIV)

> The soldiers led Jesus away into the palace (that is, the Praetorium) and called together the whole company of soldiers. They put a purple robe on him, then twisted together a crown of thorns and set it on him. And they began to call out to him, “Hail, king of the Jews!” Again and again they struck him on the head with a staff and spit on him. Falling on their knees, they paid homage to him. And when they had mocked him, they took off the purple robe and put his own clothes on him. Then they led him out to crucify him.


### Thoughts and questions 

He we have the Messiah,  King of Heaven and Earth, the Son of God mocked and abused.  Jesus' execution/ death has been ordered, but going to his destined death was not easy -- it was full of pain and suffering.  

I have to wonder, from the soldier's perspective, did they even regard Jesus as human?  Perhaps, from the Roman soldiers' perspective, here was an opportunity to lash out at the entire Jewish people to hurl insult at them all.  For they had the Jewish king, crowning him with thorns, and they could beat him, humiliate him, and pour their hate on him.

What Jesus had to endure as he made his way to the cross:

-   _Mental anguish of anticipation_, in the Garden of Gethsemane 
-   _Betrayal_ by Judas
-   _Abandonment_ by his followers 
-   _Injustice_ from Jewish and Roman authorities.  Authorities who's role it was to administer justice.
-   _Mockery and abuse_ from the Roman soldiers 
-   ... and we are not done...




### Prayer

Lord Jesus, how you suffered. \
How your mind and body were racked with pain and abuse.

Forgive me Lord.\  
Forgive me when my heart or my words, hurl hurt.\
Forgive me Lord

Jesus help me to see those in anguish and bring them relief.\
Lord soften my heart to tenderly give compassion to those who have been betrayed and abandoned, may my actions help them know they are not alone. 

Strengthen me to stand in the face of injustice. \ 
Empower me to take a stand against injustices being committed against others -- especially those with no strength to stand.  

Forgive me Lord Jesus and grant me the grace to forgive those who have hurt me.


<!-- 
Lord my heart is broken.  I am torn to shreds.  
Fear has its grip on me.  Despair threatens to consume me.  

I am to take comfort in knowing that you also had a broken heart.  
I am to believe that your heart breaks even now for all of the pains, sufferings, and injustices in this world?  

Let me see your heart.  Comfort me for I am broken hearted. 

How can I live? How can I live when my son travels towards death? 
How shall I live?  How can I comfort him?   -->