---
title: "Jesus died"
description: "Pilate confirms Jesus' death before releasing his body."
author: Colin C.
date: 2024-02-27
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 15: 42 - 47](https://www.bible.com/bible/111/MRK.15.NIV)

>  It was Preparation Day (that is, the day before the Sabbath). So as evening approached, Joseph of Arimathea, a prominent member of the Council, who was himself waiting for the kingdom of God, went boldly to Pilate and asked for Jesus’ body. Pilate was surprised to hear that he was already dead. Summoning the centurion, he asked him if Jesus had already died. When he learned from the centurion that it was so, he gave the body to Joseph. So Joseph bought some linen cloth, took down the body, wrapped it in the linen, and placed it in a tomb cut out of rock. Then he rolled a stone against the entrance of the tomb. Mary Magdalene and Mary the mother of Joseph saw where he was laid.


### Thoughts and questions 

It is interesting that Pilate was surprised that Jesus had died already.  Pilate obviously thought it unusual that Jesus had dies already. As I understand it, it takes a long time for a person to succumb to crucifixion (i.e. they can no longer resist death).  This lines up well with our previous passage when Jesus gave a great yell and then died.  Instead of succumbing to death as breathing becomes more and more difficult it seems Jesus chose the moment of his death.  Instead of death quietly taking him he gave his war-cry to say _I am coming for you (Death)_! 

It is also interesting that this had to go all the way to Pilate.  Why wouldn't the executioners just give Joseph the body? What would it matter?  It mattered because this was a high profile case.  There could not be any mistakes here.  Pilate had to have confirmation that Jesus was actually dead before releasing the body.  

This part of the story is important -- it tells us that Jesus did die.  It was over and his body was buried. Of course, from our viewpoint in history we know that it was not over.   

### Prayer

Lord Jesus, Wow! 

You did it!  I can't help but wonder what it was like to be dead.  Were you a taking on battles in unseen realms?  Or were you held in death until your appointed time when you burst forth. 

Death could not defeat you.  Death could not hold you.  

I hold to the promise that you have also defeated death for me.  I do not want to die -- I want to live and do your works.  Yet when my time to die comes, I know you have a place for me and will raise me up to life eternal. 

Let your will be done. \
Let your kingdom come. 