---
title: "Jesus' Death-cry"
description: "Jesus does not simply pass away quietly. His death is marked in the sky and temple."
author: Colin C.
date: 2024-02-26
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 15: 21 - 32](https://www.bible.com/bible/111/MRK.15.NIV)

>  At noon, darkness came over the whole land until three in the afternoon. And at three in the afternoon Jesus cried out in a loud voice, “_Eloi, Eloi, lema sabachthani?_”(which means “My God, my God, why have you forsaken me?”).
>
> When some of those standing near heard this, they said, “Listen, he’s calling Elijah.”
>
> Someone ran, filled a sponge with wine vinegar, put it on a staff, and offered it to Jesus to drink. “Now leave him alone. Let’s see if Elijah comes to take him down,” he said.
>
> With a loud cry, Jesus breathed his last.
>
> The curtain of the temple was torn in two from top to bottom. And when the centurion, who stood there in front of Jesus, saw how he died, he said, “Surely this man was the Son of God!”
>
> Some women were watching from a distance. Among them were Mary Magdalene, Mary the mother of James the younger and of Joseph, and Salome. In Galilee these women had followed him and cared for his needs. Many other women who had come up with him to Jerusalem were also there.


### Thoughts and questions 

When Jesus died the world was changed.  His death was not peaceful.  He cries out to God, with apparently no response -- perhaps feeling abandoned by God himself.  

He expels a loud cry that seems to echo beyond the physical realm.  Could this be a war-cry against death itself (my thought ... I have not ever heard that idea).  I like this idea of a supernatural war-cry -- one that would shake the heavens.  To support this idea, the sky goes dark (in the middle of the day), and the curtain in the temple is torn from top to bottom.  

The temple curtain being torn in has strong implications.  This curtain was massive and would not rip on its own as it was woven, 80 feet high, and 4 inches think.  More significant than its impressive size is what it guarded.  This curtain guarded the Holy-of-Holies.  As per the Old Testament laws only the Jewish High Priest could go behind the curtain once per year to atone for the sins of the people ([Leviticus 16](https://www.bible.com/bible/111/LEV.16.NIV)).  Jesus' death marks the rending of this curtain -- by his death and sacrifice he atoned for our sins and made the way open to God.  We can approach God because of Jesus (see [Heb. 4: 14 - 16](https://www.bible.com/bible/111/HEB.4.NIV)).




### Prayer

Lord Jesus, thank you that by your sacrifice:

Death is defeated\
But greater still -- we can approach God!  

Your love for us has saved us from eternal death

Thank you that, because of you, we can be called children of God. 

Call all your children -- empower your people\
May we care and share the love and compassion that you have taught us.

Let you kingdom come.