---
title: "Crucifixion"
description: "Roman soldiers take custody of Jesus and spend time mocking him"
author: Colin C.
date: 2024-02-25
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 15: 21 - 32](https://www.bible.com/bible/111/MRK.15.NIV)

>  A certain man from Cyrene, Simon, the father of Alexander and Rufus, was passing by on his way in from the country, and they forced him to carry the cross. They brought Jesus to the place called Golgotha (which means “the place of the skull”). Then they offered him wine mixed with myrrh, but he did not take it. And they crucified him. Dividing up his clothes, they cast lots to see what each would get.
> 
> It was nine in the morning when they crucified him. The written notice of the charge against him read: <span style="font-variant-caps: small-caps;">the king of the jews.</span>
>
> They crucified two rebels with him, one on his right and one on his left. Those who passed by hurled insults at him, shaking their heads and saying, “So! You who are going to destroy the temple and build it in three days, come down from the cross and save yourself!” In the same way the chief priests and the teachers of the law mocked him among themselves. “He saved others,” they said, “but he can’t save himself! Let this Messiah, this king of Israel, come down now from the cross, that we may see and believe.” Those crucified with him also heaped insults on him.



### Thoughts and questions 

The physical agony must have been horrendous.  Gladly we live in a culture that does not execute people nor execute people via public torture -- for that is what crucifixion is.  In this passage Jesus is nailed to a cross, large spikes were hammered through his hands, likely his forearms just below the wrists, and again through his feet.  With each breath he would either need to push against the spikes in his feet or pull against the spikes in his hands.  He was pinned, immobilized, in physical agony with no ability to find any simple relief (e.g. scratch an itch).

To add to this Jesus was mocked by criminals, common people, and the authorities.  No one understood.  

If you were a disciple at the time -- how would you feel?  I am reading it again now and it confuses me.  Why God did you need to suffer so.  Yet Jesus chose to suffer and through it He defeated death.  Death did not have a hold on Him, and because of Jesus death will not have a hold on me.  


### Prayer

Lord Jesus, it pains me to simply start considering all that you went through.  Thank you that you have walked the road of suffering.  Not only did you walk that road but you made it through that road.  Your suffering led to death.  Yet death could not hold you.  Son of the Most High God.  As I suffer, I remember you suffered for me.  As I consider my mortality I remember that you have opened the way beyond mortality.  Grant me peace and assurance that you are with me all of my days. 