---
title: "Jesus' Second Trial"
description: "Seeking Jesus' execution the religious leaders bring him before the Pilate, the Roman authority."
author: Colin C.
date: 2024-02-21
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 7
---

### [Mark 15: 1 - 15](https://www.bible.com/bible/111/MRK.15.NIV)

> Very early in the morning, the chief priests, with the elders, the teachers of the law and the whole Sanhedrin, made their plans. So they bound Jesus, led him away and handed him over to Pilate.
>
> “Are you the king of the Jews?” asked Pilate.
>
> “You have said so,”Jesus replied.
>
> The chief priests accused him of many things. So again Pilate asked him, “Aren’t you going to answer? See how many things they are accusing you of.”
>
> But Jesus still made no reply, and Pilate was amazed.
>
> Now it was the custom at the festival to release a prisoner whom the people requested. A man called Barabbas was in prison with the insurrectionists who had committed murder in the uprising. The crowd came up and asked Pilate to do for them what he usually did.
>
> “Do you want me to release to you the king of the Jews?” asked Pilate, knowing it was out of self-interest that the chief priests had handed Jesus over to him. 11But the chief priests stirred up the crowd to have Pilate release Barabbas instead.
> 
> “What shall I do, then, with the one you call the king of the Jews?” Pilate asked them.
>
> “Crucify him!” they shouted.
>
> “Why? What crime has he committed?” asked Pilate.
>
> But they shouted all the louder, “Crucify him!”
>
> Wanting to satisfy the crowd, Pilate released Barabbas to them. He had Jesus flogged, and handed him over to be crucified.

### Thoughts and questions 

It is mind boggling the foolishness of the trials that Jesus had to endure.  The injustice that he faced from the authorities.  Pilate knew that Jesus was innocent.  He knew: 

1. That it was _out of self-interest that the chief priests had handed Jesus over to him_, and 
2. You were innocent:  _Why [crucufy him]? What crime has he committed?_

To top it off, 1\) the Jews chose the release of an convicted man -- a criminal (how backwards is that), and 2\) demanded the crucifixion of Jesus. 
 

### Prayer

Lord you endured so much suffering.  You received to much physical pain.  You faced such mental anguish -- having to endure these trials.  The Jewish authorities seemed blind -- your claims were beyond their ability to accept.  The Roman authorities simple turned a blind-eye knowingly administering injustice.  

Thank you that, in the end, you will make all things right.  That you are just, that you are compassionate.  That despite the injustices that you faced you remain compassionate with us.  

Please bring hope, bring justice, bring us true life.  

Let your kingdom come.