---
title: "Mark -- Answering the call"
description: "Jesus' first disciples answer the call"
author: Colin C.
date: 2023-06-05
search: false
categories: [Mark, healing]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 1: 16 - 20](https://www.bible.com/bible/111/MRK.1.NIV)


> They went to Capernaum, and when the Sabbath came, Jesus went into the synagogue and began to teach. The people were amazed at his teaching, because he taught them as one who had authority, not as the teachers of the law. Just then a man in their synagogue who was possessed by an impure spirit cried out, “What do you want with us, Jesus of Nazareth? Have you come to destroy us? I know who you are—the Holy One of God!”\
“Be quiet!”said Jesus sternly. “Come out of him!” The impure spirit shook the man violently and came out of him with a shriek.\
The people were all so amazed that they asked each other, “What is this? A new teaching—and with authority! He even gives orders to impure spirits and they obey him.” 28News about him spread quickly over the whole region of Galilee.


### Thoughts and questions

Jesus starts to call his disciples.  ... At my work, most jobs for that matter, and generally within our society who get the jobs, the scholarships, or the opportunities?  It is those that are deemed worthy, those that excel, those that have proven themselves.  From what I have been taught is wasn't so different back at Jesus' time.  But Jesus did not look at a pile of applications and select the best.  He selected regular people.  I also believe that he knew their hearts.  He knew that they would be up for the task!

How is Jesus calling you?  What is he calling you to?  ... If you don't know -- have you asked him? 

### Prayer

Jesus, I know that you have called me.  I know that you will use me.  Help me see it.  Help me understand your vision for my life.  Guide me so that I may act to answer your call.  That, like your disciples, when you call that I would be willing to drop everything and go with you. 
