---
title: "Jesus appoints his disciples"
description: "Jesus calls his disciples giving them a special calling and tasks"
author: Colin C.
date: 2023-06-27
search: false
categories: [Mark, disciples]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 3:7 - 12](https://www.bible.com/bible/111/MRK.2.NIV)

> Jesus went up on a mountainside and called to him those he wanted, and
> they came to him. He appointed twelve that they might be with him and
> that he might send them out to preach and to have authority to drive
> out demons. These are the twelve he appointed: Simon (to whom he gave
> the name Peter), James son of Zebedee and his brother John (to them he
> gave the name Boanerges, which means "sons of thunder"), Andrew,
> Philip, Bartholomew, Matthew, Thomas, James son of Alphaeus,
> Thaddaeus, Simon the Zealot and Judas Iscariot, who betrayed him.

### Thoughts and questions

Jesus had a lot of followers at this point. The previous passages
suggest that many many people were following him. In this passage he
appoints 12 to take on a special roll -- to be with him, to be sent out
to preach, and have authority.

The thought I am struck with is that it is Jesus that did the choosing.
He call these men to a specific work and gave them authority for
specific tasks. I think his followers sometimes lose track of these
details:

1.  It is Jesus who has and gives the authority to do things.

2.  Some believers act as if they have Christ's power and authority...
    that if they somehow pray a certain way they can access the
    authority of God.\
3.  Jesus/ God may give some people power to heal and drive out demons.

This leads to several questions

1.  What is God calling me to? Am I open to him calling me to specific
    things in my life?

3.  Am I willing to see God move with supernatural power? Should I expect to see God move with supernatural power (i.e. as a common occurrence)

2.  What is more important?
    -   To show love and compassion as Jesus did, or
    -   demonstrate power and authority.

    I would suggest the first.


### Prayer

Jesus, what are you calling me to?  Use my life for your glory.  Guide me in all my choices.  Help me to show love and compassion to all those around me.  Especially those who are hurting -- that my act of comfort and care would be received as your hand of love and care in their lives. 