---
title: "Family thankfulness"
description: ""
author: Colin C.
date: 2023-05-01
draft: true
editor: 
  markdown: 
    wrap: 72
---

We received some great advice to record what we are thankful for.  Here we capture some of these items 


We are thankful for

- Time together as a family
- We received the initial results from Sam's CT scan today.  The tumor is down in size by ~40%
- That Dr. S. Cheng has other doctors to consult
- Ronald McDonald House
- Care of the entire medical team.  That we are not juzt here to treat cancer, but to bring whole healing (physio, OT, diet, spiritual)
- Nurses and staff who care for Sam and us as individuals ... not just as a patient. Alex, Pam, Victoria, Lauren, Peter the Ambulance guy. ... others.  
- John, John, and Al the crew that took us to BC Cancer Clinic and then Wendy's 
- Generally, all the staff
- Over a hundred of messages of of encouragement and prayer
- Over a hundred donations to help support us financially 
- I love that there are so many people caring for me --Sam
- There is so much for me to actually do here -- Sam
- That I can truly rest -- Sam
- Dad's work providing a paid family leave and that I can be here with the family
- I love the way our hearts are being carried.  ... I feel their prayers, I have joy and peace.  Carried and cared for my God. --Tina



Gifts

- Stiegers gift card for Second Cup
- Callaways gift breakfast from Juliet's Cafe
- Tim Hortons from Senga
- Gifts from Russel
- Banstra's gift of prayer shawls
- Pill brings gift of Tina friendly groceries
- Blanket from Diana Smith



Visits from: 

- Gram and Papa visited 
- Uncle Kev and Shan's visit 
- Cal and Tricia have invested a lot in us 
- Chris and Mary-Joy, Amanda and Jaynme, Jane
- Darren and Shalom 
- Dave and Rhoda
- Wes and Jodie 
- Rod and Leanne 
