---
title: "Messengers and the Son"
description: "God sends his messengers and finally his son."
author: Colin C.
date: 2024-01-04
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 1 - 12](https://www.bible.com/bible/111/MRK.11.NIV)

> Jesus then began to speak to them in parables: “A man planted a vineyard. He put a wall around it, dug a pit for the winepress and built a watchtower. Then he rented the vineyard to some farmers and moved to another place. At harvest time he sent a servant to the tenants to collect from them some of the fruit of the vineyard. But they seized him, beat him and sent him away empty-handed.4Then he sent another servant to them; they struck this man on the head and treated him shamefully.5He sent still another, and that one they killed. He sent many others; some of them they beat, others they killed.\
> “He had one left to send, a son, whom he loved. He sent him last of all, saying, ‘They will respect my son.’\
> “But the tenants said to one another, ‘This is the heir. Come, let’s kill him, and the inheritance will be ours.’ So they took him and killed him, and threw him out of the vineyard.\
> “What then will the owner of the vineyard do? He will come and kill those tenants and give the vineyard to others. Haven’t you read this passage of Scripture:\
> 
> “ ‘The stone the builders rejected\
> \ has become the cornerstone;\
> the Lord has done this,\
> \ and it is marvelous in our eyes’ ?”\
>
> Then the chief priests, the teachers of the law and the elders looked for a way to arrest him because they knew he had spoken the parable against them. But they were afraid of the crowd; so they left him and went away.

### Thoughts and questions 

Jesus lays out the an analogy of the history of Israel.  Where God continually sends messengers and the people running the vineyard, the leaders, keep killing the messengers.  Jesus is obviously speaking out against the leadership.  He also declares himself a messenger and also Son of God.  

### Prayer

It seems I pray this a lot, but I think it so important.  Jesus I recognize you as God's messenger and Son.  May my life also reflect the way that you lived.  May I read what you taught and apply and integrate it into my life.  Be the leader of my life and never let me push you away.  

