---
title: "Son of David?"
description: "Jesus goes on the offensive"
author: Colin C.
date: 2024-01-25
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 28 - 34](https://www.bible.com/bible/111/MRK.12.NIV)

> While Jesus was teaching in the temple courts, he asked, “Why do the teachers of the law say that the Messiah is the son of David? David himself, speaking by the Holy Spirit, declared:\
> 
> “ ‘The Lord said to my Lord:\
> “Sit at my right hand\
> until I put your enemies\
> under your feet.” ’\
> 
> David himself calls him ‘Lord.’ How then can he be his son?”\
> The large crowd listened to him with delight.

### Thoughts and questions 

This and the next passages Jesus seems to go on the attack.  He speaks directly against the religious leaders -- highlighting they have deviated from the God's intent.  The religious intention of the time was that the Messiah had to be a descendant of King David... to the point that they were fixated on this.  However, Jesus highlights, using King David's words ([Psalm 110:1](https://www.bible.com/bible/111/PSA.110.NIV)), that the Messiah will be more than just a descendant, he will also be called Lord -- something greater.  

Jesus in doing this poked holes in the way that the religious authorities think and also highlights something about himself.  As Messiah, he is more than just a man, more than just a descendant.  He is Lord. 

### Prayer

Jesus thank you that you are more than just a good teacher.  More than a man that was willing to die for a good cause.  He are Lord.  You are God incarnate -- God born as a man.  Thank you that you came to teach us and save us.  Leader me Lord, teach me my God to walk in your way.  Let me never get caught up in the rules of the religiosity but, by your Holy Spirit, that I would know and understand the best ways to live in my time and my culture.  