---
title: "On resurrection"
description: "A different religious group attempts to trap Jesus."
author: Colin C.
date: 2024-01-22
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 18 - 27](https://www.bible.com/bible/111/MRK.12.NIV)

> Then the Sadducees, who say there is no resurrection, came to him with a question. “Teacher,” they said, “Moses wrote for us that if a man’s brother dies and leaves a wife but no children, the man must marry the widow and raise up offspring for his brother. Now there were seven brothers. The first one married and died without leaving any children. The second one married the widow, but he also died, leaving no child. It was the same with the third. In fact, none of the seven left any children. Last of all, the woman died too. At the resurrection whose wife will she be, since the seven were married to her?”\
> 
> Jesus replied, “Are you not in error because you do not know the Scriptures or the power of God? When the dead rise, they will neither marry nor be given in marriage; they will be like the angels in heaven. Now about the dead rising—have you not read in the Book of Moses, in the account of the burning bush, how God said to him, ‘I am the God of Abraham, the God of Isaac, and the God of Jacob’? He is not the God of the dead, but of the living. You are badly mistaken!”

### Thoughts and questions 

The Sadducees were another religious group.  Using today's churches as an analogy -- it is how we have Protestants and Catholics.  Both groups believe in God and in Jesus.  However, there understandings and practices are different.  

The question that these Sadducees as is weird.  Why do they create a question, an a complex one at that, about resurrection when they do not believe there is a resurrection (my understanding is that they believe that death is final)?

I do love how Jesus puts them in their place.  His primary response is effectively _You are wrong.  There is a resurrection -- death is not final.  Not only will there will be a resurrection, but He also highlights that God is the God of the living. (e.g. Abraham, Issac, and Jacob are alive)_.  Secondarily, Jesus addresses their convoluted question about the the family and who will belong to who and who will be the husband or wife of who.  Jesus again simplifies.  The legality and human rules around marriage and son-ship will be irrelevant.  Will there be romantic relations after the resurrection?  I do not know, but I know that human legalities will not be there. 


### Prayer

Lord God, I praise you that you are the God of the living!  That this life is not all that we have but that you have an eternity for us.  Lord, grant me an eternal perspective.  Though my heart often desires things in this world that you would transform my heart for your eternal purposes.  