---
title: "On Givers and Takers"
description: "Jesus continues his offensive teaching"
author: Colin C.
date: 2024-01-30
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 38 - 44](https://www.bible.com/bible/111/MRK.12.NIV)

> As he taught, Jesus said, “Watch out for the teachers of the law. They like to walk around in flowing robes and be greeted with respect in the marketplaces, and have the most important seats in the synagogues and the places of honor at banquets. They devour widows’ houses and for a show make lengthy prayers. These men will be punished most severely.”
>
> Jesus sat down opposite the place where the offerings were put and watched the crowd putting their money into the temple treasury. Many rich people threw in large amounts. But a poor widow came and put in two very small copper coins, worth only a few cents.
>
> Calling his disciples to him, Jesus said, “Truly I tell you, this poor widow has put more into the treasury than all the others. They all gave out of their wealth; but she, out of her poverty, put in everything—all she had to live on.”

### Thoughts and questions 

Jesus remains on the offensive -- directly attacking the religious leaders.  In the first paragraph Jesus highlights how the leaders like their social/spiritual power.  But how do they get that power?  They take and they lie.  They take from the poor (e.g. widows' houses), and they are false providing prayers for show -- not prayers of the heart, not works and prayers of compassion.  

The next two paragraphs provide contrast to the teachers of the law.   A dramatic contrast to the teachers who think themselves important and who are takers we have the story of the widow.  The widow gave all that she had.  

What are we willing to give?  Of ourselves, of our wealth, of our time, and resources? 

### Prayer

Lord God, I seems to be part of our human nature to want affirmation to what to be held up and admired.  Forgive me for this.  Forgive me for when I want to the the center of attention.  Teach me to not be a taker.  Teach me and direct me that I would be a giver.  One who provides compassion and relief to others.  One who sees needs and works to bring relief.  My life and all that I have are yours.  Help me to use all of the resources that you have given me to extend Your love to others. 