---
title: "The greatest commandments"
description: "Finally, the teachers of the law have agreement to agree with Jesus"
author: Colin C.
date: 2024-01-23
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 28 - 34](https://www.bible.com/bible/111/MRK.12.NIV)

> One of the teachers of the law came and heard them debating. Noticing that Jesus had given them a good answer, he asked him, “Of all the commandments, which is the most important?”\
> 
> “The most important one,”answered Jesus, “is this: ‘Hear, O Israel: The Lord our God, the Lord is one. Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.’ The second is this: ‘Love your neighbor as yourself.’ There is no commandment greater than these.”\
> 
> “Well said, teacher,” the man replied. “You are right in saying that God is one and there is no other but him. To love him with all your heart, with all your understanding and with all your strength, and to love your neighbor as yourself is more important than all burnt offerings and sacrifices.”\
> 
> When Jesus saw that he had answered wisely, he said to him, “You are not far from the kingdom of God.” And from then on no one dared ask him any more questions.

### Thoughts and questions 

I loved re-reading this today.  What struck me was the scene.  Jesus is debating with various teachers of the law.  They are trying to trap him and then this other teacher shows up.  He is likely really interested having heard some of the ongoing dialogues.  I also get the impression that he is not part of the group attempting to trap Jesus.  So this last teacher gets in there and asks a question that is core to faith.  Not a question about the interpretation of minor laws but a question that is at the core of everything.  I wonder if Jesus smiled.  Jesus' answers are often getting back to basics.  

> _‘Hear, O Israel: The Lord our God, the Lord is one. Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.’ The second is this: ‘Love your neighbor as yourself.’ There is no commandment greater than these.”_

I love how there was only affirmation -- there was nothing to debate.  This was the core of it all.  

### Prayer

Lord God, I love you.  Help me to grow in my love for you.  Let you word become alive in my heart.  Let you Holy Spirit speak to me:  Inspire me to your ways,  enlighten my mind to your thoughts, strengthen my body for your works.  

Inspire me to love and care of my neighbors.  The ones in this house and the ones in our houses back home.  