---
title: "Giving made simple"
description: "On giving and revolution."
author: Colin C.
date: 2024-01-16
search: false
categories: [Mark]
draft: false
editor: 
  markdown: 
    wrap: 72
---

### [Mark 12: 13 - 17](https://www.bible.com/bible/111/MRK.12.NIV)

> Later they sent some of the Pharisees and Herodians to Jesus to catch him in his words. They came to him and said, “Teacher, we know that you are a man of integrity. You aren’t swayed by others, because you pay no attention to who they are; but you teach the way of God in accordance with the truth. Is it right to pay the imperial tax to Caesar or not? Should we pay or shouldn’t we?”\
> But Jesus knew their hypocrisy. “Why are you trying to trap me?” he asked. “Bring me a denarius and let me look at it.”They brought the coin, and he asked them, “Whose image is this? And whose inscription?”\
> “Caesar’s,” they replied.\
> Then Jesus said to them, “Give back to Caesar what is Caesar’s and to God what is God’s.”\
> And they were amazed at him.

### Thoughts and questions 

We know that the leaders were trying to trap Jesus -- this is part of their attempt to get him arrested.  From their perspective he was causing a major disruption in their way of life and undermining their leadership.  But why this question about taxes? How is that going to trap him? 

I think that they thought Jesus was a revolutionary.  The classic understanding was that a messiah would free Israel by actively throwing off its political oppression.  I think the religious leaders expected that Jesus was also looking for the political revolution and if he said they should not pay to the political oppressor then they would have trapped him and could get the Romans to arrest him, but again they got it all wrong.   

Jesus was not about political revolution but revolution of the heart -- of the soul.  A simple question to answer is how to pay my taxes to the government.  But what does it mean to give to God?  What is God's portion?  What do I give him?  The Sunday-school answers is all of yourself.  But what does this even mean -- what does that look like practically? 


### Prayer

Lord God, I am yours.  You have redeemed me with by giving of yourself.  I choose to give myself to you.  But God I am confused.  I say these words and I intend to mean them.  But what does that look like?  Show me.  Call me. Let my life be a reflection of yours.  